*CD gcdraw
      COMMON/GCDRAW/NGMNOD,MGXNOD,NGMND1,LGVVER,LGVHOR,MGAXV,IGPICK,
     + MGLEVV,MGLEVH,NGWCUT,JGNAM,JGMOT,JGXON,JGBRO,JGDUP,JGSCA,
     + JGDVM,JGPSM,
     + JGNAM1,JGMOT1,JGXON1,JGBRO1,JGDUP1,JGSCA1,JGULEV,JGVLEV,
     + LGOKTB(16),
     + GRMAT0(10),GTRAN0(3),IGRNUM,GSIN(41),GCOS(41),GSNPSI,GCSPSI,
     + GTHETA,GPHI,GPSI,GU0,GV0,GSCU,GSCV,NGGVIE,
     + IGCTFL,IGCUT,GCTHET,GCPHI,GDCUT,NGSURF,IGSURF,
     + GZUA,GZVA,GZUB,GZVB,GZUC,GZVC,GPLTRX,GPLTRY,
     + LGINAT,LGINAP,IGXATT,IGTHRZ,IGPRJ,GDPERS,IGTR3D,IGKHIT,IGOBJ,
     + LGINBU,
     + MGAXGU,MGORGU,MGAXGS,MGORGS,MGAXTU,MGORTU,MGAXTS,MGORTS,
     + IGU,IGS,IGTU,IGTS,NGKVIE,IGVIEW,
     + NGOPEN,IGMR,IGPION,IGTROP,
     + GDUMMY(19)
C
