*CD MUSTJJ  
      PARAMETER (JMUSFF= 1,JMUSPL= 2,JMUSET= 3,JMUSTU= 4,JMUSXI= 5, 
     +           JMUSYI= 6,JMUSZI= 7,JMUSXO= 8,JMUSYO= 9,JMUSZO=10, 
     +           JMUSXY=11,JMUSXZ=12,JMUSYZ=13,LMUSTA=13)   
