C---------------------------------------------------------------------
C! ECBAPL: POSITIONS OF ECAL BARREL PLANES (IN X0)
C! ECENPL: POSITIONS OF ECAL ENDCAP PLANES (IN X0)
C! ECPLAN: POSITIONS OF ECAL PLANES CROSSED BY THE CURRENT PARTICLE
C! ESTACK: ENERGY MEASURED IN EACH STACK OF ECAL
C!--------------------------------------------------------------------
      PARAMETER (LECMOD=45,LESTAC=3)
      COMMON/ECMODE/ECBAPL(LECMOD),ECENPL(LECMOD)
     *,ECPLAN(LECMOD),ESTACK(LESTAC)
