      INTEGER LVDL,NWAFN,NSLOM,NVIEWS
      PARAMETER (LVDL=2,NSLOM=15,NWAFN=4)
      PARAMETER (NVIEWS=2)
      REAL WGAINS, WSCENT
      INTEGER IBFLAG
      COMMON/VDMODS/WGAINS(LVDL,NWAFN,NSLOM,NVIEWS),
     &              WSCENT(LVDL,NWAFN,NSLOM,NVIEWS),
     &              IBFLAG(LVDL,NWAFN,NSLOM,NVIEWS)
