      PARAMETER (NRGION = 11)
      COMMON/FMGEOM/FMZMIN(NRGION),FMZMAX(NRGION),FMRMIN(NRGION),
     &              FMRMAX(NRGION)
      COMMON/FMSMUL/FMRADL(NRGION),SINMUL(101),COSMUL(101),SQRMUL(101)
      COMMON/FMELSS/FRATIO(NRGION),CONBB1(NRGION),CONBB2(NRGION),XMUMAS,
     &              XMUMS2
C
