#! /bin/sh

$LSB_TRAPSIGS
$LSB_RCP1
$LSB_RCP2
$LSB_RCP3
# LSBATCH: User input
( cat <<_USER_\SCRIPT_
#!/bin/csh
#BSUB -q xu_8nm
#BSUB -J alpha123_11_afal08
time /afs/cern.ch/aleph/shared/script/updlib < /afs/cern.ch/aleph/reference/cvs/alpha123/alpha123_11.input
exec_end:
exit
_USER_SCRIPT_
) > $LSB_CHKFILENAME.shell
chmod u+x $LSB_CHKFILENAME.shell
$LSB_JOBFILENAME.shell
saveExit=$?
/bin/rm -f $LSB_JOBFILENAME.shell
(exit $saveExit)

ExitStat=$?
wait
# LSBATCH: End user input
true
exit `expr $? "|" $ExitStat`
