
========================================================================
                             ALPHA 123 News
                        Last Update:  15 March 1999
========================================================================

  ALPHA version 123 first release on 12 October 1998

  All features of the successive correction files are summarized below ,
  starting from the most recent one. 

  At the end of this file one finds the description of corrections done 
  in the previous ALPHA version 122 since ALPHA 122.30.
  All older corrections or new features are described in the 
  ALPHA 122 User's Guide released on June 6th, 1997.

==================================================
  Correction file 123.12 released 15 March 1999   
  Modifications w.r.t ALPHA 123.11

 ** Fix in QFMCPA : increase size of internal bank QLIN if needed,
    before filling it
 
 ** Protection added in QFMCBM to avoid infinite loops for some events
    generated by Herwig - code provided by Stan Thompson

 ** Useless printout suppressed in QYFIT - corr. from E.Rohne

==================================================
  Correction file 123.11 released 23 February 1999
  Modifications w.r.t ALPHA 123.10

  ** Protection added in QGTPDDX (from F. Palla, to avoid
     crashes in two runs during the LEP1 MINI-making)

==================================================

  Correction file 123.10 released 5  February 1999
  Modifications w.r.t ALPHA 123.09

  ** in QFPTPX : allow the execution also for data DSTs 
  
==================================================

  Correction file 123.09 released 21 January  1999
  Modifications w.r.t ALPHA 123.08

  ** In QGTPDDX : set a maximum number of warning printouts (10)
                  in case of error.

  ** In QMNEWR : PART bank taken from database on run change 
                 only for MCarlo datasets

===================================================

  Correction file 123.08 released 17 January  1999
  Modifications w.r.t ALPHA 123.06
  
  ** Fix in QMCARD to set up automatically the NSEQ data card

  ** New feature : subroutine QFPTPX , from F. Palla , called in QFILL
     (and subroutines called inside it : QGTPDDX,QDOTPXS,QWRTPXS)

     !!  Warnings !! ===> Works only on POTS, not on DSTs !
                     ===> Needs unpacking and sorting of TPC coordinates,
                          i.e. data card  UNPK  'AL SO'
                          Doesn't work with default UNPK data card !!
  
     Purpose: 
     Recreates the pad dE/dx bank PTPX with the good calibration
     in the following cases :
 
     LEP1 : 
     ====
     The routine QFPTPX is called when doing the MINIs from POTs for :

     - all MCarlos produced from December 1998 onwards with Julia >= 308.6
     - all reprocessed DATA using  Julia versions >=300.0 AND <=308.3

     When reading a POT the default is to call the subroutine. 
     The user is allowed to use the full information when reading
     MCarlo datasets  produced with Julia >=308.6  
     but is  warned that the calibration might be different.

     If the user would like not to apply the correction to the Data
     (in that case, just put the card NOPX in the data cards)
     he/she is warned that the Pad dE/dx is WRONG.
  
     LEP2 :
     ====

     For 1998 reprocessed data (Julia >=308.4) the routine acts as do-nothing.
     
     For all other years for which the reprocessing of the data has not yet been
     done (1995 LEP2->1997 i.e. Julia<=308.3) QFPTPX is called when reading POTs
     both for Data or MC even if this has been produced using Julia => 308.4.
     In case the Data will be reprocessed in the future then the call to the
     subroutine will not be the default.

  ** Modif in QMININC to set up correctly the UNPK data card for MINI
     official productions when QFPTPX has to be called. 
   
===================================================

  Correction file 123.06 released 05 November 1998
  Modifications w.r.t ALPHA 123.04
                                  
  ** Fix in QFILL to have QPI0DO working properly on POTS/DSTs
     together with the modification for photon energy rescaling
     needed by the W group
                          
  ** Fix in LKFORM (Energy Flow package) to avoid throwing away 
     all ECAL clusters with more than 100 Gev...

  ** Fix in QMINIT : correct definition of local variable FMT*75
                     for the call to ALFMT

===================================================

  Correction file 123.04 released 28 October 1998
  Modifications w.r.t ALPHA 122.48
 

 1 - Various changes,fixes or protections :
     ====================================

    **  Protections added in TRSEL,QIPBTAG,QXTRAP (QIPBTAG package)

    **  QDATA : change default of KDEBUG KDEBU1 KDEBU2  from 1 1 999999
                                                        to 0 1 3

    **  QMCARD : protect DEBU card against less than 3 words
              with a DEBU 0 card KDEBU1 and KDEBU2 keep the default
              values set in QDATA

    **  MDIPBT : protect print statement with DEBU card KDEBU1,2
                 limits, or NERROR < 10.  

    **  QFILL : The filling of the GAT section (Photons from GAMPEK  
                bank PGAC) is now done BEFORE calling the energy flow
                to allow for photon energy rescaling by calling 
                the modified version of GAMPEK released on 28.10.98
                To perform this photon rescaling, one has to put
                in the CARDs file the two data cards below:
                
                DRGA  !  to drop the existing PGAC bank
                REPG  !  to call GAMPEK and fill the new PGAC

    **  QFILL,QTRESC : to get the momentum correction using QPCORR
                       ("sagitta correction" for charged tracks)
                       working properly according to the data card PCOR:
        PCOR 0  if the analysis doesn't require specifically VDET
                coordinates
        PCOR 1  if the analysis ONLY uses tracks with VDET coordinates 

    **  KGTBLQ : put IAND instead of AND to compile on HP machines

    **  QWSUMM : change luminosity format (was not OK since we have more
                 than 100 pb**-1 in the same year in 1998 !)
  
    **  XSAME statement function : works now for all 448 possible bits
              and not only for the 320 first ones (bug present since 
              July 1993...)


     2 - MINI initialisation for official productions:
     ================================================

     Modifications in QMCARD, and new routine QMININC to make a standard
     initialisation of the MINI running conditions for official productions.

     - triggered by a new data card   MINP
      
     - the only cards needed now in addition of MINP are 
       FILI,FILO,NSEQ (and possibly SRUN/IRUN or SEVT cards)

     - all necessary data cards for ENFLW, jets, QFNDIP, QIPBTAG etc..
       are generated automatically

     - the data cards for QSELEP are generated with the official 
       cuts to make the MINI properly. If MINP is present, any
       user-supplied data card for QSELEP will be IGNORED.

     Nothing is changed for private MINI productions.


 3 - LEP energy and ALPHA variable QELEP :
     ===================================
  
     A - Motivation :
         ----------

  The previous situation in ALPHA was very unsatisfactory. For historical
  reasons, the QELEP variable giving the LEP energy was defined only once 
  per LEP fill as the average energy for all good runs of the fill and 
  taken from a database bank.

  The "instantaneous" energy made available by the LEP experts (for time 
  slices of 15 minutes) for 1996 and 1997 LEP 2 runs, and the precise 
  run-averaged LEP energies for LEP1 runs were available from the 
  user-callable routines QELEP2 and QELEP1, the existence of which
  was ignored by a majority of users.

  The modifications done in the new version put in QELEP the best possible  
  available value of the energy, on an event-by-event basis and not as an
  average over a LEP fill. There is no more need to call privately QELEP1
  or QELEP2.

     B - Modifications :
         -------------

  QMNEWR : no more call to GETLEP, no more filling of QELEP (done now  
           in QFGET_BP for each event).

  QFGET_BP : calls the ALEPHLIB routine GETLEP which returns QELEP

     C - User subroutine to know how QELEP was found :
         -------------------------------------------

         CALL QWHICH_EN(ISTAT)

         Ouput argument :  ISTAT

   ISTAT = 0  no energy found (should never happen !)
         = 1  from the 'RLEP' bank (always the case for MCarlo)
         = 2  from the 'LFIL' bank
              for 1989 -> 1992 real data
              or LEP2 data when neither time-slice nor run-averaged
         = 3  from the run-averaged values of the LEP Working Group
              for 1993 -> 1995 LEP 1 data, 
              or for LEP 2 data if no time-slice available
         = 4  from the 15' time-slices of the LEP Working Group
              for LEP 2 data

  
 4 - Beam spot position and d0,z0 of charged tracks :
     ============================================== 

     A - Motivation :
         ----------

  Here the previous situation gave rise to contradictions.   
  Such a contradiction occured in the 1998 MINI-making where the beam spot
  definition was not the same at the time of the MINI-making and at the time
  of reading the resulting MINIs.

  The event-chunk beam position (see ALPHA user's guide p 31) was used to
  compute the event interaction point (QFNDIP package) or the secondary
  vertices or b tags in the QIPBTAG package. As a result, the ALPHA
  variables for d0,z0  of charged tracks didn't match with the ones
  used inside these packages.
  
  The modifications introduced in ALPHA 123 have the following effect:

  The event-chunk beam position is always used as beam spot whenever it exists.
  The d0,z0 variables in ALPHA are computed with respect to it and are
  therefore consistent everywhere.
 
  Differences between the new, correct values and the old ones are usually
  very small but may result in differences when applying cuts on d0,z0.
 
  Users - especially LEP 2 data users - are warned that this modfication is 
  NOT backward compatible, but that the new values are the good ones, to be 
  used both for real data and for Monte Carlo data.


     B - Modifications :
         -------------

  QMDBAS : the reading of the old LEP1 beam positions for 1991-1994 from
           file BEAMPOSITION is removed from QMDBAS; it is done now in
           the ALEPHLIB routine getbp

  QMNEWR : does not fill QVXNOM,QVYNOM,QVZNOM any more


  QFILL  : calls QFILBP twice, the first time to compute the beam spot
           the second time after the Energy Flow to call QFNDIP

  QFILBP : modified to be called twice, as explained above

  QFGET_BP : calls now the ALEPHLIB routine GETLEP, which in turn
             calls the event-chunk routine GETBP, previously
             QVXNOM,QVYNOM,QVZNOM filled here now
             If the event-chunk beam position exists:
             the arrays QVTXBP,QVTEBP,QVTSBP are filled here
  QBEAMX : reads the beam.position file for LEP1 MCarlo datasets, if needed,
           to get the banks WIDN and WIDE.

  FIXALPB and XFMCBP : removed from ALPHA , put in the ALEPHLIB

  Remarks : 1 / Nothing is changed for the use of the LEP BOMS
  =======       obtained when using the data card BOBS
                (see the description in this NEWS file below,
                in the modifications done for the correction file
                ALPHA 122.41). 

            2 / QFD0Z0 : modified to be called only if the data card 'D0NW'
                is present and if one asks for the QFNDIP package.
        ===>    Be careful: the errors quoted on d0,z0 are not correct.
        ===>    Will be updated and fixed later.
        ===>    Should not be used for the time being.


     C - User subroutine to know how the beam spot was found :
         ---------------------------------------------------

         CALL QWHICH_BP(ISTAT)

         Ouput argument :  ISTAT
  
  ISTAT  = 0  no beam position found (should never happen)
         = 1  from the 'JSUM' bank - should be very rare,
              only if getbp fails and neither RXYZ nor LFIL exist
         = 2  from the 'LFIL' bank, if getbp fails and no RXYZ exists
         = 3  from the 'RXYZ' bank (only for old LEP1 data processing
              of 1989 -> 1995 if getbp fails )
         = 4  from getbp (event-chunk beam position)
  
  Remark : If the LEP BOMs were used, the corresponding status is obtained 
           with the subroutine QFILBP_STATUS(KFILBP), see ALPHA 122.41


========================================================================
                             ALPHA 122 News
                        Last Update: 17 July  1998
========================================================================
 
  ALPHA version 122 

  All features of the successive correction files are summarized below ,
  starting from the most recent one. The oldest one corresponds to ALPHA 122.30
  All older corrections or new features are described in the ALPHA User's Guide 
  released on June 6th, 1997.

===================================================

  Correction file 122.48 released 17 July 1998
  Modifications w.r.t ALPHA 122.47

  ** Modifications in QFILL, from F. Ligabue
     in order to make easier the work of the LEP 2 W group.
     All these modifications act as do-nothing by default.

     - Call a new user routine QURESC (dummy) 
       the user may call it to make several rescalings of HCAL and ECAL 
       for systematic studies
       see explanations in the comments of the routine:
       /al/reference/cvs/alpha122/pack/quresc.F
     - If a data card PCOR is provided, a new routine QTRESC is called
       by QFILL to rescale all charged track momenta (so-called "sagitta
       correction"). QTRESC calls automatically for all tracks the routine
       QPCORR (see news for ALPHA 122.44 of March 2nd, 1998)
       which does the sagitta correction track by track.

===================================================

  Correction file 122.47 released 4 June 1998
  Modifications w.r.t ALPHA 122.46

  ** Modifications in the Beam position routines, from S. Wasserbach:

     - Mod in qfget_bp to handle the glitch in the ALPB bank for MINI LEP1
       reprocessing and MINI 1997 made with MINI versions 103 and 104
       (a very small fraction of events have the uncertainty on y_beam =0.,
        the correction sets this uncertainty to the average value for the
        corresponding year).

     - Mod in qfilbp: default values of QVTXBP,QVTEBP,QVTSBP are set to
       crazy values (position = 999. cm, uncertainty and luminous region =0.) 
       to force people to make a test on XGETBP=.TRUE.

  ** The 10 routines XLUMOK,..XVDEOK removed from the cvs source code are now 
     really removed from the ALPHA binary libraries (see news for ALPHA 122.42
     of January 20th,1998): they were still on the libraries and used intead of
     the ALEPHLIB ones, by mistake. 


===================================================

  Correction file 122.46 released 15 May 1998
  Modifications w.r.t ALPHA 122.45

  New format to print the ALEPHLIB version number in QADATI

===================================================

  Correction file 122.45 released 02 Mar 1998
  Modifications w.r.t ALPHA 122.44

  ** New Function QPCORR  (from Ian Tomalin).
       
     Purpose :

     Corrects particle momenta for the effects of residual distortions in
     the central tracking detector.
     This is the so called "sagitta correction".
     It depends upon cos(theta) and the year of data taking.
  
     Motivation:

     Every year, even after the detector alignment is finished and
     corrections have been made for field distortions etc., it is found
     that Ebeam/P in Z0 -> mu+mu- events is not precisely 1, presumably
     because of residual distortions.
     (Typically, in the region |cos(theta)| > 0.9, Ebeam/p is about 0.94
     for +ve tracks and 1.06 for -ve tracks. Elsewhere, Ebeam/p is usually
     consistent with 1 to within a percent or so. The effect is not quite
     forward-backward symmetric).

     The relative bias in momentum is proportional to P, so most people
     analysing hadronic events can ignore it. Exceptions include analyses
     using the ECAL electron identifiers in the region |cos(theta)| > 0.9,
     or analyses which are very sensitive to systematic biases in the
     momenta (e.g. jet charge, tau polarization).

     This routine provides a correction for the momenta based upon
     Ebeam/P measurements in Z0 -> mu+mu- events. It assumes that the
     corrections for -ve and +ve particles are equal in size, but of
     opposite sign. This is observed to be true, apart from a constant
     offset, Ebeam/p = 1.002, which is also present in the MC and so not
     corrected for.
     
     In principle, the correction depends upon your track selection
     cuts, but providing that the corrections have a small effect on your
     analysis, you can ignore this. Arguement NVDET does correct for this
     to first approximation however.

     Calling the routine: 

      FUNCTION QPCORR(ITRK,ASCALE,NVDET,ERCORR)

     Input Arguments:
       ITRK    (Integer): ALPHA track number.
       ASCALE  (Logical): Set .TRUE. if ALPHA variables like QX,QY,QZ
                          are to be rescaled by calling QVSCAL.
                          N.B. Don't call this routine twice for the
                          same track with ASCALE = .TRUE. !
       NVDET   (Integer): If your analysis only uses tracks with at
                          least 1 VDET hit, set NVDET=1; otherwise =0.
     Output Arguments:
       QPCORR  (Real)   : Scale factor applied/to be applied to momentum.
       ERCORR  (Real)   : Statistical error on this factor.
 
     If corrections are not available for any year, please contact the 
     tracking group.
   

  ** New data cards FR12 and FR10 for the Monte Carlo smearing of charged
     tracks introduced in JULIA 306:
 
     Purpose:
    
     JULIA 306 implements the TPC hit smearing for MonteCarlo. FRFT/0 (without
     VDET) and FRFT/2 (with VDET) contain the track parameters after refit
     with the smeared hits but keeping the error matrix from the unsmeared fit.
     This gives the best agreement between data and MonteCarlo.
     The track fit using the unsmeared TPC hits is still available in 
     FRFT/10 (no VDET hits in the fit), and FRFT/12 (with VDET).
     Note that the V0s, kinks etc. are done with the  smeared tracks.
    
     Therefore when reading in ALPHA a dataset written by JULIA >= 306, the
     charged tracks obtained by default are as usual the FRFT/2 ones, i.e. 
     the smeared ones with VDET hits in the track fit.   

     The new data cards allow to get in the ALPHA variables the unsmeared tracks
     for checks or comparisons, allowing to redo e.g. the V0 finding using the
     data card REV0, or the pair finding calling the routine QPAIRF. 

     Usage:

     FR12   puts in the ALPHA variables the FRFT/12 tracks : unsmeared, with
            VDET hits in the track fit;

     FR10   puts in the ALPHA variables the FRFT/10 tracks : unsmeared, without
            VDET hits in the track fit.
     

     N.B.1: the old FRF0 data card still works and puts in the ALPHA variables
            the FRFT/10 tracks : SMEARED without VDET hits in the track fit.
               
     N.B.2: one cannot give simultaneously 2 of the 3 data above data cards 
            (FR10,FR12,FRF0): if this is the case, ALPHA stops immediately.

===================================================

  Correction file 122.44 released 10 Feb 1998
  Modifications w.r.t ALPHA 122.42

  ** Increase BOS array to 1,500,000 by default (for LEP2 MCarlos) in QUIBOS

  ** Mod in QFILL, new routines QD0Z0 and KD0FL for new d0,z0 calculation:
     with use of a new data card D0NW as follows :

  1 - by default, one gets the same d0,z0 as in previous versions of ALPHA in
      the variables QDB(ITK) and QZB(ITK). This ensures backward-compatibility,
      but should not be taken as good for LEP2 runs and future LEP1 reprocessing

  2 - if the user puts a new data card:  D0NW       in the  CARDS file,
      QDB(ITK) and QZB(ITK) give new values of d0,z0 obtained as follows:

   ==> if there is no QFND data card, the "beam position" which is used
       is the event-chunk one, if it exists;

   ==> if there is a QFND card, the "beam position" which is used is the event
       main vertex computed by QFNDIP, if it exists.

   This new feature is valid both for LEP1 and LEP2 runs.
     
     In all cases, a new integer function tells which kind of beam position
     was used for a given event to compute d0,z0:

   IFLAG = KD0FL(dummy)

   The return value IFLAG has the following meaning:

   IFLAG = 1 if beam position from the QFNDIP event primary vertex
   IFLAG = 2 if beam position is the event-chunk one
   IFLAG = 3 if beam position from the old LEP 1 run-by-run average
               (= QVXNOM,QVYNOM,QVZNOM)
   IFLAG = 0 if none of the above values available
             in that case the beam position is set to 0.,0.,0. 

===================================================

  Correction file 122.42 released 20 Jan 1998
  Modifications w.r.t ALPHA 122.41

 ** Removal of XLUMOK and XVDEOK from the ALPHA code, since these functions are
    now in the ALEPHLIB. The calls to these routines are of course left in 
    ALPHA and this removal is user-transparent.

    All routines called by XLUMOK and now in the ALEPHLIB are also removed
    from ALPHA: LLUMOK,SLUMOK,XLSLUM,XT0SYN,XPTENB,QRE133,QRE94

    All routines called by XVDEOK and now in the ALEPHLIB are also removed
    from ALPHA: QHVSTA,KVGOOD

 ** Modification in QIPBTAG for LEP2 data and MCarlo: (from M. Thulasidas)
    Mod in BTAG_PAR96, new routine GTIPBK.
    The calibration constants for QIPBTAG are now read from the ADBSCONS
    database bank 'QIPC'. 
    The user MUST remove any old FITP cards from his CARDs file for LEP2 data
    and MCarlo, otherwise ALPHA stops. The use of FITP cards remains possible
    for LEP1 data/MCarlo.

===================================================

  Correction file 122.41 released 27 Nov 1997
  Modifications w.r.t ALPHA 122.40
  
 
 ** New facility: calculation of the beam spot informations using the LEP BOMs
                  for 1996 and 1997 data. 

    Code written by O. Schneider and maintained by C.Loomis.

    The ALPHA routine QFILBP has been modified to call a new routine, KGTBLQ.
    It allows to use the LEP BOMs+QS0 informations to compute the beam spot 
    information, stored in the ALPHA arrays QVTXBP, QVTEBP and QVTSBP
    which are used by QFNDIP and QIPBTAG.

    By default, nothing is changed w.r.t to the previous ALPHA version. 

    The user does'nt need to call any routine. To activate the new facility,
    one has to provide a data card BOBS with the following syntax:

 BOBS sigmax sigmay bom_only debug 

     sigmax   = real number equal to the LEP_BOM+QS0 intrinsic resolution in x; 
     sigmay   = real number equal to the LEP_BOM+QS0 intrinsic resolution in y; 
     bom_only = integer flag to indicate whether one wants to use only
                LEP_BOM+QS0information (bom_only=1)
                or if one wants to use the weighted average between the
                LEP_BOM+QS0 information and the VDET chunk-by-chunk information
                (bom_only=0); 
     debug    = integer flag to switch debug printout ON (debug=1) or OFF
                (debug=0). 

     If any of the above values are missing on the BOBS card, the following 
     default values are used:

     sigmax   = 0.0040 (i.e., 40 microns); 
     sigmay   = 0.0010 (i.e., 10 microns); 
     bom_only = 0 (i.e., use weighted average); 
     debug    = 0 (i.e., no debug printout). 

  ==>  Notes: 

        1 - if sigmax (or sigmay) is given a negative value on the BOBS card,
            then the LEP_BOM+QS0 information is not used for the x (or y)
            coordinate of the beam spot position. 

        2 - This new facility needs a bank, BLQP, which is not available for
            datasets produced with JULIA versions before 284. For these data
            sets, the BOBS card acts as do-nothing.

        3 - When using this new facility, to know the status of the ALPHA beam
            spot position one may call :

                       CALL QFILBP_STATUS(KFILBP) 

     KFILBP is an integer output argument with the following meaning: 

     KFILBP = 0 means that XGETBP=.FALSE.,
                           i.e. chunk-by-chunk VDET beam position not available
                           ---> QVTXBP(I)=QVTEBP(I)=QVTSBP(I)=0 for I=1,3
 
     KFILBP > 0 means that XGETBP=.TRUE.,
                           i.e. chunk-by-chunk VDET beam position     available
                           ---> QVTXBP(I) and QVTEBP(I), I=1,2 are filled with
                                VDET data or BOM+QS0 data or a weighted average
                                of both according to the table below

               KFILBP   I=1 (x)   I=2 (y)
               ------   -------   -------
                 0      -         -
                 1      VDET      VDET
                 2      BOM+QS0   VDET
                 3      VDET      BOM+QS0
                 4      BOM+QS0   BOM+QS0
                 5      Average   VDET
                 6      VDET      Average
                 7      Average   Average
 

      More details can be found if necessary in the following Web page:

       http://alephwww.cern.ch/LEP2ANALYSIS/HTF/code/instructions.html

===================================================

  Correction file 122.40 released 17 Nov 1997
  Modifications w.r.t ALPHA 122.36

 ** Bug fix in QFYLV0 to avoid infinite loops when using KSAME

====================================================

  Correction file 122.36 released 21 Oct 1997
  Modifications w.r.t correction file ALPHA 122.35

 ** New feature in the QFNDIP package, introduced by  N. Konstantinidis for   
    LEP 2 events:
   
   A new data card DWIN allows to control the use of the longitudinal
   component of tracks. 

   Syntax and usage of the data card:

 DWIN USE_LONG WINDOW
 
   If USE_LONG=1, use tracks with: Distance(track-jet) < WINDOW
   If USE_LONG=2, use tracks with: ABS(Distance(track-jet)) < WINDOW
 
   If DWIN is absent or USE_LONG=1 and WINDOW=0.0, the user gets 
   the standard QFNDIP results.
   
   Recommended values for LEP2:

   DWIN  1  0.035
 

 ** New fix in QFYLV0 (Routine which stores the so-called "Long V0s" from
    datasets processed with the new tracking, JULIA version > 300) :
    A bug in the mother-daughter relations was introduced 
    by the previous fix of version 122.35. Thanks to H. Seywerd, who found the 
    bug and checked the corrected version.

====================================================

  Correction file 122.35 released 16 Oct 1997
  Modifications w.r.t correction file ALPHA 122.34

  - Bug fix in QFYLV0 : the pointers to the daughter tracks of "Long V0s" 
    coming from the new tracking were not set correctly

  - Small fix in QNVSTO (internal routine to store new vertices from the
                         new tracking)
  
  - New user printout routine QWNEWTR to get details of the new vertices
    ("Long V0s", Kinks, Nuclear Interactions) from the new tracking.
    This routine is called automatically by QWEVNT but may be called 
    independently for a given event by the user :   CALL QWNEWTR
 
====================================================

  Correction file 122.34 released 08 Oct 1997
  Modifications w.r.t correction file ALPHA 122.33

  - Mod in XVDEOK to take into account a VDET HV bit change for 1997 data
  - Small fix in GETLE1 for LEP1 run-by-run exact energy 
  - Small fix in KNMCHC for the LINUX compiler

====================================================

  Correction file 122.33 released 26 Aug 1997
  Modifications w.r.t correction file ALPHA 122.31
   
  ** - Modification in QFMCPA to avoid  crashes in some ALPHA statement
       functions, due to very low energy photons with Px=Py=0. generated by   
       some 1997 Monte-Carlos.

  ** - New version of GETLUM put provisionnally in ALPHA (to be put in the
       ALEPHLIB in the future) to get the run luminosity from the LUMI bank
       if the luminosity in the RLUM bank is 0.

  ** - New routine QELEP1 to get the exact LEP energy for all EW/EA runs  
       of 1993,1994 and for the runs at the Z0 taken in 1995. 
       
       For more details, see the ALEPH note from Paul Bright-Thomas:
 
       "LEP Energies for 1993-1995", ALEPH 97/082, PHYSIC 97/072
       (11 August 1997).
  
 
      This routine has to be called by the user once per run:   

              CALL QELEP1(ENERGY,IFLAG)

       It gives 2 output arguments:

 
     IFLAG = 2     ENERGY (in GeV) is the exact energy of the current run. 
                 
     IFLAG = 3     ENERGY = QELEP (in GeV) for all other cases: runs which are
                   not good for the EW/EA groups, MCarlo runs, runs of 1989-92.

  The information for IFLAG = 2 has been taken from the official tables provided
  by the LEP experts. For the time being they are available from the temporary
  ALEPH database ADBSTEST. They will be put in the ADBSCONS.DAF in its next
  release. See the ALPHA user's guide p. 15-16 to get the ADBSTEST database.
        
     N.B.   This routine makes no sense for LEP2 runs. For LEP2 runs, please 
            use the routine QELEP2 described in the ALPHA user's guide p. 118.

====================================================

 Correction file 122.31 released 06 Aug 1997
  Modifications w.r.t correction file ALPHA 122.29
   
  ** - Fix in FIXGAEN to call the modification only when necessary

  ** - Fixes in ISP and QTFUNC (QTRUTH/QSELEP package) to avoid endless
       loops due to an  unforeseen feature for electrons coming from
       the conversion of ISR photons in HVFL05 MCarlo datasets. 

  ** - Fixes for multiple declarations of variables for the LINUX compiler
       in the KNTRU package introduced in version 122.30



