      COMMON/E4COM0/ICLU,ITRCL,JTRAK
     &,KSINT,IMOD,ISUB,ISUB2,INDI,SK
     &,A(3),B(3),C(3),D(3),XI,YI,ZI
#if defined(DOC)
C
C!  Use for Electron I.D.
C
C   ICLU NUMERO CLUSTER
C   ITRCL INDICE CLUSTER DE LA TRACE
C   JTRAK INDICE FRFT DE LA TRACE
C  KSINT INDICE DU STACK DE TRAVAIL
C  IMOD    "       MODULE     "
C  ISUB    "       SUBCOMP    "
C  ISUB2   "       SUBCOMP    "     APRES CHGMT DE SUBCOMP
C  INDI INDICE INTERNE A E4FIND
C  SK   INDICE INTERNE A E4FIND
C  A(3),B(3),C(3),D(3) PARAMETRES DES EQUATION PLAN ET DTE
C  XI YI ZI POINT D INTERSECTION SUR STACK DE TRAVAIL
C
#endif
