#if defined(DOC)
C!
C! ECLUSTER COMMONS
C!    KEWLOC = POINTER TO WORK BANK FOR SECOND LEVEL ARRAY
C!    NINDEB( 4110) = NUMBER OF DIFFERENT ROSEVE_CASES
C!    IROSEV(21900) = ARRAY CONTAINING OFFSET OF NEIGBOUR STOREYS
C!    IARRAY( 6144) = ARRAY IMAGE OF ONE ECAL SLICE STOREYS
C!    IDRRAY( 6144) = ARRAY IMAGE OF ONE ECAL SLICE (DEAD STOREYS)
C!    ENELOW = LOWER THRESHOLD FOR CLUSTERS
C!    ENHIGH = HIGH  THRESHOLD FOR CLUSTERS
C!    ECGTHR = TOTAL THRESHOLD FOR CLUSTERS
C!    ENDEAD = DEFAULT ENERGY GIVEN TO DEAD STOREYS
C!
#endif
      COMMON/ECLUST/KEWLOC,IARRAY(6144),IROSEV(21900),NINDEB(4110),
     +             IDRRAY(6144),ENHIGH,ENELOW,ECGTHR,ENDEAD
C
