      PARAMETER (LLBAN =  9)
      PARAMETER (LESDA = 10)
      PARAMETER (LECLU = 29)
      PARAMETER (LTRAK =  1)
      PARAMETER (LCLUT =  2)
      PARAMETER (LCLTR =  3)
C
#if defined(DOC)
C
C! ECAL BOS BANK DEFINITION
C
C        LLBAN = LENGTH OF BOUNDARY TPC POINTS BOS BANK ("LAST")
C         LESDA = LENGTH OF STOREY BANK ("ESDA")
C         LECLU = LENGTH OF CLUSTER BANK ("ECLU")
C         LTRAK = LENGTH OF TPC_TO_ECAL BANK ("TRCL")
C         LCLUT  = LENGTH OF ECAL_TO_TPC BANK ("CLTR")
C        LCLTR  = LENGTH OF RELATION TPC_CLU BANK ("RLCT")
C
#endif
