      COMMON /ECTCOM/STPKEC,STMNEC,PMINEC,AAAKEC,FILDEC
#if defined(DOC)
C! CLUSTER-TRACK ASSOCIATION COMMON
C!    STPKEC = STEP SIZE FOR HELIX EXTRAPOLATION (CM)
C!    PMINEC = MINIMUM MOMENTUM FOR TRACKS TO BE EXTRAPOLATED (GEV)
C!    AAAKEC = P=AAAKEC.B.R
C!             =3.E-1 FOR GEV, TESLA AND M
C!             =3.E-4 FOR GEV, KILOGAUSS AND CM
C!    FILDEC = FIELD (KILOGAUSS) IN ECAL
C!    STMNEC = MINIMAL STEP SIZE FOR EXTRAPOLATION (IN ECLTRK)
#endif
