#if defined(DOC)
C! DEFINE CONSTANT USE FOR MINION IDENTIFICATION IN ECAL
C!
C!      ENFMIP = MEAN ENERGY LOSS OF MINIONS IN STACKS 1-3 (GEV)
C!      ER2ST1 = RMS**2 OF LOSS IN STACK1 (GEV**2)
C!      ER2ST2 = RMS**2 OF LOSS IN STACK2 (GEV**2)
C!      ER2ST3 = RMS**2 OF LOSS IN STACK3 (GEV**2)
C!      EPRMIP = MINIMUM PROBABILITY FOR MINION IDENTIFICATION
C!      ECHIMN = MAXIMUM CHISQD FOR MINION IDENTIFICATION
C!      ETOMIN = MAXIMUM ENERGY FOR A CONSIDERED MINION CANDIDATE
#endif
      PARAMETER ( NMAX = 5 )
      COMMON/EMINIP/BARYCL(3),ENLVCL(3),NTRACL(NMAX),PTPCCL(NMAX)
     +,IFLAMP
      COMMON/EMINIC/ENFMIP(3),ER2ST1,ER2ST2,ER2ST3,
     1              EPRMIP,ETOMIN,ECHIMN
