         COMMON/ MGDBAR/ BPLADI,BYOFFS(NRPLAN,NRSLBA),MBVOLU(NRSLBA),
     +     BZETAC(NRSLBA),BERREC(NRSLBA),BDELTC(NRSLBA),
     +     BTOFFS(NRPLAN,NRSLBA),MBNAST(NRSLBA),MBTAST(NRSLBA),
     +     MBPNT2(NRSLBA),BZBOXG(NRTYBA),BRBOXG(NRTYBA),MBNSY1(NRTYBA),
     +     MBNSY2(NRTYBA),MBNSXT(NRPLAN,NRTYBA),BRTOOT(NRTYBA),
     +     BZTOOT(NRTYBA),BPIT16(NRTYBA)
