      INTEGER NAVPLH ,NAVHLS ,NAVGTL ,NAVCPL ,NAVDCO ,
     &  NAVDXY ,NAVDZT ,NAVGCL ,NAVHOT ,NAVRCN ,NAVMRE ,NAVMPC ,
     &  NAVMGN, NAVFPH
C
      COMMON /VDNAMC/ NAVPLH ,NAVHLS ,NAVGTL ,NAVCPL ,NAVDCO ,
     &  NAVDXY ,NAVDZT ,NAVGCL ,NAVHOT ,NAVRCN ,NAVMRE ,NAVMPC ,
     &  NAVMGN, NAVFPH
