      INTEGER INSCOD,MOTINS,NDAUGH,NMCUNS
      REAL    ZFRAGM,V0VXMI,V0VYMI,V0VZMI
      COMMON /NCOMMI/ZFRAGM(MAXMCT),INSCOD(MAXMCT),MOTINS(MAXMCT),
     +               NDAUGH(MAXMCT),V0VXMI(MAXMCT),V0VYMI(MAXMCT),
     +               V0VZMI(MAXMCT),NMCUNS
