      INTEGER IPACOD,MATCHT,MOTIST,NLDAUG,IPATYP,NMCSTA
      REAL    PMCTRK,V0VXMS,V0VYMS,V0VZMS
      COMMON /NCOMMS/PMCTRK(4,MAXMCT),IPACOD(MAXMCT),MATCHT(MAXMCT),
     +               MOTIST(MAXMCT),NLDAUG(MAXMCT),IPATYP(MAXMCT),
     +               V0VXMS(MAXMCT),V0VYMS(MAXMCT),V0VZMS(MAXMCT),
     +               NMCSTA
