C?.Start of NPCDSH -----------------------------------------------------
C?.to be used in NDSTPnnn instead of NCDESH
C
      CHARACTER*80 LNNDSB
      PARAMETER(LNNDSB=
     &  'NDARNDCLNDDENDEJNBIPNDGCNDJTNDLVNDMSNDNTNDOBNDPHNDTKNDV0')
      CHARACTER*40 NCLPOT,NCLRUN
      CHARACTER*80 NCLNDS
      COMMON /NDST01/NCLPOT,NCLRUN,NCLNDS
      COMMON /NDST02/LPBLIS,LRBLIS,LNBLIS,
     +               IPNAMI(20),IRNAMI(20),
     +               IINDAR,IINDBM,IINDCL,IINDDE,IINBIP,IINDJT,IINDLV,
     +               IINDMS,IINDNT,IINDOB,IINDPH,IINDTK,IINDV0,IINDGC,
     +               IINDEJ
      PARAMETER(NPARHY=15,NBRHYP=5)
      COMMON /NDST03/PARMPH(NPARHY,NBRHYP)
      LOGICAL NXPAHY
      COMMON /NDST04/NXPAHY(NBRHYP)
      CHARACTER*4 NCCNH(NBRHYP)
      DATA NCCNH/'HYEL','HYMU','HYPI','HYKA','HYPR'/
      COMMON /NDST05/RMASPA(NBRHYP)
      COMMON /NDST06/NEPROC,NEWRIT,NRWRIT,NTWRIT,NUOUTP,NULOST,
     +               NEVTLO,IRUNLO(6),IEVTLO(6)
      PARAMETER(NPNDST=20)
      COMMON /NDST07/IOFLAG,MINTRK,
     +               PCUTMI,PCUTMA,THCCUT,NITCUT,NTPCUT,BD0CUT,BZ0CUT,
     +               PCUMIJ,PCUMAJ,THCCUJ,NITCUJ,NTPCUJ,BD0CUJ,BZ0CUJ,
     +               BMYCUT,ENEVIS,PHOCUT,ALIVER,ECHMIN,V0CHSI,V0CHBO
      CHARACTER*2 RECOOP
      COMMON /NDST08/RECOOP
      LOGICAL NXWREV,NXBANK,NXONLY,NXNDST
      COMMON /NDST09/NXWREV,NXBANK(20),NXONLY(20),NXNDST
      CHARACTER*4 NCPROD
      CHARACTER*8 NCALPH,NCDATE
      COMMON /NDST10/NCPROD,NCALPH,NCDATE
      LOGICAL        NXWRLO,NXLUMO,NXHVBI,NXVDBI,NXECBI,NXHVOK,NXDEOK,
     +               NXVDOK,NXMUOK,NXEFOK,NXLEPT,NXQVSR,NXQVSS,NXSRCH,
     +               NXGIPT,NXIPBT,NXGAMP,NXQFVX,NXQFFA,NXPGAC
      COMMON /NDST11/NXWRLO,NXLUMO,NXHVBI,NXVDBI,NXECBI,NXHVOK,NXDEOK,
     +               NXVDOK,NXMUOK,NXEFOK,NXLEPT,NXQVSR,NXQVSS,NXSRCH,
     +               NXGIPT,NXIPBT,NXGAMP,NXQFVX,NXQFFA,NXPGAC
      COMMON /NDST12/MCOPTI,PMINMC,LFLAVR
      LOGICAL NXYRMI
      COMMON /NDST14/NYRNPF,NXYRMI
      COMMON /NDST15/REFMIN,RMYCUT,BJSPCH,BJSPEF,BBSPR1,BBSPR2,BEETT1,
     &  BEETT2,BEETM1,BEETM2,BIPTAG,BIPTA1,BIPTA2,THRUST
      LOGICAL NXRQEI
      COMMON /NDST16/NXRQEI
      COMMON /NDST17/NCORSP
      PARAMETER(MAXLEC=15,MAXJET=15,MAXGAM=255,MAXTRK=255,
     &  MAXV0C=50,MAXMCT=511,MAXGCO=100,MAXMCP=1000,MAXEFT=255)
      COMMON /LEPVAL/IFILL,BEAMX(3),DBEAMX(3),NHADBX
C?.End of NPCDSH -------------------------------------------------------
