*CD evehjj
      INTEGER JEVEEN,JEVERN,JEVERT,JEVEDA,JEVETI,JEVEEV,JEVEM1,JEVEM2,
     +          JEVEM3,JEVEM4,JEVETY,JEVEES,JEVETE,LEVEHA
      PARAMETER(JEVEEN=1,JEVERN=2,JEVERT=3,JEVEDA=4,JEVETI=5,JEVEEV=6,
     +          JEVEM1=7,JEVEM2=8,JEVEM3=9,JEVEM4=10,JEVETY=11,
     +          JEVEES=12,JEVETE=13,LEVEHA=13)
