*CD itcojj
      INTEGER JITCWN,JITCRA,JITCP1,JITCP2,JITCZH,JITCSR,JITCSZ,JITCDT,
     +          LITCOA
      PARAMETER(JITCWN=1,JITCRA=2,JITCP1=3,JITCP2=4,JITCZH=5,JITCSR=6,
     +          JITCSZ=7,JITCDT=8,LITCOA=8)
