*CD metgjj
      INTEGER JMETID,JMETVR,JMETNA,JMETXB,JMETYB,JMETX1,JMETX2,JMETYS,
     +          JMETPI,JMETNX,JMETNY,JMETNP,JMETN2,JMETN1,JMETLE,LMETGA
      PARAMETER(JMETID=1,JMETVR=2,JMETNA=4,JMETXB=5,JMETYB=6,JMETX1=7,
     +          JMETX2=8,JMETYS=9,JMETPI=10,JMETNX=11,JMETNY=12,
     +          JMETNP=13,JMETN2=14,JMETN1=15,JMETLE=16,LMETGA=40)
