*CD mmtgjj
      INTEGER JMMTID,JMMTVR,JMMTNA,JMMTZB,JMMTRB,JMMTZT,JMMTRT,JMMTNX,
     +          LMMTGA
      PARAMETER(JMMTID=1,JMMTVR=2,JMMTNA=4,JMMTZB=5,JMMTRB=6,JMMTZT=7,
     +          JMMTRT=8,JMMTNX=9,LMMTGA=9)
