*CD tconjj
      INTEGER JTCOID,JTCOVR,JTCODV,JTCOSL,JTCOTO,JTCORW,JTCOSD,JTCOOT,
     +          LTCONA
      PARAMETER(JTCOID=1,JTCOVR=2,JTCODV=4,JTCOSL=5,JTCOTO=6,JTCORW=7,
     +          JTCOSD=8,JTCOOT=9,LTCONA=9)
