      SUBROUTINE ADRZ(IV)
C------------------------------------------
C   B. BLOCH-DEVAUX 850910
C!    Draw the R-Z cut view of ALEPH in view bank #iv
C
C   Called by    ADINIT , GUVIEW                 from this .HLB
C   Calls  GEANT3 drawing routines
C
C ---------------------------------------------------------
      SAVE
      COMMON/GCDRAW/NGMNOD,MGXNOD,NGMND1,LGVVER,LGVHOR,MGAXV,IGPICK,
     + MGLEVV,MGLEVH,NGWCUT,JGNAM,JGMOT,JGXON,JGBRO,JGDUP,JGSCA,
     + JGDVM,JGPSM,
     + JGNAM1,JGMOT1,JGXON1,JGBRO1,JGDUP1,JGSCA1,JGULEV,JGVLEV,
     + LGOKTB(16),
     + GRMAT0(10),GTRAN0(3),IGRNUM,GSIN(41),GCOS(41),GSNPSI,GCSPSI,
     + GTHETA,GPHI,GPSI,GU0,GV0,GSCU,GSCV,NGGVIE,
     + IGCTFL,IGCUT,GCTHET,GCPHI,GDCUT,NGSURF,IGSURF,
     + GZUA,GZVA,GZUB,GZVB,GZUC,GZVC,GPLTRX,GPLTRY,
     + LGINAT,LGINAP,IGXATT,IGTHRZ,IGPRJ,GDPERS,IGTR3D,IGKHIT,IGOBJ,
     + LGINBU,
     + MGAXGU,MGORGU,MGAXGS,MGORGS,MGAXTU,MGORTU,MGAXTS,MGORTS,
     + IGU,IGS,IGTU,IGTS,NGKVIE,IGVIEW,
     + NGOPEN,IGMR,IGPION,IGTROP,
     + GDUMMY(19)
C
      CALL GDELET(IV)
      CALL GDOPEN(IV)
      XX0=0.2
      CALL GDRAWC('ALEF',1,XX0,GU0,GV0,GSCU,GSCV)
      XTEXT=10.*GPLTRX/20.
      YTEXT=1. *GPLTRY/20.
      CSIZE=0.4*GPLTRY/20.
      CALL GDRAWT(XTEXT,YTEXT,'R-Z SIDE  VIEW AT X=0.$',
     1            CSIZE,0.,2,0)
      CALL GDCLOS
      RETURN
      END
