      SUBROUTINE ADVIEW
C------------------------------------------------------------------
C B. BLOCH-DEVAUX  - 850910
C!  Draw two typical cut views of ALEF with header and text
C
C   Called by user   in ASCEVE   from this .HLB
C   Calls  GEANT3 drawing routines
C ---------------------------------------------------------
      SAVE
      PARAMETER (LFIL=6)
      COMMON /IOCOM/   LGETIO,LSAVIO,LGRAIO,LRDBIO,LINPIO,LOUTIO
      DIMENSION LUNIIO(LFIL)
      EQUIVALENCE (LUNIIO(1),LGETIO)
      COMMON /IOKAR/   TFILIO(LFIL),TFORIO(LFIL)
      CHARACTER TFILIO*60, TFORIO*4
C
      COMMON/GCDRAW/NGMNOD,MGXNOD,NGMND1,LGVVER,LGVHOR,MGAXV,IGPICK,
     + MGLEVV,MGLEVH,NGWCUT,JGNAM,JGMOT,JGXON,JGBRO,JGDUP,JGSCA,
     + JGDVM,JGPSM,
     + JGNAM1,JGMOT1,JGXON1,JGBRO1,JGDUP1,JGSCA1,JGULEV,JGVLEV,
     + LGOKTB(16),
     + GRMAT0(10),GTRAN0(3),IGRNUM,GSIN(41),GCOS(41),GSNPSI,GCSPSI,
     + GTHETA,GPHI,GPSI,GU0,GV0,GSCU,GSCV,NGGVIE,
     + IGCTFL,IGCUT,GCTHET,GCPHI,GDCUT,NGSURF,IGSURF,
     + GZUA,GZVA,GZUB,GZVB,GZUC,GZVC,GPLTRX,GPLTRY,
     + LGINAT,LGINAP,IGXATT,IGTHRZ,IGPRJ,GDPERS,IGTR3D,IGKHIT,IGOBJ,
     + LGINBU,
     + MGAXGU,MGORGU,MGAXGS,MGORGS,MGAXTU,MGORTU,MGAXTS,MGORTS,
     + IGU,IGS,IGTU,IGTS,NGKVIE,IGVIEW,
     + NGOPEN,IGMR,IGPION,IGTROP,
     + GDUMMY(19)
C
      ISEL=111110
      CSIZE=0.4*GPLTRY/20.
C
C   X-Y view
C
      CALL ICLRWK(0,0)
      CALL GDOPT('THRZ','OFF ')
      IGCUT=3
      CALL GDSHOW(1)
      CALL GDXYZ(0)
      CALL GDHEAD(ISEL,'$',CSIZE)
C
C   R-Z view
C
      CALL ICLRWK(0,0)
      CALL GDOPT('THRZ','ON  ')
      IGCUT=1
      CALL GDSHOW(2)
      CALL GDXYZ(0)
      CALL GDHEAD(ISEL,'$',CSIZE)
C
      RETURN
      END
