      SUBROUTINE ECBOOK
C.-----------------------------------------------------------------
C
C! Book ECAL histograms
C.-----------------------------------------------------------------
      SAVE
C
      PARAMETER (LOFFMC = 1000)
      PARAMETER (LHIS=20, LPRI=20, LTIM=6, LPRO=6, LRND=3)
      PARAMETER (LBIN=20, LST1=LBIN+3, LST2=3)
      PARAMETER (LSET=15, LTCUT=5, LKINP=20)
      PARAMETER (LDET=9,  LGEO=LDET+4, LBGE=LGEO+5)
      PARAMETER (LCVD=10, LCIT=10, LCTP=10, LCEC=15, LCHC=10, LCMU=10)
      PARAMETER (LCLC=10, LCSA=10, LCSI=10)
      COMMON /JOBCOM/   JDATJO,JTIMJO,VERSJO
     &                 ,NEVTJO,NRNDJO(LRND),FDEBJO,FDISJO
     &                 ,FBEGJO(LDET),TIMEJO(LTIM),NSTAJO(LST1,LST2)
     &                 ,IDB1JO,IDB2JO,IDB3JO,IDS1JO,IDS2JO
     &                 ,MBINJO(LST2),MHISJO,FHISJO(LHIS)
     &                 ,IRNDJO(LRND,LPRO)
     &                 ,IPRIJO(LPRI),MSETJO,IRUNJO,IEXPJO,AVERJO
     3                 ,MPROJO,IPROJO(LPRO),MGETJO,MSAVJO,TIMLJO,IDATJO
     5                 ,TCUTJO(LTCUT),IBREJO,NKINJO,BKINJO(LKINP),IPACJO
     6                 ,IDETJO(LDET),IGEOJO(LGEO),LVELJO(LGEO)
     7                 ,ICVDJO(LCVD),ICITJO(LCIT),ICTPJO(LCTP)
     8                 ,ICECJO(LCEC),ICHCJO(LCHC),ICLCJO(LCLC)
     9                 ,ICSAJO(LCSA),ICMUJO(LCMU),ICSIJO(LCSI)
     &                 ,FGALJO,FPARJO,FXXXJO,FWRDJO,FXTKJO,FXSHJO,CUTFJO
     &                 ,IDAFJO,IDCHJO,TVERJO
      LOGICAL FDEBJO,FDISJO,FHISJO,FBEGJO,FGALJO,FPARJO,FXXXJO,FWRDJO
     &       ,FXTKJO,FXSHJO
      COMMON /JOBKAR/   TITLJO,TSETJO(LSET),TPROJO(LPRO)
     1                 ,TKINJO,TGEOJO(LBGE),TRUNJO
      CHARACTER TRUNJO*60
      CHARACTER*4 TKINJO,TPROJO,TSETJO,TITLJO*40
      CHARACTER*2 TGEOJO
C
      PARAMETER (LERR=20)
      COMMON /JOBERR/   ITELJO,KERRJO,NERRJO(LERR)
      COMMON /JOBCAR/   TACTJO
      CHARACTER*6 TACTJO
C
      INTEGER LMHLEN, LMHCOL, LMHROW
      PARAMETER (LMHLEN=2, LMHCOL=1, LMHROW=2)
C
      COMMON /BCS/   IW(1000)
      INTEGER IW
      REAL RW(1000)
      EQUIVALENCE (RW(1),IW(1))
C
      COMMON /NAMCOM/   NARUNH, NAPART, NAEVEH, NAVERT, NAKINE, NAKRUN
     &                 ,NAKEVH, NAIMPA, NAASEV, NARUNE, NAKLIN, NARUNR
     &                 ,NAKVOL, NAVOLU
      EQUIVALENCE (NAPAR,NAPART)
C
      PARAMETER (NECST = 30)
      COMMON/ ECSTAT / NECONT(NECST),ECCONT(NECST)
C
C    booking of histograms
C
      IF(TKINJO.EQ.'LUND'.OR.TKINJO.EQ.'USER')  THEN
           XMAX=BKINJO(4)*500.
       ELSE IF(TKINJO.EQ.'PART') THEN
           XMAX = BKINJO(4)*1000.
       ENDIF
       EMAX=0.05
       IDSKI=439
       NB1SKI=50
       NB2SKI=100
       SKIZ=0.
       ZLMAX1=5.
       ZLMAX2=20.
       NPSKI=45
       ZPSKI=45.
       CALL HBOOK2(IDSKI,'TRACK ELTS PHOTONS : LI VS EI (CM,KEV)$',
     &NB1SKI,SKIZ,EMAX,NB1SKI,SKIZ,ZLMAX2,SKIZ)
       CALL HBOOK2(IDSKI+1,'TRACK ELTS (E+,E-) : LI VS EI (CM,KEV)$',
     &NB1SKI,SKIZ,EMAX,NB1SKI,SKIZ,ZLMAX1,SKIZ)
       CALL HBOOK1(IDSKI+2,'ANALOG SIGNAL BARREL S1 + S2 (MEV)$',NB2SKI,
     &ZLMAX1,ZLMAX1,SKIZ)
       CALL HBOOK1(IDSKI+3,'EC ANALOG SIGNAL BARREL S3 (MEV)$',NB2SKI,
     &ZLMAX1,ZLMAX1,SKIZ)
       CALL HBOOK1(IDSKI+4,'ANALOG SIGNAL ENDCAP S1 + S2 (MEV)$',NB2SKI,
     &ZLMAX1,ZLMAX1,SKIZ)
       CALL HBOOK1(IDSKI+5,'ANALOG SIGNAL ENDCAP S3 (MEV)$',NB2SKI,
     &ZLMAX1,ZLMAX1,SKIZ)
       CALL HBOOK2(IDSKI+6,'ODD VS EVEN PLANES (ANALOG.) (MEV)$',
     &NB1SKI,SKIZ,XMAX,NB1SKI,SKIZ,XMAX,SKIZ)
       CALL HBOOK1(IDSKI+7,'TOTAL ANALOG SIGNAL ON THE WIRES (MEV)$',
     &NB2SKI,ZLMAX1,ZLMAX1,SKIZ)
       CALL HBOOK1(IDSKI+8,'LONG. PROFILE OF WIRES (ANALOG.) (MEV)$',
     &NPSKI,SKIZ,ZPSKI,SKIZ)
       CALL HBOOK1(IDSKI+9,'NB. OF HITS/WIRE PLANES (ANALOG.)$',
     &NPSKI,SKIZ,ZPSKI,SKIZ)
       CALL HBOOK1(IDSKI+10,'ANALOG SIGNAL IN TOWERS ALL STACKS (MEV)$',
     &NB2SKI,ZLMAX1,ZLMAX1,SKIZ)
       CALL HBOOK1(IDSKI+11,'ANALOG SIGNAL IN TOWERS STACK1 (MEV)$',
     &NB2SKI,ZLMAX1,ZLMAX1,SKIZ)
       CALL HBOOK1(IDSKI+12,'ANALOG SIGNAL IN TOWERS STACK2 (MEV)$',
     &NB2SKI,ZLMAX1,ZLMAX1,SKIZ)
       CALL HBOOK1(IDSKI+13,'ANALOG SIGNAL IN TOWERS STACK3 (MEV)$',
     &NB2SKI,ZLMAX1,ZLMAX1,SKIZ)
       CALL HBOOK2(IDSKI+16,'ODD VS EVEN PLANES (DIGIT.) (MEV)$',
     &NB1SKI,SKIZ,XMAX,NB1SKI,SKIZ,XMAX,SKIZ)
       CALL HBOOK1(IDSKI+17,'TOTAL DIGITAL SIGNAL ON THE WIRES (MEV)$',
     &NB2SKI,ZLMAX1,ZLMAX1,SKIZ)
       CALL HBOOK1(IDSKI+18,'LONGIT. PROFILE OF WIRES (DIGIT.) (MEV)$',
     &NPSKI,SKIZ,ZPSKI,SKIZ)
       CALL HBOOK1(IDSKI+19,'NUMBER OF HITS/WIRE PLANES (DIGIT)$',
     &NPSKI,SKIZ,ZPSKI,SKIZ)
       CALL HBOOK1(IDSKI+20,'DIGIT. SIGNAL IN TOWERS ALL STACKS (MEV)$',
     &NB2SKI,ZLMAX1,ZLMAX1,SKIZ)
       CALL HBOOK1(IDSKI+21,'DIGIT. SIGNAL IN TOWERS STACK1 (MEV)$',
     &NB2SKI,ZLMAX1,ZLMAX1,SKIZ)
       CALL HBOOK1(IDSKI+22,'DIGIT. SIGNAL IN TOWERS STACK2 (MEV)$',
     &NB2SKI,ZLMAX1,ZLMAX1,SKIZ)
       CALL HBOOK1(IDSKI+23,'DIGIT. SIGNAL IN TOWERS STACK3 (MEV)$',
     &NB2SKI,ZLMAX1,ZLMAX1,SKIZ)
       CALL HBOOK1(IDSKI+24,'EC DIGIT. NB OF HIT TOWERS/EVT$',NB2SKI,
     &ZLMAX1,ZLMAX1,SKIZ)
       CALL HIDOPT(IDSKI+2,'1EVL','AEVL')
       CALL HIDOPT(IDSKI+3,'1EVL','AEVL')
       CALL HIDOPT(IDSKI+4,'1EVL','AEVL')
       CALL HIDOPT(IDSKI+5,'1EVL','AEVL')
       CALL HIDOPT(IDSKI+7,'1EVL','AEVL')
       CALL HIDOPT(IDSKI+9,'1EVL','AEVL')
       CALL HIDOPT(IDSKI+10,'1EVL','AEVL')
       CALL HIDOPT(IDSKI+11,'1EVL','AEVL')
       CALL HIDOPT(IDSKI+12,'1EVL','AEVL')
       CALL HIDOPT(IDSKI+13,'1EVL','AEVL')
       CALL HIDOPT(IDSKI+17,'1EVL','AEVL')
       CALL HIDOPT(IDSKI+19,'1EVL','AEVL')
       CALL HIDOPT(IDSKI+20,'1EVL','AEVL')
       CALL HIDOPT(IDSKI+21,'1EVL','AEVL')
       CALL HIDOPT(IDSKI+22,'1EVL','AEVL')
       CALL HIDOPT(IDSKI+23,'1EVL','AEVL')
       CALL HIDOPT(IDSKI+24,'1EVL','AEVL')
      END
