      SUBROUTINE EHGEOB (ILAY,X,Y,Z,U,V,W,XSEP,YSEP,ZTB,DTB,MFLSI)
C.----------------------------------------------------------------
C R.CLIFFT        mod Rumpf
C! Edges geom for barrel mod.
C *** CALCULATE EDGES GEOMETRY FOR BARREL MODULES
C Calls EHBARI
C.----------------------------------------------------------------
      SAVE
      REAL PI, TWOPI, PIBY2, PIBY3, PIBY4, PIBY6, PIBY8, PIBY12
      REAL RADEG, DEGRA
      REAL CLGHT, ALDEDX
      INTEGER NBITW, NBYTW, LCHAR
      PARAMETER (PI=3.141592653589)
      PARAMETER (RADEG=180./PI, DEGRA=PI/180.)
      PARAMETER (TWOPI = 2.*PI , PIBY2 = PI/2., PIBY4 = PI/4.)
      PARAMETER (PIBY6 = PI/6. , PIBY8 = PI/8.)
      PARAMETER (PIBY12= PI/12., PIBY3 = PI/3.)
      PARAMETER (CLGHT = 29.9792458, ALDEDX = 0.000307)
      PARAMETER (NBITW = 32 , NBYTW = NBITW/8 , LCHAR = 4)
C
      PARAMETER  (D360=TWOPI*RADEG   ,D180=PI*RADEG   ,D90=0.5*D180)
      PARAMETER  (D45=0.5*D90   ,D15=D45/3.   ,D210=7.*D90/3.)
      PARAMETER  (D225=D180+D45   ,D270=D180+D90  ,D7P5=0.5*D15)
      PARAMETER(LSENV=30)
      PARAMETER (LIMVOL=17)
C
      COMMON/AGCONS/ IAGROT,IAGMAT,IAGMED,IAGFHB,IAGSLV,IAGSEN(LSENV,2)
     2      , NAGIMP,LAGIMP(3,LIMVOL)
C
       COMMON /WRKSPC/ WSPACE(88320)
      PARAMETER (LPTAB=50)
      DIMENSION PTAB(LPTAB),JTAB(LPTAB)
      EQUIVALENCE (PTAB(1),JTAB(1),WSPACE(1))
C
C
      DATA NCALL /0/
      IF (NCALL.EQ.0)                   THEN
        NCALL = 1
        DTB=0.
        ZTB=0.
        TPHB2=TAN(PIBY12)
        CALL EHBARI(XMAX1,XMAX2,YMAX,ZMAX1,ZMAX2)
      ENDIF
      MFLSI=0
C
C *** EDGE SEPERATION FOR CURRENT COORDS
C
      IWSI=SIGN(1.,W)
      IF(ILAY.EQ.1) THEN
        XMAX = XMAX1
        ZMAX = ZMAX1
      ELSE
        XMAX = XMAX2
        ZMAX = ZMAX2
      ENDIF
      XWH=XMAX-(ZMAX-Z)*TPHB2
      YSEPC=YMAX- ABS(Y)
      XSEPC=XWH-ABS(X)
C
C *** EDGE SEPERATION AT BACK OR FRONT OF MODULE
C
      ZTB=ZMAX-IWSI*Z
      ZB=IWSI*ZMAX
      IF (ABS(W) .GT. 1.) W = SIGN(1.,W)
      TH=ACOS(W)
      PH=ATAN2(U,V)
      TANTH = TAN(TH)
      XB=X+ZTB*TANTH*SIN(PH)
      YB=Y+ZTB*TANTH*COS(PH)
      XSEPB=XMAX+ZMAX*TPHB2*(IWSI-1)-ABS(XB)
      YSEPB=YMAX-ABS(YB)
C
      IF(XSEPB.LE.0..OR.YSEPB.LE.0..OR.XSEPC.LE.0..OR.YSEPC.LE.0.)
     &   RETURN
      YSEP=0.5*(YSEPC+YSEPB)
      XSEP=0.5*(XSEPC+XSEPB)
C
C *** CALCULATE PATH LENGTH IN MODULE
C
      DTB=SQRT((X-XB)**2+(Y-YB)**2+(Z-ZB)**2)
      MFLSI=1
C
 50   CONTINUE
      RETURN
      END
