      SUBROUTINE HCSETP
C------------------------------------------------
C
C!Prepare information from track banks for the parametrization routines
C!Transform coordinates to the local frame : z-axis is
C!    always normal to the wire planes
C!
C!         Authors   :G.Catanesi,F.Romano 86/09/01
C!
C!         Called by : CAHMOD
C -----------------------------------
      SAVE
      PARAMETER (LOFFMC = 1000)
      PARAMETER (LHIS=20, LPRI=20, LTIM=6, LPRO=6, LRND=3)
      PARAMETER (LBIN=20, LST1=LBIN+3, LST2=3)
      PARAMETER (LSET=15, LTCUT=5, LKINP=20)
      PARAMETER (LDET=9,  LGEO=LDET+4, LBGE=LGEO+5)
      PARAMETER (LCVD=10, LCIT=10, LCTP=10, LCEC=15, LCHC=10, LCMU=10)
      PARAMETER (LCLC=10, LCSA=10, LCSI=10)
      COMMON /JOBCOM/   JDATJO,JTIMJO,VERSJO
     &                 ,NEVTJO,NRNDJO(LRND),FDEBJO,FDISJO
     &                 ,FBEGJO(LDET),TIMEJO(LTIM),NSTAJO(LST1,LST2)
     &                 ,IDB1JO,IDB2JO,IDB3JO,IDS1JO,IDS2JO
     &                 ,MBINJO(LST2),MHISJO,FHISJO(LHIS)
     &                 ,IRNDJO(LRND,LPRO)
     &                 ,IPRIJO(LPRI),MSETJO,IRUNJO,IEXPJO,AVERJO
     3                 ,MPROJO,IPROJO(LPRO),MGETJO,MSAVJO,TIMLJO,IDATJO
     5                 ,TCUTJO(LTCUT),IBREJO,NKINJO,BKINJO(LKINP),IPACJO
     6                 ,IDETJO(LDET),IGEOJO(LGEO),LVELJO(LGEO)
     7                 ,ICVDJO(LCVD),ICITJO(LCIT),ICTPJO(LCTP)
     8                 ,ICECJO(LCEC),ICHCJO(LCHC),ICLCJO(LCLC)
     9                 ,ICSAJO(LCSA),ICMUJO(LCMU),ICSIJO(LCSI)
     &                 ,FGALJO,FPARJO,FXXXJO,FWRDJO,FXTKJO,FXSHJO,CUTFJO
     &                 ,IDAFJO,IDCHJO,TVERJO
      LOGICAL FDEBJO,FDISJO,FHISJO,FBEGJO,FGALJO,FPARJO,FXXXJO,FWRDJO
     &       ,FXTKJO,FXSHJO
      COMMON /JOBKAR/   TITLJO,TSETJO(LSET),TPROJO(LPRO)
     1                 ,TKINJO,TGEOJO(LBGE),TRUNJO
      CHARACTER TRUNJO*60
      CHARACTER*4 TKINJO,TPROJO,TSETJO,TITLJO*40
      CHARACTER*2 TGEOJO
C
      PARAMETER (LERR=20)
      COMMON /JOBERR/   ITELJO,KERRJO,NERRJO(LERR)
      COMMON /JOBCAR/   TACTJO
      CHARACTER*6 TACTJO
C
      REAL PI, TWOPI, PIBY2, PIBY3, PIBY4, PIBY6, PIBY8, PIBY12
      REAL RADEG, DEGRA
      REAL CLGHT, ALDEDX
      INTEGER NBITW, NBYTW, LCHAR
      PARAMETER (PI=3.141592653589)
      PARAMETER (RADEG=180./PI, DEGRA=PI/180.)
      PARAMETER (TWOPI = 2.*PI , PIBY2 = PI/2., PIBY4 = PI/4.)
      PARAMETER (PIBY6 = PI/6. , PIBY8 = PI/8.)
      PARAMETER (PIBY12= PI/12., PIBY3 = PI/3.)
      PARAMETER (CLGHT = 29.9792458, ALDEDX = 0.000307)
      PARAMETER (NBITW = 32 , NBYTW = NBITW/8 , LCHAR = 4)
C
      PARAMETER (LFIL=6)
      COMMON /IOCOM/   LGETIO,LSAVIO,LGRAIO,LRDBIO,LINPIO,LOUTIO
      DIMENSION LUNIIO(LFIL)
      EQUIVALENCE (LUNIIO(1),LGETIO)
      COMMON /IOKAR/   TFILIO(LFIL),TFORIO(LFIL)
      CHARACTER TFILIO*60, TFORIO*4
C
      PARAMETER (LETRK=27, LITRK=11, LNTRK=10)
      COMMON /TRKCOM/   ITRKEL(LITRK), TRKELE(LETRK), TRKNXT(LNTRK)
     &                , FTRHAD
      LOGICAL FTRHAD
      COMMON /TRKKAR/   TRKVOL
      CHARACTER*4 TRKVOL
C
      COMMON /HCCOUN/NHCC01,NHCC02,NHCC03,NHCC04,NHCC05,HCEAVE ,HCANST,
     +               HCEPOR(3) ,FHCDEB,FHCDB1,FHCDB2
      LOGICAL FHCDEB,FHCDB1,FHCDB2
C
      PARAMETER (LPHC=3,LSHC=3,LPECA=1,LPECB=3,LPBAR=2)
      PARAMETER (LHCNL=23,LHCSP=2,LHCTR=62,LHCRE=3)
      PARAMETER (LHCNO = 3)
      PARAMETER (LPHCT = 4)
      PARAMETER (LPHCBM = 24,LPHCES = 6)
      COMMON/HCGEGA/ HCSMTH,HCIRTH,HCLSLA,HCTUTH, NHCINL,NHCOUL,NHCTRE,
     +HCPHOF,NHCTU1(LHCNL), HCLARA(LHCNL),HCLAWI(LHCNL),IHCREG(LHCTR),
     +HCZMIN(LPHC),HCZMAX(LPHC),HCRMIN(LPHC), HCRMAX(LPHC),HCTIRF(LPHC),
     +NHCPLA(LPHC), HCWINO(LPHC),HCLTNO(LPHC)
      COMMON/HCLOC/HCPDIP,HCPPHI,HCPACX,HCPACY,HCPACZ ,HCPAX0,HCPAY0,
     +             HCPAZ0,FHADRC,FHCPRJ ,IHCPOR,IHCMOD,IHCIPL
      LOGICAL FHADRC,FHCPRJ
      COMMON /HCCONG/ HCTUAC,HCSTDT,HCADCE,HADCMX,HCPFAC,
     &                HCTINS,RHBAMN,ZHECMN,ZHBAMX,HSTREA,HSTUST,
     +                NHCFSS,HCFSS1,HCFSS2,HCFLSS(100)
     &               ,HTLEMX,HCTEFF(3),HPINDU
C
      PARAMETER(LDIM=3)
      DIMENSION XX0(LDIM),XX1(LDIM)
C.....................
      UNO=1.
      IHCMOD=ITRKEL(10)
C
      IF(IHCPOR.EQ.LPBAR) THEN
C
C.....Rotate to the module frame
         DO 10 I=1,LDIM
            XX0(I)=0.
            XX1(I)=0.
            DO 10 J=1,LDIM
C
               XX0(I)=TRKELE(J)*TRKELE(14+3*I+J)+XX0(I)
               XX1(I)=(TRKELE(J+3)+TRKELE(J))*TRKELE(14+3*I+J)+XX1(I)
   10    CONTINUE
C.....
C     Transform to the 'parametrization' frame
C.....
C........in the barrel
C.....
         IF(MOD(IHCMOD,2).EQ.1) UNO=-1.
         HCPAX0 = UNO*XX0(3)
         HCPAY0 = UNO*XX0(1)
         HCPAZ0 = XX0(2)-RHBAMN
         X1 = UNO*XX1(3)
         Y1 = UNO*XX1(1)
         Z1 = XX1(2)-RHBAMN
C
      ELSE
C.....
C........in the endcap
C.....
         IF(IHCPOR.EQ.LPECB) UNO=-1.
         HCPAX0 = TRKELE(1)
         HCPAY0 = UNO*TRKELE(2)
         HCPAZ0 = UNO*TRKELE(3)-ZHECMN
         X1 = TRKELE(1)+TRKELE(4)
         Y1 = UNO*(TRKELE(2)+TRKELE(5))
         Z1 = UNO*(TRKELE(3)+TRKELE(6))-ZHECMN
      ENDIF
C
C...find theta-phi angles in the new system
C
      ALXYZ = SQRT((X1-HCPAX0)**2+(Y1-HCPAY0)**2+(Z1-HCPAZ0)**2)

      HCPACX =(X1-HCPAX0)/ALXYZ
      HCPACY =(Y1-HCPAY0)/ALXYZ
      HCPACZ =(Z1-HCPAZ0)/ALXYZ
      HCPDIP =ASIN(HCPACZ)
      HCPPHI =ATG(HCPACY,HCPACX)
C.....
      IF(FHCDB2)THEN
         WRITE(LOUTIO,510)ITRKEL(1)
         WRITE (LOUTIO,500) HCPAX0,HCPAY0,HCPAZ0,HCPACX,HCPACY,HCPACZ ,
     +   HCPDIP*RADEG,HCPPHI*RADEG,IHCMOD
      ENDIF
      RETURN

  500 FORMAT (/1X,'+++HCSETP+++ shower starting pt. ',3F10.3,3F10. 6/3X,
     +'Theta phi in show.ref.sys. ',2F7.2,3X, ' starting mod. ',I4)
  510 FORMAT(1X,'The GEANT track # is ==> ',I6)
      END
