C-------  start of  / NANCOM/ --- NanoDst steering -------------------          
C! XNANO   .TRUE. if input is a NanoDst                                         
C!                                                                              
      LOGICAL XNANO                                                             
      COMMON /NANCOM/XNANO                                                      
C--------------------- end of NANCOM ----------------------------------         
