#! /bin/csh
#==============================================================================
#                                 albank
# 30/08/94                                                            F.Blin
#=============================================================================
# Procedure to print /aleph/doc/bos.bank on XEROXDD
# deliver default = X1    
# to change deliver parameter -r        [eg: albank -r X0]
#=============================================================================
set n_copy = 1
set deliver = "X1"
if ( $#argv > 0) then
  switch ( $argv[1])

  case -r:
  set deliver = $argv[2]
  shift
  breaksw

endsw
endif 

~fblxu/doc/xprdoc -cc -d xeroxdd -r ${deliver} -cop ${n_copy} /aleph/doc/bos.bank
exit
