*CD esdajj
      INTEGER JESDTJ,JESDFI,JESDDK,JESDME,JESDSC,JESDIO,JESDDI,JESDER,
     +          JESDEC,JESDED,JESDES,LESDAA
      PARAMETER(JESDTJ=1,JESDFI=2,JESDDK=3,JESDME=4,JESDSC=5,JESDIO=6,
     +          JESDDI=7,JESDER=8,JESDEC=9,JESDED=10,JESDES=11,
     +          LESDAA=11)
