*CD hbgejj
      INTEGER JHBGID,JHBGVR,JHBGYI,JHBGYX,JHBGZX,JHBGIT,JHBGRA,JHBGPO,
     +          JHBGHB,LHBGEA
      PARAMETER(JHBGID=1,JHBGVR=2,JHBGYI=4,JHBGYX=5,JHBGZX=6,JHBGIT=7,
     +          JHBGRA=8,JHBGPO=9,JHBGHB=10,LHBGEA=10)
