*CD hsdajj
      INTEGER JHSDTI,JHSDPI,JHSDSN,JHSDDE,JHSDMN,JHSDSC,JHSDRN,JHSDCN,
     +          JHSDNS,LHSDAA
      PARAMETER(JHSDTI=1,JHSDPI=2,JHSDSN=3,JHSDDE=4,JHSDMN=5,JHSDSC=6,
     +          JHSDRN=7,JHSDCN=8,JHSDNS=9,LHSDAA=9)
