*CD mbagjj
      INTEGER JMBAID,JMBAVR,JMBASU,JMBANB,JMBATH,JMBALE,JMBAR1,JMBAR2,
     +          JMBAPD,JMBAY1,JMBAY2,LMBAGA
      PARAMETER(JMBAID=1,JMBAVR=2,JMBASU=4,JMBANB=5,JMBATH=6,JMBALE=7,
     +          JMBAR1=8,JMBAR2=9,JMBAPD=10,JMBAY1=11,JMBAY2=12,
     +          LMBAGA=12)
