*CD mbsgjj
      INTEGER JMBSID,JMBSVR,JMBSNO,JMBSVO,JMBSZC,JMBSRC,JMBSDE,JMBST1,
     +          JMBST2,JMBSTA,JMBSNA,JMBSK1,JMBSK2,LMBSGA
      PARAMETER(JMBSID=1,JMBSVR=2,JMBSNO=4,JMBSVO=5,JMBSZC=6,JMBSRC=7,
     +          JMBSDE=8,JMBST1=9,JMBST2=10,JMBSTA=11,JMBSNA=12,
     +          JMBSK1=13,JMBSK2=14,LMBSGA=14)
