*CD mhitjj
      INTEGER JMHISC,JMHISN,JMHILN,JMHIXL,JMHIYL,JMHIRH,JMHITH,JMHIPH,
     +          LMHITA
      PARAMETER(JMHISC=1,JMHISN=2,JMHILN=3,JMHIXL=4,JMHIYL=5,JMHIRH=6,
     +          JMHITH=7,JMHIPH=8,LMHITA=8)
