*CD mmagjj
      INTEGER JMMAID,JMMAVR,JMMASU,JMMANS,JMMAZ0,JMMAPD,JMMATH,JMMAPI,
     +          JMMADS,JMMAZ1,JMMATB,LMMAGA
      PARAMETER(JMMAID=1,JMMAVR=2,JMMASU=4,JMMANS=5,JMMAZ0=6,JMMAPD=7,
     +          JMMATH=8,JMMAPI=9,JMMADS=10,JMMAZ1=11,JMMATB=12,
     +          LMMAGA=12)
