/*
 * External entry points redefined for UNIX.
 */
#define dgalef     dgalef_
#define dgalph     dgalph_
#define dgarcl     dgarcl_
#define dgarea     dgarea_
#define dgbtit     dgbtit_
#define dgchkx     dgchkx_
#define dgcler     dgcler_
#define dgclev     dgclev_
#define dgclpa     dgclpa_
#define dgclwk     dgclwk_
#define dgcome     dgcome_
#define dgcsme     dgcsme_
#define dgcurg     dgcurg_
#define dgcwin     dgcwin_
#define dgdash     dgdash_
#define dgdwin     dgdwin_
#define dgdfcu     dgdfcu_
#define dgdmsk     dgdmsk_
#define dgdraw     dgdraw_
#define dgeast     dgeast_
#define dgedme     dgedme_
#define dgetst     dgetst_
#define dgexec     dgexec_
#define dgfime     dgfime_
#define dgfxcu     dgfxcu_
#define dggcur     dggcur_
#define dggtcu     dggtcu_
#define dghlev     dghlev_
#define dghlp      dghlp_
#define dghlp_line dghlp_line_
#define dghmrk     dghmrk_
#define dgiast     dgiast_
#define dgifoc     dgifoc_
#define dginit     dginit_
#define dglbut     dglbut_
#define dglevl     dglevl_
#define dglevs     dglevs_
#define dglinf     dglinf_
#define dglinm     dglinm_
#define dgmbof     dgmbof_
#define dgmbon     dgmbon_
#define dgmkme     dgmkme_
#define dgname     dgname_
#define dgnsiz     dgnsiz_
#define dgooba     dgooba_
#define dgopme     dgopme_
#define dgplot     dgplot_
#define dgpntr     dgpntr_
#define dgpoin     dgpoin_
#define dgpop      dgpop_
#define dgprcl     dgprcl_
#define dgprnt     dgprnt_
#define dgprop     dgprop_
#define dgpst0     dgpst0_
#define dgpst1     dgpst1_
#define dgqinf     dgqinf_
#define dgqume     dgqume_
#define dgrar      dgrar_
#define dgrmet     dgrmet_
#define dgrsme     dgrsme_
#define dgsbut     dgsbut_
#define dgscur     dgscur_
#define dgsdmp     dgsdmp_
#define dgsetc     dgsetc_
#define dgsms1     dgsms1_
#define dgsmsk     dgsmsk_
#define dgspme     dgspme_
#define dgsppt     dgsppt_
#define dgstev     dgstev_
#define dgstop     dgstop_
#define dgstr1     dgstr1_
#define dgstr2     dgstr2_
#define dgswin     dgswin_
#define dgswpt     dgswpt_
#define dgsync     dgsync_
#define dgtdir     dgtdir_
#define dgtext     dgtext_
#define dgtflg     dgtflg_
#define dgtint     dgtint_
#define dgtlnx     dgtlnx_
#define dgtlnx_lc  dgtlnx_lc_
#define dgtxtf     dgtxtf_
#define dgtxtg     dgtxtg_
#define dgtxtm     dgtxtm_
#define dguxcu     dguxcu_
#define dgwmov     dgwmov_
#define dgwtlp     dgwtlp_
#define dgzoom     dgzoom_
#define dqcl0      dqcl0_
#define dqclp      dqclp_
#define dqhlp      dqhlp_
#define dqzrb      dqzrb_
#define ucopy      ucopy_
#define scrsize    scrsize_
#define tty_reset  tty_reset_
#define tty_set    tty_set_
#define dgfish     dgfish_
#define dgtim0     dgtim0_
#define dgtim1     dgtim1_
#define idate2     idate2_
