C! YTOP vertex parameters
      COMMON/YVTXTO/ NEVTOP,NVXTOP,NVXLOT,
     &  VXTOP0(3,MXVTOP,MXVTYP),VVXTOP(6,MXVTOP,MXVTYP),
     &  CHVTOP(MXVTOP,MXVTYP),DRVTOP(MXVTOP,MXVTYP),
     &  MULTVX(MXVTOP,MXVTYP),
     &  IXTRVT(MKDIMM,MXVTOP,MXVTYP),IXVQLI(MAXTRK,MXVTOP),
     &  CHIVXI(MAXTRK,MXVTOP),
     &  NLOTRK,ILOTRK(MAXTRK),
     &  JTRVXA(MAXTRK,MXVTYP),NTRVXA(MAXTRK,MXVTYP),
     &  NEVVTX(3,MXVTOP),NMULVX(MXMULS,MXVTYP),
     &  NMULTA(MXVTOP,MXVTYP),MULMAT(MXMULS,MXMULS)
#if defined(DOC)
C     NVXTOP ....... # OF  VERTICES
C     NVXLOT ....... # OF VTX WITH LEFT OVER DISPLACED TRKS
C     VXTOP0 ........ VERTEX COORDINATES
C     VVXTOP ....... VERTEX VARIANCES
C     CHVTOP(I,K) .... CHISQ OF VERTEX I (K=1 BEFORE, K=2 AFTER
C                      ADDING TRACKS)
C     DRVTOP(I,K) .... DISTANCE (R) FROM PRIMARY VERTEX
C     MULTVX(I,K) .... MULTIPLICITY OF VERTEX I
C     IXTRVT(MKDIMM,I) .... CODE WORD FOR TRACKS IN VERTEX I
C     IXVQLI(J,I) .. QLINE # OF J'TH TRACK IN VERTEX I
C     CHIVXI(L,I) .... VERTEX CHISQ AFTER ADDING L'TH TRACK
C     NLOTRK ....... # OF LEFT OVER (SINGLE) TRACKS
C     ILOTRK ....... INDICES OF LEFT OVER TRACKS
C     JTRVXA(IT) ... MARKER FOR TRACK IT HAS BITS SET FOR VERTICES
C                    TO WHICH IT CAN BE ASSIGNED. 1..PRIM.,
C                    2**IV FOR SECONDARY VERTEX IV
C                    2**(LOV+15) FOR LEFT OVER TRACK VTX CAND  LOV
C     NTRVXA(IT) ... # OF VERTICES TO WHICH TRACK IT CAN BE ASSIGNED
C                    I+100*#OF VTX CAND WITH LEFT OVER TR.TO WHICH ASS.
C     NEVVTX(1,I) .. # OF EV. WITH I-1 VERTICES AND NO LEFT OVER TRKS
C           (2,I) ..       "          WITH  LEFT OVER TRKS FORMING VTX
C           (3,I) ..       "          WITH  SINGLE LEFT OVER TRKS
C     NMULVX(I) .... # OF VERTICES WITH MULTIPLICITY I
C     NMULTA(I) .... # OF TRACKS ASSIGNED TO I-1 VERTICES
C     MULMAT(K,L) .. VERTEX MULTIPL. CHANGE FROM K TO L
C
#endif
