#! /bin/sh

$LSB_TRAPSIGS
$LSB_RCP1
$LSB_RCP2
$LSB_RCP3
# LSBATCH: User input
( cat <<_USER_\SCRIPT_
#!/bin/csh
#BSUB -q xu_8nm
#BSUB -J jul308_6_afal14
time /afs/cern.ch/aleph/shared/script/updlib < /afs/cern.ch/aleph/reference/cvs/jul308/jul308_6.input
exec_end:
exit
_USER_SCRIPT_
) > $LSB_CHKFILENAME.shell
chmod u+x $LSB_CHKFILENAME.shell
$LSB_JOBFILENAME.shell
saveExit=$?
/bin/rm -f $LSB_JOBFILENAME.shell
(exit $saveExit)

ExitStat=$?
wait
# LSBATCH: End user input
true
exit `expr $? "|" $ExitStat`
