         COMMON/ MGDMDA/ AZ0PLA,APLADI,APIT16,AZZBOX(NRTYMA),
     +          ARRBOX(NRTYMA),AZTOOT(NRTYMA),ARTOOT(NRTYMA),
     +          MANXST(NRTYMA),MANYST(NRSLMA),MADZFL(NRSLMA),
     +          MAPNTY(NRSLMA),MATAST(NRSLMA),MANAST(NRSLMA),
     +          MAOAST(NRSLMA),AZETAC(NRSLMA),AERREC(NRSLMA),
     +          ADELTC(NRSLMA),AYLEOF(NRPLAN,NRSLMA),
     +          AXOFFS(NRPLAN,NRSLMA),MAVOLU(NRSLMA)
