      FUNCTION KPCOMP (CINP)
CKEY PART /INTERNAL
C----------------------------------------------------------------------
C! Get particle code from QPAR. Input : particle name CINP
C                                                   H.Albrecht 27.11.88
C    Add KPCHEK entry to just test                  T.Burnett  16.16.90
C  Completely rewritten to use LOCTAB and 'QPSP'    J.Boucrot  21.09.93
C----------------------------------------------------------------------
      PARAMETER ( ITPNMX = 2000 )
      CHARACTER*12 FLISPA
      COMMON / PARNA / FLISPA(ITPNMX)
C Start of QCDESH ----------------------- Description in QDATA ---------
      PARAMETER (KCQDET=34, KCQFPA=8, KCQPAR=10, KCQVEC=73, KCQVRT=30,
     & KHE=1, KHMU=2, KHPI=3, KHK=4, KHP=5, KHPHOT=1, KHNHAD=2,
     & KMONTE=-2, KRECO=-1, KLOCKM=14, KSOVT=1, KSCHT=2, KSIST=3,
     & KSAST=4, KSEHT=5, KSV0T=6, KSDCT=7, KSEFT=8, KSNET=9, KSGAT=10,
     & KSJET=11, KSMCT=12, KSREV=13,
     & KSMCV=14, KUNDEF=-12344321, QQPI=3.141593, QQE=2.718282,
     & QQ2PI=QQPI*2., QQPIH=QQPI/2., QQRADP=180./QQPI, QQC=2.997925E10,
     & QQH=6.582173E-25, QQHC=QQH*QQC, QQIRP=.00029979)
      CHARACTER CQDATE*8, CQDWRK*80, CQFHIS*80, CQFOUT*80, CQFWRK*80,
     & CQHTIT*80, CQSEC*3, CQTIME*8, CQUNPK*30, CQVERS*6, CQRLST*800,
     & CQELST*800
      COMMON /QCDEC/ CQDATE, CQDWRK, CQFHIS, CQFOUT, CQFWRK, CQHTIT,
     & CQSEC(14), CQTIME, CQUNPK, CQVERS, CQRLST, CQELST
      COMMON /QCDE/ QELEP, QMFLD ,QMFLDC, QTIME, QTIMEI, QTIMEL,
     & QTIMES, QTIMET, QDHEEC, QDHEEL, QDHEPF, QDHETH, QDHEPH, QDHEEF,
     & QDHEET, QDHET1, QDHEP1, QDHET2, QDHEP2, QDHEE1, QDHEE2, QDHEE3,
     & QKEVRN, QKEVWT, QVXNOM, QVYNOM, QVZNOM, QVXNSG, QVYNSG, QVZNSG,
     & QINLUM, QRINLN, QRINLU, QDBOFS, QEECWI(36), QVXBOM, QVYBOM,
     & QSILUM, QRSLLU, QRSLBK, QRSLEW , QVTXBP(3), QVTEBP(3), QVTSBP(3)
      COMMON /QCDE/  KFOVT, KLOVT, KNOVT, KFCHT, KLCHT, KNCHT, KFIST,
     & KLIST, KNIST, KFAST, KLAST, KNAST, KFEHT, KLEHT, KNEHT, KFV0T,
     & KLV0T, KNV0T, KFDCT, KLDCT, KNDCT, KFEFT, KLEFT, KNEFT, KFNET,
     & KLNET, KNNET, KFGAT, KLGAT, KNGAT, KFJET, KLJET, KNJET, KFMCT,
     & KLMCT, KNMCT, KFREV, KLREV, KNREV, KFMCV, KLMCV, KNMCV, KLUST,
     & KLUSV, KFFRT, KLFRT, KFFRV, KLFRV, KNRET, KNCOT, KFFRD,
     & KLFJET,KLLJET,KLNJET
      COMMON /QCDE/ KBIT(32), KCLACO(KCQFPA), KCLAFR(KCQFPA), KCLARM
     & (KCQFPA), KDEBUG, KEVT, KEXP, KFFILL, KFEOUT, KJOPTN(2,2),
     & KLEOUT, KLROUT, KLOCK0(KLOCKM,2), KLOCK1(KLOCKM,2), KLOCK2(
     & KLOCKM,2), KMATIX(6,6), KMQFPA, KNEFIL, KNEOUT, KNEVT, KNPAST,
     & KNQDET, KNQFPA, KNQLIN, KNQMTX, KNQPAR, KNQPST, KNREIN, KNREOU,
     & KOQDET, KOQFPA, KOQLIN, KOQMTL, KOQMTS, KOQPAR, KOQPBT, KOQPLI,
     & KOQTRA, KOQVEC, KOQVRT, KQPAR, KQVEC, KQVRT, KQWRK, KQZER, KRUN,
     & KSTATU, KTDROP, KUCARD, KUCONS, KUHIST, KUINPU, KUOUTP, KUPRNT,
     & KUPTER, KDEBU1, KDEBU2, KNWRLM, KEFOPT, KUEDIN, KUEDOU, KURTOX,
     & KUCAR2, KNHDRN, KNBHAB, KSBHAB, KRSLLQ, KRSLNB
      COMMON /QCDE/ INDATA
      COMMON /QCDE/ KRINNE, KRINNF, KRINDC, KRINDQ, KRINNZ, KRINNB,
     & KRINBM, KRINFR, KRINLR, KRINLF
      COMMON /QCDE/ KEVERT, KEVEDA, KEVETI, KEVEMI(4), KEVETY, KEVEES,
     & KDHEFP, KDHENP, KDHENM, KKEVNT, KKEVNV, KKEVID, KDHENX, KDHENV,
     & KDHENJ, KREVDS, KXTET1, KXTET2, KXTEL2, KXTCGC, KXTCLL, KXTCBN,
     & KXTCCL, KXTCHV, KXTCEN, KCLASW, KERBOM, KBPSTA
      DIMENSION KLOCUS(3,14)
      EQUIVALENCE (KLOCUS(1,1),KFOVT), (KFOVT,KFRET), (KLIST,KLRET),
     & (KFIST,KFCOT), (KLAST,KLCOT)
      COMMON /QCDE/ XCOPYJ, XFLIAC, XHISTO, XLREV(2), XLREV2(2), XMCEV,
     & XMINI, XSYNTX, XWREVT, XWRRUN, XFILMC, XFILCH, XFILV0, XFILCO,
     & XFILEF, XFILPC, XFILGA, XFILJE,
     & XPRHIS, XFILL, XVITC, XVTPC, XVECAL, XVLCAL, XVTPCD,
     & XVSATR, XVHCAL, XHVTRG, XSREC, XWMINI, XIOKLU, XIOKSI, XFRF2,
     & XNSEQ, XVDOK, XFRF0, XFMUID, XFILEM, XWNANO, XROKSI, XGETBP,
     & XJTHRU
      LOGICAL XCOPYJ, XFLIAC, XHISTO, XLREV, XLREV2, XMCEV, XMINI,
     & XSYNTX, XWREVT, XWRRUN, XFILMC, XFILCH, XFILV0, XFILCO, XFILEF,
     & XFILPC, XPRHIS, XFILL, XVITC, XVTPC, XVECAL, XVLCAL, XVTPCD,
     & XVSATR, XVHCAL, XHVTRG, XSREC, XWMINI, XIOKLU, XFRF2, XFILJE,
     & XNSEQ, XFILGA, XVDOK, XFRF0, XFMUID, XFILEM, XWNANO, XIOKSI,
     & XROKSI, XGETBP, XJTHRU
C-------------------- /NANCOM/ --- NanoDst steering -------------------
C! XNANO   .TRUE. if input is a NanoDst (in NANO or EPIO format, dependi
C!                   XNANOR)
C!
      LOGICAL XNANO
      COMMON /NANCOM/XNANO
C--------------------- end of NANCOM ----------------------------------
      INTEGER LMHLEN, LMHCOL, LMHROW
      PARAMETER (LMHLEN=2, LMHCOL=1, LMHROW=2)
      INTEGER IW
      REAL RW(10000)
      COMMON /BCS/ IW(10000)
      EQUIVALENCE (RW(1),IW(1))
C------------------ /QCNAMI/ --- name indices -------------------------
      COMMON /QCNAMI/ NAAFID,NAAJOB,NAASEV,NABCNT,NABHIT,NABOMB,
     1 NABOME,NABOMP,NABOMR,NABPTR,NADCAL,NADCRL,NADECO,NADEID,NADENF,
     2 NADEVT,NADEWI,NADFMC,NADFOT,NADGAM,NADHCO,NADHEA,NADHRL,NADJET,
     3 NADMID,NADMJT,NADMUO,NADNEU,NADPOB,NADRES,NADTBP,NADTMC,NADTRA,
     4 NADVER,NADVMC,NAECRQ,NAECTE,NAEGID,NAEGPC,NAEIDT,NAEJET,NAERRF,
     5 NAETDI,NAETKC,NAEVEH,NAEWHE,NAFICL,NAFKIN,NAFPOI,NAFPOL,NAFRFT,
     6 NAFRID,NAFRTL,NAFSTR,NAFTCL,NAFTCM,NAFTOC,NAFTTM,NAFVCL,NAFVER,
     7 NAFZFR,NAHCCV,NAHCTE,NAHINF,NAHMAD,NAHPDI,NAHROA,NAHSDA,NAHTUB,
     8 NAIASL,NAIPJT,NAIRJT,NAITCO,NAITMA,NAIXTR,NAIZBD,NAJBER,NAJEST,
     9 NAJSUM,NAKEVH,NAKINE,NAKJOB,NAKLIN,NAKPOL,NAKRUN,NALIDT,NALOLE,
     A NALUPA,NAMCAD,NAMHIT,NAMTHR,NAMUDG,NAMUEX,NAOSTS,NAPART,NAPASL,
     B NAPCHY,NAPCOB,NAPCOI,NAPCPA,NAPCQA,NAPCRL,NAPECO,NAPEHY,NAPEID,
     C NAPEMH,NAPEPT,NAPEST,NAPEWI,NAPFER,NAPFHR,NAPFRF,NAPFRT,NAPHCO,
     D NAPHER,NAPHHY,NAPHMH,NAPHST,NAPIDI,NAPITM,NAPLID,NAPLPD,NAPLSD,
     E NAPMSK,NAPNEU,NAPPDS,NAPPOB,NAPPRL,NAPRTM,NAPSCO,NAPSPO,NAPSTR,
     F NAPT2X,NAPTBC,NAPTCO,NAPTEX,NAPTMA,NAPTML,NAPTNC,NAPTST,NAPVCO,
     G NAPYER,NAPYFR,NAPYNE,NAQDET,NAQFPA,NAQLIN,NAQMTL,NAQMTS,NAQPAR,
     H NAQPBT,NAQPLI,NAQTRA,NAQVEC,NAQVRT,NAQWRK,NAQZER,NAREVH,NARHAH,
     I NARTLO,NARTLS,NARUNH,NARUNR,NASFTR,NATEXS,NATGMA,NATMTL,NATPCO,
     J NAVCOM,NAVCPL,NAVDCO,NAVDHT,NAVDXY,NAVDZT,NAVERT,NAVFHL,NAVFLG,
     K NAVFPH,NAVHLS,NAVPLH,NAX1AD,NAX1SC,NAX1TI,NAX2DF,NAX3EC,NAX3EW,
     L NAX3HC,NAX3IT,NAX3L2,NAX3LU,NAX3TM,NAX3TO,NAX3TP,NAX3X3,NAXTBN,
     M NAXTBP,NAXTCN,NAXTEB,NAXTOP,NAXTRB,NAYV0V,NAZPFR,NAEFOL,NAMUID,
     N NAPGID,NAPGPC,NAPGAC,NAPMSC,NAPTHR,NANBIP,NAPDLT,NAPMLT,NAPLJT
C--------------------- end of QCNAMI ----------------------------------
C------------------ /QQQQJJ/ --- HAC parameters for ALPHA banks -------
      PARAMETER (JQVEQX= 1,JQVEQY= 2,JQVEQZ= 3,JQVEQE= 4,JQVEQM= 5,
     & JQVEQP= 6,JQVECH= 7,JQVETN= 8,JQVESC= 9,JQVEKS=10,JQVECL=11,
     & JQVEPA=12,JQVEQD=13,JQVENP=14,JQVESP=15,JQVEOV=16,JQVEEV=17,
     & JQVEND=18,JQVEDL=19,JQVENO=20,JQVEOL=21,JQVENM=22,JQVEML=23,
     & JQVEBM=24,JQVELK=38,JQVEDB=39,JQVEZB=40,JQVESD=41,JQVESZ=42,
     & JQVECB=43,JQVEEM=44,JQVECF=54,JQVEEW=55,JQVEUS=56)
      PARAMETER ( JQVRVX=1,JQVRVY=2,JQVRVZ=3,JQVRVN=4,JQVRTY=5,
     1   JQVRIP=6,JQVRND=7,JQVRDL=8,JQVRAY=9,JQVRAF=10,JQVREM=11,
     2   JQVRCF=17,JQVRET=18)
      PARAMETER ( JQDEAF= 1,JQDEAL= 2,JQDENT= 3,JQDEAT= 4,JQDELT= 8,
     &  JQDEAE= 9,JQDEAH=10,JQDEAM=11,JQDECF=12,JQDEEC=13,JQDEHC=14,
     &  JQDEET=15,JQDEFI=16,JQDENF=17,JQDEFL=18,JQDENE=19,JQDEEL=20,
     &  JQDENH=21,JQDEHL=22,JQDELH=23,JQDEEF=24,JQDEPC=25,JQDEEG=26,
     &  JQDEMU=27,JQDEDX=28,JQDEPG=29,JQDEPD=30,JQDEPM=31)
      PARAMETER ( JQPAGN=1, JQPANA=2, JQPACO=5, JQPAMA=6, JQPACH=7,
     & JQPALT=8,JQPAWI=9,JQPAAN=10)
C--------------------- end of QCDESH ----------------------------------
      CHARACTER *(*) CINP
      CHARACTER CNAM * 12, CTAB * 12, CHAINT * 4, SPACES * 12
      LOGICAL CHECK
      COMMON / FINDPA / NAQPSP,NAQAFP,NQAFP
      INTEGER ITB(2)
      DATA CNAM /' '/
C - # of words/row in bank with index ID
      LCOLS(ID) = IW(ID+LMHCOL)
C - # of rows in bank with index ID
      LROWS(ID) = IW(ID+LMHROW)
C - index of next row in the bank with index ID
      KNEXT(ID) = ID + LMHLEN + IW(ID+1)*IW(ID+2)
C - index of row # NRBOS in the bank with index ID
      KROW(ID,NRBOS) = ID + LMHLEN + IW(ID+1)*(NRBOS-1)
C - # of free words in the bank with index ID
      LFRWRD(ID) = ID + IW(ID) - KNEXT(ID)
C - # of free rows in the bank with index ID
      LFRROW(ID) = LFRWRD(ID) / LCOLS(ID)
C - Lth integer element of the NRBOSth row of the bank with index ID
      ITABL(ID,NRBOS,L) = IW(ID+LMHLEN+(NRBOS-1)*IW(ID+1)+L)
C - Lth real element of the NRBOSth row of the bank with index ID
      RTABL(ID,NRBOS,L) = RW(ID+LMHLEN+(NRBOS-1)*IW(ID+1)+L)
C-----------------------------------------------------------------------
C
      CHECK = .FALSE.
    1 CONTINUE
C
C       convert lower case into upper case and remove blanks
C
      CNAM = SPACES (CINP,0)
      CALL CLTOU (CNAM)
C
C       go through particle table
C
      KPCOMP = 0
      DO 2 I = 1,2
 2    ITB(I) = INTCHA('    ')
      LCINP = LNBLNK(CNAM)
      NWC = 1+(LCINP-1)/4
      IF (CNAM(1:4).EQ.'NUMU')  NWC=2
      ITB(1) = INTCHA(CNAM(1:4))
      ITB(2) = INTCHA(CNAM(5:8))
      JQAFP = IW(NAQAFP)
      IF (NQAFP.EQ.0) GO TO 10
      J = LOCTAB(IW(JQAFP+LMHLEN+1),JQPANA+1,LROWS(JQAFP),JQPANA,ITB(1))
      IF (J.GT.0.AND.NWC.EQ.1) THEN
         KPCOMP = ITABL(JQAFP,J,JQPAGN)
         GO TO 90
      ENDIF
      IF (J.GT.0.AND.NWC.GE.2) THEN
         KTMIN = MAX0(1,J-25)
         KTMAX = MIN0(LROWS(JQAFP),J+25)
         DO 3 IK = KTMIN,KTMAX
            KQAFP = KROW(JQAFP,IK)
            IF (IW(KQAFP+JQPANA).NE.ITB(1)) GO TO 3
            IF (IW(KQAFP+JQPANA+1).EQ.ITB(2)) THEN
               KPCOMP = ITABL(JQAFP,IK,JQPAGN)
               GO TO 90
            ENDIF
 3       CONTINUE
      ENDIF
C
C CINP not found in 'QAFP' :
C Search for it in bank QPSP , then store it in 'QAFP' :
C
 10   JQPSP = IW(NAQPSP)
      J = LOCTAB(IW(JQPSP+LMHLEN+1),JQPANA+1,LROWS(JQPSP),JQPANA,ITB(1))
      IF (J.GT.0.AND.NWC.EQ.1) THEN
         KPCOMP = ITABL(JQPSP,J,JQPAGN)
         GO TO 70
      ENDIF
      IF (J.GT.0.AND.NWC.GE.2) THEN
         KTMIN = MAX0(1,J-25)
         KTMAX = MIN0(LROWS(JQPSP),J+25)
         DO 30 IK = KTMIN,KTMAX
            KQPSP = KROW(JQPSP,IK)
            IF (IW(KQPSP+JQPANA).NE.ITB(1)) GO TO 30
            IF (IW(KQPSP+JQPANA+1).EQ.ITB(2)) THEN
               KPCOMP = IW(KQPSP+JQPAGN)
               GO TO 70
            ENDIF
 30      CONTINUE
      ENDIF
 60   CONTINUE
C
C CINP was not in the 'QPSP' bank : it is a new particle , which
C has to be stored in 'QPAR' . 'QPSP' and 'QAFP' :
C
      IF (CHECK) GOTO 90
      KNQPAR = KNQPAR + 1
      IF (KNQPAR .GE. IW(KOQPAR+KCQPAR)) THEN
        CALL QSBANK ('QPAR',KNQPAR+50)
        CALL QSBANK ('QPSP',KNQPAR+50)
      ENDIF
      JQPAR = KOQPAR + KNQPAR * KCQPAR
      KPCOMP = KNQPAR
C
      CNAM = SPACES (CINP,0)
      IW(JQPAR+JQPANA)   = INTCHA (CNAM(1:4))
      IW(JQPAR+JQPANA+1) = INTCHA (CNAM(5:8))
      IW(JQPAR+JQPANA+2) = INTCHA (CNAM(9:12))
      IW(JQPAR+JQPAGN) = 100
      IW(JQPAR+JQPACO) = 100
      RW(JQPAR+JQPALT) = 1.E16
      RW(JQPAR+JQPAWI) = 0.
      IW(JQPAR+JQPAAN) = KPCOMP
      RW(JQPAR+JQPAMA) = QPPMMA(CINP)
      IF (KNQPAR.LE.ITPNMX) FLISPA(KNQPAR) = CNAM
      IF (KDEBUG.EQ.0) GO TO 65
      CALL QWMESS ('_KPCOMP_ New particle established : ' // CNAM)
 65   CONTINUE
C Fill a new row in 'QPSP' and 'QAFP'  banks for subsequent fast search
      JQPSP = IW(NAQPSP)
      IW(JQPSP+LMHROW) = KNQPAR
      KPSP = KROW(JQPSP,KNQPAR)
      IW(KPSP+JQPAGN) = KNQPAR
      IW(KPSP+JQPANA) = ITB(1)
      IW(KPSP+JQPANA+1) = ITB(2)
C  Sort the 'QPSP' bank for subsequent fast search :
      CALL  SORTIQ(IW(JQPSP+LMHLEN+1),LCOLS(JQPSP),LROWS(JQPSP),JQPANA)
C  Fill and Sort the 'QAFP' bank for subsequent fast search :
 70   NQAFP = NQAFP + 1
      JQAFP = IW(NAQAFP)
      NNQ = IW(JQAFP)/LCOLS(JQAFP)
      IF (NQAFP.GE.NNQ) CALL QSBANK('QAFP',NNQ+50)
      IW(JQAFP+LMHROW) = NQAFP
      KQAFP = KROW(JQAFP,NQAFP)
      IW(KQAFP+JQPAGN) = KPCOMP
      IW(KQAFP+JQPANA)   = ITB(1)
      IW(KQAFP+JQPANA+1) = ITB(2)
      CALL SORTIQ(IW(JQAFP+LMHLEN+1),LCOLS(JQAFP),LROWS(JQAFP),
     +                     JQPANA)
      GOTO 90
C
            ENTRY KPCHEK(CINP)
C-----------------------------------------------------------------
      CHECK = .TRUE.
      GOTO 1
C
   90 CONTINUE
      END
