#if defined(DOC)
C! DEFINE CONSTANT USE FOR ENERGY/MOMENTUM BALANCE TEST
C!
C!      ERENB2 = RESOLUTION**2 OF ECAL
C!      EPREBA = MINIMUM PROBABILITY FOR ENERGY BALANCE
#endif
      COMMON/EENBAC/ERENB2,EPREBA
