*CD ewtmco
      COMMON/EWTMCO/IWIRES(LWPLA+9,LMODU*LCOMP)
#if defined(DOC)
C   IWIRES(1,*)= MODULE NUMBER
C   IWIRES(2-46,*)= PLANE 1-45 CONTENTS
C   IWIRES(47-54,*)= ANALOG SUM SAMPLING FOR 8 DIFFERENT TIMES
#endif
