C! multiple-scattering constants in VDET,ITC,TPC
      COMMON /VRLDCOM/  UKRITC,UKSITC,UKRTPC,UKSTPC,UKSPITC,UKSPTPC,
     &                  UKRVAC,UKSVAC,UKZICA,UKRIICA,UKROICA,UKSICA,
     &                  UKZOCA,UKRIOCA,UKROOCA,UKSOCA
      REAL UKRITC,UKSITC,UKRTPC,UKSTPC,UKSPITC,UKSPTPC,UKRVAC,UKSVAC,
     &     UKZICA,UKRIICA,UKROICA,UKSICA,UKZOCA,UKRIOCA,UKROOCA,UKSOCA
