      PARAMETER(LROWSG=1,LROWSH=36,LROWSS=23,NSCALS=60)
      PARAMETER(NSEGMS=72,NBWRDS=3,NBITPW=32)
      LOGICAL OKFLAG
      COMMON/XTACCU/OKFLAG,NRUNNB,GBXSUM,ITIMEV(2,2),NBREVT,
     &              TTREAL,TTOPEN,STARTT,STOPTI,ISTRTD,
     &              NBXTEB,NBXTCN,NBX1AD,NBX1SC,NEVREC,
     &              ITBITS(NBWRDS*NBITPW,LROWSH),
     &              ITACCU(NBWRDS*NBITPW,LROWSH),
     &              ITSCAL(NSCALS,LROWSS),
     &              ITACSC(NSCALS,LROWSS)
