C! YTOP array dimensions
      PARAMETER(NMSIZZ=31,MKDIMM=6,MAXTRK=186,MAXHLX=124,MAXNTR=62,
     &  MXVTOP=10,MXMULS=10,MAXVXP=50,MAXEXC=60,MXVTYP=2)
#if defined(DOC)
C
C     NMSIZZ ......... # OF BITS USED IN MARKER WORDS
C     MKDIMM ......... DIMENSION OF TRACK MARKER FOR SINGLE TRACK
C     MAXTRK ........ MAX # OF TRKS ALLOWED ( LE.  NMSIZZ*MKDIMM)
C     MAXHLX ........ MAX # OF HELICES ALLOWED ( LE.  MAXTRK)
C     MAXNTR ........ MAX # OF NEUTRAL TRKS ALLOWED (LE. MAXTRK-MAXHLX)
C     MXVTOP ........ MAX # OF VERTICES
C     MXMULS ........ MAX MULTIPLICITY IN STATISTICS
C     MAXVXP ........ MAX. # OF VTX POSSIBILITIES IN YVPOSS
C     MAXEXC ........ MAX. # OF EXCLUDED VTX. POSS. IN YVPOSS
C     MXVTYP ........ MAX. # OF VTX TYPES IN YVPOSS
C
#endif
