      COMMON/LCNAMC/NALCLU,NALSDA,NALTDI,NALPDA,NALWDI,NALCRE,
     1              NALTRK,NALOBJ,NALIDT,NALUMI,NALSTA,NABHAB,
     2              NALIFL,NALMAP,NALCAL,NALLAY,NALMTY,NALPMO,
     3              NALRWG,NALSCO,NALSLO,NALWRG,NALALI,NALECA,
     4              NALDST,NALDWP,NALACC,NALBAK,NALSIN,NALONL,
     5              NAPLSD,NAPLPD,NALOCL,NALEHI,NALVHI,NALCPG,
     6              NABHZ0
C
