      PARAMETER (MXTRA=80)
      COMMON/UVPWRK/ XYI(2,MXTRA),X0(MXTRA),Y0(MXTRA),Z0(MXTRA),
     1               RADI(MXTRA),Q(MXTRA),CPHC(MXTRA),SPHC(MXTRA),
     2               TDIP(MXTRA),SIGX(MXTRA),SIGZ(MXTRA),
     3               G(3),GG(3,3),GGINV(3,3),XS(3),XV(3),
     4               CHISQ8,CHISQO,CHISQN
C
      DOUBLE PRECISION XYI,X0,Y0,Z0,RADI,Q,CPHC,SPHC,TDIP,SIGX,SIGZ,
     1                 G,GG,GGINV,XS,XV,CHISQ8,CHISQO,CHISQN
C
