C
C!  Defines flag bits used in VTXT flag word
C
      INTEGER NITCHB,NTPCHB,MCHISB,NSIGUB,NSIGWB
      PARAMETER (NITCHB = 1)
      PARAMETER (NTPCHB = 2)
      PARAMETER (MCHISB = 4)
      PARAMETER (NSIGUB = 8)
      PARAMETER (NSIGWB = 16)
