      PARAMETER(IMAX=5)
      COMMON/E4IDEN/R1ESTI(IMAX),R2ESTI(IMAX),E4STK1(IMAX)
     &,E4STK2(IMAX),E4STK3(IMAX),IPPOTH(IMAX),R3ESTI(IMAX),R4ESTI(IMAX)
     &,R5ESTI(IMAX),R6ESTI(IMAX),R7ESTI(IMAX)
     &,XBARY1(IMAX),XBARY2(IMAX),XBARY3(IMAX)
#if defined(DOC)
C
C!  COMMON FOR ELECTRON IDENTIFICATION RESULTS
C
C---------------------------------------------------------------------
C!
C!    COMMON FOR ELECTRON IDENTIFICATION RESULTS
C!    R2ESTI(ITR) VALUE OF ESTIMATOR 2
C!    E4STK1(ITR) ENERGY OF THE 4 CENTERED STOREYS FOR STACK 1
C!    E4STK2(ITR) ENERGY OF THE 4 CENTERED STOREYS FOR STACK 2
C!    E4STK2(ITR) ENERGY OF THE 4 CENTERED STOREYS FOR STACK 2
C!    XBARY1(ITR) RO   BARYCENTER OF THE 4 CENTERED STOREYS
C!    XBARY2(ITR) TETA BARYCENTER OF THE 4 CENTERED STOREYS
C!    XBARY3(ITR) PHI  BARYCENTER OF THE 4 CENTERED STOREYS
C!    IPPOTH(ITR) HYPOTHESIS  =0 NO ELECTRON HYPOTHESIS
C!                                =1 ELECTRON HYPOTHESIS
C!                                =2 ELECTRON+ SOMETHING HYPOTHESIS
C!
C!    VALUES ARE GIVEN FOR EACH TRACK ITR (ITR =1 TO 5) OF CLUSTER ICL
C! -------------------------------------------------------------------
#endif
