      DOUBLE PRECISION POINEH(8),CONSEH,COSIEH,SINUEH,STXYEH,STZZEH
      COMMON /EHLCOM/POINEH,CONSEH,COSIEH,SINUEH,STXYEH,STZZEH
#if defined(DOC)
C?     STEPEH = STEP SIZE FOR HELIX EXTRAPOLATION (CURRENT)
C?     POINEH = X,Y,Z,U,V,W,P,CHARGE FOR RUNNING POINT
C?     CONSEH = CONSTANT USED FOR CALCULATION OF NEXT POINT
C?     COSIEH = COS (ALPHA)
C?     SINUEH = SIN (ALPHA)
C?                   ALPHA  = CHANGE OF DIRECTION DURING STEP
#endif
