      PARAMETER (LMATIE=4,LCOORD=3,NSTMAX=20)
      INTEGER EISTOR,EJSTOR,EKSTOR,ENSTOU
      COMMON/EINTER/EMAXYZ(LMATIE,LCOORD),EMATET(LMATIE),EMAPHI(LMATIE)
     *,EISTOR(LMATIE,NSTMAX),EJSTOR(LMATIE,NSTMAX),EKSTOR(LMATIE,NSTMAX)
     *,ENSTOU(LMATIE)
