      COMMON/FILDAT/IADARR(0:NBNK),NUMBKD(NBNK),NUMREF(NBNK)
      COMMON/FILCAR/BKDLIN(NBNK,NENTR),REFLIN(NBNK,NENTR),COMLIN(NBNK)
     &             ,NAMARR(NBNK),INPLIN
      CHARACTER*4  NAMARR
      CHARACTER*25 REFLIN
      CHARACTER*40 BKDLIN
      CHARACTER*80 COMLIN
      CHARACTER*80 INPLIN
