C! Decoded command line parameters
      LOGICAL XBOOKG,XCONTT,XREFER,XCOMMT,XUNDOC,XOUTPT
      CHARACTER*80 CHOUTP,CHARGV
      COMMON /SBKCOM/XBOOKG,XCONTT,XREFER,XCOMMT,XUNDOC,XOUTPT
      COMMON /SBKCOC/CHOUTP,CHARGV
