*970615:TI:merge
*970419:TI:kmcntl
* File inclk.f generated by GRACE Ver. 2.00(37)        1996/05/14/12:00
* 
*          Fortran source code generator
*     (c)copyright 1990-1996 Minami-Tateya Group, Japan
*-----------------------------------------------------------------------
* masses and width of particles
      common /ammass/   amw,   amz,   ama,   amg,   amh,   amx,   amy,
     &                 amne,  amnm,  amnt,  amel,  ammu,  amta,  amuq,
     &                 amcq,  amtq,  amdq,  amsq,  ambq,  amcp,  amcm,
     &                 amcz,  amca,  amcg

      common /amgmma/   agw,   agz,   agh,   agx,   agy,  agcq,  agtq,
     &                 agsq,  agbq,  agcp,  agcm,  agcz

      common /amcnst/ pi, pi2, rad, gevpb, alpha, alphas, alpha0
      common /amreg / mxreg
      common /amopts/ jtgamm, jano3v, jcolmb, jqcdcr
      common /amoptc/ colmbf
      common /amoptm/ jqmass,jlmass
      common /aman3v/ ang1a, ang1z, ankaa, ankaz, andka, andkz,
     &                anlma, anlmz
      common /amoptj/ jdecay, jhadrn, jshowr
      common /amopti/ eisr

* external particles name
      character*16    kmprtc
      common /kmprt1/ kmprtc(6)
      common /kmprt2/ kmprtl(6)

* QEDPS flags
      common /amoptq/ jctype, jqedps

* masses of external particles
      common /kmmass/ amass1(6), amass2(6)

* charge(*3) and KFcode of external particles
      common /kminfo/ kcharg(6), kfcode(6)

* Color string information
      common /kmcsti/ kmcbas, kmcbmx, kmcstr(4,0:1), icinfo(6), icolst
      common /grc4fc/ jcanon, jschem
      common /grcsed/ jseed
      common /grcfil/ lubsrl, lubsdt, lubshb, lusprl, lusphb

*** ------------- for two-photon
* external,internal particle momenta
      common /kmmomt/ppi2 ,ppi3 ,ppi4 ,ppi5 ,ppi6 ,ppi7 ,ppi8 ,ppi9 
     .,  ppi10,ppi11,ppi12,ppi13,ppi14,ppi15,ppi16,ppi17,ppi18,ppi19
     .,  ppi20,ppi21,ppi22,ppi23,ppi24,ppi25,ppi26,ppi27,ppi28,ppi29
     .,  ppi30,ppi31,ppi32,ppi33,ppi34,ppi35,ppi36,ppi37,ppi38,ppi39
     .,  ppi40,ppi41,ppi42,ppi43,ppi44,ppi45,ppi46,ppi47,ppi48,ppi49
     .,  ppi50,ppi51,ppi52,ppi53,ppi54,ppi55,ppi56,ppi57,ppi58,ppi59
     .,  ppi60,ppi61,ppi62,ppi63
      dimension          ppi2(4) ,ppi3(4) ,ppi4(4)
     .,ppi5(4) ,ppi6(4) ,ppi7(4) ,ppi8(4) ,ppi9(4)
     .,ppi10(4),ppi11(4),ppi12(4),ppi13(4),ppi14(4)
     .,ppi15(4),ppi16(4),ppi17(4),ppi18(4),ppi19(4)
     .,ppi20(4),ppi21(4),ppi22(4),ppi23(4),ppi24(4)
     .,ppi25(4),ppi26(4),ppi27(4),ppi28(4),ppi29(4)
     .,ppi30(4),ppi31(4),ppi32(4),ppi33(4),ppi34(4)
     .,ppi35(4),ppi36(4),ppi37(4),ppi38(4),ppi39(4)
     .,ppi40(4),ppi41(4),ppi42(4),ppi43(4),ppi44(4)
     .,ppi45(4),ppi46(4),ppi47(4),ppi48(4),ppi49(4)
     .,ppi50(4),ppi51(4),ppi52(4),ppi53(4),ppi54(4)
     .,ppi55(4),ppi56(4),ppi57(4),ppi58(4),ppi59(4)
     .,ppi60(4),ppi61(4),ppi62(4),ppi63(4)
      common /kmmom2/pqs2 ,     pqs4 ,     pqs6 ,     pqs8       
     .,    pqs10,     pqs12,     pqs14,     pqs16,     pqs18      
     .,    pqs20,     pqs22,     pqs24,     pqs26,     pqs28      
     .,    pqs30,     pqs32,     pqs34,     pqs36,     pqs38      
     .,    pqs40,     pqs42,     pqs44,     pqs46,     pqs48      
     .,    pqs50,     pqs52,     pqs54,     pqs56,     pqs58      
     .,    pqs60,     pqs62     

*add 
*970419
      common/kmcntl/iresns(4),icos3,icosq3,icos5,isr,iswap,ident,iphi6
     .,ieeee,i34,itag,isym

*add
*970615
      common /kmcnt2/kimtyp,jit1,jit2,jncall
*     common /kinem1/s,w,fact
      common /cut001/coscut(2,4),engyct(2,4),amasct(2,6),aresns(2,4)
     .,opncut,swapm2
