c----------------------------------------------
c      Initialzation table generated by grcpars
c----------------------------------------------
* inclgi.f 
      parameter( maxadr = 629 )
      parameter( maxprt = 24 )
      parameter( maxgen = 33 )
      parameter( maxnam = 57 )
      parameter( maxprc = 76 )
      common /grcpdt/ idat(0:maxadr-1),ichg(0:maxprt-1),
     .                iptr(0:maxnam-1),iprc(0:maxprc-1,2),
     .                iprclt(0:maxprc-1)
      character*2  name
      common /grcpdc/ name(0:maxnam-1)
      character*8  prcnms
      common /grcppn/ prcnms(0:maxprc-1)
