*CD mesgjj
      INTEGER JMESID,JMESVR,JMESNO,JMESXC,JMESYC,JMESZC,JMESTA,JMESNA,
     +          JMESK1,JMESK2,LMESGA
      PARAMETER(JMESID=1,JMESVR=2,JMESNO=4,JMESXC=5,JMESYC=6,JMESZC=7,
     +          JMESTA=8,JMESNA=9,JMESK1=10,JMESK2=11,LMESGA=11)
