*CD vdcojj
      INTEGER JVDCWI,JVDCR0,JVDCPH,JVDCZ0,JVDCSR,JVDCSZ,JVDCQF,JVDCTN,
     +          LVDCOA
      PARAMETER(JVDCWI=1,JVDCR0=2,JVDCPH=3,JVDCZ0=4,JVDCSR=5,JVDCSZ=6,
     +          JVDCQF=7,JVDCTN=8,LVDCOA=8)
