#!/bin/csh -f
set echo
#
# U. Schafer, 13 Apr 1994
# Checks for availability of all ALEPH UNIX hosts as specified in al_hosts,
# writes them to table  host_table 
# % replaces any single character, numeric only !
#==========================================================================
# F. Blin 04/04/95 suppress dxal%% in al_hosts
# R.Hagelb.26/1/96 added  shift50  and removed  csf%%  in al_hosts
# F.Blin 23/04/97 changed /aleph by $ALEPH
# F.Blin 29/05/97 no ping
# L.Brarda 14/11/2k removed afal39, 35, 06
#==========================================================================
# set al_hosts='saga0% shift9 afal%% dxal%% csf csf%%'
 set al_hosts='shift50 afal%% '
 set host_table=$ALEPH/log/aleph_hosts
 set tries=3
# it's difficult to process a "[" !!!!
 set al_hosts=\^`echo "$al_hosts" | sed 's/%/%0-9]/g;s/ /$|^/g'`\$
 alias exe 'echo $al_hosts | tr \% \\\['
 set al_hosts="`exe`"
 set al_hosts=`echo ls cern.ch | nslookup | awk '{print $1}' | egrep         "$al_hosts" |sort || exit $status`

# set str_ping = "ping"
# if (${HOST} == "shift9") set str_ping = "/usr/etc/ping"

 if ( $status ) then
   echo error
   exit 7 
 else
   set host_alive=""
   foreach al_host ($al_hosts)
#     set perc=`${str_ping} -c $tries $al_host |tr "," "\12" |grep loss|tr " " "\12"              |grep %`
# only if all packages (100%) lost  machine is taken out! 
#     if ("$perc" == "100%") set al_host="#$al_host" 
#    remove (comment out) machines which are responding to ping but not  UNIX 
##   afal02 and afal16 nomore removed, because nomore with VMS or windowsNT
if ("$al_host" == "afal39" | "$al_host" == "afal35" | "$al_host" == "afal06") set al_host="#$al_host"
#if ("$al_host" == "afal03") set al_host="#$al_host"
     set host_alive=`echo $host_alive $al_host`
   end
   echo "$host_alive" | tr " " "\12" >! $host_table 
   exit 0
 endif
 exit 0
