#!/bin/csh
#
# re-format files *.f and save old to *.fugly
#
# cut out everything after col. 72
# removes trailing blanks
# formats statement like <label> END to <label> CONTINUE<nl> END
# makes \ to \\ problem: line could get >72 chars!
# if inserting double \ extends line over col 72, make continuation line 
#
# 2-Mar-1991, by L.A.T.Bauerdick/CERN PPE
#
set noglob

foreach i ($argv)
	if ($i !~ *.f ) continue
	echo formatting $i 
	mv $i $i:r.fugly
	awk ' {print  substr($0,1,72)}' $i:r.fugly |  sed 's/ *$//' | \
	sed '/ *[0-9][0-9]* * END *$/s/END/CONTINUE\\
      END/'   | \
	sed 's/\\/\\\\/g' | \
	sed 's/^\(........................................................................\)\(..*\)/\1\\
     +\2/' \
	 >$i:r.f	
  end
