#!/bin/csh
#------------------------------------------------------------------------
#
# next_talks
# display the future talks given by Aleph members
#
# J. Boucrot  4-Mar-1999
#
# no argument
#
#------------------------------------------------------------------------
#
    more /afs/cern.ch/aleph/reference/book/next_talks.list   
exit
