#!/bin/csh
#------------------------------------------------------------------------
#
# scanbook
# 
# runs by default the Java/Oracle version
#
# J. Boucrot  28-Mar-2000
#
# Argument given :  if -i : standard interactive execution
#                   if cards file name : execution with input cards file
# If no argument :  execution of Java/Oracle version
#
#------------------------------------------------------------------------
#
#  no argument given : execute xscanbook :    
#

if (${#argv} == 0) then
   java -classpath /afs/cern.ch/aleph/reference/book/scanbook.jar scanbook   

else
#  1  argument given : check if it is  -i
#                      
      set arg_name = $argv[1] 
      if ($arg_name == -i) then
         iscanbook 
      else
         iscanbook $arg_name
      endif
endif
exit
