#!/bin/csh
###############################################################################
#                          sycheck_rsh
# 19/06/96                                                         F.Blin
###############################################################################
# call by sycheck_perl
###############################################################################
# to check QUEUES on shift50 
 set string_4 = `echo ${HOST} | awk '{print substr($0,1,4)}'`

# to check df -k and scwork/scweek on nodes_DF [shift50 afal01]
 if (${string_4} == "shif" || ${HOST} == "afal01") then
     if (-e ${home}/scwork_${HOST}) rm -f ${home}/scwork_${HOST}
     if (-e ${home}/scweek_${HOST}) rm -f ${home}/scweek_${HOST}
     df -k /aleph/scwork | tail -1 > ${home}/scwork_${HOST} 
     df -k /aleph/scweek | tail -1 > ${home}/scweek_${HOST}
     if (-e ${home}/df_${HOST}) rm -f ${home}/df_${HOST}
     df -k > ${home}/df_${HOST}
 endif

 if (-e ${home}/who_b_${HOST}} ) rm -f ${home}/who_b_${HOST}
 who -b | awk '{print $4 " " $5 " " $6}' >${home}/who_b_${HOST} 

 if (-e ${home}/ps_${HOST}} ) rm -f ${home}/ps_${HOST}
 ps axw > ${home}/ps_${HOST} 

 if (${HOST} == "afal01" || ${HOST} == "shift50") then
    if (-e ${home}/ls_aouR_${HOST}) rm -f ${home}/ls_aouR_${HOST}
    ls -aouR $ALEPH/data | sort -r -n +3 | head > ${home}/ls_aouR_${HOST}

    if (-e ${home}/nfsd_${HOST}) rm -f ${home}/nfsd_${HOST}
    if (${HOST} == "afal01" || ${HOST} == "shift50") then 
       top -d1 -n | grep nfsd | awk '{print substr($9,1,index($9,".")-1)}' > ${home}/nfsd_${HOST}
    endif
 endif

# echo "${HOST} /aleph/script/sycheck_rsh" >> /aleph/log/check_sycheck_rsh
 if (${HOST} == "afal10") then
    if (-e ${home}/error_shift50.rsh) rm -f ${home}/error_shift50.rsh
    if (-e ${home}/error_csf.rsh) rm -f ${home}/error_csf.rsh
 endif
 
 if (-e ${home}/df_usr_${HOST}) rm -f ${home}/df_usr_${HOST}
 df -k /usr > ${home}/df_usr_${HOST}

 exit
