*CD ehfcon
      COMMON/EHFCON/CUTFEH,CEDGEH(4),CST1EH(3),CBS3EH(9),
     *              CCS3EH(9)
C
#if defined(DOC)
      CUTFEH = CUT OFF ENERGY AT THE BOUNDARY
      CEDGEH = CUT OFF CONSTANTS FOR THE MODULE EDGES
      CST1EH = CUT OFF CONSTANTS FOR STACKS 1/2
      CBS3EH = CUT OFF CONSTANTS FOR BARREL STACK 3
      CCS3EH = CUT OFF CONSTANTS FOR END CAP STACK 3
#endif
