C?.Start of NCDESH -----------------------------------------------------
C
#include "npcdsh.h"
#include "nbnkpo.h"
      PARAMETER(QQPI=3.141593,QQE=2.718282,QQ2PI=QQPI*2.,QQPIH=QQPI/2.,
     +          QQRADP=180./QQPI,QQC=2.997925E10,QQH=6.582173E-25,
     +          QQHC=QQH*QQC,QQIRP=.00029979)
      LOGICAL XSIG,XSIGOV,XTEX,XEID,XUID,XPART,XEL,XMU,XPI,XKA,XPR,
     +        XFRF,XC2OV,XMCNE,XMCGA,XMCCH,XRIMOV,XRSIOV,XV0SVA,XV0KIA,
     +        XV0TRA,XGE1,XGE2,XK0,XLA,XAL,XGA
      PARAMETER(MAXFIL=1000)
      PARAMETER(MAXREC=2000)
      COMMON /NUNITS/KUCARD,KUPRNT,KUPTER,KUSEVT,KUHIST
      COMMON /NPOINT/KOEVEH,KCEVEH,KOQVEC,KCQVEC,KOPART,KCPART,
     +               KFCHT,KLCHT,KFACT,KLACT,KFBCT,KLBCT,
     +               KFPH1,KLPH1,KFNH1,KLNH1,
     +               KFPH2,KLPH2,KFNH2,KLNH2,
     +               KFJET,KLJET,
     +               KFGAM,KLGAM,KFGH1,KLGH1,KFGH2,KLGH2,
     +               KFMCT,KLMCT,KFMUT,KLMUT,KFMST,KLMST,
     +               KFV0T,KLV0T,KFGCO,KLGCO,KFEFT,KLEFT,
     +               KTHRU,KQ,KQBAR,KFPAR,KLPAR
      COMMON /NVARIA/KRUN,KEVT,KNEVT,
     +               KNCHT,KNACT,KNBCT,KNPH1,KNNH1,KNPH2,KNNH2,
     +               KNJET,
     +               KNGAM,KNGH1,KNGH2,
     +               KNLEC,
     +               KNMUT,KNMST,KNMCT,
     +               KNV0T,KNGCO,KNEFT,
     +               KNPART,
     +               QTHRU,QTTHE,QTPHI,KRUNR,QELEP,QMFLD,KREVDS,
     +               QMCUT,QSMCUT,QSYCUT,KNREIN,KNEFIL
      CHARACTER*80 NCHIST
      COMMON /NINTCH/NCHIST
      COMMON /OUTPUT/NRUREC,NEVREC
      LOGICAL        NXWRHI,NXMASS,XLUMOK,XMCEV,NXNEWF,NXNEWR,NXOUTP,
     +               NXCOPY,NXJSPY,NXWOUT,NXNOPH,NXEVOL,XNSEQ
      COMMON /NINTLO/NXWRHI,NXMASS,XLUMOK,XMCEV,NXNEWF,NXNEWR,NXOUTP,
     +               NXCOPY,NXJSPY,NXWOUT,NXNOPH,NXEVOL,XNSEQ
      COMMON /NINTER/KFLAV,NJETB,NFFREE,NRONVE
      PARAMETER(MAXSEV=10000)
      COMMON /NSEVTC/ICARDS(2,MAXSEV),NSELEV
      COMMON /NVERSI/NVERSP,NVERSS,NCORSS
      CHARACTER*4 SAVERS
      COMMON /SANDYC/SAVERS
#include "gampi0.h"
C?.End of NCDESH -------------------------------------------------------
