#!/bin/sh
#------------------------------------------------------------------------
#
# cp_ibm
# send a file to the alsoft service machine
#
# J. Boucrot  10-Jun-1996
#
# $1 - file name
#
#------------------------------------------------------------------------
Mail -s $1 alsoft@aloha.cern.ch < $1
 
