      COMMON /NBNKPO/KONVEC,KCNVEC,KONDBM,KCNDBM,KONDCL,KCNDCL,
     +               KONDDE,KCNDDE,KONDHE,KCNDHE,KONBIP,KCNBIP,
     +               KONDJT,KCNDJT,KONDLV,KCNDLV,KONDMS,KCNDMS,
     +               KONDOB,KCNDOB,KONDPH,KCNDPH,KONDTK,KCNDTK,
     +               KONDNT,KCNDNT,KONDAR,KCNDAR,KONDV0,KCNDV0,
     +               KONDGC,KCNDGC,KONDEJ,KCNDEJ,KONEHE,KCNEHE
