      INTEGER ISEL,ISIN,IPI,IKA,IMU,IEL,INI,IGA,IPR,INE,IUQ,IDQ,ISQ,ICQ,
     &  IBQ,ITQ
      REAL    PCUT
      COMMON /NRSKMC/ISEL,PCUT,ISIN,IPI,IKA,IMU,IEL,INI,IGA,IPR,INE,
     +               IUQ,IDQ,ISQ,ICQ,IBQ,ITQ
