C -------- Start of /QNCDE/ Specific commons for the NANO -------------
#include "nbpdcl.h"
#include "nbnkpo.h"
#include "ndv0jj.h"
#include "ndtkjj.h"
      REAL    BJSPCH,BJSPEF,BBSPR1,BBSPR2,BEETT1,BEETT2,BEETM1,BEETM2
      LOGICAL NXHVOK,NXDEOK,NXVDOK,NXMUOK,NXLEPT,NXBJSC,NXBJSF,NXBEES,
     &        NXGAMP,NXQFVX,NXQFOK
      INTEGER MINTRK,NITCUT,NTPCUT,NITCUJ,NTPCUJ,MCOPTI
      REAL    ECHMIN,PCUTMI,PCUTMA,THCCUT,BD0CUT,BZ0CUT,PCUMIJ,PCUMAJ,
     &        THCCUJ,BD0CUJ,BZ0CUJ,BMYCUT,ENEVIS,PHOCUT,V0CHSI,V0CHBO,
     &        PMINMC,REFMIN,RMYCUT
      INTEGER KTNO
      REAL    QV0PCH,QV0NCH
      CHARACTER*2 RECOOP
      CHARACTER*4 NCPROD
      CHARACTER*80 NCLPOT,NCLRUN
      CHARACTER*80 NCLNDS
      COMMON  /QNCDE/BJSPCH,BJSPEF,BBSPR1,BBSPR2,BEETT1,BEETT2,BEETM1,
     &        BEETM2,
     &        NXHVOK,NXDEOK,NXVDOK,NXMUOK,NXLEPT,NXBJSC,NXBJSF,NXBEES,
     &        NXGAMP,NXQFVX,NXQFOK
      COMMON  /QNCDE/ECHMIN,MINTRK,PCUTMI,PCUTMA,THCCUT,NITCUT,NTPCUT,
     &        BD0CUT,BZ0CUT,PCUMIJ,PCUMAJ,THCCUJ,NITCUJ,NTPCUJ,BD0CUJ,
     &        BZ0CUJ,BMYCUT,ENEVIS,PHOCUT,V0CHSI,V0CHBO,MCOPTI,PMINMC,
     &        REFMIN,RMYCUT
      COMMON  /QNCDE/RECOOP,NCPROD,NCLPOT,NCLRUN,NCLNDS
C -------- End of /QNCDE/ Specific commons for the NANO ----------------
