*CD igeojj
      INTEGER JIGEID,JIGEVR,JIGENA,JIGERI,JIGERO,JIGEZN,JIGEZX,JIGEIP,
     +          LIGEOA
      PARAMETER(JIGEID=1,JIGEVR=2,JIGENA=4,JIGERI=8,JIGERO=9,JIGEZN=10,
     +          JIGEZX=11,JIGEIP=12,LIGEOA=12)
