*CD mecgjj
      INTEGER JMECID,JMECVR,JMECSU,JMECNS,JMECZI,JMECZE,JMECPD,JMECTH,
     +          JMECDZ,JMECXO,LMECGA
      PARAMETER(JMECID=1,JMECVR=2,JMECSU=4,JMECNS=5,JMECZI=6,JMECZE=7,
     +          JMECPD=8,JMECTH=9,JMECDZ=10,JMECXO=11,LMECGA=11)
