*CD satrjj
      INTEGER JSATID,JSATVR,JSATCN,JSATSU,JSATLA,JSATSC,JSATWI,JSATIR,
     +          JSATOR,JSATIM,JSATOM,JSATWD,JSATLD,JSATLO,JSATGL,JSATET,
     +          JSATBT,JSATOT,JSATGD,JSATMT,JSATDL,JSATDR,JSATCR,JSATCA,
     +          JSATTD,JSATPR,JSATPP,JSATPD,JSATPA,JSATBN,JSATBX,JSATBY,
     +          JSATBZ,JSATBR,JSATMP,JSATFR,JSATFD,LSATRA
      PARAMETER(JSATID=1,JSATVR=2,JSATCN=4,JSATSU=5,JSATLA=6,JSATSC=7,
     +          JSATWI=8,JSATIR=9,JSATOR=10,JSATIM=11,JSATOM=12,
     +          JSATWD=13,JSATLD=14,JSATLO=15,JSATGL=16,JSATET=17,
     +          JSATBT=18,JSATOT=19,JSATGD=20,JSATMT=21,JSATDL=29,
     +          JSATDR=32,JSATCR=35,JSATCA=36,JSATTD=37,JSATPR=38,
     +          JSATPP=39,JSATPD=40,JSATPA=41,JSATBN=45,JSATBX=46,
     +          JSATBY=47,JSATBZ=48,JSATBR=49,JSATMP=50,JSATFR=56,
     +          JSATFD=57,LSATRA=57)
