*CD gcmulo
*
      COMMON/GCMULO/GSINMUL(101),GCOSMUL(101),GSQRMUL(101),GOMCMOL
     +  ,GCHCMOL,GEKMIN,GEKMAX,NGEKBIN,NGEK1
     +  ,GEKINV,GEKA,GEKB,GEKBIN(200),GELOW(200)
C
      REAL GSINMUL,GCOSMUL,GSQRMUL,GOMCMOL,GCHCMOL,GEKMIN,GEKMAX,
     +     GEKINV,GEKA,GEKB,GEKBIN,GELOW
      INTEGER NGEKBIN,NGEK1
