*CD geacom
      COMMON/GCLIST/NGHSTA,NGGET ,NGSAVE,NGSETS,NGPRIN,NGGEOM,NGVIEW
     +,NGPLOT,NGSTAT,LGHSTA(20),LGGET (20),LGSAVE(20),LGSETS(20)
     + ,LGPRIN(20),LGGEOM(20),LGVIEW(20),LGPLOT(20),LGSTAT(20)
C
      COMMON/GCONST/GPI,GTWOPI ,GPIBY2,GDERAD,GRADEG,GCLIGH,GBIG,GEMASS
      COMMON/GCONSX/GEMMU,GPMASS,GAVO
C
      COMMON/GCPOLY/IGZSEC,IGPSEC
C
      COMMON/GCSETS/IGHSET,IGHDET,IGSET,IGDET,IGDTYP,NGVNAM,NGUMBV(20)
C
      COMMON/GCTIME/GTIMIN,GTIMEN,IGTIME ,IGDATE,IGGTIM
C
      COMMON/GCUNIT/LGIN,LGOUT,NGUNIT,LGUNIT(5)
      COMMON /GCMAIL/   GCHMAI
      CHARACTER*132 GCHMAI
C
