         COMMON/ MGDECA/
     +     EZIPLA,EZEPLA,EPLADI,EXXXXC(NRSLEC),EYYYYC(NRSLEC),
     +     EZETAC(NRSLEC),METAST(NRSLEC),MENAST(NRSLEC),MEPNTY(NRSLEC),
     +     ELENGT(NRTYEC,NRELEC),EXXBOX(NRTYEC),EYYBOX(NRTYEC),
     +     EXSTOF(NRPLAN,NRSLEC),EPIT16(NRTYEC),
     +     MENXST(NRTYEC),MENYST(NRTYEC),EYSTOF(NRPLAN,NRSLEC),
     +     EXSTOC(NRPLAN,NRSLEC),EYSTOC(NRPLAN,NRSLEC)
