      INTEGER NEVNTS, NRAWHT, NFNLHT, NMATHT, NNOSHT
      INTEGER HISOFF, PRNTLV, HISTLV,NHOTEV
      COMMON /VPRTNC/ NEVNTS, NRAWHT(2), NFNLHT(2), NMATHT(2),
     &     NNOSHT(2), PRNTLV, HISTLV, HISOFF,NHOTEV
