*CD gcphys
      COMMON/GCPHYS/ IGPAIR,GSPAIR,GSLPAI,GZINPA,GSTPPA
     &              ,IGCOMP,GSCOMP,GSLCOM,GZINCO,GSTPCO
     &              ,IGPHOT,GSPHOT,GSLPHO,GZINPH,GSTPPH
     &              ,IGPFIS,GSPFIS,GSLPFI,GZINPF,GSTPPF
     &              ,IGDRAY,GSDRAY,GSLDRA,GZINDR,GSTPDR
     &              ,IGANNI,GSANNI,GSLANN,GZINAN,GSTPAN
     &              ,IGBREM,GSBREM,GSLBRE,GZINBR,GSTPBR
     &              ,IGHADR,GSHADR,GSLHAD,GZINHA,GSTPHA
     &              ,IGMUNU,GSMUNU,GSLMUN,GZINMU,GSTPMU
     &              ,IGDCAY,GSDCAY,GSLIFE,GSUMLI,GDPHY1
     &              ,IGLOSS,GSLOSS,GSOLOS,GSTLOS,GDPHY2
     &              ,IGMULS,GSMULS,GSOMUL,GSTMUL,GDPHY3
     &              ,IGRAYL,GSRAYL,GSLRAY,GZINRA,GSTPRA
C
