C!  Internal Common for VDHMATCH
      INTEGER MAXHT, NVWMAX, NVVIEW
C   NVVIEW = number of views
C   NVWMAX = maximum number of wafers =
C   24 faces * 2 modules/face * 3 wafers/module
      PARAMETER (MAXHT = 20, NVWMAX = 24*2*3, NVVIEW =2)
C
      INTEGER ITRK_U(MAXHT,NVWMAX),ITRK_W(MAXHT,NVWMAX)
      INTEGER ITRK_G(MAXHT,NVWMAX)
      INTEGER IUMATCH(MAXHT,NVWMAX),IWMATCH(MAXHT,NVWMAX)
      INTEGER NUMATCH(MAXHT,NVWMAX),NWMATCH(MAXHT,NVWMAX)
      INTEGER NGAL(NVWMAX),NU(NVWMAX),NW(NVWMAX)
C
      COMMON / VHMAT / ITRK_U,ITRK_W,ITRK_G,IUMATCH,IWMATCH,
     &                 NUMATCH,NWMATCH,NU,NW,NGAL
