      INTEGER MST(L1MST),MSTE(LEMSTE),K(LJNPAR,2),N
      EQUIVALENCE (MST(1),MSTLU1(1)),(MSTE(1),MSTELE(1)),
     &            (K(1,1),KODELU(1,1)),(N,NPARLU)
      REAL PAR(L1PAR),PARE(LEPARE),P(LJNPAR,5)
      EQUIVALENCE (PAR(1),PARLU1(1)),(PARE(1),PARELE(1)),
     &            (P(1,1),PARTLU(1,1))
