      SUBROUTINE GOODMOD(KEEP)
C---------------------------------------------------------------------
C! Compute pad - wire differences in ECAL
C
C  Patrick Janot -- 18 Apr 1990
C---------------------------------------------------------------------
      COMMON / indibk / iewhe, newhe, ipeco, npeco, ipest, npest,
     .                  ietdi, netdi, iphco, nphco, ipcob, npcob,
     .                  iplpd, nplpd, iplsd, nplsd, ipewi, npewi,
     .                  iefol, nefol, isilu, nsilu
      COMMON / verpro / julver, julcor, libver
      COMMON / indifw / ifwvc(7), kfwvc
C
      COMMON / paramfw / idbg,n0,z0,d0,ntrack,mtrack,echmin,echmax,
     .                   rpsf,nngama,sigec,sighc,epilca,epiend,epibar,
     .                   nclea
      COMMON / phyout / gdmult, v0mult, chatot, chapo,chane, enechq(5),
     .                  hadtot, splash, ene12, hadkil, enelon, enetran,
     .                  ierph30, ediff(36),ewire(36),epad(36), difl(4),
     .                  padl(4), wirl(4), sicapi(2)
      COMMON / trknew / lch, lv0, lmg, lmh, lum, lkg, lkh, ltot,
     .                  inew, isave, kfrefw, klsefw, kfrtot(7),
     .                  klstot(7),kan(200),kav(200),kag(200),kam(200),
     .                  nphoch(200),nphocr(200)
      COMMON / flgidt / idtflg(200),muflg(200),muwrd(200),ehcal(200),
     .                  leflg(200),elrtr(200),elrlg(200),dzero(200)
      COMMON / infomu / yxmult(200),yrapp (200),yang (200),
     .                  ysudnt(200),jishad(200),jimcf(200)
      COMMON / infefo / newefol(200),indefol(200)
      COMMON / infohn / propec(200)
      COMMON / infodx / dedxhy(4,200)
      DIMENSION vec(4), lps(7)
      EQUIVALENCE (lps(1), lch)
      CHARACTER*6 prnam(7)
      DATA prnam/'CHARGE','VZERO ','PHOTON','HADRON','LUMI  ',
     .           'KILPHO','KILHAD'/
C
C-------------------- /QCDE/ --- COMMONs, DIMENSIONs, etc. ------------
C Start of QCDESH ----------------------- Description in QDATA ---------
      PARAMETER (KCQDET=34, KCQFPA=8, KCQPAR=10, KCQVEC=73, KCQVRT=30,
     & KHE=1, KHMU=2, KHPI=3, KHK=4, KHP=5, KHPHOT=1, KHNHAD=2,
     & KMONTE=-2, KRECO=-1, KLOCKM=14, KSOVT=1, KSCHT=2, KSIST=3,
     & KSAST=4, KSEHT=5, KSV0T=6, KSDCT=7, KSEFT=8, KSNET=9, KSGAT=10,
     & KSJET=11, KSMCT=12, KSREV=13,
     & KSMCV=14, KUNDEF=-12344321, QQPI=3.141593, QQE=2.718282,
     & QQ2PI=QQPI*2., QQPIH=QQPI/2., QQRADP=180./QQPI, QQC=2.997925E10,
     & QQH=6.582173E-25, QQHC=QQH*QQC, QQIRP=.00029979)
      CHARACTER CQDATE*8, CQDWRK*80, CQFHIS*80, CQFOUT*80, CQFWRK*80,
     & CQHTIT*80, CQSEC*3, CQTIME*8, CQUNPK*30, CQVERS*6, CQRLST*800,
     & CQELST*800
      COMMON /QCDEC/ CQDATE, CQDWRK, CQFHIS, CQFOUT, CQFWRK, CQHTIT,
     & CQSEC(14), CQTIME, CQUNPK, CQVERS, CQRLST, CQELST
      COMMON /QCDE/ QELEP, QMFLD ,QMFLDC, QTIME, QTIMEI, QTIMEL,
     & QTIMES, QTIMET, QDHEEC, QDHEEL, QDHEPF, QDHETH, QDHEPH, QDHEEF,
     & QDHEET, QDHET1, QDHEP1, QDHET2, QDHEP2, QDHEE1, QDHEE2, QDHEE3,
     & QKEVRN, QKEVWT, QVXNOM, QVYNOM, QVZNOM, QVXNSG, QVYNSG, QVZNSG,
     & QINLUM, QRINLN, QRINLU, QDBOFS, QEECWI(36), QVXBOM, QVYBOM,
     & QSILUM, QRSLLU, QRSLBK, QRSLEW , QVTXBP(3), QVTEBP(3), QVTSBP(3)
      COMMON /QCDE/  KFOVT, KLOVT, KNOVT, KFCHT, KLCHT, KNCHT, KFIST,
     & KLIST, KNIST, KFAST, KLAST, KNAST, KFEHT, KLEHT, KNEHT, KFV0T,
     & KLV0T, KNV0T, KFDCT, KLDCT, KNDCT, KFEFT, KLEFT, KNEFT, KFNET,
     & KLNET, KNNET, KFGAT, KLGAT, KNGAT, KFJET, KLJET, KNJET, KFMCT,
     & KLMCT, KNMCT, KFREV, KLREV, KNREV, KFMCV, KLMCV, KNMCV, KLUST,
     & KLUSV, KFFRT, KLFRT, KFFRV, KLFRV, KNRET, KNCOT, KFFRD,
     & KLFJET,KLLJET,KLNJET
      COMMON /QCDE/ KBIT(32), KCLACO(KCQFPA), KCLAFR(KCQFPA), KCLARM
     & (KCQFPA), KDEBUG, KEVT, KEXP, KFFILL, KFEOUT, KJOPTN(2,2),
     & KLEOUT, KLROUT, KLOCK0(KLOCKM,2), KLOCK1(KLOCKM,2), KLOCK2(
     & KLOCKM,2), KMATIX(6,6), KMQFPA, KNEFIL, KNEOUT, KNEVT, KNPAST,
     & KNQDET, KNQFPA, KNQLIN, KNQMTX, KNQPAR, KNQPST, KNREIN, KNREOU,
     & KOQDET, KOQFPA, KOQLIN, KOQMTL, KOQMTS, KOQPAR, KOQPBT, KOQPLI,
     & KOQTRA, KOQVEC, KOQVRT, KQPAR, KQVEC, KQVRT, KQWRK, KQZER, KRUN,
     & KSTATU, KTDROP, KUCARD, KUCONS, KUHIST, KUINPU, KUOUTP, KUPRNT,
     & KUPTER, KDEBU1, KDEBU2, KNWRLM, KEFOPT, KUEDIN, KUEDOU, KURTOX,
     & KUCAR2, KNHDRN, KNBHAB, KSBHAB, KRSLLQ, KRSLNB
      COMMON /QCDE/ INDATA
      COMMON /QCDE/ KRINNE, KRINNF, KRINDC, KRINDQ, KRINNZ, KRINNB,
     & KRINBM, KRINFR, KRINLR, KRINLF
      COMMON /QCDE/ KEVERT, KEVEDA, KEVETI, KEVEMI(4), KEVETY, KEVEES,
     & KDHEFP, KDHENP, KDHENM, KKEVNT, KKEVNV, KKEVID, KDHENX, KDHENV,
     & KDHENJ, KREVDS, KXTET1, KXTET2, KXTEL2, KXTCGC, KXTCLL, KXTCBN,
     & KXTCCL, KXTCHV, KXTCEN, KCLASW, KERBOM, KBPSTA
      DIMENSION KLOCUS(3,14)
      EQUIVALENCE (KLOCUS(1,1),KFOVT), (KFOVT,KFRET), (KLIST,KLRET),
     & (KFIST,KFCOT), (KLAST,KLCOT)
      COMMON /QCDE/ XCOPYJ, XFLIAC, XHISTO, XLREV(2), XLREV2(2), XMCEV,
     & XMINI, XSYNTX, XWREVT, XWRRUN, XFILMC, XFILCH, XFILV0, XFILCO,
     & XFILEF, XFILPC, XFILGA, XFILJE,
     & XPRHIS, XFILL, XVITC, XVTPC, XVECAL, XVLCAL, XVTPCD,
     & XVSATR, XVHCAL, XHVTRG, XSREC, XWMINI, XIOKLU, XIOKSI, XFRF2,
     & XNSEQ, XVDOK, XFRF0, XFMUID, XFILEM, XWNANO, XROKSI, XGETBP,
     & XJTHRU
      LOGICAL XCOPYJ, XFLIAC, XHISTO, XLREV, XLREV2, XMCEV, XMINI,
     & XSYNTX, XWREVT, XWRRUN, XFILMC, XFILCH, XFILV0, XFILCO, XFILEF,
     & XFILPC, XPRHIS, XFILL, XVITC, XVTPC, XVECAL, XVLCAL, XVTPCD,
     & XVSATR, XVHCAL, XHVTRG, XSREC, XWMINI, XIOKLU, XFRF2, XFILJE,
     & XNSEQ, XFILGA, XVDOK, XFRF0, XFMUID, XFILEM, XWNANO, XIOKSI,
     & XROKSI, XGETBP, XJTHRU
C-------------------- /NANCOM/ --- NanoDst steering -------------------
C! XNANO   .TRUE. if input is a NanoDst (in NANO or EPIO format, dependi
C!                   XNANOR)
C!
      LOGICAL XNANO
      COMMON /NANCOM/XNANO
C--------------------- end of NANCOM ----------------------------------
      INTEGER LMHLEN, LMHCOL, LMHROW
      PARAMETER (LMHLEN=2, LMHCOL=1, LMHROW=2)
      INTEGER IW
      REAL RW(10000)
      COMMON /BCS/ IW(10000)
      EQUIVALENCE (RW(1),IW(1))
C------------------ /QCNAMI/ --- name indices -------------------------
      COMMON /QCNAMI/ NAAFID,NAAJOB,NAASEV,NABCNT,NABHIT,NABOMB,
     1 NABOME,NABOMP,NABOMR,NABPTR,NADCAL,NADCRL,NADECO,NADEID,NADENF,
     2 NADEVT,NADEWI,NADFMC,NADFOT,NADGAM,NADHCO,NADHEA,NADHRL,NADJET,
     3 NADMID,NADMJT,NADMUO,NADNEU,NADPOB,NADRES,NADTBP,NADTMC,NADTRA,
     4 NADVER,NADVMC,NAECRQ,NAECTE,NAEGID,NAEGPC,NAEIDT,NAEJET,NAERRF,
     5 NAETDI,NAETKC,NAEVEH,NAEWHE,NAFICL,NAFKIN,NAFPOI,NAFPOL,NAFRFT,
     6 NAFRID,NAFRTL,NAFSTR,NAFTCL,NAFTCM,NAFTOC,NAFTTM,NAFVCL,NAFVER,
     7 NAFZFR,NAHCCV,NAHCTE,NAHINF,NAHMAD,NAHPDI,NAHROA,NAHSDA,NAHTUB,
     8 NAIASL,NAIPJT,NAIRJT,NAITCO,NAITMA,NAIXTR,NAIZBD,NAJBER,NAJEST,
     9 NAJSUM,NAKEVH,NAKINE,NAKJOB,NAKLIN,NAKPOL,NAKRUN,NALIDT,NALOLE,
     A NALUPA,NAMCAD,NAMHIT,NAMTHR,NAMUDG,NAMUEX,NAOSTS,NAPART,NAPASL,
     B NAPCHY,NAPCOB,NAPCOI,NAPCPA,NAPCQA,NAPCRL,NAPECO,NAPEHY,NAPEID,
     C NAPEMH,NAPEPT,NAPEST,NAPEWI,NAPFER,NAPFHR,NAPFRF,NAPFRT,NAPHCO,
     D NAPHER,NAPHHY,NAPHMH,NAPHST,NAPIDI,NAPITM,NAPLID,NAPLPD,NAPLSD,
     E NAPMSK,NAPNEU,NAPPDS,NAPPOB,NAPPRL,NAPRTM,NAPSCO,NAPSPO,NAPSTR,
     F NAPT2X,NAPTBC,NAPTCO,NAPTEX,NAPTMA,NAPTML,NAPTNC,NAPTST,NAPVCO,
     G NAPYER,NAPYFR,NAPYNE,NAQDET,NAQFPA,NAQLIN,NAQMTL,NAQMTS,NAQPAR,
     H NAQPBT,NAQPLI,NAQTRA,NAQVEC,NAQVRT,NAQWRK,NAQZER,NAREVH,NARHAH,
     I NARTLO,NARTLS,NARUNH,NARUNR,NASFTR,NATEXS,NATGMA,NATMTL,NATPCO,
     J NAVCOM,NAVCPL,NAVDCO,NAVDHT,NAVDXY,NAVDZT,NAVERT,NAVFHL,NAVFLG,
     K NAVFPH,NAVHLS,NAVPLH,NAX1AD,NAX1SC,NAX1TI,NAX2DF,NAX3EC,NAX3EW,
     L NAX3HC,NAX3IT,NAX3L2,NAX3LU,NAX3TM,NAX3TO,NAX3TP,NAX3X3,NAXTBN,
     M NAXTBP,NAXTCN,NAXTEB,NAXTOP,NAXTRB,NAYV0V,NAZPFR,NAEFOL,NAMUID,
     N NAPGID,NAPGPC,NAPGAC,NAPMSC,NAPTHR,NANBIP,NAPDLT,NAPMLT,NAPLJT
C--------------------- end of QCNAMI ----------------------------------
C------------------ /QQQQJJ/ --- HAC parameters for ALPHA banks -------
      PARAMETER (JQVEQX= 1,JQVEQY= 2,JQVEQZ= 3,JQVEQE= 4,JQVEQM= 5,
     & JQVEQP= 6,JQVECH= 7,JQVETN= 8,JQVESC= 9,JQVEKS=10,JQVECL=11,
     & JQVEPA=12,JQVEQD=13,JQVENP=14,JQVESP=15,JQVEOV=16,JQVEEV=17,
     & JQVEND=18,JQVEDL=19,JQVENO=20,JQVEOL=21,JQVENM=22,JQVEML=23,
     & JQVEBM=24,JQVELK=38,JQVEDB=39,JQVEZB=40,JQVESD=41,JQVESZ=42,
     & JQVECB=43,JQVEEM=44,JQVECF=54,JQVEEW=55,JQVEUS=56)
      PARAMETER ( JQVRVX=1,JQVRVY=2,JQVRVZ=3,JQVRVN=4,JQVRTY=5,
     1   JQVRIP=6,JQVRND=7,JQVRDL=8,JQVRAY=9,JQVRAF=10,JQVREM=11,
     2   JQVRCF=17,JQVRET=18)
      PARAMETER ( JQDEAF= 1,JQDEAL= 2,JQDENT= 3,JQDEAT= 4,JQDELT= 8,
     &  JQDEAE= 9,JQDEAH=10,JQDEAM=11,JQDECF=12,JQDEEC=13,JQDEHC=14,
     &  JQDEET=15,JQDEFI=16,JQDENF=17,JQDEFL=18,JQDENE=19,JQDEEL=20,
     &  JQDENH=21,JQDEHL=22,JQDELH=23,JQDEEF=24,JQDEPC=25,JQDEEG=26,
     &  JQDEMU=27,JQDEDX=28,JQDEPG=29,JQDEPD=30,JQDEPM=31)
      PARAMETER ( JQPAGN=1, JQPANA=2, JQPACO=5, JQPAMA=6, JQPACH=7,
     & JQPALT=8,JQPAWI=9,JQPAAN=10)
C--------------------- end of QCDESH ----------------------------------
      EXTERNAL CQPART, CQTPN, XCEQAN, XLUMOK, XPEQAN, XPEQOR, XPEQU,
     & XVDEOK, LLUMOK, SLUMOK
      CHARACTER * 12 CQPART, CQTPN
      LOGICAL XCAL, XCEQAN, XCEQOR, XCEQU, XECAL, XEID, XFRF, XHCAL,
     & XHMA, XLOCK, XLOCKN, XMC, XLUMOK, XMCA, XPEO, XPHO, XPEQAN,
     & XPEQOR, XPEQU, XSAME, XSIG, XTEX, XPEC, XPEP, XPHC, XYV0,
     & XFRIQF, XEFO, XPCQ, XEGP, XMUI, XVDEOK, XPGP, LLUMOK, SLUMOK,
     & XPGAC, XLEPTG, XLEPTH
      REAL PI, TWOPI, PIBY2, PIBY3, PIBY4, PIBY6, PIBY8, PIBY12
      REAL RADEG, DEGRA
      REAL CLGHT, ALDEDX
      INTEGER NBITW, NBYTW, LCHAR
      PARAMETER (PI=3.141592653589)
      PARAMETER (RADEG=180./PI, DEGRA=PI/180.)
      PARAMETER (TWOPI = 2.*PI , PIBY2 = PI/2., PIBY4 = PI/4.)
      PARAMETER (PIBY6 = PI/6. , PIBY8 = PI/8.)
      PARAMETER (PIBY12= PI/12., PIBY3 = PI/3.)
      PARAMETER (CLGHT = 29.9792458, ALDEDX = 0.000307)
      PARAMETER (NBITW = 32 , NBYTW = NBITW/8 , LCHAR = 4)
      INTEGER JEFOPX,JEFOPY,JEFOPZ,JEFOEW,JEFOWE,JEFOTY,JEFOLE,JEFOLT,
     +          JEFOLH,JEFOLC,JEFOLJ,LEFOLA
      PARAMETER(JEFOPX=1,JEFOPY=2,JEFOPZ=3,JEFOEW=4,JEFOWE=5,JEFOTY=6,
     +          JEFOLE=7,JEFOLT=8,JEFOLH=9,JEFOLC=10,JEFOLJ=11,
     +          LEFOLA=11)
      INTEGER JEGPPX,JEGPPY,JEGPPZ,JEGPR1,JEGPR2,JEGPF4,JEGPDM,JEGPST,
     +          JEGPQU,JEGPPE,LEGPCA
      PARAMETER(JEGPPX=1,JEGPPY=2,JEGPPZ=3,JEGPR1=4,JEGPR2=5,JEGPF4=6,
     +          JEGPDM=7,JEGPST=8,JEGPQU=9,JEGPPE=10,LEGPCA=10)
      INTEGER JEIDIF,JEIDR1,JEIDR2,JEIDR3,JEIDR4,JEIDR5,JEIDR6,JEIDR7,
     +          JEIDEC,JEIDIP,JEIDE1,JEIDE2,JEIDE3,JEIDFR,JEIDPE,LEIDTA
      PARAMETER(JEIDIF=1,JEIDR1=2,JEIDR2=3,JEIDR3=4,JEIDR4=5,JEIDR5=6,
     +          JEIDR6=7,JEIDR7=8,JEIDEC=9,JEIDIP=10,JEIDE1=11,
     +          JEIDE2=12,JEIDE3=13,JEIDFR=14,JEIDPE=15,LEIDTA=15)
      INTEGER JFRFIR,JFRFTL,JFRFP0,JFRFD0,JFRFZ0,JFRFAL,JFRFEM,JFRFC2,
     +          JFRFDF,JFRFNO,LFRFTA
      PARAMETER(JFRFIR=1,JFRFTL=2,JFRFP0=3,JFRFD0=4,JFRFZ0=5,JFRFAL=6,
     +          JFRFEM=7,JFRFC2=28,JFRFDF=29,JFRFNO=30,LFRFTA=30)
      INTEGER JFRIBP,JFRIDZ,JFRIBC,JFRIDC,JFRIPE,JFRIPM,JFRIPI,JFRIPK,
     +          JFRIPP,JFRINK,JFRIQF,LFRIDA
      PARAMETER(JFRIBP=1,JFRIDZ=2,JFRIBC=3,JFRIDC=4,JFRIPE=5,JFRIPM=6,
     +          JFRIPI=7,JFRIPK=8,JFRIPP=9,JFRINK=10,JFRIQF=11,
     +          LFRIDA=11)
      INTEGER JFRTIV,JFRTNV,JFRTII,JFRTNI,JFRTNE,JFRTIT,JFRTNT,JFRTNR,
     +          LFRTLA
      PARAMETER(JFRTIV=1,JFRTNV=2,JFRTII=3,JFRTNI=4,JFRTNE=5,JFRTIT=6,
     +          JFRTNT=7,JFRTNR=8,LFRTLA=8)
      INTEGER JHMANF,JHMANE,JHMANL,JHMAMH,JHMAIG,JHMAED,JHMACS,JHMAND,
     +          JHMAIE,JHMAIT,JHMAIF,JHMATN,LHMADA
      PARAMETER(JHMANF=1,JHMANE=2,JHMANL=3,JHMAMH=4,JHMAIG=5,JHMAED=6,
     +          JHMACS=7,JHMAND=8,JHMAIE=9,JHMAIT=10,JHMAIF=11,
     +          JHMATN=12,LHMADA=12)
      INTEGER JMCANH,JMCADH,JMCADC,JMCAAM,JMCAAC,JMCATN,LMCADA
      PARAMETER(JMCANH=1,JMCADH=3,JMCADC=5,JMCAAM=7,JMCAAC=8,JMCATN=9,
     +          LMCADA=9)
      INTEGER JMUIIF,JMUISR,JMUIDM,JMUIST,JMUITN,LMUIDA
      PARAMETER(JMUIIF=1,JMUISR=2,JMUIDM=3,JMUIST=4,JMUITN=5,LMUIDA=5)
      INTEGER JPCQNA,JPCQPX,JPCQPY,JPCQPZ,JPCQEN,LPCQAA
      PARAMETER(JPCQNA=1,JPCQPX=2,JPCQPY=3,JPCQPZ=4,JPCQEN=5,LPCQAA=5)
      INTEGER JPDLPA,JPDLJT,JPDLPI,JPDLPE,JPDLVP,JPDLFR,LPDLTA
      PARAMETER (JPDLPA=1,JPDLJT=2,JPDLPI=3,JPDLPE=4,JPDLVP=5,
     &           JPDLFR=6,LPDLTA=6)
      INTEGER JPECER,JPECE1,JPECE2,JPECTH,JPECPH,JPECEC,JPECKD,JPECCC,
     +          JPECRB,JPECPC,LPECOA
      PARAMETER(JPECER=1,JPECE1=2,JPECE2=3,JPECTH=4,JPECPH=5,JPECEC=6,
     +          JPECKD=7,JPECCC=8,JPECRB=9,JPECPC=10,LPECOA=10)
      INTEGER JPEPT1,JPEPP1,JPEPT3,JPEPP3,LPEPTA
      PARAMETER(JPEPT1=1,JPEPP1=2,JPEPT3=3,JPEPP3=4,LPEPTA=4)
      INTEGER JPGAEC,JPGATC,JPGAPC,JPGAR1,JPGAR2,JPGAF4,JPGADM,JPGAST,
     +          JPGAQU,JPGAQ1,JPGAQ2,JPGAM1,JPGAM2,JPGAMA,JPGAER,JPGATR,
     +          JPGAPR,JPGAEF,JPGAGC,JPGAZS,JPGAPL,JPGAPH,JPGAPN,JPGAFA,
     +          JPGAPE,LPGACA
      PARAMETER(JPGAEC=1,JPGATC=2,JPGAPC=3,JPGAR1=4,JPGAR2=5,JPGAF4=6,
     +          JPGADM=7,JPGAST=8,JPGAQU=9,JPGAQ1=10,JPGAQ2=11,
     +          JPGAM1=12,JPGAM2=13,JPGAMA=14,JPGAER=15,JPGATR=16,
     +          JPGAPR=17,JPGAEF=18,JPGAGC=19,JPGAZS=20,JPGAPL=21,
     +          JPGAPH=22,JPGAPN=23,JPGAFA=24,JPGAPE=25,LPGACA=25)
      INTEGER JPGPEC,JPGPTC,JPGPPC,JPGPR1,JPGPR2,JPGPF4,JPGPDM,JPGPST,
     +          JPGPQU,JPGPQ1,JPGPQ2,JPGPM1,JPGPM2,JPGPMA,JPGPER,JPGPTR,
     +          JPGPPR,JPGPPE,LPGPCA
      PARAMETER(JPGPEC=1,JPGPTC=2,JPGPPC=3,JPGPR1=4,JPGPR2=5,JPGPF4=6,
     +          JPGPDM=7,JPGPST=8,JPGPQU=9,JPGPQ1=10,JPGPQ2=11,
     +          JPGPM1=12,JPGPM2=13,JPGPMA=14,JPGPER=15,JPGPTR=16,
     +          JPGPPR=17,JPGPPE=18,LPGPCA=18)
      INTEGER JPHCER,JPHCTH,JPHCPH,JPHCEC,JPHCKD,JPHCCC,JPHCRB,JPHCNF,
     +          JPHCPC,LPHCOA
      PARAMETER(JPHCER=1,JPHCTH=2,JPHCPH=3,JPHCEC=4,JPHCKD=5,JPHCCC=6,
     +          JPHCRB=7,JPHCNF=8,JPHCPC=9,LPHCOA=9)
      INTEGER JPMLFL,JPMLPO,JPMLCH,JPMLSP,JPMLLE,JPMLME,JPMLKT,JPMLFR,
     +          LPMLTA
      PARAMETER (JPMLFL=1,JPMLPO=2,JPMLCH=3,JPMLSP=4,JPMLLE=5,
     &           JPMLME=6,JPMLKT=7,JPMLFR=8,LPMLTA=8)
      INTEGER JTEXSI,JTEXTM,JTEXTL,JTEXNS,JTEXAD,JTEXTN,JTEXSF,LTEXSA
      PARAMETER(JTEXSI=1,JTEXTM=2,JTEXTL=3,JTEXNS=4,JTEXAD=5,JTEXTN=6,
     +          LTEXSA=6)
      INTEGER JYV0K1,JYV0K2,JYV0VX,JYV0VY,JYV0VZ,JYV0VM,JYV0PX,JYV0PY,
     +          JYV0PZ,JYV0PM,JYV0X1,JYV0X2,JYV0XM,JYV0C2,JYV0IC,JYV0P1,
     +          JYV0P2,JYV0EP,JYV0DM,JYV0S1,JYV0S2,LYV0VA
      PARAMETER(JYV0K1=1,JYV0K2=2,JYV0VX=3,JYV0VY=4,JYV0VZ=5,JYV0VM=6,
     +          JYV0PX=12,JYV0PY=13,JYV0PZ=14,JYV0PM=15,JYV0X1=21,
     +          JYV0X2=22,JYV0XM=23,JYV0C2=26,JYV0IC=27,JYV0P1=28,
     +          JYV0P2=31,JYV0EP=34,JYV0DM=55,JYV0S1=56,JYV0S2=57,
     +          LYV0VA=57)
C--------------------- end of QCDE ------------------------------------
      DIMENSION QT(KCQVEC,1), KT(KCQVEC,1), QV(KCQVRT,1), KV(KCQVEC,1)
C ALPHA Version 122 - HAC parameters include file created 12 April 1996
C-----------------------------------
      INTEGER JAFIAR,JAFIAZ,JAFIMF,JAFIBE,LAFIDA
      PARAMETER(JAFIAR=1,JAFIAZ=2,JAFIMF=3,JAFIBE=4,LAFIDA=4)
      INTEGER JAJOBM,JAJORM,JAJOGI,JAJOSO,JAJOSD,JAJOGC,JAJOJD,JAJOJT,
     +          JAJOGV,JAJOAV,JAJOFT,JAJOFS,JAJOFC,JAJODV,JAJODD,JAJOTV,
     +          JAJOCV,JAJOGN,LAJOBA
      PARAMETER(JAJOBM=1,JAJORM=2,JAJOGI=3,JAJOSO=4,JAJOSD=5,JAJOGC=6,
     +          JAJOJD=7,JAJOJT=8,JAJOGV=9,JAJOAV=10,JAJOFT=11,
     +          JAJOFS=12,JAJOFC=13,JAJODV=14,JAJODD=15,JAJOTV=16,
     +          JAJOCV=17,JAJOGN=18,LAJOBA=18)
      INTEGER JASERG,LASEVA
      PARAMETER(JASERG=1,LASEVA=3)
      INTEGER JBCNBT,JBCNB1,JBCNB2,JBCNST,JBCND1,JBCND2,JBCNCT,LBCNTA
      PARAMETER(JBCNBT=1,JBCNB1=2,JBCNB2=3,JBCNST=4,JBCND1=8,JBCND2=9,
     +          JBCNCT=10,LBCNTA=10)
      INTEGER JBHIDB,LBHITA
      PARAMETER(JBHIDB=1,LBHITA=1)
      INTEGER JBOMRU,JBOMXO,JBOMXS,JBOMYO,JBOMYS,JBOMFL,LBOMAA
      PARAMETER(JBOMRU=1,JBOMXO=2,JBOMXS=3,JBOMYO=4,JBOMYS=5,
     +          JBOMFL=6,LBOMAA=6)
      INTEGER JBOMXX,JBOMYY,JBOMEE,LBOMBA
      PARAMETER(JBOMXX=1,JBOMYY=2,JBOMEE=3,LBOMBA=3)
      INTEGER JBOMXI,JBOMXP,JBOMYI,JBOMYP,JBOMBU,JBOMIA,JBOMIB,JBOMR1,
     +          JBOMR2,JBOMR3,JBOMR4,JBOMER,LBOMEA
      PARAMETER(JBOMXI=1,JBOMXP=2,JBOMYI=3,JBOMYP=4,JBOMBU=5,JBOMIA=6,
     +          JBOMIB=7,JBOMR1=8,JBOMR2=9,JBOMR3=10,JBOMR4=11,
     +          JBOMER=12,LBOMEA=12)
      INTEGER JBOMXA,JBOMYA,JBOMSA,JBOMCA,JBOMXB,JBOMYB,JBOMSB,JBOMCB,
     +          JBOMBI,JBOMPU,LBOMPA
      PARAMETER(JBOMXA=1,JBOMYA=2,JBOMSA=3,JBOMCA=4,JBOMXB=5,JBOMYB=6,
     +          JBOMSB=7,JBOMCB=8,JBOMBI=9,JBOMPU=10,LBOMPA=10)
      INTEGER JBOMMN,JBOMSI,JBOMPE,JBOMCL,LBOMRA
      PARAMETER(JBOMMN=1,JBOMSI=2,JBOMPE=3,JBOMCL=4,LBOMRA=4)
      INTEGER JBPTAB,LBPTRA
      PARAMETER(JBPTAB=1,LBPTRA=1)
      INTEGER JDCRDE,JDCRDH,JDCRDT,LDCRLA
      PARAMETER(JDCRDE=1,JDCRDH=2,JDCRDT=3,LDCRLA=3)
      INTEGER JDECE0,JDECTH,JDECPH,JDECEF,JDECCC,LDECOA
      PARAMETER(JDECE0=1,JDECTH=2,JDECPH=3,JDECEF=4,JDECCC=6,LDECOA=6)
      INTEGER JDEIR2,JDEIR3,JDEIQF,JDEIDE,JDEIDT,LDEIDA
      PARAMETER(JDEIR2=1,JDEIR3=2,JDEIR6=3,JDEIR7=4,JDEIQF=5,JDEIDE=6,
     +          JDEIDT=7,LDEIDA=7)
      INTEGER JDENPX,JDENPY,JDENPZ,JDENE0,JDENWE,JDENTY,JDENPC,JDENDT,
     +          JDENDJ,LDENFA
      PARAMETER(JDENPX=1,JDENPY=2,JDENPZ=3,JDENE0=4,JDENWE=5,JDENTY=6,
     +          JDENPC=7,JDENDT=8,JDENDJ=9,LDENFA=9)
      INTEGER JDEVLE,JDEVWT,JDEVNX,JDEVNV,JDEVWR,JDEVWA,JDEVWB,JDEVPR,
     +          JDEVPA,JDEVPB,JDEVLA,JDEVLB,JDEVHR,JDEVHA,JDEVHB,LDEVTA
      PARAMETER(JDEVCW=1,JDEVT1=2,JDEVT2=3,JDEVLE=4,JDEVWT=5,LDEVTA=5)
      INTEGER JDEWMN,JDEWE0,JDEWEF,LDEWIA
      PARAMETER(JDEWMN=1,JDEWE0=2,JDEWEF=3,LDEWIA=4)
      INTEGER JDFMZF,LDFMCA
      PARAMETER(JDFMZF=1,LDFMCA=1)
      INTEGER JDFOPX,JDFOPY,JDFOPZ,JDFOQF,JDFODE,LDFOTA
      PARAMETER(JDFOPX=1,JDFOPY=2,JDFOPZ=3,JDFOQF=4,JDFODE=5,LDFOTA=5)
      INTEGER JDGANA,JDGAE1,JDGAE2,JDGAE3,JDGAE5,JDGAE6,JDGAE8,JDGAE0,
     +          JDGATH,JDGAPH,JDGADE,LDGAMA
      PARAMETER(JDGANA=1,JDGAE1=2,JDGAE2=3,JDGAE3=4,JDGAE5=5,JDGAE6=6,
     +          JDGAE8=7,JDGAE0=8,JDGATH=9,JDGAPH=10,JDGADE=11,
     +          LDGAMA=11)
      INTEGER JDHCE0,JDHCTH,JDHCPH,LDHCOA
      PARAMETER(JDHCE0=1,JDHCTH=2,JDHCPH=3,LDHCOA=3)
      INTEGER JDHEFP,JDHENX,JDHENP,JDHENM,JDHENV,JDHENJ,JDHEEC,JDHEEL,
     +          JDHEPF,JDHETH,JDHEPH,JDHEEF,JDHEET,JDHET1,JDHEP1,JDHET2,
     +          JDHEP2,JDHEE1,JDHEE2,JDHEE3,JDHERS,JDHEWT,LDHEAA
      PARAMETER(JDHEFP=1,JDHENX=2,JDHENP=3,JDHENM=4,JDHENV=5,JDHENJ=6,
     +          JDHEEC=7,JDHEEL=8,JDHEPF=9,JDHETH=10,JDHEPH=11,
     +          JDHEEF=12,JDHEET=13,JDHET1=14,JDHEP1=15,JDHET2=16,
     +          JDHEP2=17,JDHEE1=18,JDHEE2=19,JDHEE3=20,JDHERS=21,
     +          JDHEWT=22,LDHEAA=22)
      INTEGER JDHRDH,JDHRDP,LDHRLA
      PARAMETER(JDHRDH=1,JDHRDP=2,LDHRLA=2)
      INTEGER JDJEPX,JDJEPY,JDJEPZ,JDJEE0,LDJETA
      PARAMETER(JDJEPX=1,JDJEPY=2,JDJEPZ=3,JDJEE0=4,LDJETA=4)
      INTEGER JDMJNP,JDMJNM,JDMJP0,JDMJTH,JDMJPH,JDMJE0,LDMJTA
      PARAMETER(JDMJNP=1,JDMJNM=2,JDMJP0=3,JDMJTH=4,JDMJPH=5,JDMJE0=6,
     +          LDMJTA=6)
      PARAMETER(JDMUHO=1,JDMUHE=2,JDMUSH=3,JDMUDT=4,LDMUOA=4)
      PARAMETER(JDNENA=1,JDNEE0=2,JDNETH=3,JDNEPH=4,JDNER1=5,JDNER2=6,
     +          JDNEPC=7,JDNEDE=8,LDNEUA=8)
      PARAMETER(JDPOE0=1,LDPOBA=1)
      PARAMETER(JDRENA=1,JDREE0=2,JDRETH=3,JDREPH=4,JDREP0=5,JDREPS=6,
     +          JDREPC=7,LDRESA=7)
      PARAMETER(JDTBT1=1,JDTBT2=2,JDTBL2=3,LDTBPA=3)
      PARAMETER(JDTMPX=1,JDTMPY=2,JDTMPZ=3,JDTMMA=4,JDTMPA=5,JDTMOV=6,
     +          JDTMEV=7,JDTMHC=8,LDTMCA=8)
      PARAMETER(JDTRCH=1,JDTRP0=2,JDTRTH=3,JDTRPH=4,JDTRD0=5,JDTRZ0=6,
     +          JDTRER=7,JDTREM=12,JDTRTF=16,JDTRHO=17,JDTRHM=18,
     +          JDTRDE=19,JDTRNS=20,JDTRTL=21,JDTRVB=22,JDTRQF=23,
     +          JDTREA=24,JDTRDR=34,LDTRAA=34)
      PARAMETER(JDVEX0=1,JDVEY0=2,JDVEZ0=3,JDVEFP=4,JDVEMV=5,JDVEDT=6,
     +          LDVERA=6)
      PARAMETER(JDVMVX=1,JDVMVY=2,JDVMVZ=3,JDVMIP=4,JDVMVN=5,JDVMVM=6,
     +          LDVMCA=6)
      PARAMETER(JECRMA=1,JECRCS=2,LECRQA=2)
      PARAMETER(JECTCA=1,JECTCE=2,LECTEA=2)
      PARAMETER(JEGIIF=1,JEGIE1=2,JEGIE2=3,JEGIE3=4,JEGIE4=5,JEGIE5=6,
     +          JEGIE6=7,JEGIE7=8,JEGIE8=9,JEGINA=10,JEGICE=11,
     +          JEGITH=12,JEGIPH=13,JEGIPE=14,LEGIDA=14)
      INTEGER JEJEPX,JEJEPY,JEJEPZ,JEJEPE,LEJETA
      PARAMETER(JEJEPX=1,JEJEPY=2,JEJEPZ=3,JEJEPE=4,LEJETA=4)
      PARAMETER(JERREF=1,JERRRO=2,JERRAC=3,JERRC1=4,JERRC2=5,JERRC3=6,
     +          JERRE1=7,JERRE2=8,JERRE3=9,JERRF1=10,JERRF2=11,
     +          LERRFA=11)
      PARAMETER(JETDTL=1,JETDS1=2,JETDS2=3,JETDS3=4,LETDIA=4)
      PARAMETER(JETKTL=1,JETKS1=2,JETKS2=3,JETKS3=4,JETKKR=5,LETKCA=5)
      PARAMETER(JEVEEN=1,JEVERN=2,JEVERT=3,JEVEDA=4,JEVETI=5,JEVEEV=6,
     +          JEVEM1=7,JEVEM2=8,JEVEM3=9,JEVEM4=10,JEVETY=11,
     +          JEVEES=12,JEVETE=13,LEVEHA=13)
      PARAMETER(JEWHSD=1,JEWHNU=2,LEWHEA=2)
      INTEGER JFKIPX,JFKIPY,JFKIPZ,JFKIMA,JFKIPA,JFKIOV,JFKIEV,JFKIHC,
     +          LFKINA
      PARAMETER(JFKIPX=1,JFKIPY=2,JFKIPZ=3,JFKIMA=4,JFKIPA=5,JFKIOV=6,
     +          JFKIEV=7,JFKIHC=8,LFKINA=8)
      INTEGER JFPOIP,JFPOIS,LFPOIA
      PARAMETER(JFPOIP=1,JFPOIS=2,LFPOIA=2)
      PARAMETER(JFPOKI=1,JFPOHX=2,JFPOHY=3,JFPOHZ=4,LFPOLA=4)
      INTEGER JFVEVX,JFVEVY,JFVEVZ,JFVETO,JFVEIP,JFVEIS,JFVENS,JFVEVN,
     +          JFVEVM,LFVERA
      PARAMETER(JFVEVX=1,JFVEVY=2,JFVEVZ=3,JFVETO=4,JFVEIP=5,JFVEIS=6,
     +          JFVENS=7,JFVEVN=8,JFVEVM=9,LFVERA=9)
      INTEGER JFZFZF,LFZFRA
      PARAMETER(JFZFZF=1,LFZFRA=1)
      PARAMETER(JHCCCC=1,LHCCVA=1)
      PARAMETER(JHCTCA=1,JHCTCE=2,LHCTEA=2)
      PARAMETER(JHINEI=1,LHINFA=1)
      PARAMETER(JHPDPA=1,JHPDED=2,LHPDIA=2)
      PARAMETER(JHRODX=1,JHROSG=2,JHROSF=3,JHROHI=4,LHROAA=4)
      PARAMETER(JHTUSN=1,JHTUMN=2,JHTULN=3,JHTULC=4,JHTUCW=5,JHTUPR=6,
     +          JHTUPP=7,LHTUBA=7)
      INTEGER JIASFK,JIASNH,JIASCS,LIASLA
      PARAMETER(JIASFK=1,JIASNH=2,JIASCS=3,LIASLA=3)
      PARAMETER(JIPJNH=1,JIPJNS=2,JIPJRN=3,LIPJTA=3)
      PARAMETER(JIRJGN=1,JIRJNH=2,JIRJSH=3,LIRJTA=3)
      INTEGER JITMNA,JITMOF,JITMNC,LITMAA
      PARAMETER(JITMNA=1,JITMOF=2,JITMNC=3,LITMAA=3)
      PARAMETER(JIXTTI=1,LIXTRA=1)
      PARAMETER(JIZDTI=1,LIZDBA=1)
      PARAMETER(JJBECO=1,LJBERA=1)
      PARAMETER(JJESET=1,JJESON=2,JJESNN=3,JJESOL=4,JJESCL=5,JJESPN=6,
     +          JJESBP=7,LJESTA=7)
      PARAMETER(JJSUNT=1,JJSUNV=2,JJSUNZ=3,JJSUNL=4,JJSUNB=5,JJSUVT=6,
     +          JJSUVV=7,JJSUVZ=8,JJSUVL=9,JJSUVB=10,JJSUTT=11,
     +          JJSUTZ=12,JJSUTB=13,JJSULI=14,JJSUIZ=15,JJSULO=16,
     +          JJSULZ=17,JJSUXV=18,JJSUYV=19,JJSUZV=20,JJSUXS=21,
     +          JJSUYS=22,JJSUZS=23,JJSUKB=24,JJSUKW=25,JJSUTN=26,
     +          JJSUTS=27,JJSUTV=28,JJSUA0=29,JJSUA1=30,JJSUA2=31,
     +          JJSUA3=32,JJSUA4=33,JJSUA5=34,JJSUA6=35,JJSUA7=36,
     +          JJSUA8=37,JJSUA9=38,JJSUB0=39,JJSUB1=40,JJSUB2=41,
     +          JJSUB3=42,JJSUB4=43,JJSUB5=44,JJSUB6=45,JJSUB7=46,
     +          JJSUB8=47,JJSUB9=48,LJSUMA=48)
      PARAMETER(JKEVRN=1,JKEVNT=2,JKEVNV=3,JKEVPI=4,JKEVWT=5,JKEVSR=6,
     +          JKEVTR=7,LKEVHA=7)
      PARAMETER(JKINPX=1,JKINPY=2,JKINPZ=3,JKINMA=4,JKINPN=5,JKINVN=6,
     +          LKINEA=6)
      PARAMETER(JKJOJD=1,JKJOJT=2,JKJOAV=3,JKJODV=4,JKJODC=5,LKJOBA=5)
      PARAMETER(JKPOKI=1,JKPOHX=2,JKPOHY=3,JKPOHZ=4,LKPOLA=4)
      PARAMETER(JLIDIF=1,JLIDEC=2,JLIDTC=3,JLIDPC=4,JLIDE4=5,JLIDE1=6,
     +          JLIDE2=7,JLIDR1=8,JLIDR2=9,JLIDXX=10,JLIDYY=11,
     +          JLIDXY=12,JLIDDA=13,JLIDNT=17,JLIDLO=18,JLIDLS=19,
     +          JLIDST=20,LLIDTA=20)
      PARAMETER(JLOLFB=1,JLOLSP=5,JLOLTO=6,JLOLMA=7,JLOLHV=11,JLOLER=12,
     +          LLOLEA=12)
      PARAMETER(JLUPGB=1,JLUPHV=2,JLUPT1=3,JLUPL2=4,JLUPTE=5,JLUPLO=6,
     +          JLUPAM=7,JLUPMD=8,JLUPEF=9,JLUPEC=10,JLUPEW=12,
     +          JLUPXC=14,JLUPYC=16,JLUPTC=18,JLUPPC=20,JLUPAX=22,
     +          JLUPAY=24,JLUPXX=26,JLUPYY=28,JLUPXY=30,JLUPXA=32,
     +          JLUPYA=34,JLUPXD=36,JLUPYD=38,JLUPAD=40,JLUPIT=42,
     +          JLUPCT=44,JLUPTT=46,JLUPPT=48,JLUPXT=50,JLUPYT=52,
     +          JLUPE1=54,JLUPE2=56,JLUPXL=58,JLUPYL=60,JLUPAI=62,
     +          JLUPES=64,JLUPXS=66,JLUPYS=68,JLUPAS=70,LLUPAA=71)
      INTEGER JMHISC,JMHISN,JMHILN,JMHIXL,JMHIYL,JMHIRH,JMHITH,JMHIPH,
     +          LMHITA
      PARAMETER(JMHISC=1,JMHISN=2,JMHILN=3,JMHIXL=4,JMHIYL=5,JMHIRH=6,
     +          JMHITH=7,JMHIPH=8,LMHITA=8)
      PARAMETER(JMTHHN=1,JMTHDD=2,JMTHTN=3,LMTHRA=3)
      PARAMETER(JMUDEA=1,LMUDGA=1)
      PARAMETER(JMUEXE=1,JMUEPE=4,JMUEC0=7,JMUEC1=8,JMUEC2=9,LMUEXA=9)
      INTEGER JNBITF,JNBITS,LNBIPA
      PARAMETER (JNBITF=1,JNBITS=2,LNBIPA=2)
      PARAMETER(JOSTEI=1,JOSTOR=2,JOSTEL=3,JOSTTN=4,JOSTTM=5,JOSTET=6,
     +          LOSTSA=6)
      INTEGER JPARGN,JPARNA,JPARCO,JPARMA,JPARCH,JPARLT,JPARMW,JPARAN,
     +          LPARTA
      PARAMETER(JPARGN=1,JPARNA=2,JPARCO=5,JPARMA=6,JPARCH=7,JPARLT=8,
     +          JPARMW=9,JPARAN=10,LPARTA=10)
      PARAMETER(JPASFK=1,JPASNH=2,LPASLA=2)
      PARAMETER(JPCHBH=1,JPCHKT=2,JPCHPC=3,LPCHYA=3)
      PARAMETER(JPCO00=3,LPCOBA=0)
      PARAMETER(JPCONP=1,JPCOPH=2,JPCOTF=3,JPCONH=4,JPCOPL=5,LPCOIA=5)
      PARAMETER(JPCPNA=1,JPCPEN=2,JPCPTE=3,JPCPFI=4,JPCPR1=5,JPCPR2=6,
     +          JPCPPC=7,LPCPAA=7)
      PARAMETER(JPCRPC=1,JPCRPE=2,JPCRPF=3,JPCRPH=4,JPCRPP=5,LPCRLA=5)
      INTEGER JPEHBH,JPEHKT,JPEHPE,LPEHYA
      PARAMETER(JPEHBH=1,JPEHKT=2,JPEHPE=3,LPEHYA=3)
      PARAMETER(JPEIIF=1,JPEIR1=2,JPEIR2=3,JPEIR3=4,JPEIR4=5,JPEIR6=6,
     +          JPEIR7=7,JPEIEC=8,JPEIET=9,JPEIP1=10,JPEIP2=11,
     +          JPEIPF=12,LPEIDA=12)
      PARAMETER(JPEMCO=1,JPEMTN=2,JPEMSE=3,LPEMHA=3)
      PARAMETER(JPESKS=1,JPESER=2,JPESED=3,JPESET=4,JPESPE=5,LPESTA=5)
      PARAMETER(JPEWMN=1,JPEWPD=2,JPEWSS=47,JPEWTI=55,LPEWIA=55)
      PARAMETER(JPFEPE=1,JPFEPF=2,LPFERA=2)
      PARAMETER(JPFHPF=1,JPFHPH=2,LPFHRA=2)
      PARAMETER(JPFRIR=1,JPFRTL=2,JPFRP0=3,JPFRD0=4,JPFRZ0=5,JPFRAL=6,
     +          JPFREO=7,JPFREM=13,JPFRC2=28,JPFRNO=29,LPFRFA=29)
      PARAMETER(JPFRNV=1,JPFRNI=2,JPFRNE=3,JPFRNT=4,JPFRNR=5,LPFRTA=5)
      PARAMETER(JPGIIF=1,JPGIDE=2,JPGICM=3,JPGIM1=4,JPGIM2=5,JPGIM3=6,
     +          JPGICE=7,JPGITH=8,JPGIPH=9,JPGIPE=10,LPGIDA=10)
      PARAMETER(JPHEPE=1,JPHEPH=2,LPHERA=2)
      PARAMETER(JPHHBH=1,JPHHKT=2,JPHHPH=3,LPHHYA=3)
      PARAMETER(JPHMCO=1,JPHMTN=2,LPHMHA=2)
      PARAMETER(JPHSTI=1,JPHSPI=2,JPHSCE=3,JPHSPH=4,LPHSTA=4)
      PARAMETER(JPIDPD=1,LPIDIA=1)
      PARAMETER(JPITNA=1,LPITMA=1)
      PARAMETER(JPLIIF=1,JPLIEC=2,JPLITC=3,JPLIPC=4,JPLIE4=5,JPLIE1=6,
     +          JPLIE2=7,JPLIR1=8,JPLIR2=9,JPLIXX=10,JPLIYY=11,
     +          JPLIXY=12,JPLIDA=13,JPLINT=17,JPLIPE=18,JPLIPL=19,
     +          JPLIST=20,LPLIDA=20)
      INTEGER JPLJPX,JPLJPY,JPLJPZ,JPLJPE,JPLJNO,LPLJTA
      PARAMETER (JPLJPX=1,JPLJPY=2,JPLJPZ=3,JPLJPE=4,JPLJNO=5,LPLJTA=5)
      PARAMETER(JPLPAD=1,JPLPEN=2,LPLPDA=2)
      PARAMETER(JPLSAD=1,JPLSE1=2,JPLSE2=3,JPLSE3=4,JPLSPE=5,LPLSDA=5)
      PARAMETER(JPMSC1=1,LPMSCA=1)
      PARAMETER(JPMSKT=1,JPMSEM=2,JPMSF1=3,JPMSF3=4,JPMST1=5,JPMSP1=6,
     +          JPMST3=7,JPMSP3=8,JPMSTH=9,JPMSPH=10,JPMSPF=11,
     +          LPMSKA=11)
      PARAMETER(JPNEPX=1,JPNEPY=2,JPNEPZ=3,JPNEPM=4,JPNEMS=10,JPNEEM=11,
     +          LPNEUA=11)
      PARAMETER(JPPDNL=1,JPPDFL=2,JPPDMD=3,JPPDPP=4,LPPDSA=4)
      PARAMETER(JPPODI=1,JPPODE=2,JPPOC1=3,JPPOC2=4,JPPOIP=5,JPPOFP=6,
     +          JPPOLP=7,JPPOMD=8,JPPOPD=9,LPPOBA=9)
      PARAMETER(JPPRPC=1,JPPRPE=2,JPPRPH=3,JPPRPP=4,LPPRLA=4)
      PARAMETER(JPRPPN=1,JPRPMR=2,JPRPMN=3,JPRPF1=4,JPRPF2=5,JPRPER=6,
     +          LPRPWA=6)
      PARAMETER(JPRTMA=1,JPRTCT=2,LPRTMA=2)
      PARAMETER(JPSCSI=1,JPSCLA=2,JPSCSC=3,JPSCTT=4,LPSCOA=5)
      PARAMETER(JPSPTC=1,LPSPOA=9)
      PARAMETER(JPT2SL=1,JPT2TM=2,JPT2UL=3,JPT2NS=4,JPT2AD=5,JPT2T1=6,
     +          JPT2T2=7,LPT2XA=7)
      PARAMETER(JPTBSL=1,JPTBSR=2,JPTBPS=3,JPTBZV=4,JPTBNP=5,JPTBNB=6,
     +          LPTBCA=6)
      PARAMETER(JPTCSL=1,JPTCSR=2,JPTCPS=3,JPTCZV=4,JPTCSP=5,JPTCSZ=6,
     +          JPTCDR=7,LPTCOA=7)
      INTEGER JPTESL,JPTETM,JPTEUL,JPTENS,JPTEAD,JPTETN,JPTESF,LPTEXA
      PARAMETER(JPTESL=1,JPTETM=2,JPTEUL=3,JPTENS=4,JPTEAD=5,JPTETN=6,
     +          JPTESF=7,LPTEXA=7)
      PARAMETER(JPTHPR=1,JPTHPX=2,JPTHPY=3,JPTHPZ=4,JPTHPE=5,LPTHRA=5)
      PARAMETER(JPTMNM=1,JPTMNA=2,LPTMAA=2)
      PARAMETER(JPTMMT=1,JPTMNH=2,LPTMLA=2)
      PARAMETER(JPTNSL=1,JPTNSR=2,JPTNRP=3,JPTNZV=4,JPTNSP=5,JPTNSZ=6,
     +          LPTNCA=6)
      PARAMETER(JPTSSP=1,JPTSTW=2,JPTSTP=3,JPTSNT=4,JPTSTE=5,LPTSTA=5)
      INTEGER JPYETY,JPYEVX,JPYEVY,JPYEVZ,JPYEVM,JPYEC2,JPYEDF,LPYERA
      PARAMETER(JPYETY=1,JPYEVX=2,JPYEVY=3,JPYEVZ=4,JPYEVM=5,JPYEC2=11,
     +          JPYEDF=12,LPYERA=12)
      PARAMETER(JPYFTN=1,JPYFVN=2,LPYFRA=2)
      PARAMETER(JPYNTN=1,JPYNVN=2,LPYNEA=2)
      PARAMETER(JREVDS=1,JREVFE=2,JREVNE=4,JREVSB=6,JREVTI=7,JREVRB=8,
     +          JREVEC=10,LREVHA=10)
      INTEGER JRHAPN,JRHAPD,JRHAPH,JRHAPV,JRHAAV,JRHADV,JRHADD,JRHANI,
     +          JRHANO,JRHACV,JRHANU,LRHAHA
      PARAMETER(JRHAPN=1,JRHAPD=3,JRHAPH=4,JRHAPV=5,JRHAAV=6,JRHADV=7,
     +          JRHADD=8,JRHANI=9,JRHANO=10,JRHACV=11,JRHANU=12,
     +          LRHAHA=12)
      PARAMETER(JRTLPA=1,JRTLET=2,JRTLTN=3,JRTLTM=4,JRTLT1=5,JRTLT2=6,
     +          JRTLT3=7,JRTLR1=8,JRTLR2=9,JRTLEL=10,JRTLCT=11,
     +          JRTLCH=12,LRTLOA=12)
      INTEGER JRUNEN,JRUNRN,JRUNRT,JRUNSD,JRUNST,JRUNTT,JRUNRC,LRUNHA
      PARAMETER(JRUNEN=1,JRUNRN=2,JRUNRT=3,JRUNSD=4,JRUNST=5,LRUNHA=5)
      PARAMETER(JSFTNF=1,JSFTC2=2,JSFTQF=3,JSFTTH=4,JSFTPH=5,JSFTX0=6,
     +          JSFTY0=7,JSFTCM=8,JSFTLI=18,LSFTRA=18)
      PARAMETER(JTC2ID=1,JTC2VR=2,JTC2NR=4,JTC2SN=5,JTC2AP=41,JTC2RP=42,
     +          JTC2SL=46,LTC2XA=46)
      INTEGER JTC3ID,JTC3VR,JTC3NR,JTC3PR,LTC3XA
      PARAMETER(JTC3ID=1,JTC3VR=2,JTC3NR=4,JTC3PR=5,LTC3XA=11)
      PARAMETER(JTC4ID=1,JTC4VR=2,JTC4MN=4,JTC4MX=5,JTC4RP=6,JTC4IP=13,
     +          LTC4XA=22)
      PARAMETER(JTGMNM=1,JTGMOM=2,JTGMNC=3,JTGMNA=4,LTGMAA=4)
      PARAMETER(JTMTMT=1,JTMTNH=2,JTMTCS=3,LTMTLA=3)
      PARAMETER(JVCOCM=1,LVCOMA=1)
      INTEGER JVCPXB,JVCPNX,JVCPZB,JVCPNZ,JVCPC2,LVCPLA
      PARAMETER(JVCPXB=1,JVCPNX=2,JVCPZB=3,JVCPNZ=4,JVCPC2=5,LVCPLA=5)
      PARAMETER(JVDCWI=1,JVDCR0=2,JVDCPH=3,JVDCZ0=4,JVDCSR=5,JVDCSZ=6,
     +          JVDCQF=7,JVDCTN=8,LVDCOA=8)
      INTEGER JVDHTN,JVDHLN,JVDHPN,JVDHXE,JVDHYE,JVDHZE,JVDHXL,JVDHYL,
     +          JVDHZL,JVDHER,LVDHTA
      PARAMETER(JVDHTN=1,JVDHLN=2,JVDHPN=3,JVDHXE=4,JVDHYE=5,JVDHZE=6,
     +          JVDHXL=7,JVDHYL=8,JVDHZL=9,JVDHER=10,LVDHTA=10)
      INTEGER JVDXXC,JVDXYC,JVDXUC,JVDXSX,JVDXSY,JVDXSU,JVDXPH,JVDXQF,
     +          JVDXNA,JVDXIP,JVDXIW,JVDXIH,LVDXYA
      PARAMETER(JVDXXC=1,JVDXYC=2,JVDXUC=3,JVDXSX=4,JVDXSY=5,JVDXSU=6,
     +          JVDXPH=7,JVDXQF=8,JVDXNA=9,JVDXIP=10,JVDXIW=11,
     +          JVDXIH=12,LVDXYA=12)
      INTEGER JVDZZC,JVDZWC,JVDZSZ,JVDZSW,JVDZPH,JVDZQF,JVDZNA,JVDZIP,
     +          JVDZIW,JVDZIH,LVDZTA
      PARAMETER(JVDZZC=1,JVDZWC=2,JVDZSZ=3,JVDZSW=4,JVDZPH=5,JVDZQF=6,
     +          JVDZNA=7,JVDZIP=8,JVDZIW=9,JVDZIH=10,LVDZTA=10)
      PARAMETER(JVERVX=1,JVERVY=2,JVERVZ=3,JVERTI=4,JVERIT=5,JVEROT=6,
     +          LVERTA=6)
      PARAMETER(JVFHHA=1,LVFHLA=1)
      PARAMETER(JVFLFG=1,LVFLGA=1)
      PARAMETER(JVFPPH=1,LVFPHA=1)
      PARAMETER(JVHLHC=1,LVHLSA=1)
      PARAMETER(JVPLPC=1,LVPLHA=1)
      PARAMETER(JX1AIT=1,JX1AAV=2,LX1ADA=37)
      PARAMETER(JX1SIT=1,JX1STS=2,JX1SSV=3,LX1SCA=32)
      PARAMETER(JX2DDA=1,LX2DFA=1)
      PARAMETER(JX3EEL=1,JX3EEH=2,JX3ESL=3,JX3ESH=6,JX3ECL=9,JX3ELX=12,
     +          JX3ELY=15,JX3ELZ=18,JX3ECH=21,JX3EHX=24,JX3EHY=27,
     +          JX3EHZ=30,LX3ECA=32)
      PARAMETER(JX3EES=1,JX3EEO=4,JX3EEE=5,JX3EEC=6,JX3EMP=7,JX3EFP=8,
     +          LX3EWA=8)
      PARAMETER(JX3HNT=1,JX3HTT=2,JX3HEC=3,JX3HET=4,JX3HEF=5,JX3HEB=6,
     +          JX3HTC=7,JX3HTF=8,JX3HTB=9,JX3HPC=10,JX3HPF=11,
     +          JX3HPB=12,JX3HFT=13,LX3HCA=13)
      PARAMETER(JX3IMN=1,JX3ITB=2,JX3IEL=3,JX3ICH=4,JX3IDF=5,JX3IRA=6,
     +          JX3IX0=7,JX3IY0=8,JX3ID0=9,JX3IRT=10,JX3IPT=11,
     +          JX3IAT=12,JX3IDP=13,LX3ITA=13)
      PARAMETER(JX3LZ0=1,JX3LTL=2,JX3LEV=3,JX3LCH=6,JX3LNF=7,LX3L2A=7)
      PARAMETER(JX3LMN=1,JX3LEC=2,JX3LTC=3,JX3LPC=4,JX3LCW=5,JX3LNT=6,
     +          JX3LEF=7,JX3LEM=8,JX3LEB=9,JX3LRE=10,LX3LUA=10)
      PARAMETER(JX3TTS=1,JX3TTT=2,LX3TMA=33)
      PARAMETER(JX3TH1=1,JX3TH2=4,JX3TH3=7,JX3TH4=10,JX3TH5=13,
     +          JX3TH6=16,JX3TE1=19,JX3TE2=22,JX3TE3=25,JX3TE4=28,
     +          JX3TE5=31,JX3TE6=34,JX3TE7=37,JX3TE8=40,JX3TW1=43,
     +          JX3TW2=46,JX3TW3=49,JX3TW4=52,JX3TW5=55,JX3TW6=58,
     +          JX3TL1=61,JX3TL2=63,JX3TL3=65,JX3TL4=67,JX3TL5=69,
     +          JX3TL6=71,JX3TL7=73,JX3TL8=75,LX3TOA=76)
      PARAMETER(JX3TTB=1,JX3TEL=2,JX3TNH=3,JX3TBL=4,JX3TIR=5,JX3TOR=6,
     +          JX3TPR=7,JX3TPI=8,JX3TTI=9,JX3TZI=10,JX3TPO=11,
     +          JX3TTO=12,JX3TZO=13,JX3TAT=14,LX3TPA=14)
      PARAMETER(JX3XTR=1,JX3XST=2,JX3XFT=3,LX3X3A=3)
      PARAMETER(JXTCTT=1,JXTCGC=3,JXTCLL=4,JXTCBN=5,JXTCCL=6,JXTCTR=7,
     +          LXTCNA=16)
      PARAMETER(JXTET1=1,JXTET2=2,JXTEL2=3,JXTEHT=4,JXTEHW=16,JXTELW=28,
     +          JXTEEW=40,JXTELT=52,JXTETE=56,JXTEIT=58,JXTETP=62,
     +          LXTEBA=65)
      PARAMETER(JXTBID=1,JXTBVR=2,JXTBTN=4,JXTBTB=5,JXTBBM=6,JXTBBN=8,
     +          JXTBAD=18,JXTBL1=23,JXTBL2=24,LXTBNA=24)
      PARAMETER(JXTOID=1,JXTOVR=2,JXTONA=4,JXTOTR=6,JXTOGS=7,JXTODS=8,
     +          JXTOTT=16,LXTOPA=16)
      PARAMETER(JXTRRP=1,JXTRRN=4,LXTRBA=4)
      PARAMETER(JZPFC1=1,JZPFC2=2,LZPFRA=2)
C--------------------- end of QHAC ------------------------------------
C-------------------- /QMACRO/ --- statement functions ----------------
C - # of words/row in bank with index ID
      LCOLS(ID) = IW(ID+LMHCOL)
C - # of rows in bank with index ID
      LROWS(ID) = IW(ID+LMHROW)
C - index of next row in the bank with index ID
      KNEXT(ID) = ID + LMHLEN + IW(ID+1)*IW(ID+2)
C - index of row # NRBOS in the bank with index ID
      KROW(ID,NRBOS) = ID + LMHLEN + IW(ID+1)*(NRBOS-1)
C - # of free words in the bank with index ID
      LFRWRD(ID) = ID + IW(ID) - KNEXT(ID)
C - # of free rows in the bank with index ID
      LFRROW(ID) = LFRWRD(ID) / LCOLS(ID)
C - Lth integer element of the NRBOSth row of the bank with index ID
      ITABL(ID,NRBOS,L) = IW(ID+LMHLEN+(NRBOS-1)*IW(ID+1)+L)
C - Lth real element of the NRBOSth row of the bank with index ID
      RTABL(ID,NRBOS,L) = RW(ID+LMHLEN+(NRBOS-1)*IW(ID+1)+L)
C-------------------- /QCFUNC/ --- statement functions for ALPHA banks
      KJQDET(KI)=IW(KOQVEC+KI*KCQVEC+JQVEQD)
      QSQT(QF)=SIGN(SQRT(ABS(QF)),QF)
      QP(KI)=RW(KOQVEC+KI*KCQVEC+JQVEQP)
      QX(KI)=RW(KOQVEC+KI*KCQVEC+JQVEQX)
      QY(KI)=RW(KOQVEC+KI*KCQVEC+JQVEQY)
      QZ(KI)=RW(KOQVEC+KI*KCQVEC+JQVEQZ)
      QE(KI)=RW(KOQVEC+KI*KCQVEC+JQVEQE)
      QM(KI)=RW(KOQVEC+KI*KCQVEC+JQVEQM)
      QCH(KI)=RW(KOQVEC+KI*KCQVEC+JQVECH)
      KCH(KI)=NINT (QCH(KI))
      QCT(KI)=QZ(KI)/QP(KI)
      QDB(KI)=RW(KOQVEC+KI*KCQVEC+JQVEDB)
      QZB(KI)=RW(KOQVEC+KI*KCQVEC+JQVEZB)
      QDBS2(KI)=RW(KOQVEC+KI*KCQVEC+JQVESD)
      QZBS2(KI)=RW(KOQVEC+KI*KCQVEC+JQVESZ)
      QBC2(KI)=RW(KOQVEC+KI*KCQVEC+JQVECB)
      QSIG(KI,KI1,KI2)=RW(KOQVEC+KI*KCQVEC+KMATIX(KI1,KI2)+JQVEEM)
      XSIG(KI)=RW(KOQVEC+KI*KCQVEC+JQVEEM).GE.0.
      QSMAT(KI,KI1)=RW(KOQVEC+KI*KCQVEC+KI1+JQVEEM)
      QSIGX(KI)=QSQT(QSMAT(KI,0))
      QSIGY(KI)=QSQT(QSMAT(KI,2))
      QSIGZ(KI)=QSQT(QSMAT(KI,5))
      QSIGEE(KI)=RW(KOQVEC+KI*KCQVEC+JQVEEM+9)
      QSIGE(KI)=QSQT(QSIGEE(KI))
      QSIGPP(KI)=(QX(KI)**2*QSMAT(KI,0)+QY(KI)**2*QSMAT(KI,2)+
     & QZ(KI)**2*QSMAT(KI,5)+2.*(QX(KI)*(QY(KI)*QSMAT(KI,1)+
     & QZ(KI)*QSMAT(KI,3))+QY(KI)*QZ(KI)*QSMAT(KI,4)))/QP(KI)**2
      QSIGP(KI)=QSQT(QSIGPP(KI))
      QSIGMM(KI)=QM(KI)*(QE(KI)**2*QSMAT(KI,9)+QX(KI)**2*QSMAT(KI,0)+
     & QY(KI)**2*QSMAT(KI,2)+QZ(KI)**2*QSMAT(KI,5)+2.*(QX(KI)*(QY(KI)*
     & QSMAT(KI,1)+QZ(KI)*QSMAT(KI,3))+QY(KI)*QZ(KI)*QSMAT(KI,4)-
     & QE(KI)*(QX(KI)*QSMAT(KI,6)+QY(KI)*QSMAT(KI,7)+
     & QZ(KI)*QSMAT(KI,8))))/AMAX1(QM(KI)**3,1.E-16)
      QSIGM(KI)=QSQT(QSIGMM(KI))
      QMCHIF(KI)=RW(KOQVEC+KI*KCQVEC+JQVECF)
      QPH(KI)=ATG(QY(KI),QX(KI))
      QPT(KI)=SQRT(QX(KI)**2+QY(KI)**2)
      KTN(KI)=IW(KOQVEC+KI*KCQVEC+JQVETN)
      KMC(KI)=KCLARM(IW(KOQVEC+KI*KCQVEC+JQVECL))
      KBMASK(KI,KI1)=IW(KOQVEC+KI*KCQVEC+KI1+JQVEBM-1)
      KCALFL(KI)=IW(KJQDET(KI)+JQDECF)
      KCHGD(KI,KI1)=IW(KOQLIN+KI1+IW(KJQDET(KI)+JQDEFL))
      KCLASS(KI)=KCLACO(IW(KOQVEC+KI*KCQVEC+JQVECL))
      KDAU(KI,KI1)=IW(KOQLIN+KI1+IW(KOQVEC+KI*KCQVEC+JQVEDL))
      KECAL(KI,KI1)=IW(KOQLIN+KI1+IW(KJQDET(KI)+JQDEEL))
      KENDV(KI)=IW(KOQVEC+KI*KCQVEC+JQVEEV)
      KFOLLO(KI)=IW(KOQVEC+KI*KCQVEC+JQVENP)
C
      KHCAL(KI,KI1)=IW(KOQLIN+KI1+IW(KJQDET(KI)+JQDEHL))
      KLUNDS(KI)=IW(KOQVEC+KI*KCQVEC+JQVEKS)
      KNCHGD(KI)=IW(KJQDET(KI)+JQDENF)
      KNECAL(KI)=IW(KJQDET(KI)+JQDENE)
      KNHCAL(KI)=IW(KJQDET(KI)+JQDENH)
      KNMOTH(KI)=IW(KOQVEC+KI*KCQVEC+JQVENO)
      KMOTH(KI,KI1)=IW(KOQLIN+KI1+IW(KOQVEC+KI*KCQVEC+JQVEOL))
      KMTCH(KI,KI1)=IW(KOQMTL+KI1+IW(KOQVEC+KI*KCQVEC+JQVEML))
      KNDAU(KI)=IW(KOQVEC+KI*KCQVEC+JQVEND)
      KNMTCH(KI)=IW(KOQVEC+KI*KCQVEC+JQVENM)
      KORIV(KI)=IW(KOQVEC+KI*KCQVEC+JQVEOV)
      KSAME(KI)=IW(KOQVEC+KI*KCQVEC+JQVESP)
      KSMTCH(KI,KI1)=IW(KOQMTS+KI1+IW(KOQVEC+KI*KCQVEC+JQVEML))
      KSTABC(KI)=IW(KOQVEC+KI*KCQVEC+JQVESC)
      KTPCOD(KI)=IW(KOQVEC+KI*KCQVEC+JQVEPA)
      XLOCKN(KI,KI1)=IAND(KBMASK(KI,KI1),KLOCK0(KI1,KMC(KI))).NE.0
      XLOCK(KI)=IW(KOQVEC+KI*KCQVEC+JQVELK).NE.0.OR.XLOCKN(KI,1).OR.
     & XLOCKN(KI,2).OR.XLOCKN(KI,3).OR.XLOCKN(KI,4).OR.
     & XLOCKN(KI,5).OR.XLOCKN(KI,6).OR.XLOCKN(KI,7).OR.
     & XLOCKN(KI,8).OR.XLOCKN(KI,9).OR.XLOCKN(KI,10).OR.
     & XLOCKN(KI,11).OR.XLOCKN(KI,12).OR.XLOCKN(KI,13).OR.
     & XLOCKN(KI,14)
      XMC(KI)=KCLARM(IW(KOQVEC+KI*KCQVEC+JQVECL)).NE.1
      QRDFL(KI,KI1)=RW(KOQVEC+KI*KCQVEC+JQVEUS+KI1-1)
      KRDFL(KI,KI1)=IW(KOQVEC+KI*KCQVEC+JQVEUS+KI1-1)
      XCAL(KI)=IW(KJQDET(KI)+JQDECF).NE.0
      XECAL(KI)=IABS(IW(KJQDET(KI)+JQDECF)).EQ.1
      XHCAL(KI)=IABS(IW(KJQDET(KI)+JQDECF)).EQ.2
C
      QVX(KI)=RW(KOQVRT+KI*KCQVRT+JQVRVX)
      QVY(KI)=RW(KOQVRT+KI*KCQVRT+JQVRVY)
      QVZ(KI)=RW(KOQVRT+KI*KCQVRT+JQVRVZ)
      KVN(KI)=IW(KOQVRT+KI*KCQVRT+JQVRVN)
      KVTYPE(KI)=IW(KOQVRT+KI*KCQVRT+JQVRTY)
      KVINCP(KI)=IW(KOQVRT+KI*KCQVRT+JQVRIP)
      KVNDAU(KI)=IW(KOQVRT+KI*KCQVRT+JQVRND)
      KVYV0V(KI)=IW(KOQVRT+KI*KCQVRT+JQVRAY)
      KVFVER(KI)=IW(KOQVRT+KI*KCQVRT+JQVRAF)
      KVDAU(KI,KI1)=IW(KOQLIN+KI1+IW(KOQVRT+KI*KCQVRT+JQVRDL))
      QVEM(KI,KI1,KI2)=RW(KOQVRT+KI*KCQVRT+KMATIX(KI1,KI2)+JQVREM)
      QVCHIF(KI)=RW(KOQVRT+KI*KCQVRT+JQVRCF)
      QVDIF2(KI1,KI2)=SQRT((QVX(KI1)-QVX(KI2))**2+(QVY(KI1)-
     &QVY(KI2))**2)
      QVDIF3(KI1,KI2)=SQRT((QVX(KI1)-QVX(KI2))**2+(QVY(KI1)-
     &QVY(KI2))**2+ (QVZ(KI1)-QVZ(KI2))**2)
C
      QMSQ2(KI1,KI2)=(QE(KI1)+QE(KI2))**2-(QX(KI1)+QX(KI2))**2-
     & (QY(KI1)+QY(KI2))**2-(QZ(KI1)+QZ(KI2))**2
      QMSQ3(KI1,KI2,KI3)=(QE(KI1)+QE(KI2)+QE(KI3))**2-
     & (QX(KI1)+QX(KI2)+QX(KI3))**2-(QY(KI1)+QY(KI2)+QY(KI3))**2-
     & (QZ(KI1)+QZ(KI2)+QZ(KI3))**2
      QMSQ4(KI1,KI2,KI3,KI4)=(QE(KI1)+QE(KI2)+QE(KI3)+QE(KI4))**2-
     & (QX(KI1)+QX(KI2)+QX(KI3)+QX(KI4))**2-(QY(KI1)+QY(KI2)+
     & QY(KI3)+QY(KI4))**2-(QZ(KI1)+QZ(KI2)+QZ(KI3)+QZ(KI4))**2
      QM2(KI1,KI2)=QSQT(QMSQ2(KI1,KI2))
      QM3(KI1,KI2,KI3)=QSQT(QMSQ3(KI1,KI2,KI3))
      QM4(KI1,KI2,KI3,KI4)=QSQT(QMSQ4(KI1,KI2,KI3,KI4))
      QDMSQ(KI1,KI2)=(QE(KI1)-QE(KI2))**2-(QX(KI1)-QX(KI2))**2-
     & (QY(KI1)-QY(KI2))**2-(QZ(KI1)-QZ(KI2))**2
      QBETA(KI)=QP(KI)/QE(KI)
      QGAMMA(KI)=1./SQRT((1.-QBETA(KI))*(1.+QBETA(KI)))
      QDOT3(KI1,KI2)=QX(KI1)*QX(KI2)+QY(KI1)*QY(KI2)+QZ(KI1)*QZ(KI2)
      QDOT4(KI1,KI2)=QE(KI1)*QE(KI2)-QDOT3(KI1,KI2)
      QCOSA(KI1,KI2)=QDOT3(KI1,KI2)/(QP(KI1)*QP(KI2))
      QPPAR(KI1,KI2)=QDOT3(KI1,KI2)/QP(KI2)
      QPPER(KI1,KI2)=SQRT((QY(KI1)*QZ(KI2)-QZ(KI1)*QY(KI2))**2+
     & (QZ(KI1)*QX(KI2)-QX(KI1)*QZ(KI2))**2+
     & (QX(KI1)*QY(KI2)-QY(KI1)*QX(KI2))**2)/QP(KI2)
      XSAME(KI1,KI2)=IAND(KBMASK(KI1,1),KBMASK(KI2,1)).NE.0.OR.
     & IAND(KBMASK(KI1,2),KBMASK(KI2,2)).NE.0.OR.
     & IAND(KBMASK(KI1,3),KBMASK(KI2,3)).NE.0.OR.
     & IAND(KBMASK(KI1,4),KBMASK(KI2,4)).NE.0.OR.
     & IAND(KBMASK(KI1,5),KBMASK(KI2,5)).NE.0.OR.
     & IAND(KBMASK(KI1,6),KBMASK(KI2,6)).NE.0.OR.
     & IAND(KBMASK(KI1,7),KBMASK(KI2,7)).NE.0.OR.
     & IAND(KBMASK(KI1,8),KBMASK(KI2,8)).NE.0.OR.
     & IAND(KBMASK(KI1,9),KBMASK(KI2,9)).NE.0.OR.
     & IAND(KBMASK(KI1,10),KBMASK(KI2,10)).NE.0
C
      QCMASS(KI)=RW(KOQPAR+KI*KCQPAR+JQPAMA)
      QCCHAR(KI)=RW(KOQPAR+KI*KCQPAR+JQPACH)
      QCLIFE(KI)=RW(KOQPAR+KI*KCQPAR+JQPALT)
      QCWIDT(KI)=RW(KOQPAR+KI*KCQPAR+JQPAWI)
      XCEQOR(KI,KI1)=KTPCOD(KI).EQ.KI1.OR.
     & KTPCOD(KI).EQ.IW(KOQPAR+KI1*KCQPAR+JQPAAN)
      XCEQU(KI,KI1)=KTPCOD(KI).EQ.KI1
C    QCFDET
      XFRF(KI)=IW(KJQDET(KI)+JQDEAF).NE.KQZER
      QFRFIR(KI)=RW(IW(KJQDET(KI)+JQDEAF)+JFRFIR)
      QFRFTL(KI)=RW(IW(KJQDET(KI)+JQDEAF)+JFRFTL)
      QFRFP0(KI)=RW(IW(KJQDET(KI)+JQDEAF)+JFRFP0)
      QFRFD0(KI)=RW(IW(KJQDET(KI)+JQDEAF)+JFRFD0)
      QFRFZ0(KI)=RW(IW(KJQDET(KI)+JQDEAF)+JFRFZ0)
      QFRFAL(KI)=RW(IW(KJQDET(KI)+JQDEAF)+JFRFAL)
      QFRFEM(KI,KI1,KI2)=RW(IW(KJQDET(KI)+JQDEAF)+
     & KMATIX(KI1,KI2)+JFRFEM)
      QFRFC2(KI)=RW(IW(KJQDET(KI)+JQDEAF)+JFRFC2)
      KFRFDF(KI)=IW(IW(KJQDET(KI)+JQDEAF)+JFRFDF)
      KFRFNO(KI)=IW(IW(KJQDET(KI)+JQDEAF)+JFRFNO)
C
      KFRTNV(KI)=IW(IW(KJQDET(KI)+JQDEAL)+JFRTNV)
      KFRTNI(KI)=IW(IW(KJQDET(KI)+JQDEAL)+JFRTNI)
      KFRTNE(KI)=IW(IW(KJQDET(KI)+JQDEAL)+JFRTNE)
      KFRTNT(KI)=IW(IW(KJQDET(KI)+JQDEAL)+JFRTNT)
      KFRTNR(KI)=IW(IW(KJQDET(KI)+JQDEAL)+JFRTNR)
C
      KFRIBP(KI)=IW(IW(KJQDET(KI)+JQDEFI)+JFRIBP)
      KFRIDZ(KI)=IW(IW(KJQDET(KI)+JQDEFI)+JFRIDZ)
      KFRIBC(KI)=IW(IW(KJQDET(KI)+JQDEFI)+JFRIBC)
      KFRIDC(KI)=IW(IW(KJQDET(KI)+JQDEFI)+JFRIDC)
      QFRIPE(KI)=RW(IW(KJQDET(KI)+JQDEFI)+JFRIPE)
      QFRIPM(KI)=RW(IW(KJQDET(KI)+JQDEFI)+JFRIPM)
      QFRIPI(KI)=RW(IW(KJQDET(KI)+JQDEFI)+JFRIPI)
      QFRIPK(KI)=RW(IW(KJQDET(KI)+JQDEFI)+JFRIPK)
      QFRIPP(KI)=RW(IW(KJQDET(KI)+JQDEFI)+JFRIPP)
      QFRINK(KI)=RW(IW(KJQDET(KI)+JQDEFI)+JFRINK)
      KFRIQF(KI)=IW(IW(KJQDET(KI)+JQDEFI)+JFRIQF)
      XFRIQF(KI)=KFRIQF(KI).EQ.1.OR.KFRIQF(KI).EQ.3
C
      KNTEX(KI)=IW(KJQDET(KI)+JQDENT)
      XTEX(KI)=IW(KJQDET(KI)+JQDENT).NE.0
      KTEXSI(KI,KI1)=IW(IW(KJQDET(KI)+KI1+JQDENT)+JTEXSI)
      QTEXTM(KI,KI1)=RW(IW(KJQDET(KI)+KI1+JQDENT)+JTEXTM)
      QTEXTL(KI,KI1)=RW(IW(KJQDET(KI)+KI1+JQDENT)+JTEXTL)
      KTEXNS(KI,KI1)=IW(IW(KJQDET(KI)+KI1+JQDENT)+JTEXNS)
      QTEXAD(KI,KI1)=RW(IW(KJQDET(KI)+KI1+JQDENT)+JTEXAD)
C
      XEID(KI)=IW(KJQDET(KI)+JQDEAE).NE.KQZER
      KEIDIF(KI)=IW(IW(KJQDET(KI)+JQDEAE)+JEIDIF)
      QEIDRI(KI,KI1)=RW(IW(KJQDET(KI)+JQDEAE)+KI1+JEIDR1-1)
      QEIDEC(KI)=RW(IW(KJQDET(KI)+JQDEAE)+JEIDEC)
      KEIDIP(KI)=IW(IW(KJQDET(KI)+JQDEAE)+JEIDIP)
      QEIDEI(KI,KI1)=RW(IW(KJQDET(KI)+JQDEAE)+KI1+JEIDE1-1)
C
      XHMA(KI)=IW(KJQDET(KI)+JQDEAH).NE.KQZER
      KHMANF(KI)=IW(IW(KJQDET(KI)+JQDEAH)+JHMANF)
      KHMANE(KI)=IW(IW(KJQDET(KI)+JQDEAH)+JHMANE)
      KHMANL(KI)=IW(IW(KJQDET(KI)+JQDEAH)+JHMANL)
      KHMAMH(KI)=IW(IW(KJQDET(KI)+JQDEAH)+JHMAMH)
      KHMAIG(KI)=IW(IW(KJQDET(KI)+JQDEAH)+JHMAIG)
      QHMAED(KI)=RW(IW(KJQDET(KI)+JQDEAH)+JHMAED)
      QHMACS(KI)=RW(IW(KJQDET(KI)+JQDEAH)+JHMACS)
      KHMAND(KI)=IW(IW(KJQDET(KI)+JQDEAH)+JHMAND)
      KHMAIE(KI)=IW(IW(KJQDET(KI)+JQDEAH)+JHMAIE)
      KHMAIT(KI)=IW(IW(KJQDET(KI)+JQDEAH)+JHMAIT)
      KHMAIF(KI)=IW(IW(KJQDET(KI)+JQDEAH)+JHMAIF)
C
      XMCA(KI)=IW(KJQDET(KI)+JQDEAM).NE.KQZER
      KMCANH(KI,KI1)=IW(IW(KJQDET(KI)+JQDEAM)+KI1+JMCANH-1)
      QMCADH(KI,KI1)=RW(IW(KJQDET(KI)+JQDEAM)+KI1+JMCADH-1)
      QMCADC(KI,KI1)=RW(IW(KJQDET(KI)+JQDEAM)+KI1+JMCADC-1)
      QMCAAM(KI)=RW(IW(KJQDET(KI)+JQDEAM)+JMCAAM)
      QMCAAC(KI)=RW(IW(KJQDET(KI)+JQDEAM)+JMCAAC)
C
      XMUI(KI)=IW(KJQDET(KI)+JQDEMU).NE.KQZER
      KMUIIF(KI)=IW(IW(KJQDET(KI)+JQDEMU)+JMUIIF)
      QMUISR(KI)=RW(IW(KJQDET(KI)+JQDEMU)+JMUISR)
      QMUIDM(KI)=RW(IW(KJQDET(KI)+JQDEMU)+JMUIDM)
      KMUIST(KI)=IW(IW(KJQDET(KI)+JQDEMU)+JMUIST)
      KMUITN(KI)=IW(IW(KJQDET(KI)+JQDEMU)+JMUITN)
C
      XPEC(KI)=IW(KJQDET(KI)+JQDEEC).NE.KQZER
      QPECER(KI)=RW(IW(KJQDET(KI)+JQDEEC)+JPECER)
      QPECE1(KI)=RW(IW(KJQDET(KI)+JQDEEC)+JPECE1)
      QPECE2(KI)=RW(IW(KJQDET(KI)+JQDEEC)+JPECE2)
      QPECTH(KI)=RW(IW(KJQDET(KI)+JQDEEC)+JPECTH)
      QPECPH(KI)=RW(IW(KJQDET(KI)+JQDEEC)+JPECPH)
      QPECEC(KI)=RW(IW(KJQDET(KI)+JQDEEC)+JPECEC)
      KPECKD(KI)=IW(IW(KJQDET(KI)+JQDEEC)+JPECKD)
      KPECCC(KI)=IW(IW(KJQDET(KI)+JQDEEC)+JPECCC)
      KPECRB(KI)=IW(IW(KJQDET(KI)+JQDEEC)+JPECRB)
      KPECPC(KI)=IW(IW(KJQDET(KI)+JQDEEC)+JPECPC)
C
      XPEP(KI)=IW(KJQDET(KI)+JQDEET).NE.KQZER
      QPEPT1(KI)=RW(IW(KJQDET(KI)+JQDEET)+JPEPT1)
      QPEPP1(KI)=RW(IW(KJQDET(KI)+JQDEET)+JPEPP1)
      QPEPT3(KI)=RW(IW(KJQDET(KI)+JQDEET)+JPEPT3)
      QPEPP3(KI)=RW(IW(KJQDET(KI)+JQDEET)+JPEPP3)
C
      XPHC(KI)=IW(KJQDET(KI)+JQDEHC).NE.KQZER
      QPHCER(KI)=RW(IW(KJQDET(KI)+JQDEHC)+JPHCER)
      QPHCTH(KI)=RW(IW(KJQDET(KI)+JQDEHC)+JPHCTH)
      QPHCPH(KI)=RW(IW(KJQDET(KI)+JQDEHC)+JPHCPH)
      QPHCEC(KI)=RW(IW(KJQDET(KI)+JQDEHC)+JPHCEC)
      KPHCKD(KI)=IW(IW(KJQDET(KI)+JQDEHC)+JPHCKD)
      KPHCCC(KI)=IW(IW(KJQDET(KI)+JQDEHC)+JPHCCC)
      KPHCRB(KI)=IW(IW(KJQDET(KI)+JQDEHC)+JPHCRB)
      KPHCPC(KI)=IW(IW(KJQDET(KI)+JQDEHC)+JPHCPC)
C
      XEFO(KI)=IW(KJQDET(KI)+JQDEEF).NE.KQZER
      QEFOWE(KI)=RW(IW(KJQDET(KI)+JQDEEF)+JEFOWE)
      KEFOTY(KI)=IW(IW(KJQDET(KI)+JQDEEF)+JEFOTY)
      KEFOLE(KI)=IW(IW(KJQDET(KI)+JQDEEF)+JEFOLE)
      KEFOLT(KI)=IW(IW(KJQDET(KI)+JQDEEF)+JEFOLT)
      KEFOLH(KI)=IW(IW(KJQDET(KI)+JQDEEF)+JEFOLH)
      KEFOLC(KI)=IW(IW(KJQDET(KI)+JQDEEF)+JEFOLC)
      KEFOLJ(KI)=IW(IW(KJQDET(KI)+JQDEEF)+JEFOLJ)
C
      XPCQ(KI)=IW(KJQDET(KI)+JQDEPC).NE.KQZER
      KPCQNA(KI)=IW(IW(KJQDET(KI)+JQDEPC)+JPCQNA)
C
      XEGP(KI)=IW(KJQDET(KI)+JQDEEG).NE.KQZER
      QEGPR1(KI)=RW(IW(KJQDET(KI)+JQDEEG)+JEGPR1)
      QEGPR2(KI)=RW(IW(KJQDET(KI)+JQDEEG)+JEGPR2)
      QEGPF4(KI)=RW(IW(KJQDET(KI)+JQDEEG)+JEGPF4)
      QEGPDM(KI)=RW(IW(KJQDET(KI)+JQDEEG)+JEGPDM)
      KEGPST(KI)=IW(IW(KJQDET(KI)+JQDEEG)+JEGPST)
      KEGPQU(KI)=IW(IW(KJQDET(KI)+JQDEEG)+JEGPQU)
      KEGPPE(KI)=IW(IW(KJQDET(KI)+JQDEEG)+JEGPPE)
C
      XPGP(KI)=IW(KJQDET(KI)+JQDEPG).NE.KQZER.AND.IW(NAPGPC).GT.0
      QPGPR1(KI)=RW(IW(KJQDET(KI)+JQDEPG)+JPGPR1)
      QPGPR2(KI)=RW(IW(KJQDET(KI)+JQDEPG)+JPGPR2)
      QPGPF4(KI)=RW(IW(KJQDET(KI)+JQDEPG)+JPGPF4)
      QPGPDM(KI)=RW(IW(KJQDET(KI)+JQDEPG)+JPGPDM)
      QPGPST(KI)=RW(IW(KJQDET(KI)+JQDEPG)+JPGPST)
      QPGPQ1(KI)=RW(IW(KJQDET(KI)+JQDEPG)+JPGPQ1)
      QPGPQ2(KI)=RW(IW(KJQDET(KI)+JQDEPG)+JPGPQ2)
      QPGPM1(KI)=RW(IW(KJQDET(KI)+JQDEPG)+JPGPM1)
      QPGPM2(KI)=RW(IW(KJQDET(KI)+JQDEPG)+JPGPM2)
      QPGPMA(KI)=RW(IW(KJQDET(KI)+JQDEPG)+JPGPMA)
      QPGPER(KI)=RW(IW(KJQDET(KI)+JQDEPG)+JPGPER)
      QPGPTR(KI)=RW(IW(KJQDET(KI)+JQDEPG)+JPGPTR)
      QPGPPR(KI)=RW(IW(KJQDET(KI)+JQDEPG)+JPGPPR)
      KPGPQU(KI)=IW(IW(KJQDET(KI)+JQDEPG)+JPGPQU)
      KPGPPE(KI)=IW(IW(KJQDET(KI)+JQDEPG)+JPGPPE)
      XPGAC(KI)=IW(KJQDET(KI)+JQDEPG).NE.KQZER.AND.IW(NAPGAC).GT.0
      KPGAST(KI)=IW(IW(KJQDET(KI)+JQDEPG)+JPGAST)
      QPGAEF(KI)=RW(IW(KJQDET(KI)+JQDEPG)+JPGAEF)
      QPGAGC(KI)=RW(IW(KJQDET(KI)+JQDEPG)+JPGAGC)
      QPGAZS(KI)=RW(IW(KJQDET(KI)+JQDEPG)+JPGAZS)
      QPGAPL(KI)=RW(IW(KJQDET(KI)+JQDEPG)+JPGAPL)
      QPGAPH(KI)=RW(IW(KJQDET(KI)+JQDEPG)+JPGAPH)
      KPGAPN(KI)=IW(IW(KJQDET(KI)+JQDEPG)+JPGAPN)
      KPGAFA(KI)=IW(IW(KJQDET(KI)+JQDEPG)+JPGAFA)
      KPGAPE(KI)=IW(IW(KJQDET(KI)+JQDEPG)+JPGAPE)
C
C
      XYV0(KI)=KVYV0V(KENDV(KI)).NE.0
      KYV0K1(KI)=IW(KVYV0V(KENDV(KI))+JYV0K1)
      KYV0K2(KI)=IW(KVYV0V(KENDV(KI))+JYV0K2)
      QYV0VX(KI)=RW(KVYV0V(KENDV(KI))+JYV0VX)
      QYV0VY(KI)=RW(KVYV0V(KENDV(KI))+JYV0VY)
      QYV0VZ(KI)=RW(KVYV0V(KENDV(KI))+JYV0VZ)
      QYV0X1(KI)=RW(KVYV0V(KENDV(KI))+JYV0X1)
      QYV0X2(KI)=RW(KVYV0V(KENDV(KI))+JYV0X2)
      QYV0C2(KI)=RW(KVYV0V(KENDV(KI))+JYV0C2)
      KYV0IC(KI)=IW(KVYV0V(KENDV(KI))+JYV0IC)
      QYV0DM(KI)=RW(KVYV0V(KENDV(KI))+JYV0DM)
      QYV0S1(KI)=RW(KVYV0V(KENDV(KI))+JYV0S1)
      QYV0S2(KI)=RW(KVYV0V(KENDV(KI))+JYV0S2)
C
      XLEPTG(KI)=IW(KJQDET(KI)+JQDEPD).NE.KQZER
      KLEPPA(KI)=IW(IW(KJQDET(KI)+JQDEPD)+JPDLPA)
      KLEPJT(KI)=IW(IW(KJQDET(KI)+JQDEPD)+JPDLJT)+KLFJET-1
      QLEPPI(KI)=RW(IW(KJQDET(KI)+JQDEPD)+JPDLPI)
      QLEPPE(KI)=RW(IW(KJQDET(KI)+JQDEPD)+JPDLPE)
      KLEPVP(KI)=IW(IW(KJQDET(KI)+JQDEPD)+JPDLVP)
C
      XLEPTH(KI)=IW(KJQDET(KI)+JQDEPM).NE.KQZER
      KLEPFL(KI)=IW(IW(KJQDET(KI)+JQDEPM)+JPMLFL)
      KLEPPO(KI)=IW(IW(KJQDET(KI)+JQDEPM)+JPMLPO)
      KLEPCH(KI)=IW(IW(KJQDET(KI)+JQDEPM)+JPMLCH)
      KLEPSP(KI)=IW(IW(KJQDET(KI)+JQDEPM)+JPMLSP)
      KLEPLE(KI)=IW(IW(KJQDET(KI)+JQDEPM)+JPMLLE)
      KLEPME(KI)=IW(IW(KJQDET(KI)+JQDEPM)+JPMLME)
      KLEPKT(KI)=IW(IW(KJQDET(KI)+JQDEPM)+JPMLKT)
C---------------------  end of QMACRO ---------------------------------
C---------------------------------------------------------------------
      keep = 0
      CALL vzero(epad(1)  ,36)
      CALL vzero(ewire(1) ,36)
      CALL vzero(ediff(1) ,36)
      IF ( iewhe .EQ. 0 ) GOTO 999
      IF ( ipewi .EQ. 0 ) GOTO 998
      IF ( ipeco .EQ. 0 ) GOTO 999
      IF ( ipest .EQ. 0 ) GOTO 998
      IF ( ietdi .EQ. 0 ) GOTO 998
      IF ( newhe .NE. 36 ) GOTO 999
C
C  Total wire energy (module by module)
C
      modbad = 0
      DO 100 iwir = 1 , newhe
        modu = itabl(iewhe, iwir, 2)
        IF ( modu .NE. iwir ) modbad = modbad + 1
        ewire(iwir) = itabl(iewhe, iwir, 1) * 1E-6 * rpsf
 100  CONTINUE
      IF ( modbad .NE. 0 ) THEN
        WRITE (IW(6),*) krun,kevt,' : +++ Warning +++ EWHE corrupted !!'
        WRITE (IW(6),*) 'modbad = ',modbad
        IF ( idbg .GE. 1 ) CALL looses('EWHECORR',1)
      ENDIF
C
C  Correction factor on the raw pad energy ( due to thresholds )
C
      facteur = .08
      iecns = 0
      naecns = namind('ECNS')
      IF ( naecns .GT. 0 ) iecns = iw(naecns)
      IF ( iecns .GT. 0 ) facteur = rtabl(iecns, 1, 26)
C
C  Loop on calobjects of PEST ( LCAL excluded !)
C  ( iclu = PECO corresponding , modu = module )
C
      DO 2 isto = 1 , npest
        iclu = itabl(ipest, isto, jpespe)
        IF ( itabl(ipest, isto, jpesed) .NE. 0) GOTO 2
        IF ( itabl(ipeco, iclu, jpeckd) .EQ. 192 ) GOTO 2
C
        eraw = rtabl(ipeco, iclu, jpecer)
        IF ( eraw .LE. 0. ) CALL bldpeco(iclu,eraw)
C
        ntow  = itabl(ipest, isto, jpeset)
        itlab = itabl(ietdi, ntow, jetdtl)
        irow  = ibits(itlab, 16, 8)
        icol  = ibits(itlab, 2, 9)
C
C  Check the reliability of Row/Column numbers
C
        IF ( invalid(irow,icol) .EQ. 0 ) GOTO 2
        CALL emdtow(irow, icol, ksbd, kmodu, krg)
        modu  = kmodu + 12*(ksbd-1)
        IF ( modu .LT. 1 .OR. modu .GT. 36) GOTO 2
C
        corr = 1.
        IF ( eraw .GT. 0.01) corr = 1. + facteur/sqrt(eraw)
C
        efrac = rtabl(ipest, isto, jpeser) * corr
        epad(modu) = epad(modu) + efrac
    2 CONTINUE
C
C  Determine the most energetic wire plane
C
      DO 4 kmodu = 1 , npewi
        totenw = 0.
        frcpla = 0.
        kwirep = 0
        frcpl0 = 0.
        kwire0 = 0
        DO 5 kplan = 2 , 46
          plafrc = ITABL(ipewi, kmodu, kplan)
          IF ( plafrc .GT. -10000. ) THEN
            totenw = totenw + plafrc
            IF ( plafrc .GT. frcpla ) THEN
              frcpla = plafrc
              kwirep = kplan-1
            ENDIF
            IF ( plafrc .GT. frcpl0 .AND. plafrc .LT. frcpla ) THEN
              frcpl0 = plafrc
              kwire0 = kplan-1
            ENDIF
          ENDIF
    5   CONTINUE
        IF ( frcpl0 .EQ. 0. ) frcpl0 = frcpla/1000.
        frcpl0 = frcpla / frcpl0
        frcpla = frcpla / totenw
        IF (( frcpla .GT. .9  .AND. totenw .GT. .5E6 ) .OR.
     .      ( frcpl0 .GT. 20. .AND. totenw .GT. 1.E6 ) .OR.
     .      ( frcpl0 .GT.  5. .AND. totenw .GT. 5.E6 )) THEN
          jmodu = ITABL(ipewi,kmodu,jpewmn)
          ewire(jmodu) = ewire(jmodu) * (1. - frcpla)
          IF ( idbg .GE. 11 ) WRITE (IW(6),*) 'Wire energy in module ',
     &         jmodu,' has been rescaled by a factor ',1.-frcpla
        ENDIF
    4 CONTINUE
C
C  Now the "Good"  modules :
C  Kill the event if a module has a crazy wire energy value
C
      DO 3 modu = 1 , 36
        IF ( ewire(modu) .GT. 200. ) GOTO 999
        ediff(modu) = epad(modu) - ewire(modu)
        IF ( ediff(modu) .LE. 0. ) ediff(modu) = 0.
   3  CONTINUE
C
 998  keep = 1
C
 999  RETURN
      END
