      SUBROUTINE QFCHGD
CKEY  FILL CHARGED /INTERNAL
C----------------------------------------------------------------------
C! Fill QVEC with reconstructed charged tracks from POT / DST
C Called from QFILL
C!                                                  H.Albrecht 20.09.88
C!                            Modified:             E.Blucher  19.04.90
C!              Modified for FRFT NR=2:             E.Blucher  04.04.91
C!                   Modified for MUID:             E.Blucher  18.08.92
C----------------------------------------------------------------------
      SAVE INIT,IER,IER2,ICHGD,NCHGD,AMASPI
C-------------------- /QCDE/ --- COMMONs, DIMENSIONs, etc. ------------
C Start of QCDESH ----------------------- Description in QDATA ---------
      PARAMETER (KCQDET=34, KCQFPA=8, KCQPAR=10, KCQVEC=73, KCQVRT=30,
     & KHE=1, KHMU=2, KHPI=3, KHK=4, KHP=5, KHPHOT=1, KHNHAD=2,
     & KMONTE=-2, KRECO=-1, KLOCKM=14, KSOVT=1, KSCHT=2, KSIST=3,
     & KSAST=4, KSEHT=5, KSV0T=6, KSDCT=7, KSEFT=8, KSNET=9, KSGAT=10,
     & KSJET=11, KSMCT=12, KSREV=13,
     & KSMCV=14, KUNDEF=-12344321, QQPI=3.141593, QQE=2.718282,
     & QQ2PI=QQPI*2., QQPIH=QQPI/2., QQRADP=180./QQPI, QQC=2.997925E10,
     & QQH=6.582173E-25, QQHC=QQH*QQC, QQIRP=.00029979)
      CHARACTER CQDATE*8, CQDWRK*80, CQFHIS*80, CQFOUT*80, CQFWRK*80,
     & CQHTIT*80, CQSEC*3, CQTIME*8, CQUNPK*30, CQVERS*6, CQRLST*800,
     & CQELST*800
      COMMON /QCDEC/ CQDATE, CQDWRK, CQFHIS, CQFOUT, CQFWRK, CQHTIT,
     & CQSEC(14), CQTIME, CQUNPK, CQVERS, CQRLST, CQELST
      COMMON /QCDE/ QELEP, QMFLD ,QMFLDC, QTIME, QTIMEI, QTIMEL,
     & QTIMES, QTIMET, QDHEEC, QDHEEL, QDHEPF, QDHETH, QDHEPH, QDHEEF,
     & QDHEET, QDHET1, QDHEP1, QDHET2, QDHEP2, QDHEE1, QDHEE2, QDHEE3,
     & QKEVRN, QKEVWT, QVXNOM, QVYNOM, QVZNOM, QVXNSG, QVYNSG, QVZNSG,
     & QINLUM, QRINLN, QRINLU, QDBOFS, QEECWI(36), QVXBOM, QVYBOM,
     & QSILUM, QRSLLU, QRSLBK, QRSLEW , QVTXBP(3), QVTEBP(3), QVTSBP(3)
      COMMON /QCDE/  KFOVT, KLOVT, KNOVT, KFCHT, KLCHT, KNCHT, KFIST,
     & KLIST, KNIST, KFAST, KLAST, KNAST, KFEHT, KLEHT, KNEHT, KFV0T,
     & KLV0T, KNV0T, KFDCT, KLDCT, KNDCT, KFEFT, KLEFT, KNEFT, KFNET,
     & KLNET, KNNET, KFGAT, KLGAT, KNGAT, KFJET, KLJET, KNJET, KFMCT,
     & KLMCT, KNMCT, KFREV, KLREV, KNREV, KFMCV, KLMCV, KNMCV, KLUST,
     & KLUSV, KFFRT, KLFRT, KFFRV, KLFRV, KNRET, KNCOT, KFFRD,
     & KLFJET,KLLJET,KLNJET
      COMMON /QCDE/ KBIT(32), KCLACO(KCQFPA), KCLAFR(KCQFPA), KCLARM
     & (KCQFPA), KDEBUG, KEVT, KEXP, KFFILL, KFEOUT, KJOPTN(2,2),
     & KLEOUT, KLROUT, KLOCK0(KLOCKM,2), KLOCK1(KLOCKM,2), KLOCK2(
     & KLOCKM,2), KMATIX(6,6), KMQFPA, KNEFIL, KNEOUT, KNEVT, KNPAST,
     & KNQDET, KNQFPA, KNQLIN, KNQMTX, KNQPAR, KNQPST, KNREIN, KNREOU,
     & KOQDET, KOQFPA, KOQLIN, KOQMTL, KOQMTS, KOQPAR, KOQPBT, KOQPLI,
     & KOQTRA, KOQVEC, KOQVRT, KQPAR, KQVEC, KQVRT, KQWRK, KQZER, KRUN,
     & KSTATU, KTDROP, KUCARD, KUCONS, KUHIST, KUINPU, KUOUTP, KUPRNT,
     & KUPTER, KDEBU1, KDEBU2, KNWRLM, KEFOPT, KUEDIN, KUEDOU, KURTOX,
     & KUCAR2, KNHDRN, KNBHAB, KSBHAB, KRSLLQ, KRSLNB
      COMMON /QCDE/ INDATA
      COMMON /QCDE/ KRINNE, KRINNF, KRINDC, KRINDQ, KRINNZ, KRINNB,
     & KRINBM, KRINFR, KRINLR, KRINLF
      COMMON /QCDE/ KEVERT, KEVEDA, KEVETI, KEVEMI(4), KEVETY, KEVEES,
     & KDHEFP, KDHENP, KDHENM, KKEVNT, KKEVNV, KKEVID, KDHENX, KDHENV,
     & KDHENJ, KREVDS, KXTET1, KXTET2, KXTEL2, KXTCGC, KXTCLL, KXTCBN,
     & KXTCCL, KXTCHV, KXTCEN, KCLASW, KERBOM, KBPSTA
      DIMENSION KLOCUS(3,14)
      EQUIVALENCE (KLOCUS(1,1),KFOVT), (KFOVT,KFRET), (KLIST,KLRET),
     & (KFIST,KFCOT), (KLAST,KLCOT)
      COMMON /QCDE/ XCOPYJ, XFLIAC, XHISTO, XLREV(2), XLREV2(2), XMCEV,
     & XMINI, XSYNTX, XWREVT, XWRRUN, XFILMC, XFILCH, XFILV0, XFILCO,
     & XFILEF, XFILPC, XFILGA, XFILJE,
     & XPRHIS, XFILL, XVITC, XVTPC, XVECAL, XVLCAL, XVTPCD,
     & XVSATR, XVHCAL, XHVTRG, XSREC, XWMINI, XIOKLU, XIOKSI, XFRF2,
     & XNSEQ, XVDOK, XFRF0, XFMUID, XFILEM, XWNANO, XROKSI, XGETBP,
     & XJTHRU
      LOGICAL XCOPYJ, XFLIAC, XHISTO, XLREV, XLREV2, XMCEV, XMINI,
     & XSYNTX, XWREVT, XWRRUN, XFILMC, XFILCH, XFILV0, XFILCO, XFILEF,
     & XFILPC, XPRHIS, XFILL, XVITC, XVTPC, XVECAL, XVLCAL, XVTPCD,
     & XVSATR, XVHCAL, XHVTRG, XSREC, XWMINI, XIOKLU, XFRF2, XFILJE,
     & XNSEQ, XFILGA, XVDOK, XFRF0, XFMUID, XFILEM, XWNANO, XIOKSI,
     & XROKSI, XGETBP, XJTHRU
C-------------------- /NANCOM/ --- NanoDst steering -------------------
C! XNANO   .TRUE. if input is a NanoDst (in NANO or EPIO format, dependi
C!                   XNANOR)
C!
      LOGICAL XNANO
      COMMON /NANCOM/XNANO
C--------------------- end of NANCOM ----------------------------------
      INTEGER LMHLEN, LMHCOL, LMHROW
      PARAMETER (LMHLEN=2, LMHCOL=1, LMHROW=2)
      INTEGER IW
      REAL RW(10000)
      COMMON /BCS/ IW(10000)
      EQUIVALENCE (RW(1),IW(1))
C------------------ /QCNAMI/ --- name indices -------------------------
      COMMON /QCNAMI/ NAAFID,NAAJOB,NAASEV,NABCNT,NABHIT,NABOMB,
     1 NABOME,NABOMP,NABOMR,NABPTR,NADCAL,NADCRL,NADECO,NADEID,NADENF,
     2 NADEVT,NADEWI,NADFMC,NADFOT,NADGAM,NADHCO,NADHEA,NADHRL,NADJET,
     3 NADMID,NADMJT,NADMUO,NADNEU,NADPOB,NADRES,NADTBP,NADTMC,NADTRA,
     4 NADVER,NADVMC,NAECRQ,NAECTE,NAEGID,NAEGPC,NAEIDT,NAEJET,NAERRF,
     5 NAETDI,NAETKC,NAEVEH,NAEWHE,NAFICL,NAFKIN,NAFPOI,NAFPOL,NAFRFT,
     6 NAFRID,NAFRTL,NAFSTR,NAFTCL,NAFTCM,NAFTOC,NAFTTM,NAFVCL,NAFVER,
     7 NAFZFR,NAHCCV,NAHCTE,NAHINF,NAHMAD,NAHPDI,NAHROA,NAHSDA,NAHTUB,
     8 NAIASL,NAIPJT,NAIRJT,NAITCO,NAITMA,NAIXTR,NAIZBD,NAJBER,NAJEST,
     9 NAJSUM,NAKEVH,NAKINE,NAKJOB,NAKLIN,NAKPOL,NAKRUN,NALIDT,NALOLE,
     A NALUPA,NAMCAD,NAMHIT,NAMTHR,NAMUDG,NAMUEX,NAOSTS,NAPART,NAPASL,
     B NAPCHY,NAPCOB,NAPCOI,NAPCPA,NAPCQA,NAPCRL,NAPECO,NAPEHY,NAPEID,
     C NAPEMH,NAPEPT,NAPEST,NAPEWI,NAPFER,NAPFHR,NAPFRF,NAPFRT,NAPHCO,
     D NAPHER,NAPHHY,NAPHMH,NAPHST,NAPIDI,NAPITM,NAPLID,NAPLPD,NAPLSD,
     E NAPMSK,NAPNEU,NAPPDS,NAPPOB,NAPPRL,NAPRTM,NAPSCO,NAPSPO,NAPSTR,
     F NAPT2X,NAPTBC,NAPTCO,NAPTEX,NAPTMA,NAPTML,NAPTNC,NAPTST,NAPVCO,
     G NAPYER,NAPYFR,NAPYNE,NAQDET,NAQFPA,NAQLIN,NAQMTL,NAQMTS,NAQPAR,
     H NAQPBT,NAQPLI,NAQTRA,NAQVEC,NAQVRT,NAQWRK,NAQZER,NAREVH,NARHAH,
     I NARTLO,NARTLS,NARUNH,NARUNR,NASFTR,NATEXS,NATGMA,NATMTL,NATPCO,
     J NAVCOM,NAVCPL,NAVDCO,NAVDHT,NAVDXY,NAVDZT,NAVERT,NAVFHL,NAVFLG,
     K NAVFPH,NAVHLS,NAVPLH,NAX1AD,NAX1SC,NAX1TI,NAX2DF,NAX3EC,NAX3EW,
     L NAX3HC,NAX3IT,NAX3L2,NAX3LU,NAX3TM,NAX3TO,NAX3TP,NAX3X3,NAXTBN,
     M NAXTBP,NAXTCN,NAXTEB,NAXTOP,NAXTRB,NAYV0V,NAZPFR,NAEFOL,NAMUID,
     N NAPGID,NAPGPC,NAPGAC,NAPMSC,NAPTHR,NANBIP,NAPDLT,NAPMLT,NAPLJT
C--------------------- end of QCNAMI ----------------------------------
C------------------ /QQQQJJ/ --- HAC parameters for ALPHA banks -------
      PARAMETER (JQVEQX= 1,JQVEQY= 2,JQVEQZ= 3,JQVEQE= 4,JQVEQM= 5,
     & JQVEQP= 6,JQVECH= 7,JQVETN= 8,JQVESC= 9,JQVEKS=10,JQVECL=11,
     & JQVEPA=12,JQVEQD=13,JQVENP=14,JQVESP=15,JQVEOV=16,JQVEEV=17,
     & JQVEND=18,JQVEDL=19,JQVENO=20,JQVEOL=21,JQVENM=22,JQVEML=23,
     & JQVEBM=24,JQVELK=38,JQVEDB=39,JQVEZB=40,JQVESD=41,JQVESZ=42,
     & JQVECB=43,JQVEEM=44,JQVECF=54,JQVEEW=55,JQVEUS=56)
      PARAMETER ( JQVRVX=1,JQVRVY=2,JQVRVZ=3,JQVRVN=4,JQVRTY=5,
     1   JQVRIP=6,JQVRND=7,JQVRDL=8,JQVRAY=9,JQVRAF=10,JQVREM=11,
     2   JQVRCF=17,JQVRET=18)
      PARAMETER ( JQDEAF= 1,JQDEAL= 2,JQDENT= 3,JQDEAT= 4,JQDELT= 8,
     &  JQDEAE= 9,JQDEAH=10,JQDEAM=11,JQDECF=12,JQDEEC=13,JQDEHC=14,
     &  JQDEET=15,JQDEFI=16,JQDENF=17,JQDEFL=18,JQDENE=19,JQDEEL=20,
     &  JQDENH=21,JQDEHL=22,JQDELH=23,JQDEEF=24,JQDEPC=25,JQDEEG=26,
     &  JQDEMU=27,JQDEDX=28,JQDEPG=29,JQDEPD=30,JQDEPM=31)
      PARAMETER ( JQPAGN=1, JQPANA=2, JQPACO=5, JQPAMA=6, JQPACH=7,
     & JQPALT=8,JQPAWI=9,JQPAAN=10)
C--------------------- end of QCDESH ----------------------------------
      EXTERNAL CQPART, CQTPN, XCEQAN, XLUMOK, XPEQAN, XPEQOR, XPEQU,
     & XVDEOK, LLUMOK, SLUMOK
      CHARACTER * 12 CQPART, CQTPN
      LOGICAL XCAL, XCEQAN, XCEQOR, XCEQU, XECAL, XEID, XFRF, XHCAL,
     & XHMA, XLOCK, XLOCKN, XMC, XLUMOK, XMCA, XPEO, XPHO, XPEQAN,
     & XPEQOR, XPEQU, XSAME, XSIG, XTEX, XPEC, XPEP, XPHC, XYV0,
     & XFRIQF, XEFO, XPCQ, XEGP, XMUI, XVDEOK, XPGP, LLUMOK, SLUMOK,
     & XPGAC, XLEPTG, XLEPTH
      REAL PI, TWOPI, PIBY2, PIBY3, PIBY4, PIBY6, PIBY8, PIBY12
      REAL RADEG, DEGRA
      REAL CLGHT, ALDEDX
      INTEGER NBITW, NBYTW, LCHAR
      PARAMETER (PI=3.141592653589)
      PARAMETER (RADEG=180./PI, DEGRA=PI/180.)
      PARAMETER (TWOPI = 2.*PI , PIBY2 = PI/2., PIBY4 = PI/4.)
      PARAMETER (PIBY6 = PI/6. , PIBY8 = PI/8.)
      PARAMETER (PIBY12= PI/12., PIBY3 = PI/3.)
      PARAMETER (CLGHT = 29.9792458, ALDEDX = 0.000307)
      PARAMETER (NBITW = 32 , NBYTW = NBITW/8 , LCHAR = 4)
      INTEGER JEFOPX,JEFOPY,JEFOPZ,JEFOEW,JEFOWE,JEFOTY,JEFOLE,JEFOLT,
     +          JEFOLH,JEFOLC,JEFOLJ,LEFOLA
      PARAMETER(JEFOPX=1,JEFOPY=2,JEFOPZ=3,JEFOEW=4,JEFOWE=5,JEFOTY=6,
     +          JEFOLE=7,JEFOLT=8,JEFOLH=9,JEFOLC=10,JEFOLJ=11,
     +          LEFOLA=11)
      INTEGER JEGPPX,JEGPPY,JEGPPZ,JEGPR1,JEGPR2,JEGPF4,JEGPDM,JEGPST,
     +          JEGPQU,JEGPPE,LEGPCA
      PARAMETER(JEGPPX=1,JEGPPY=2,JEGPPZ=3,JEGPR1=4,JEGPR2=5,JEGPF4=6,
     +          JEGPDM=7,JEGPST=8,JEGPQU=9,JEGPPE=10,LEGPCA=10)
      INTEGER JEIDIF,JEIDR1,JEIDR2,JEIDR3,JEIDR4,JEIDR5,JEIDR6,JEIDR7,
     +          JEIDEC,JEIDIP,JEIDE1,JEIDE2,JEIDE3,JEIDFR,JEIDPE,LEIDTA
      PARAMETER(JEIDIF=1,JEIDR1=2,JEIDR2=3,JEIDR3=4,JEIDR4=5,JEIDR5=6,
     +          JEIDR6=7,JEIDR7=8,JEIDEC=9,JEIDIP=10,JEIDE1=11,
     +          JEIDE2=12,JEIDE3=13,JEIDFR=14,JEIDPE=15,LEIDTA=15)
      INTEGER JFRFIR,JFRFTL,JFRFP0,JFRFD0,JFRFZ0,JFRFAL,JFRFEM,JFRFC2,
     +          JFRFDF,JFRFNO,LFRFTA
      PARAMETER(JFRFIR=1,JFRFTL=2,JFRFP0=3,JFRFD0=4,JFRFZ0=5,JFRFAL=6,
     +          JFRFEM=7,JFRFC2=28,JFRFDF=29,JFRFNO=30,LFRFTA=30)
      INTEGER JFRIBP,JFRIDZ,JFRIBC,JFRIDC,JFRIPE,JFRIPM,JFRIPI,JFRIPK,
     +          JFRIPP,JFRINK,JFRIQF,LFRIDA
      PARAMETER(JFRIBP=1,JFRIDZ=2,JFRIBC=3,JFRIDC=4,JFRIPE=5,JFRIPM=6,
     +          JFRIPI=7,JFRIPK=8,JFRIPP=9,JFRINK=10,JFRIQF=11,
     +          LFRIDA=11)
      INTEGER JFRTIV,JFRTNV,JFRTII,JFRTNI,JFRTNE,JFRTIT,JFRTNT,JFRTNR,
     +          LFRTLA
      PARAMETER(JFRTIV=1,JFRTNV=2,JFRTII=3,JFRTNI=4,JFRTNE=5,JFRTIT=6,
     +          JFRTNT=7,JFRTNR=8,LFRTLA=8)
      INTEGER JHMANF,JHMANE,JHMANL,JHMAMH,JHMAIG,JHMAED,JHMACS,JHMAND,
     +          JHMAIE,JHMAIT,JHMAIF,JHMATN,LHMADA
      PARAMETER(JHMANF=1,JHMANE=2,JHMANL=3,JHMAMH=4,JHMAIG=5,JHMAED=6,
     +          JHMACS=7,JHMAND=8,JHMAIE=9,JHMAIT=10,JHMAIF=11,
     +          JHMATN=12,LHMADA=12)
      INTEGER JMCANH,JMCADH,JMCADC,JMCAAM,JMCAAC,JMCATN,LMCADA
      PARAMETER(JMCANH=1,JMCADH=3,JMCADC=5,JMCAAM=7,JMCAAC=8,JMCATN=9,
     +          LMCADA=9)
      INTEGER JMUIIF,JMUISR,JMUIDM,JMUIST,JMUITN,LMUIDA
      PARAMETER(JMUIIF=1,JMUISR=2,JMUIDM=3,JMUIST=4,JMUITN=5,LMUIDA=5)
      INTEGER JPCQNA,JPCQPX,JPCQPY,JPCQPZ,JPCQEN,LPCQAA
      PARAMETER(JPCQNA=1,JPCQPX=2,JPCQPY=3,JPCQPZ=4,JPCQEN=5,LPCQAA=5)
      INTEGER JPDLPA,JPDLJT,JPDLPI,JPDLPE,JPDLVP,JPDLFR,LPDLTA
      PARAMETER (JPDLPA=1,JPDLJT=2,JPDLPI=3,JPDLPE=4,JPDLVP=5,
     &           JPDLFR=6,LPDLTA=6)
      INTEGER JPECER,JPECE1,JPECE2,JPECTH,JPECPH,JPECEC,JPECKD,JPECCC,
     +          JPECRB,JPECPC,LPECOA
      PARAMETER(JPECER=1,JPECE1=2,JPECE2=3,JPECTH=4,JPECPH=5,JPECEC=6,
     +          JPECKD=7,JPECCC=8,JPECRB=9,JPECPC=10,LPECOA=10)
      INTEGER JPEPT1,JPEPP1,JPEPT3,JPEPP3,LPEPTA
      PARAMETER(JPEPT1=1,JPEPP1=2,JPEPT3=3,JPEPP3=4,LPEPTA=4)
      INTEGER JPGAEC,JPGATC,JPGAPC,JPGAR1,JPGAR2,JPGAF4,JPGADM,JPGAST,
     +          JPGAQU,JPGAQ1,JPGAQ2,JPGAM1,JPGAM2,JPGAMA,JPGAER,JPGATR,
     +          JPGAPR,JPGAEF,JPGAGC,JPGAZS,JPGAPL,JPGAPH,JPGAPN,JPGAFA,
     +          JPGAPE,LPGACA
      PARAMETER(JPGAEC=1,JPGATC=2,JPGAPC=3,JPGAR1=4,JPGAR2=5,JPGAF4=6,
     +          JPGADM=7,JPGAST=8,JPGAQU=9,JPGAQ1=10,JPGAQ2=11,
     +          JPGAM1=12,JPGAM2=13,JPGAMA=14,JPGAER=15,JPGATR=16,
     +          JPGAPR=17,JPGAEF=18,JPGAGC=19,JPGAZS=20,JPGAPL=21,
     +          JPGAPH=22,JPGAPN=23,JPGAFA=24,JPGAPE=25,LPGACA=25)
      INTEGER JPGPEC,JPGPTC,JPGPPC,JPGPR1,JPGPR2,JPGPF4,JPGPDM,JPGPST,
     +          JPGPQU,JPGPQ1,JPGPQ2,JPGPM1,JPGPM2,JPGPMA,JPGPER,JPGPTR,
     +          JPGPPR,JPGPPE,LPGPCA
      PARAMETER(JPGPEC=1,JPGPTC=2,JPGPPC=3,JPGPR1=4,JPGPR2=5,JPGPF4=6,
     +          JPGPDM=7,JPGPST=8,JPGPQU=9,JPGPQ1=10,JPGPQ2=11,
     +          JPGPM1=12,JPGPM2=13,JPGPMA=14,JPGPER=15,JPGPTR=16,
     +          JPGPPR=17,JPGPPE=18,LPGPCA=18)
      INTEGER JPHCER,JPHCTH,JPHCPH,JPHCEC,JPHCKD,JPHCCC,JPHCRB,JPHCNF,
     +          JPHCPC,LPHCOA
      PARAMETER(JPHCER=1,JPHCTH=2,JPHCPH=3,JPHCEC=4,JPHCKD=5,JPHCCC=6,
     +          JPHCRB=7,JPHCNF=8,JPHCPC=9,LPHCOA=9)
      INTEGER JPMLFL,JPMLPO,JPMLCH,JPMLSP,JPMLLE,JPMLME,JPMLKT,JPMLFR,
     +          LPMLTA
      PARAMETER (JPMLFL=1,JPMLPO=2,JPMLCH=3,JPMLSP=4,JPMLLE=5,
     &           JPMLME=6,JPMLKT=7,JPMLFR=8,LPMLTA=8)
      INTEGER JTEXSI,JTEXTM,JTEXTL,JTEXNS,JTEXAD,JTEXTN,JTEXSF,LTEXSA
      PARAMETER(JTEXSI=1,JTEXTM=2,JTEXTL=3,JTEXNS=4,JTEXAD=5,JTEXTN=6,
     +          LTEXSA=6)
      INTEGER JYV0K1,JYV0K2,JYV0VX,JYV0VY,JYV0VZ,JYV0VM,JYV0PX,JYV0PY,
     +          JYV0PZ,JYV0PM,JYV0X1,JYV0X2,JYV0XM,JYV0C2,JYV0IC,JYV0P1,
     +          JYV0P2,JYV0EP,JYV0DM,JYV0S1,JYV0S2,LYV0VA
      PARAMETER(JYV0K1=1,JYV0K2=2,JYV0VX=3,JYV0VY=4,JYV0VZ=5,JYV0VM=6,
     +          JYV0PX=12,JYV0PY=13,JYV0PZ=14,JYV0PM=15,JYV0X1=21,
     +          JYV0X2=22,JYV0XM=23,JYV0C2=26,JYV0IC=27,JYV0P1=28,
     +          JYV0P2=31,JYV0EP=34,JYV0DM=55,JYV0S1=56,JYV0S2=57,
     +          LYV0VA=57)
C--------------------- end of QCDE ------------------------------------
      DATA INIT, IER, IER2 /0, 0, 0/
      DATA  TMX,TMX2 / 1000000. ,  1.E+10  /
C----------------------------------------------------------------------
C
      IF (QMFLDC .EQ. 0.)THEN
        IER=IER+1
        IF(IER.LE.5)CALL QWMESE
     +   ('_QFCHGD_ Mag. field = 0; CHT section not filled ')
        GOTO 999
      ENDIF
C
      IF (INIT .EQ. 0)  THEN
        INIT = 1
        N = KPCOMP ('PI+')
        AMASPI = RW(KOQPAR+N*KCQPAR+JQPAMA)
        ICHGD = KPCOMP ('CHARGED')
        NCHGD = KFPADR(ICHGD)
      ENDIF
      IF (XMINI.AND.IW(NAPMSC).GT.0) CALL QFPMSC
C
      JFRFT = IW(NAFRFT) + LMHLEN
C
C     IF(XFRF2)THEN
C        IFRF2=NLINK('FRFT',2)
C        IF(IFRF2.NE.0)THEN
C          JFRFT=IFRF2+LMHLEN
C        ELSE
C          IF(IER2.LT.5)CALL QWMESE
C    +    ('_QFCHGD_ FRFT NR=2 not available -- NR=0 used.')
C          IER2=IER2+1
C        ENDIF
C     ENDIF
C
      LFRFT = IW(JFRFT-1)
      KNCHT = IW(JFRFT)
C
      JFRTL = IW(NAFRTL) + LMHLEN
      LFRTL = IW(JFRTL-1)
      JFRID = IW(NAFRID) + LMHLEN
      LFRID = IW(JFRID-1)
C
      KLCHT = KLCHT + KNCHT
      IF (KLCHT .GE. KLFRT)  CALL QSBANK ('QVEC', KLCHT + 200)
      IF (KLCHT - KLUST .GE. IW(KOQDET))
     &   CALL QSBANK ('QDET', KLCHT - KLUST + 50)
      IF (KNQLIN + KNCHT .GE. IW(KOQLIN))
     &   CALL QSBANK ('QLIN', KNQLIN + KNCHT + 500)
C
      JQVEC = KOQVEC + KFCHT * KCQVEC
C       do not use the first row in KOQDET :
      JQDET = KOQDET + (KFCHT - KLUST) * KCQDET
      JQDET0 = JQDET - KCQDET
C----------------------------------------------------------------------
C  Loop on all tracks of bank FRFT :
C
C
      ITK = KFCHT
      DO 10 NJUL = 1, KNCHT
C
C         basic track attributes :
C
        PS = QMFLDC / RW(JFRFT+JFRFIR)
        IF (PS .GT. 0.)  THEN
          RW(JQVEC+JQVECH) = -1.
          PT = PS
        ELSE
          RW(JQVEC+JQVECH) = 1.
          PT = - PS
        ENDIF
C
        CP = COS (RW(JFRFT+JFRFP0))
        SP = SIN (RW(JFRFT+JFRFP0))
        TL = RW(JFRFT+JFRFTL)
C
        PX = PT * CP
        RW(JQVEC+JQVEQX) = PX
        PY = PT * SP
        RW(JQVEC+JQVEQY) = PY
        PZ = PT * TL
        RW(JQVEC+JQVEQZ) = PZ
        RW(JQVEC+JQVEQP) = SQRT (PT**2 + PZ**2)
C         set mass = mass (pi+)
        RW(JQVEC+JQVEQM) = AMASPI
        E = SQRT (RW(JQVEC+JQVEQM)**2 + RW(JQVEC+JQVEQP)**2)
        RW(JQVEC+JQVEQE) = E
        IOKMA=1
        IF (E.GT.TMX) IOKMA=0
        DO 1 IMAT=JFRFEM,JFRFC2-1
           IF (ABS(RW(JFRFT+IMAT)).GT.TMX2) IOKMA=0
 1      CONTINUE
C
C         error matrix
C
        IF(XFILEM)THEN
        IF (IOKMA.EQ.1) THEN
        DPDK = PS**2 / QMFLDC
        XY = 2. * PS * DPDK * CP * SP * RW(JFRFT+JFRFEM+3)
        SXX = (DPDK * CP)**2 * RW(JFRFT+JFRFEM) +
     &        (PS * SP)**2 * RW(JFRFT+JFRFEM+5) + XY
        RW(JQVEC+JQVEEM) = SXX
        SXY = CP * SP * (DPDK**2 * RW(JFRFT+JFRFEM) -
     &                   PS**2 * RW(JFRFT+JFRFEM+5)) +
     &        PS * DPDK * (SP**2 - CP**2) * RW(JFRFT+JFRFEM+3)
        RW(JQVEC+JQVEEM+1) = SXY
        SYY = (DPDK * SP)**2 * RW(JFRFT+JFRFEM) +
     &        (PS * CP)**2 * RW(JFRFT+JFRFEM+5) - XY
        RW(JQVEC+JQVEEM+2) = SYY
        SXZ = DPDK**2 * CP * TL * RW(JFRFT+JFRFEM) -
     &        PS * DPDK * (CP * RW(JFRFT+JFRFEM+1) -
     &                     SP * TL * RW(JFRFT+JFRFEM+3)) -
     &        PS**2 * SP * RW(JFRFT+JFRFEM+4)
        RW(JQVEC+JQVEEM+3) = SXZ
        SYZ = DPDK**2 * SP * TL * RW(JFRFT+JFRFEM) -
     &        PS * DPDK * (SP * RW(JFRFT+JFRFEM+1) +
     &                     CP * TL * RW(JFRFT+JFRFEM+3)) +
     &        PS**2 * CP * RW(JFRFT+JFRFEM+4)
        RW(JQVEC+JQVEEM+4) = SYZ
        SZZ = (DPDK * TL)**2 * RW(JFRFT+JFRFEM) +
     &        PS**2 * RW(JFRFT+JFRFEM+2) -
     &        2. * PS * DPDK * TL * RW(JFRFT+JFRFEM+1)
        RW(JQVEC+JQVEEM+5) = SZZ
C
        RW(JQVEC+JQVEEM+6) = (PX * SXX + PY * SXY + PZ * SXZ) / E
        RW(JQVEC+JQVEEM+7) = (PX * SXY + PY * SYY + PZ * SYZ) / E
        RW(JQVEC+JQVEEM+8) = (PX * SXZ + PY * SYZ + PZ * SZZ) / E
        RW(JQVEC+JQVEEM+9) = (PX**2 * SXX + PY**2 * SYY + PZ**2 * SZZ +
     &    2. * (PX * (PY * SXY + PZ * SXZ) + PY * PZ * SYZ)) / E**2
        ELSE
        CALL QWMESE
     +  ('_QFCHGD_ Unphysical momentum -- error matrix not filled')
        RW(JQVEC+JQVEEM) = -1.
        ENDIF
        ELSE
          RW(JQVEC+JQVEEM) = -1.
        ENDIF
C
        RW(JQVEC+JQVECF) = -1.
C
C         distance to interaction point :
C
        RW(JQVEC+JQVEDB) = RW(JFRFT+JFRFD0) +
     +    QVYNOM * CP - QVXNOM * SP
        RW(JQVEC+JQVEZB) = RW(JFRFT+JFRFZ0) - QVZNOM
     &   + RW(JFRFT+JFRFTL) * ( QVXNOM * CP + QVYNOM * SP )
        IF (IOKMA.EQ.0) GO TO 5
        RW(JQVEC+JQVESD) = RW(JFRFT+JFRFEM+9)
        RW(JQVEC+JQVESZ) = RW(JFRFT+JFRFEM+14)
        DET = RW(JQVEC+JQVESD) * RW(JQVEC+JQVESZ) -
     &        RW(JFRFT+JFRFEM+13)**2
        IF (DET .GT. 0.)  RW(JQVEC+JQVECB) =
     &   (RW(JQVEC+JQVEDB)**2 * RW(JQVEC+JQVESZ) +
     &    RW(JQVEC+JQVEZB)**2 * RW(JQVEC+JQVESD) -
     &    2. * RW(JQVEC+JQVEDB) * RW(JQVEC+JQVEZB) *
     &    RW(JFRFT+JFRFEM+13)) / DET
 5      CONTINUE
C
C         flags :
C
        IW(JQVEC+JQVETN) = NJUL
        IW(JQVEC+JQVESC) = 1
        IW(JQVEC+JQVEKS) = 0
        IW(JQVEC+JQVECL) = 1
        IW(JQVEC+JQVEPA) = ICHGD
        IW(JQVEC+JQVEQD) = JQDET
        IW(JQVEC+JQVENP) = ITK + 1
        IW(JQVEC+JQVESP) = ITK
        IW(JQVEC+JQVEOV) = 0
        IW(JQVEC+JQVEEV) = 0
        IW(JQVEC+JQVEND) = 0
        IW(JQVEC+JQVENO) = 0
        IW(JQVEC+JQVENM) = 0
        DO 9 IB=1,KLOCKM
          IW(JQVEC+JQVEBM+IB-1) = 0
 9      CONTINUE
        IW(JQVEC+JQVELK) = 0
        RW(JQVEC+JQVEEW) = 0.
C
C         bank QDET :
C
        IW(JQDET+JQDEAF) = JFRFT
        IW(JQDET+JQDEAL) = JFRTL
        IW(JQDET+JQDENT) = 0
        IW(JQDET+JQDEAT) = KQZER
        IW(JQDET+JQDEAE) = KQZER
        IW(JQDET+JQDEAH) = KQZER
        IW(JQDET+JQDEAM) = KQZER
        IW(JQDET+JQDECF) = 0
        IW(JQDET+JQDEEC) = KQZER
        IW(JQDET+JQDEHC) = KQZER
        IW(JQDET+JQDEET) = KQZER
        IW(JQDET+JQDEFI) = JFRID
        IW(JQDET+JQDENF) = 1
        IW(JQDET+JQDEFL) = KNQLIN
        KNQLIN = KNQLIN + 1
        IW(KOQLIN+KNQLIN) = ITK
        IW(JQDET+JQDENE) = 0
        IW(JQDET+JQDENH) = 0
        IW(JQDET+JQDEEF) = KQZER
        IW(JQDET+JQDEPC) = KQZER
        IW(JQDET+JQDEEG) = KQZER
        IW(JQDET+JQDEMU) = KQZER
        IW(JQDET+JQDEPD) = KQZER
        IW(JQDET+JQDEPM) = KQZER
C
        ITK = ITK + 1
        JQDET = JQDET + KCQDET
        JQVEC = JQVEC + KCQVEC
        JFRTL = JFRTL + LFRTL
        JFRID = JFRID + LFRID
   10 JFRFT = JFRFT + LFRFT
C----------------------------------------------------------------------
C       set first and last KPDIR / KFOLLO relation
C
      IW(KOQFPA+NCHGD*KCQFPA+1) = KFCHT
      IW(JQVEC+JQVENP-KCQVEC) = 0
C
C         bank TEXS
C
      JTEXS = IW(NATEXS)
      IF (JTEXS .NE. 0)  THEN
        LTEXS = IW(JTEXS+1)
        LAST = IW(JTEXS+2)
        JTEXS = JTEXS + LMHLEN
C
        DO 20 N=1,LAST
          JQDET = JQDET0 + IW(JTEXS+JTEXTN) * KCQDET
          IF (IW(JQDET+JQDENT) .LT. JQDELT - JQDEAT + 1)  THEN
            IW(JQDET+JQDEAT+IW(JQDET+JQDENT)) = JTEXS
            IW(JQDET+JQDENT) = IW(JQDET+JQDENT) + 1
          ENDIF
   20   JTEXS = JTEXS + LTEXS
      ENDIF
C
C         bank EIDT
C
      JEIDT = IW(NAEIDT)
      IF (JEIDT .NE. 0)  THEN
        LEIDT = IW(JEIDT+1)
        LAST = IW(JEIDT+2)
        JEIDT = JEIDT + LMHLEN
C
        DO 30 N=1,LAST
          IW(JQDET0+IW(JEIDT+JEIDFR)*KCQDET+JQDEAE) = JEIDT
   30   JEIDT = JEIDT + LEIDT
      ENDIF
C
C         bank HMAD
C
      JHMAD = IW(NAHMAD)
      IF (JHMAD .NE. 0)  THEN
        LHMAD = IW(JHMAD+1)
        LAST = IW(JHMAD+2)
        JHMAD = JHMAD + LMHLEN
C
        DO 40 N=1,LAST
          IW(JQDET0+IW(JHMAD+JHMATN)*KCQDET+JQDEAH) = JHMAD
   40   JHMAD = JHMAD + LHMAD
      ENDIF
C
C         bank MCAD
C
      JMCAD = IW(NAMCAD)
      IF (JMCAD .NE. 0)  THEN
        LMCAD = IW(JMCAD+1)
        LAST = IW(JMCAD+2)
        JMCAD = JMCAD + LMHLEN
C
        DO 50 N=1,LAST
          IW(JQDET0+IW(JMCAD+JMCATN)*KCQDET+JQDEAM) = JMCAD
   50   JMCAD = JMCAD + LMCAD
      ENDIF
C
C         bank MUID
C
      JMUID = IW(NAMUID)
      IF (JMUID .NE. 0)  THEN
        LMUID = IW(JMUID+1)
        LAST = IW(JMUID+2)
        JMUID = JMUID + LMHLEN
C
        DO 60 N=1,LAST
          IW(JQDET0+IW(JMUID+JMUITN)*KCQDET+JQDEMU) = JMUID
   60   JMUID = JMUID + LMUID
      ENDIF
C
C       loci :
C
      DO 80 N = KSCHT+1,KSMCT
        KLOCUS(1,N) = KLOCUS(2,KSCHT) + 1
   80 KLOCUS(2,N) = KLOCUS(2,KSCHT)
      KFFRT = KLOCUS(2,KSCHT) + 1
      KFFRD = KFFRT
C
999   CONTINUE
      END
