      SUBROUTINE QMIHIS
CKEY INIT HIST /INTERNAL
C----------------------------------------------------------------------
C! initialize histogram package
C!called from QUIHIS
C!                                                  H.Albrecht 20.09.88
C!                  Options NREC and RECL added     O.Schneider 1.06.94
C----------------------------------------------------------------------
      SAVE CTYPE
C Start of QCDESH ----------------------- Description in QDATA ---------
      PARAMETER (KCQDET=34, KCQFPA=8, KCQPAR=10, KCQVEC=73, KCQVRT=30,
     & KHE=1, KHMU=2, KHPI=3, KHK=4, KHP=5, KHPHOT=1, KHNHAD=2,
     & KMONTE=-2, KRECO=-1, KLOCKM=14, KSOVT=1, KSCHT=2, KSIST=3,
     & KSAST=4, KSEHT=5, KSV0T=6, KSDCT=7, KSEFT=8, KSNET=9, KSGAT=10,
     & KSJET=11, KSMCT=12, KSREV=13,
     & KSMCV=14, KUNDEF=-12344321, QQPI=3.141593, QQE=2.718282,
     & QQ2PI=QQPI*2., QQPIH=QQPI/2., QQRADP=180./QQPI, QQC=2.997925E10,
     & QQH=6.582173E-25, QQHC=QQH*QQC, QQIRP=.00029979)
      CHARACTER CQDATE*8, CQDWRK*80, CQFHIS*80, CQFOUT*80, CQFWRK*80,
     & CQHTIT*80, CQSEC*3, CQTIME*8, CQUNPK*30, CQVERS*6, CQRLST*800,
     & CQELST*800
      COMMON /QCDEC/ CQDATE, CQDWRK, CQFHIS, CQFOUT, CQFWRK, CQHTIT,
     & CQSEC(14), CQTIME, CQUNPK, CQVERS, CQRLST, CQELST
      COMMON /QCDE/ QELEP, QMFLD ,QMFLDC, QTIME, QTIMEI, QTIMEL,
     & QTIMES, QTIMET, QDHEEC, QDHEEL, QDHEPF, QDHETH, QDHEPH, QDHEEF,
     & QDHEET, QDHET1, QDHEP1, QDHET2, QDHEP2, QDHEE1, QDHEE2, QDHEE3,
     & QKEVRN, QKEVWT, QVXNOM, QVYNOM, QVZNOM, QVXNSG, QVYNSG, QVZNSG,
     & QINLUM, QRINLN, QRINLU, QDBOFS, QEECWI(36), QVXBOM, QVYBOM,
     & QSILUM, QRSLLU, QRSLBK, QRSLEW , QVTXBP(3), QVTEBP(3), QVTSBP(3)
      COMMON /QCDE/  KFOVT, KLOVT, KNOVT, KFCHT, KLCHT, KNCHT, KFIST,
     & KLIST, KNIST, KFAST, KLAST, KNAST, KFEHT, KLEHT, KNEHT, KFV0T,
     & KLV0T, KNV0T, KFDCT, KLDCT, KNDCT, KFEFT, KLEFT, KNEFT, KFNET,
     & KLNET, KNNET, KFGAT, KLGAT, KNGAT, KFJET, KLJET, KNJET, KFMCT,
     & KLMCT, KNMCT, KFREV, KLREV, KNREV, KFMCV, KLMCV, KNMCV, KLUST,
     & KLUSV, KFFRT, KLFRT, KFFRV, KLFRV, KNRET, KNCOT, KFFRD,
     & KLFJET,KLLJET,KLNJET
      COMMON /QCDE/ KBIT(32), KCLACO(KCQFPA), KCLAFR(KCQFPA), KCLARM
     & (KCQFPA), KDEBUG, KEVT, KEXP, KFFILL, KFEOUT, KJOPTN(2,2),
     & KLEOUT, KLROUT, KLOCK0(KLOCKM,2), KLOCK1(KLOCKM,2), KLOCK2(
     & KLOCKM,2), KMATIX(6,6), KMQFPA, KNEFIL, KNEOUT, KNEVT, KNPAST,
     & KNQDET, KNQFPA, KNQLIN, KNQMTX, KNQPAR, KNQPST, KNREIN, KNREOU,
     & KOQDET, KOQFPA, KOQLIN, KOQMTL, KOQMTS, KOQPAR, KOQPBT, KOQPLI,
     & KOQTRA, KOQVEC, KOQVRT, KQPAR, KQVEC, KQVRT, KQWRK, KQZER, KRUN,
     & KSTATU, KTDROP, KUCARD, KUCONS, KUHIST, KUINPU, KUOUTP, KUPRNT,
     & KUPTER, KDEBU1, KDEBU2, KNWRLM, KEFOPT, KUEDIN, KUEDOU, KURTOX,
     & KUCAR2, KNHDRN, KNBHAB, KSBHAB, KRSLLQ, KRSLNB
      COMMON /QCDE/ INDATA
      COMMON /QCDE/ KRINNE, KRINNF, KRINDC, KRINDQ, KRINNZ, KRINNB,
     & KRINBM, KRINFR, KRINLR, KRINLF
      COMMON /QCDE/ KEVERT, KEVEDA, KEVETI, KEVEMI(4), KEVETY, KEVEES,
     & KDHEFP, KDHENP, KDHENM, KKEVNT, KKEVNV, KKEVID, KDHENX, KDHENV,
     & KDHENJ, KREVDS, KXTET1, KXTET2, KXTEL2, KXTCGC, KXTCLL, KXTCBN,
     & KXTCCL, KXTCHV, KXTCEN, KCLASW, KERBOM, KBPSTA
      DIMENSION KLOCUS(3,14)
      EQUIVALENCE (KLOCUS(1,1),KFOVT), (KFOVT,KFRET), (KLIST,KLRET),
     & (KFIST,KFCOT), (KLAST,KLCOT)
      COMMON /QCDE/ XCOPYJ, XFLIAC, XHISTO, XLREV(2), XLREV2(2), XMCEV,
     & XMINI, XSYNTX, XWREVT, XWRRUN, XFILMC, XFILCH, XFILV0, XFILCO,
     & XFILEF, XFILPC, XFILGA, XFILJE,
     & XPRHIS, XFILL, XVITC, XVTPC, XVECAL, XVLCAL, XVTPCD,
     & XVSATR, XVHCAL, XHVTRG, XSREC, XWMINI, XIOKLU, XIOKSI, XFRF2,
     & XNSEQ, XVDOK, XFRF0, XFMUID, XFILEM, XWNANO, XROKSI, XGETBP,
     & XJTHRU
      LOGICAL XCOPYJ, XFLIAC, XHISTO, XLREV, XLREV2, XMCEV, XMINI,
     & XSYNTX, XWREVT, XWRRUN, XFILMC, XFILCH, XFILV0, XFILCO, XFILEF,
     & XFILPC, XPRHIS, XFILL, XVITC, XVTPC, XVECAL, XVLCAL, XVTPCD,
     & XVSATR, XVHCAL, XHVTRG, XSREC, XWMINI, XIOKLU, XFRF2, XFILJE,
     & XNSEQ, XFILGA, XVDOK, XFRF0, XFMUID, XFILEM, XWNANO, XIOKSI,
     & XROKSI, XGETBP, XJTHRU
C-------------------- /NANCOM/ --- NanoDst steering -------------------
C! XNANO   .TRUE. if input is a NanoDst (in NANO or EPIO format, dependi
C!                   XNANOR)
C!
      LOGICAL XNANO
      COMMON /NANCOM/XNANO
C--------------------- end of NANCOM ----------------------------------
      INTEGER LMHLEN, LMHCOL, LMHROW
      PARAMETER (LMHLEN=2, LMHCOL=1, LMHROW=2)
      INTEGER IW
      REAL RW(10000)
      COMMON /BCS/ IW(10000)
      EQUIVALENCE (RW(1),IW(1))
C------------------ /QCNAMI/ --- name indices -------------------------
      COMMON /QCNAMI/ NAAFID,NAAJOB,NAASEV,NABCNT,NABHIT,NABOMB,
     1 NABOME,NABOMP,NABOMR,NABPTR,NADCAL,NADCRL,NADECO,NADEID,NADENF,
     2 NADEVT,NADEWI,NADFMC,NADFOT,NADGAM,NADHCO,NADHEA,NADHRL,NADJET,
     3 NADMID,NADMJT,NADMUO,NADNEU,NADPOB,NADRES,NADTBP,NADTMC,NADTRA,
     4 NADVER,NADVMC,NAECRQ,NAECTE,NAEGID,NAEGPC,NAEIDT,NAEJET,NAERRF,
     5 NAETDI,NAETKC,NAEVEH,NAEWHE,NAFICL,NAFKIN,NAFPOI,NAFPOL,NAFRFT,
     6 NAFRID,NAFRTL,NAFSTR,NAFTCL,NAFTCM,NAFTOC,NAFTTM,NAFVCL,NAFVER,
     7 NAFZFR,NAHCCV,NAHCTE,NAHINF,NAHMAD,NAHPDI,NAHROA,NAHSDA,NAHTUB,
     8 NAIASL,NAIPJT,NAIRJT,NAITCO,NAITMA,NAIXTR,NAIZBD,NAJBER,NAJEST,
     9 NAJSUM,NAKEVH,NAKINE,NAKJOB,NAKLIN,NAKPOL,NAKRUN,NALIDT,NALOLE,
     A NALUPA,NAMCAD,NAMHIT,NAMTHR,NAMUDG,NAMUEX,NAOSTS,NAPART,NAPASL,
     B NAPCHY,NAPCOB,NAPCOI,NAPCPA,NAPCQA,NAPCRL,NAPECO,NAPEHY,NAPEID,
     C NAPEMH,NAPEPT,NAPEST,NAPEWI,NAPFER,NAPFHR,NAPFRF,NAPFRT,NAPHCO,
     D NAPHER,NAPHHY,NAPHMH,NAPHST,NAPIDI,NAPITM,NAPLID,NAPLPD,NAPLSD,
     E NAPMSK,NAPNEU,NAPPDS,NAPPOB,NAPPRL,NAPRTM,NAPSCO,NAPSPO,NAPSTR,
     F NAPT2X,NAPTBC,NAPTCO,NAPTEX,NAPTMA,NAPTML,NAPTNC,NAPTST,NAPVCO,
     G NAPYER,NAPYFR,NAPYNE,NAQDET,NAQFPA,NAQLIN,NAQMTL,NAQMTS,NAQPAR,
     H NAQPBT,NAQPLI,NAQTRA,NAQVEC,NAQVRT,NAQWRK,NAQZER,NAREVH,NARHAH,
     I NARTLO,NARTLS,NARUNH,NARUNR,NASFTR,NATEXS,NATGMA,NATMTL,NATPCO,
     J NAVCOM,NAVCPL,NAVDCO,NAVDHT,NAVDXY,NAVDZT,NAVERT,NAVFHL,NAVFLG,
     K NAVFPH,NAVHLS,NAVPLH,NAX1AD,NAX1SC,NAX1TI,NAX2DF,NAX3EC,NAX3EW,
     L NAX3HC,NAX3IT,NAX3L2,NAX3LU,NAX3TM,NAX3TO,NAX3TP,NAX3X3,NAXTBN,
     M NAXTBP,NAXTCN,NAXTEB,NAXTOP,NAXTRB,NAYV0V,NAZPFR,NAEFOL,NAMUID,
     N NAPGID,NAPGPC,NAPGAC,NAPMSC,NAPTHR,NANBIP,NAPDLT,NAPMLT,NAPLJT
C--------------------- end of QCNAMI ----------------------------------
C------------------ /QQQQJJ/ --- HAC parameters for ALPHA banks -------
      PARAMETER (JQVEQX= 1,JQVEQY= 2,JQVEQZ= 3,JQVEQE= 4,JQVEQM= 5,
     & JQVEQP= 6,JQVECH= 7,JQVETN= 8,JQVESC= 9,JQVEKS=10,JQVECL=11,
     & JQVEPA=12,JQVEQD=13,JQVENP=14,JQVESP=15,JQVEOV=16,JQVEEV=17,
     & JQVEND=18,JQVEDL=19,JQVENO=20,JQVEOL=21,JQVENM=22,JQVEML=23,
     & JQVEBM=24,JQVELK=38,JQVEDB=39,JQVEZB=40,JQVESD=41,JQVESZ=42,
     & JQVECB=43,JQVEEM=44,JQVECF=54,JQVEEW=55,JQVEUS=56)
      PARAMETER ( JQVRVX=1,JQVRVY=2,JQVRVZ=3,JQVRVN=4,JQVRTY=5,
     1   JQVRIP=6,JQVRND=7,JQVRDL=8,JQVRAY=9,JQVRAF=10,JQVREM=11,
     2   JQVRCF=17,JQVRET=18)
      PARAMETER ( JQDEAF= 1,JQDEAL= 2,JQDENT= 3,JQDEAT= 4,JQDELT= 8,
     &  JQDEAE= 9,JQDEAH=10,JQDEAM=11,JQDECF=12,JQDEEC=13,JQDEHC=14,
     &  JQDEET=15,JQDEFI=16,JQDENF=17,JQDEFL=18,JQDENE=19,JQDEEL=20,
     &  JQDENH=21,JQDEHL=22,JQDELH=23,JQDEEF=24,JQDEPC=25,JQDEEG=26,
     &  JQDEMU=27,JQDEDX=28,JQDEPG=29,JQDEPD=30,JQDEPM=31)
      PARAMETER ( JQPAGN=1, JQPANA=2, JQPACO=5, JQPAMA=6, JQPACH=7,
     & JQPALT=8,JQPAWI=9,JQPAAN=10)
C--------------------- end of QCDESH ----------------------------------
      COMMON / QUEST / IQUEST(100)
      LOGICAL LOV,LUP,LEX
      INTEGER ACARD1,ACARD2,ACARD3
      CHARACTER CH2*2, CWRK*24, CTYPE*4
      PARAMETER (LRDEF = 1024)
      DATA CTYPE /'EXCH'/
C
C       HBOOK title
C
      IF (ACARD1 ('HTIT') .NE. 0)  I = ACARD2 (1,CQHTIT(41:80))
      IF (I .GE. 40)  I =  ACARD2 (1,CQHTIT)
      CALL HTITLE (CQHTIT)
C
C       get name of histogram file
C
      CALL ACDARG ('HIST',CTYPE,'A',CQFHIS,CWRK,CQDWRK,IER)
      IF (IER .LT. 0)  THEN
        CALL QWMESS ('_QMIHIS_ No HIST card given')
        GO TO 90
      ENDIF
      CALL CUTOL (CQFHIS)
      CALL QWMESS ('_QMIHIS_ Histogram file : ' // CQFHIS)
      IF (IER .GT. 0)  CALL QWERRC (IER,'QMIHIS',CTYPE)
      IF (CQDWRK(1:4) .NE. 'DISK')  CALL QWERRC (7,'QMIHIS',CTYPE)
      IF (INDEX(CQDWRK,'DISP').NE.0) THEN
         CALL ADSPOS (KUHIST,CQFHIS,CWRK(1:3),CQDWRK,IER)
      ENDIF
C
C       get parameters UPDA, NOOV, NREC, RECL
C
      LUP = ACARD3 (2, 'UPDA', CWRK) .GT. 0
      LOV = ACARD3 (2, 'NOOV', CWRK) .GT. 0
      IF (LUP .AND. LOV)  CALL QWSYNT
     +   ('_QMIHIS_ UPDA and NOOV are mutually exclusive')
      NREC = 16000
      IF (LUP) THEN
        LRECL = 0
      ELSE
        LRECL = LRDEF
      ENDIF
      IF (ACARD3(2,'NREC ',CWRK) .NE. 0) THEN
        IF (LUP) CALL QWSYNT
     +   ('_QMIHIS_ UPDA and NREC are mutually exclusive')
        READ(CWRK(6:),*,ERR=10) ITMP
        IF (ITMP.GE.100) NREC=MIN0(MAX0(ITMP,100),65000)
   10   CONTINUE
      ENDIF
      IF (ACARD3(2,'RECL ',CWRK) .NE. 0) THEN
        READ(CWRK(6:),*,ERR=20) ITMP
        IF(ITMP.GT.0.AND.ITMP.LT.1000000) LRECL=ITMP
   20   CONTINUE
      ENDIF
C
C       does file already exist ?
C
      CALL AINQUI (0, CQFHIS, LEX)
      IF (LEX)  THEN
        IF (LOV)  THEN
          CALL QWSYNT
     +      ('_QMIHIS_ File exists. NOOV specified !')
        ELSE
          IF (LUP)  THEN
            CALL QWMESS  ('_QMIHIS_ File exists and will be updated')
          ELSE
            CALL QWMESS
     +       ('_QMIHIS_ File exists. On VAX : create new version')
C           For unix machines: remove file first
            CALL SYSTEM ('rm '//CQFHIS(1:LNBLNK(CQFHIS)))
            CALL QWMESS
     +       ('           On other machines : OVERWRITE')
          ENDIF
        ENDIF
      ELSE
        IF (LUP)  THEN
          CALL QWMESS
     +      ('_QMIHIS_ File does not yet exist : UPDATE ignored')
          LUP = .FALSE.
          IF (LRECL .EQ. 0) LRECL = LRDEF
        ENDIF
      ENDIF
C
C       syntax flag ?
C
      IF (XSYNTX)  THEN
        CALL QWMESS
     +    ('_QMIHIS_ Syntax flag --> histogram file NOT opened')
        GO TO 90
      ENDIF
C
C       open histogram file
C
      CWRK = ' '
      IF (LUP) THEN
        CH2 = 'U'
      ELSE
        CH2 = 'NQ'
        IQUEST(10) = NREC
        WRITE(CWRK(14:),'(A,I6)') 'NREC=', NREC
      ENDIF
   30 ITMP=LRECL
      CALL HROPEN (KUHIST, 'ALPHA', CQFHIS, CH2, LRECL, IER)
      WRITE(CWRK(:11),'(A,I6)') 'RECL=', LRECL
      IF (IER .EQ. 0)  THEN
        CALL QWMESS ('_QMIHIS_ Open successful: '//CWRK)
        XHISTO = .TRUE.
      ELSE
        IF (LUP .AND. ITMP .NE. LRDEF) THEN
C       this code is needed because RZOPEN fails on UNIX/OSF1 when LRECL
          CALL QWMESS
     +    ('_QMIHIS_ ZEBRA not able to determine RECL from file.')
          CALL QWMESS ('_QMIHIS_ Making best guess for RECL'//
     +                         ' and trying to open again ...')
          LRECL = LRDEF
          GOTO 30
        ENDIF
        CALL QWSYNT ('_QMIHIS_ Open failed: '//CWRK)
        LUP = .FALSE.
      ENDIF
C
C       read histogram file for updating
C
      IF (LUP)  THEN
        I = 9999
        CALL HRIN (0,I,0)
        CALL QWMESS
     +    ('_QMIHIS_ Read existing histos/ntuples for updating')
        CALL HINDEX
      ENDIF
C
   90 CONTINUE
      END
