      SUBROUTINE QMNAMI
CKEY INIT /INTERNAL
C----------------------------------------------------------------------
C! define NAMe Indices
C! called from QMINIT
C                                                 D. Schlatter 26.06.88
C                                                   H.Albrecht 20.09.88
C                                                      M.Talby 15.02.89
C                                                    E.Blucher 10.04.89
C                                                    E.Blucher 01.08.90
C                                                    E.Blucher 05.05.91
C                                                    E.Blucher 31.01.92
C----------------------------------------------------------------------
C Start of QCDESH ----------------------- Description in QDATA ---------
      PARAMETER (KCQDET=34, KCQFPA=8, KCQPAR=10, KCQVEC=73, KCQVRT=30,
     & KHE=1, KHMU=2, KHPI=3, KHK=4, KHP=5, KHPHOT=1, KHNHAD=2,
     & KMONTE=-2, KRECO=-1, KLOCKM=14, KSOVT=1, KSCHT=2, KSIST=3,
     & KSAST=4, KSEHT=5, KSV0T=6, KSDCT=7, KSEFT=8, KSNET=9, KSGAT=10,
     & KSJET=11, KSMCT=12, KSREV=13,
     & KSMCV=14, KUNDEF=-12344321, QQPI=3.141593, QQE=2.718282,
     & QQ2PI=QQPI*2., QQPIH=QQPI/2., QQRADP=180./QQPI, QQC=2.997925E10,
     & QQH=6.582173E-25, QQHC=QQH*QQC, QQIRP=.00029979)
      CHARACTER CQDATE*8, CQDWRK*80, CQFHIS*80, CQFOUT*80, CQFWRK*80,
     & CQHTIT*80, CQSEC*3, CQTIME*8, CQUNPK*30, CQVERS*6, CQRLST*800,
     & CQELST*800
      COMMON /QCDEC/ CQDATE, CQDWRK, CQFHIS, CQFOUT, CQFWRK, CQHTIT,
     & CQSEC(14), CQTIME, CQUNPK, CQVERS, CQRLST, CQELST
      COMMON /QCDE/ QELEP, QMFLD ,QMFLDC, QTIME, QTIMEI, QTIMEL,
     & QTIMES, QTIMET, QDHEEC, QDHEEL, QDHEPF, QDHETH, QDHEPH, QDHEEF,
     & QDHEET, QDHET1, QDHEP1, QDHET2, QDHEP2, QDHEE1, QDHEE2, QDHEE3,
     & QKEVRN, QKEVWT, QVXNOM, QVYNOM, QVZNOM, QVXNSG, QVYNSG, QVZNSG,
     & QINLUM, QRINLN, QRINLU, QDBOFS, QEECWI(36), QVXBOM, QVYBOM,
     & QSILUM, QRSLLU, QRSLBK, QRSLEW , QVTXBP(3), QVTEBP(3), QVTSBP(3)
      COMMON /QCDE/  KFOVT, KLOVT, KNOVT, KFCHT, KLCHT, KNCHT, KFIST,
     & KLIST, KNIST, KFAST, KLAST, KNAST, KFEHT, KLEHT, KNEHT, KFV0T,
     & KLV0T, KNV0T, KFDCT, KLDCT, KNDCT, KFEFT, KLEFT, KNEFT, KFNET,
     & KLNET, KNNET, KFGAT, KLGAT, KNGAT, KFJET, KLJET, KNJET, KFMCT,
     & KLMCT, KNMCT, KFREV, KLREV, KNREV, KFMCV, KLMCV, KNMCV, KLUST,
     & KLUSV, KFFRT, KLFRT, KFFRV, KLFRV, KNRET, KNCOT, KFFRD,
     & KLFJET,KLLJET,KLNJET
      COMMON /QCDE/ KBIT(32), KCLACO(KCQFPA), KCLAFR(KCQFPA), KCLARM
     & (KCQFPA), KDEBUG, KEVT, KEXP, KFFILL, KFEOUT, KJOPTN(2,2),
     & KLEOUT, KLROUT, KLOCK0(KLOCKM,2), KLOCK1(KLOCKM,2), KLOCK2(
     & KLOCKM,2), KMATIX(6,6), KMQFPA, KNEFIL, KNEOUT, KNEVT, KNPAST,
     & KNQDET, KNQFPA, KNQLIN, KNQMTX, KNQPAR, KNQPST, KNREIN, KNREOU,
     & KOQDET, KOQFPA, KOQLIN, KOQMTL, KOQMTS, KOQPAR, KOQPBT, KOQPLI,
     & KOQTRA, KOQVEC, KOQVRT, KQPAR, KQVEC, KQVRT, KQWRK, KQZER, KRUN,
     & KSTATU, KTDROP, KUCARD, KUCONS, KUHIST, KUINPU, KUOUTP, KUPRNT,
     & KUPTER, KDEBU1, KDEBU2, KNWRLM, KEFOPT, KUEDIN, KUEDOU, KURTOX,
     & KUCAR2, KNHDRN, KNBHAB, KSBHAB, KRSLLQ, KRSLNB
      COMMON /QCDE/ INDATA
      COMMON /QCDE/ KRINNE, KRINNF, KRINDC, KRINDQ, KRINNZ, KRINNB,
     & KRINBM, KRINFR, KRINLR, KRINLF
      COMMON /QCDE/ KEVERT, KEVEDA, KEVETI, KEVEMI(4), KEVETY, KEVEES,
     & KDHEFP, KDHENP, KDHENM, KKEVNT, KKEVNV, KKEVID, KDHENX, KDHENV,
     & KDHENJ, KREVDS, KXTET1, KXTET2, KXTEL2, KXTCGC, KXTCLL, KXTCBN,
     & KXTCCL, KXTCHV, KXTCEN, KCLASW, KERBOM, KBPSTA
      DIMENSION KLOCUS(3,14)
      EQUIVALENCE (KLOCUS(1,1),KFOVT), (KFOVT,KFRET), (KLIST,KLRET),
     & (KFIST,KFCOT), (KLAST,KLCOT)
      COMMON /QCDE/ XCOPYJ, XFLIAC, XHISTO, XLREV(2), XLREV2(2), XMCEV,
     & XMINI, XSYNTX, XWREVT, XWRRUN, XFILMC, XFILCH, XFILV0, XFILCO,
     & XFILEF, XFILPC, XFILGA, XFILJE,
     & XPRHIS, XFILL, XVITC, XVTPC, XVECAL, XVLCAL, XVTPCD,
     & XVSATR, XVHCAL, XHVTRG, XSREC, XWMINI, XIOKLU, XIOKSI, XFRF2,
     & XNSEQ, XVDOK, XFRF0, XFMUID, XFILEM, XWNANO, XROKSI, XGETBP,
     & XJTHRU
      LOGICAL XCOPYJ, XFLIAC, XHISTO, XLREV, XLREV2, XMCEV, XMINI,
     & XSYNTX, XWREVT, XWRRUN, XFILMC, XFILCH, XFILV0, XFILCO, XFILEF,
     & XFILPC, XPRHIS, XFILL, XVITC, XVTPC, XVECAL, XVLCAL, XVTPCD,
     & XVSATR, XVHCAL, XHVTRG, XSREC, XWMINI, XIOKLU, XFRF2, XFILJE,
     & XNSEQ, XFILGA, XVDOK, XFRF0, XFMUID, XFILEM, XWNANO, XIOKSI,
     & XROKSI, XGETBP, XJTHRU
C-------------------- /NANCOM/ --- NanoDst steering -------------------
C! XNANO   .TRUE. if input is a NanoDst (in NANO or EPIO format, dependi
C!                   XNANOR)
C!
      LOGICAL XNANO
      COMMON /NANCOM/XNANO
C--------------------- end of NANCOM ----------------------------------
      INTEGER LMHLEN, LMHCOL, LMHROW
      PARAMETER (LMHLEN=2, LMHCOL=1, LMHROW=2)
      INTEGER IW
      REAL RW(10000)
      COMMON /BCS/ IW(10000)
      EQUIVALENCE (RW(1),IW(1))
C------------------ /QCNAMI/ --- name indices -------------------------
      COMMON /QCNAMI/ NAAFID,NAAJOB,NAASEV,NABCNT,NABHIT,NABOMB,
     1 NABOME,NABOMP,NABOMR,NABPTR,NADCAL,NADCRL,NADECO,NADEID,NADENF,
     2 NADEVT,NADEWI,NADFMC,NADFOT,NADGAM,NADHCO,NADHEA,NADHRL,NADJET,
     3 NADMID,NADMJT,NADMUO,NADNEU,NADPOB,NADRES,NADTBP,NADTMC,NADTRA,
     4 NADVER,NADVMC,NAECRQ,NAECTE,NAEGID,NAEGPC,NAEIDT,NAEJET,NAERRF,
     5 NAETDI,NAETKC,NAEVEH,NAEWHE,NAFICL,NAFKIN,NAFPOI,NAFPOL,NAFRFT,
     6 NAFRID,NAFRTL,NAFSTR,NAFTCL,NAFTCM,NAFTOC,NAFTTM,NAFVCL,NAFVER,
     7 NAFZFR,NAHCCV,NAHCTE,NAHINF,NAHMAD,NAHPDI,NAHROA,NAHSDA,NAHTUB,
     8 NAIASL,NAIPJT,NAIRJT,NAITCO,NAITMA,NAIXTR,NAIZBD,NAJBER,NAJEST,
     9 NAJSUM,NAKEVH,NAKINE,NAKJOB,NAKLIN,NAKPOL,NAKRUN,NALIDT,NALOLE,
     A NALUPA,NAMCAD,NAMHIT,NAMTHR,NAMUDG,NAMUEX,NAOSTS,NAPART,NAPASL,
     B NAPCHY,NAPCOB,NAPCOI,NAPCPA,NAPCQA,NAPCRL,NAPECO,NAPEHY,NAPEID,
     C NAPEMH,NAPEPT,NAPEST,NAPEWI,NAPFER,NAPFHR,NAPFRF,NAPFRT,NAPHCO,
     D NAPHER,NAPHHY,NAPHMH,NAPHST,NAPIDI,NAPITM,NAPLID,NAPLPD,NAPLSD,
     E NAPMSK,NAPNEU,NAPPDS,NAPPOB,NAPPRL,NAPRTM,NAPSCO,NAPSPO,NAPSTR,
     F NAPT2X,NAPTBC,NAPTCO,NAPTEX,NAPTMA,NAPTML,NAPTNC,NAPTST,NAPVCO,
     G NAPYER,NAPYFR,NAPYNE,NAQDET,NAQFPA,NAQLIN,NAQMTL,NAQMTS,NAQPAR,
     H NAQPBT,NAQPLI,NAQTRA,NAQVEC,NAQVRT,NAQWRK,NAQZER,NAREVH,NARHAH,
     I NARTLO,NARTLS,NARUNH,NARUNR,NASFTR,NATEXS,NATGMA,NATMTL,NATPCO,
     J NAVCOM,NAVCPL,NAVDCO,NAVDHT,NAVDXY,NAVDZT,NAVERT,NAVFHL,NAVFLG,
     K NAVFPH,NAVHLS,NAVPLH,NAX1AD,NAX1SC,NAX1TI,NAX2DF,NAX3EC,NAX3EW,
     L NAX3HC,NAX3IT,NAX3L2,NAX3LU,NAX3TM,NAX3TO,NAX3TP,NAX3X3,NAXTBN,
     M NAXTBP,NAXTCN,NAXTEB,NAXTOP,NAXTRB,NAYV0V,NAZPFR,NAEFOL,NAMUID,
     N NAPGID,NAPGPC,NAPGAC,NAPMSC,NAPTHR,NANBIP,NAPDLT,NAPMLT,NAPLJT
C--------------------- end of QCNAMI ----------------------------------
C------------------ /QQQQJJ/ --- HAC parameters for ALPHA banks -------
      PARAMETER (JQVEQX= 1,JQVEQY= 2,JQVEQZ= 3,JQVEQE= 4,JQVEQM= 5,
     & JQVEQP= 6,JQVECH= 7,JQVETN= 8,JQVESC= 9,JQVEKS=10,JQVECL=11,
     & JQVEPA=12,JQVEQD=13,JQVENP=14,JQVESP=15,JQVEOV=16,JQVEEV=17,
     & JQVEND=18,JQVEDL=19,JQVENO=20,JQVEOL=21,JQVENM=22,JQVEML=23,
     & JQVEBM=24,JQVELK=38,JQVEDB=39,JQVEZB=40,JQVESD=41,JQVESZ=42,
     & JQVECB=43,JQVEEM=44,JQVECF=54,JQVEEW=55,JQVEUS=56)
      PARAMETER ( JQVRVX=1,JQVRVY=2,JQVRVZ=3,JQVRVN=4,JQVRTY=5,
     1   JQVRIP=6,JQVRND=7,JQVRDL=8,JQVRAY=9,JQVRAF=10,JQVREM=11,
     2   JQVRCF=17,JQVRET=18)
      PARAMETER ( JQDEAF= 1,JQDEAL= 2,JQDENT= 3,JQDEAT= 4,JQDELT= 8,
     &  JQDEAE= 9,JQDEAH=10,JQDEAM=11,JQDECF=12,JQDEEC=13,JQDEHC=14,
     &  JQDEET=15,JQDEFI=16,JQDENF=17,JQDEFL=18,JQDENE=19,JQDEEL=20,
     &  JQDENH=21,JQDEHL=22,JQDELH=23,JQDEEF=24,JQDEPC=25,JQDEEG=26,
     &  JQDEMU=27,JQDEDX=28,JQDEPG=29,JQDEPD=30,JQDEPM=31)
      PARAMETER ( JQPAGN=1, JQPANA=2, JQPACO=5, JQPAMA=6, JQPACH=7,
     & JQPALT=8,JQPAWI=9,JQPAAN=10)
C--------------------- end of QCDESH ----------------------------------
C----------------------------------------------------------------------
      NAAFID = NAMIND ('AFID')
      NAAJOB = NAMIND ('AJOB')
      NAASEV = NAMIND ('ASEV')
      NABCNT = NAMIND ('BCNT')
      NABHIT = NAMIND ('BHIT')
      NABOMB = NAMIND ('BOMB')
      NABOME = NAMIND ('BOME')
      NABOMP = NAMIND ('BOMP')
      NABOMR = NAMIND ('BOMR')
      NABPTR = NAMIND ('BPTR')
      NADCRL = NAMIND ('DCRL')
      NADECO = NAMIND ('DECO')
      NADEID = NAMIND ('DEID')
      NADENF = NAMIND ('DENF')
      NADEVT = NAMIND ('DEVT')
      NADEWI = NAMIND ('DEWI')
      NADFMC = NAMIND ('DFMC')
      NADFOT = NAMIND ('DFOT')
      NADGAM = NAMIND ('DGAM')
      NADHCO = NAMIND ('DHCO')
      NADHEA = NAMIND ('DHEA')
      NADHRL = NAMIND ('DHRL')
      NADJET = NAMIND ('DJET')
      NADMJT = NAMIND ('DMJT')
      NADMUO = NAMIND ('DMUO')
      NADNEU = NAMIND ('DNEU')
      NADPOB = NAMIND ('DPOB')
      NADRES = NAMIND ('DRES')
      NADTBP = NAMIND ('DTBP')
      NADTMC = NAMIND ('DTMC')
      NADTRA = NAMIND ('DTRA')
      NADVER = NAMIND ('DVER')
      NADVMC = NAMIND ('DVMC')
      NAECRQ = NAMIND ('ECRQ')
      NAECTE = NAMIND ('ECTE')
      NAEFOL = NAMIND ('EFOL')
      NAEGID = NAMIND ('EGID')
      NAEGPC = NAMIND ('EGPC')
      NAEIDT = NAMIND ('EIDT')
      NAEJET = NAMIND ('EJET')
      NAERRF = NAMIND ('ERRF')
      NAETDI = NAMIND ('ETDI')
      NAETKC = NAMIND ('ETKC')
      NAEVEH = NAMIND ('EVEH')
      NAEWHE = NAMIND ('EWHE')
      NAFICL = NAMIND ('FICL')
      NAFKIN = NAMIND ('FKIN')
      NAFPOI = NAMIND ('FPOI')
      NAFPOL = NAMIND ('FPOL')
      NAFRFT = NAMIND ('FRFT')
      NAFRID = NAMIND ('FRID')
      NAFRTL = NAMIND ('FRTL')
      NAFSTR = NAMIND ('FSTR')
      NAFTCL = NAMIND ('FTCL')
      NAFTCM = NAMIND ('FTCM')
      NAFTOC = NAMIND ('FTOC')
      NAFTTM = NAMIND ('FTTM')
      NAFVCL = NAMIND ('FVCL')
      NAFVER = NAMIND ('FVER')
      NAFZFR = NAMIND ('FZFR')
      NAHCCV = NAMIND ('HCCV')
      NAHCTE = NAMIND ('HCTE')
      NAHINF = NAMIND ('HINF')
      NAHMAD = NAMIND ('HMAD')
      NAHPDI = NAMIND ('HPDI')
      NAHROA = NAMIND ('HROA')
      NAHSDA = NAMIND ('HSDA')
      NAHTUB = NAMIND ('HTUB')
      NAIASL = NAMIND ('IASL')
      NAIPJT = NAMIND ('IPJT')
      NAIRJT = NAMIND ('IRJT')
      NAITCO = NAMIND ('ITCO')
      NAITMA = NAMIND ('ITMA')
      NAIXTR = NAMIND ('IXTR')
      NAIZBD = NAMIND ('IZBD')
      NAJBER = NAMIND ('JBER')
      NAJEST = NAMIND ('JEST')
      NAJSUM = NAMIND ('JSUM')
      NAKEVH = NAMIND ('KEVH')
      NAKINE = NAMIND ('KINE')
      NAKJOB = NAMIND ('KJOB')
      NAKLIN = NAMIND ('KLIN')
      NAKPOL = NAMIND ('KPOL')
      NAKRUN = NAMIND ('KRUN')
      NALIDT = NAMIND ('LIDT')
      NALOLE = NAMIND ('LOLE')
      NALUPA = NAMIND ('LUPA')
      NAMCAD = NAMIND ('MCAD')
      NAMHIT = NAMIND ('MHIT')
      NAMTHR = NAMIND ('MTHR')
      NAMUDG = NAMIND ('MUDG')
      NAMUEX = NAMIND ('MUEX')
      NAMUID = NAMIND ('MUID')
      NANBIP = NAMIND ('NBIP')
      NAOSTS = NAMIND ('OSTS')
      NAPART = NAMIND ('PART')
      NAPASL = NAMIND ('PASL')
      NAPCHY = NAMIND ('PCHY')
      NAPCOB = NAMIND ('PCOB')
      NAPCOI = NAMIND ('PCOI')
      NAPCPA = NAMIND ('PCPA')
      NAPCQA = NAMIND ('PCQA')
      NAPCRL = NAMIND ('PCRL')
      NAPDLT = NAMIND ('PDLT')
      NAPECO = NAMIND ('PECO')
      NAPEHY = NAMIND ('PEHY')
      NAPEID = NAMIND ('PEID')
      NAPEMH = NAMIND ('PEMH')
      NAPEPT = NAMIND ('PEPT')
      NAPEST = NAMIND ('PEST')
      NAPEWI = NAMIND ('PEWI')
      NAPFER = NAMIND ('PFER')
      NAPFHR = NAMIND ('PFHR')
      NAPFRF = NAMIND ('PFRF')
      NAPFRT = NAMIND ('PFRT')
      NAPGAC = NAMIND ('PGAC')
      NAPGID = NAMIND ('PGID')
      NAPGPC = NAMIND ('PGPC')
      NAPHCO = NAMIND ('PHCO')
      NAPHER = NAMIND ('PHER')
      NAPHHY = NAMIND ('PHHY')
      NAPHMH = NAMIND ('PHMH')
      NAPHST = NAMIND ('PHST')
      NAPIDI = NAMIND ('PIDI')
      NAPITM = NAMIND ('PITM')
      NAPLID = NAMIND ('PLID')
      NAPLJT = NAMIND ('PLJT')
      NAPLPD = NAMIND ('PLPD')
      NAPLSD = NAMIND ('PLSD')
      NAPMLT = NAMIND ('PMLT')
      NAPMSC = NAMIND ('PMSC')
      NAPMSK = NAMIND ('PMSK')
      NAPNEU = NAMIND ('PNEU')
      NAPPDS = NAMIND ('PPDS')
      NAPPOB = NAMIND ('PPOB')
      NAPPRL = NAMIND ('PPRL')
      NAPRTM = NAMIND ('PRTM')
      NAPSCO = NAMIND ('PSCO')
      NAPSPO = NAMIND ('PSPO')
      NAPT2X = NAMIND ('PT2X')
      NAPTBC = NAMIND ('PTBC')
      NAPTCO = NAMIND ('PTCO')
      NAPTEX = NAMIND ('PTEX')
      NAPTHR = NAMIND ('PTHR')
      NAPTMA = NAMIND ('PTMA')
      NAPTML = NAMIND ('PTML')
      NAPTNC = NAMIND ('PTNC')
      NAPTST = NAMIND ('PTST')
      NAPYER = NAMIND ('PYER')
      NAPYFR = NAMIND ('PYFR')
      NAPYNE = NAMIND ('PYNE')
      NAQDET = NAMIND ('QDET')
      NAQFPA = NAMIND ('QFPA')
      NAQLIN = NAMIND ('QLIN')
      NAQMTL = NAMIND ('QMTL')
      NAQMTS = NAMIND ('QMTS')
      NAQPAR = NAMIND ('QPAR')
      NAQPBT = NAMIND ('QPBT')
      NAQPLI = NAMIND ('QPLI')
      NAQTRA = NAMIND ('QTRA')
      NAQVEC = NAMIND ('QVEC')
      NAQVRT = NAMIND ('QVRT')
      NAQWRK = NAMIND ('QWRK')
      NAQZER = NAMIND ('QZER')
      NAREVH = NAMIND ('REVH')
      NARHAH = NAMIND ('RHAH')
      NARTLO = NAMIND ('RTLO')
      NARTLS = NAMIND ('RTLS')
      NARUNH = NAMIND ('RUNH')
      NARUNR = NAMIND ('RUNR')
      NASFTR = NAMIND ('SFTR')
      NATEXS = NAMIND ('TEXS')
      NATGMA = NAMIND ('TGMA')
      NATMTL = NAMIND ('TMTL')
      NATPCO = NAMIND ('TPCO')
      NAVCOM = NAMIND ('VCOM')
      NAVCPL = NAMIND ('VCPL')
      NAVDCO = NAMIND ('VDCO')
      NAVDHT = NAMIND ('VDHT')
      NAVDXY = NAMIND ('VDXY')
      NAVDZT = NAMIND ('VDZT')
      NAVERT = NAMIND ('VERT')
      NAVFHL = NAMIND ('VFHL')
      NAVFLG = NAMIND ('VFLG')
      NAVFPH = NAMIND ('VFPH')
      NAVHLS = NAMIND ('VHLS')
      NAVPLH = NAMIND ('VPLH')
      NAX1AD = NAMIND ('X1AD')
      NAX1SC = NAMIND ('X1SC')
      NAX2DF = NAMIND ('X2DF')
      NAX3EC = NAMIND ('X3EC')
      NAX3EW = NAMIND ('X3EW')
      NAX3HC = NAMIND ('X3HC')
      NAX3IT = NAMIND ('X3IT')
      NAX3L2 = NAMIND ('X3L2')
      NAX3LU = NAMIND ('X3LU')
      NAX3TM = NAMIND ('X3TM')
      NAX3TO = NAMIND ('X3TO')
      NAX3TP = NAMIND ('X3TP')
      NAX3X3 = NAMIND ('X3X3')
      NAXTBN = NAMIND ('XTBN')
      NAXTCN = NAMIND ('XTCN')
      NAXTEB = NAMIND ('XTEB')
      NAXTOP = NAMIND ('XTOP')
      NAXTRB = NAMIND ('XTRB')
      NAYV0V = NAMIND ('YV0V')
      NAZPFR = NAMIND ('ZPFR')
      END
