      CHARACTER  SCHEME*2
      CHARACTER  VERSN*6
      CHARACTER  CNAM*13
      PARAMETER  (EVIS   =  0.0      )
      PARAMETER  (SCHEME='E')
      PARAMETER  (VERSN ='JADE')
c     PARAMETER  (VERSN ='DURHAM')
      PARAMETER  (CNAM   = 'AXESJETS')
      COMMON / COM1 / IG,ID,J1,JJ1,J2,JJ2,ILOOP1,ITQUA,IOPVA1,
     >                ITKMAX
      COMMON / COM2 / ENERC,PNERC,YCUT,EIGNAM
      COMMON / COM3 / NGEN,NKCOUT,NKPRIS,NKTRUS,NB1,NC1,NUDS1,NDAT1,
     >                NB2,NC2,NUDS2,NDAT2,NEVTYPE,NERR(9,0:3),NJET,
     >                IFLAG4,IFLAG5
      COMMON / COM4 / VTOT(25)
      COMMON / IVAR / KK2,KK3,KK,KK1,NLEPH
      COMMON / RVAR / XMINV(11),SDIR(11),EMINV(11),PCL(4),PCT(4),
     >                XJTLJET,PTJETS,SPT,PTLJET,YMT,REVIS,XJFM,
     >                YMJET,SMJETS,XMKK1,ENU,FRACIT,FRACC,XMKK3,XMKKC,
     >                SPTC,XMKKI,FRACI,ENUCL,HJ1,HJ2,HJ3,HJ4,HJ5,POIDS
