*CD adbrjj
      INTEGER JADBPN,JADBFR,JADBBP,JADBVD,JADBIT,JADBTP,JADBEC,JADBLC,
     +          JADBSA,JADBHC,JADBMU,JADBTR,JADBGE,JADBDB,JADBSI,JADBBE,
     +          LADBRA
      PARAMETER(JADBPN=1,JADBFR=2,JADBBP=3,JADBVD=4,JADBIT=5,JADBTP=6,
     +          JADBEC=7,JADBLC=8,JADBSA=9,JADBHC=10,JADBMU=11,
     +          JADBTR=12,JADBGE=13,JADBDB=14,JADBSI=15,JADBBE=16,
     +          LADBRA=16)
