*CD ajobjj
      INTEGER JAJOBM,JAJORM,JAJOGI,JAJOSO,JAJOSD,JAJOGC,JAJOJD,JAJOJT,
     +          JAJOGV,JAJOAV,JAJOFT,JAJOFS,JAJOFC,JAJODV,JAJODD,JAJOTV,
     +          JAJOCV,JAJOGN,LAJOBA
      PARAMETER(JAJOBM=1,JAJORM=2,JAJOGI=3,JAJOSO=4,JAJOSD=5,JAJOGC=6,
     +          JAJOJD=7,JAJOJT=8,JAJOGV=9,JAJOAV=10,JAJOFT=11,
     +          JAJOFS=12,JAJOFC=13,JAJODV=14,JAJODD=15,JAJOTV=16,
     +          JAJOCV=17,JAJOGN=18,LAJOBA=18)
