*CD alcbjj
      INTEGER JALCMI,JALCMV,JALCMT,JALCMM,JALCD0,JALCZ0,JALCC2,JALCKX,
     +          JALCKY,JALCKZ,JALCNB,JALCNU,JALCNL,JALCSC,LALCBA
      PARAMETER(JALCMI=1,JALCMV=2,JALCMT=3,JALCMM=4,JALCD0=5,JALCZ0=6,
     +          JALCC2=7,JALCKX=8,JALCKY=9,JALCKZ=10,JALCNB=11,
     +          JALCNU=12,JALCNL=13,JALCSC=14,LALCBA=17)
