*CD allrjj
      INTEGER JALLYE,JALLXS,JALLYS,JALLZS,JALLXR,JALLYR,JALLZR,JALLRA,
     +          JALLM1,JALLS1,JALLM2,JALLS2,LALLRA
      PARAMETER(JALLYE=1,JALLXS=2,JALLYS=3,JALLZS=4,JALLXR=5,JALLYR=6,
     +          JALLZR=7,JALLRA=8,JALLM1=9,JALLS1=10,JALLM2=11,
     +          JALLS2=12,LALLRA=12)
