*CD alrpjj
      INTEGER JALRPN,JALRWE,JALRER,JALRXS,JALRYS,JALRZS,JALRXR,JALRYR,
     +          JALRF1,JALRM1,JALRS1,JALRM2,JALRS2,LALRPA
      PARAMETER(JALRPN=1,JALRWE=2,JALRER=3,JALRXS=4,JALRYS=5,JALRZS=6,
     +          JALRXR=7,JALRYR=8,JALRF1=9,JALRM1=10,JALRS1=11,
     +          JALRM2=12,JALRS2=13,LALRPA=13)
