*CD bcarjj
      INTEGER JBCAVS,JBCAVI,JBCALA,JBCATY,JBCALO,JBCAMN,JBCAIN,JBCAPD,
     +          JBCACO,JBCAON,JBCARD,JBCART,JBCACM,JBCADN,JBCAWN,JBCARF,
     +          LBCARA
      PARAMETER(JBCAVS=1,JBCAVI=3,JBCALA=5,JBCATY=7,JBCALO=10,JBCAMN=13,
     +          JBCAIN=15,JBCAPD=18,JBCACO=20,JBCAON=21,JBCARD=24,
     +          JBCART=26,JBCACM=28,JBCADN=43,JBCAWN=48,JBCARF=49,
     +          LBCARA=49)
