*CD bcpdjj
      INTEGER JBCPPA,JBCPAA,JBCPSA,JBCPMA,JBCPDA,JBCPPS,JBCPAS,JBCPSS,
     +          JBCPMS,JBCPDS,LBCPDA
      PARAMETER(JBCPPA=1,JBCPAA=5,JBCPSA=9,JBCPMA=393,JBCPDA=397,
     +          JBCPPS=401,JBCPAS=405,JBCPSS=409,JBCPMS=793,JBCPDS=797,
     +          LBCPDA=800)
