*CD bhabjj
      INTEGER JBHAID,JBHAVR,JBHAME,JBHAQF,JBHAEH,JBHAEL,JBHADP,JBHAXL,
     +          JBHAYL,JBHACL,JBHACH,JBHATL,JBHATH,JBHACS,JBHAER,JBHAGE,
     +          JBHAES,JBHAEG,LBHABA
      PARAMETER(JBHAID=1,JBHAVR=2,JBHAME=4,JBHAQF=5,JBHAEH=6,JBHAEL=7,
     +          JBHADP=8,JBHAXL=9,JBHAYL=11,JBHACL=13,JBHACH=15,
     +          JBHATL=17,JBHATH=19,JBHACS=21,JBHAER=22,JBHAGE=23,
     +          JBHAES=24,JBHAEG=25,LBHABA=25)
