*CD bhz0jj
      INTEGER JBHZID,JBHZVR,JBHZME,JBHZQF,JBHZEH,JBHZEL,JBHZDP,JBHZXL,
     +          JBHZYL,JBHZCL,JBHZCH,JBHZTL,JBHZTH,JBHZCS,JBHZER,JBHZGE,
     +          JBHZES,JBHZEG,LBHZ0A
      PARAMETER(JBHZID=1,JBHZVR=2,JBHZME=4,JBHZQF=5,JBHZEH=6,JBHZEL=7,
     +          JBHZDP=8,JBHZXL=9,JBHZYL=11,JBHZCL=13,JBHZCH=15,
     +          JBHZTL=17,JBHZTH=19,JBHZCS=21,JBHZER=22,JBHZGE=23,
