*CD blasjj
      INTEGER JBLALO,JBLAOU,JBLAMA,JBLARQ,JBLALE,JBLALU,JBLALF,JBLAP4,
     +          JBLAD4,JBLAMI,JBLANA,LBLASA
      PARAMETER(JBLALO=1,JBLAOU=2,JBLAMA=3,JBLARQ=4,JBLALE=5,JBLALU=6,
     +          JBLALF=7,JBLAP4=8,JBLAD4=9,JBLAMI=10,JBLANA=11,
     +          LBLASA=11)
