*CD blprjj
      INTEGER JBLPNT,JBLPFR,JBLPLR,JBLPFD,JBLPLD,JBLPRL,JBLPTQ,JBLPJV,
     +          LBLPRA
      PARAMETER(JBLPNT=1,JBLPFR=2,JBLPLR=3,JBLPFD=4,JBLPLD=5,JBLPRL=6,
     +          JBLPTQ=7,JBLPJV=8,LBLPRA=8)
