*CD blumjj
      INTEGER JBLUTI,JBLUNI,JBLUBT,JBLUAT,JBLUBI,JBLUAI,JBLUUI,JBLUUA,
     +          JBLUBB,JBLUUB,JBLULB,JBLUHV,JBLUL1,JBLUL2,JBLUNS,JBLUC1,
     +          JBLUC2,JBLURA,JBLURC,JBLUR1,JBLUR2,JBLUN1,JBLUN2,JBLURV,
     +          LBLUMA
      PARAMETER(JBLUTI=1,JBLUNI=2,JBLUBT=3,JBLUAT=4,JBLUBI=5,JBLUAI=6,
     +          JBLUUI=7,JBLUUA=8,JBLUBB=9,JBLUUB=17,JBLULB=25,
     +          JBLUHV=33,JBLUL1=34,JBLUL2=35,JBLUNS=36,JBLUC1=40,
     +          JBLUC2=41,JBLURA=42,JBLURC=46,JBLUR1=50,JBLUR2=51,
     +          JBLUN1=52,JBLUN2=53,JBLURV=54,LBLUMA=66)
