*CD bmcljj
      INTEGER JBMCKG,JBMCLA,JBMCTO,JBMCKI,JBMCRA,JBMCPO,JBMCDS,JBMCMI,
     +          JBMCCR,JBMCNA,JBMCOT,LBMCLA
      PARAMETER(JBMCKG=1,JBMCLA=2,JBMCTO=3,JBMCKI=4,JBMCRA=5,JBMCPO=6,
     +          JBMCDS=7,JBMCMI=8,JBMCCR=9,JBMCNA=10,JBMCOT=11,
     +          LBMCLA=11)
