*CD bomejj
      INTEGER JBOMXI,JBOMXP,JBOMYI,JBOMYP,JBOMBU,JBOMIA,JBOMIB,JBOMR1,
     +          JBOMR2,JBOMR3,JBOMR4,JBOMER,LBOMEA
      PARAMETER(JBOMXI=1,JBOMXP=2,JBOMYI=3,JBOMYP=4,JBOMBU=5,JBOMIA=6,
     +          JBOMIB=7,JBOMR1=8,JBOMR2=9,JBOMR3=10,JBOMR4=11,
     +          JBOMER=12,LBOMEA=12)
