*CD bompjj
      INTEGER JBOMXA,JBOMYA,JBOMSA,JBOMCA,JBOMXB,JBOMYB,JBOMSB,JBOMCB,
     +          JBOMBI,JBOMPU,LBOMPA
      PARAMETER(JBOMXA=1,JBOMYA=2,JBOMSA=3,JBOMCA=4,JBOMXB=5,JBOMYB=6,
     +          JBOMSB=7,JBOMCB=8,JBOMBI=9,JBOMPU=10,LBOMPA=10)
