*CD bperjj
      INTEGER JBPEPA,JBPEPN,JBPELP,JBPEFE,JBPELE,JBPEFR,JBPELR,JBPEFD,
     +          JBPELD,LBPERA
      PARAMETER(JBPEPA=1,JBPEPN=11,JBPELP=12,JBPEFE=13,JBPELE=14,
     +          JBPEFR=15,JBPELR=16,JBPEFD=17,JBPELD=18,LBPERA=18)
