*CD bpg1jj
      INTEGER JBPGID,JBPGVR,JBPGNA,JBPGRI,JBPGRO,JBPGZM,JBPGZW,JBPGNM,
     +          LBPG1A
      PARAMETER(JBPGID=1,JBPGVR=2,JBPGNA=4,JBPGRI=8,JBPGRO=9,JBPGZM=10,
     +          JBPGZW=11,JBPGNM=12,LBPG1A=12)
