*CD bprojj
      INTEGER JBPRPN,JBPROP,JBPRNN,JBPRVN,JBPRCV,JBPRAV,JBPRDN,JBPRDD,
     +          JBPRNI,LBPROA
      PARAMETER(JBPRPN=1,JBPROP=2,JBPRNN=4,JBPRVN=6,JBPRCV=7,JBPRAV=8,
     +          JBPRDN=9,JBPRDD=10,JBPRNI=11,LBPROA=11)
