*CD brucjj
      INTEGER JBRUVS,JBRUTT,JBRULF,JBRURN,JBRUMC,JBRUWD,JBRUWH,JBRUEV,
     +          JBRUEF,JBRUTE,JBRUNE,JBRUFL,JBRUDC,JBRUNZ,JBRUNB,JBRULD,
     +          JBRUCS,JBRUBR,JBRULU,JBRUBK,JBRUBT,JBRUVL,LBRUCA
      PARAMETER(JBRUVS=1,JBRUTT=3,JBRULF=5,JBRURN=6,JBRUMC=7,JBRUWD=8,
     +          JBRUWH=9,JBRUEV=10,JBRUEF=11,JBRUTE=12,JBRUNE=13,
     +          JBRUFL=14,JBRUDC=15,JBRUNZ=16,JBRUNB=17,JBRULD=18,
     +          JBRUCS=19,JBRUBR=20,JBRULU=21,JBRUBK=22,JBRUBT=23,
     +          JBRUVL=24,LBRUCA=24)
