*CD bscljj
      INTEGER JBSCKG,JBSCLA,JBSCTO,JBSCKI,JBSCRA,JBSCPO,JBSCDS,JBSCMI,
     +          JBSCCR,JBSCNA,JBSCOT,LBSCLA
      PARAMETER(JBSCKG=1,JBSCLA=2,JBSCTO=3,JBSCKI=4,JBSCRA=5,JBSCPO=6,
     +          JBSCDS=7,JBSCMI=8,JBSCCR=9,JBSCNA=10,JBSCOT=11,
     +          LBSCLA=11)
