*CD bsetjj
      INTEGER JBSEAD,JBSEAU,JBSEFR,JBSEFE,JBSELR,JBSELE,JBSEWD,JBSEWH,
     +          JBSEND,JBSEBN,JBSEDF,JBSEBA,JBSEBP,JBSEBR,JBSEBS,JBSEBT,
     +          LBSETA
      PARAMETER(JBSEAD=1,JBSEAU=6,JBSEFR=8,JBSEFE=9,JBSELR=10,JBSELE=11,
     +          JBSEWD=12,JBSEWH=13,JBSEND=14,JBSEBN=15,JBSEDF=16,
     +          JBSEBA=17,JBSEBP=18,JBSEBR=19,JBSEBS=20,JBSEBT=21,
     +          LBSETA=21)
