*CD btmejj
      INTEGER JBTMTN,JBTMMA,JBTMFD,JBTMMS,JBTMDE,JBTMEP,JBTMST,JBTMVO,
     +          JBTMGP,JBTMFL,LBTMEA
      PARAMETER(JBTMTN=1,JBTMMA=5,JBTMFD=9,JBTMMS=10,JBTMDE=11,
     +          JBTMEP=12,JBTMST=13,JBTMVO=14,JBTMGP=15,JBTMFL=16,
     +          LBTMEA=16)
