*CD capajj
      INTEGER JCAPST,JCAPPT,JCAPTE,JCAPTX,JCAPTL,JCAPEM,JCAPEA,JCAPEB,
     +          JCAPA1,JCAPER,JCAPEF,JCAPED,JCAPEZ,JCAPHE,JCAPHA,JCAPHB,
     +          JCAPHD,JCAPHP,JCAPGA,JCAPSX,JCAPSA,JCAPNA,LCAPAA
      PARAMETER(JCAPST=1,JCAPPT=2,JCAPTE=3,JCAPTX=4,JCAPTL=5,JCAPEM=6,
     +          JCAPEA=7,JCAPEB=8,JCAPA1=9,JCAPER=10,JCAPEF=11,
     +          JCAPED=12,JCAPEZ=13,JCAPHE=14,JCAPHA=15,JCAPHB=16,
     +          JCAPHD=17,JCAPHP=18,JCAPGA=19,JCAPSX=20,JCAPSA=21,
     +          JCAPNA=22,LCAPAA=22)
