*CD cog1jj
      INTEGER JCOGID,JCOGVR,JCOGNA,JCOGRI,JCOGDR,JCOGZM,JCOGZW,JCOGNM,
     +          LCOG1A
      PARAMETER(JCOGID=1,JCOGVR=2,JCOGNA=4,JCOGRI=8,JCOGDR=9,JCOGZM=10,
     +          JCOGZW=11,JCOGNM=12,LCOG1A=12)
