*CD crftjj
      INTEGER JCRFIR,JCRFTL,JCRFP0,JCRFD0,JCRFZ0,JCRFRP,JCRFEM,JCRFNL,
     +          LCRFTA
      PARAMETER(JCRFIR=1,JCRFTL=2,JCRFP0=3,JCRFD0=4,JCRFZ0=5,JCRFRP=6,
     +          JCRFEM=7,JCRFNL=22,LCRFTA=30)
