*CD denfjj
      INTEGER JDENPX,JDENPY,JDENPZ,JDENE0,JDENWE,JDENTY,JDENPC,JDENDT,
     +          JDENDJ,LDENFA
      PARAMETER(JDENPX=1,JDENPY=2,JDENPZ=3,JDENE0=4,JDENWE=5,JDENTY=6,
     +          JDENPC=7,JDENDT=8,JDENDJ=9,LDENFA=9)
