*CD devtjj
      INTEGER JDEVLE,JDEVWT,JDEVNX,JDEVNV,JDEVWR,JDEVWA,JDEVWB,JDEVPR,
     +          JDEVPA,JDEVPB,JDEVLA,JDEVLB,JDEVHR,JDEVHA,JDEVHB,LDEVTA
      PARAMETER(JDEVLE=1,JDEVWT=2,JDEVNX=3,JDEVNV=4,JDEVWR=5,JDEVWA=6,
     +          JDEVWB=7,JDEVPR=8,JDEVPA=9,JDEVPB=10,JDEVLA=11,
     +          JDEVLB=12,JDEVHR=13,JDEVHA=14,JDEVHB=15,LDEVTA=15)
