*CD dgacjj
      INTEGER JDGAEC,JDGATC,JDGAPC,JDGAR1,JDGAR2,JDGAF4,JDGADM,JDGAST,
     +          JDGAQU,JDGAQ1,JDGAQ2,JDGAM1,JDGAM2,JDGAMA,JDGAER,JDGATR,
     +          JDGAPR,JDGAEF,JDGAGC,JDGAZS,JDGAPL,JDGAPF,JDGAPN,JDGAFA,
     +          JDGAPE,LDGACA
      PARAMETER(JDGAEC=1,JDGATC=2,JDGAPC=3,JDGAR1=4,JDGAR2=5,JDGAF4=6,
     +          JDGADM=7,JDGAST=8,JDGAQU=9,JDGAQ1=10,JDGAQ2=11,
     +          JDGAM1=12,JDGAM2=13,JDGAMA=14,JDGAER=15,JDGATR=16,
     +          JDGAPR=17,JDGAEF=18,JDGAGC=19,JDGAZS=20,JDGAPL=21,
     +          JDGAPF=22,JDGAPN=23,JDGAFA=24,JDGAPE=25,LDGACA=25)
