*CD dgidjj
      INTEGER JDGIIF,JDGIDE,JDGICM,JDGIM1,JDGIM2,JDGIM3,JDGICE,JDGITH,
     +          JDGIPH,JDGIPE,LDGIDA
      PARAMETER(JDGIIF=1,JDGIDE=2,JDGICM=3,JDGIM1=4,JDGIM2=5,JDGIM3=6,
     +          JDGICE=7,JDGITH=8,JDGIPH=9,JDGIPE=10,LDGIDA=10)
