*CD dgpcjj
      INTEGER JDGPEC,JDGPTC,JDGPPC,JDGPR1,JDGPR2,JDGPF4,JDGPDM,JDGPST,
     +          JDGPQU,JDGPQ1,JDGPQ2,JDGPM1,JDGPM2,JDGPMA,JDGPER,JDGPTR,
     +          JDGPPR,JDGPPE,LDGPCA
      PARAMETER(JDGPEC=1,JDGPTC=2,JDGPPC=3,JDGPR1=4,JDGPR2=5,JDGPF4=6,
     +          JDGPDM=7,JDGPST=8,JDGPQU=9,JDGPQ1=10,JDGPQ2=11,
     +          JDGPM1=12,JDGPM2=13,JDGPMA=14,JDGPER=15,JDGPTR=16,
     +          JDGPPR=17,JDGPPE=18,LDGPCA=18)
