*CD dheajj
      INTEGER JDHEFP,JDHENX,JDHENP,JDHENM,JDHENV,JDHENJ,JDHEEC,JDHEEL,
     +          JDHEPF,JDHETH,JDHEPH,JDHEEF,JDHEET,JDHET1,JDHEP1,JDHET2,
     +          JDHEP2,JDHEE1,JDHEE2,JDHEE3,JDHERS,JDHEWT,LDHEAA
      PARAMETER(JDHEFP=1,JDHENX=2,JDHENP=3,JDHENM=4,JDHENV=5,JDHENJ=6,
     +          JDHEEC=7,JDHEEL=8,JDHEPF=9,JDHETH=10,JDHEPH=11,
     +          JDHEEF=12,JDHEET=13,JDHET1=14,JDHEP1=15,JDHET2=16,
     +          JDHEP2=17,JDHEE1=18,JDHEE2=19,JDHEE3=20,JDHERS=21,
     +          JDHEWT=22,LDHEAA=22)
