*CD dknkjj
      INTEGER JDKNIT,JDKNOT,JDKNVX,JDKNPK,JDKNPT,JDKNPL,JDKNC2,JDKNBH,
     +          LDKNKA
      PARAMETER(JDKNIT=1,JDKNOT=2,JDKNVX=3,JDKNPK=6,JDKNPT=7,JDKNPL=8,
     +          JDKNC2=9,JDKNBH=10,LDKNKA=10)
