*CD dmltjj
      INTEGER JDMLFL,JDMLPO,JDMLCH,JDMLSP,JDMLLE,JDMLME,JDMLKT,JDMLFR,
     +          LDMLTA
      PARAMETER(JDMLFL=1,JDMLPO=2,JDMLCH=3,JDMLSP=4,JDMLLE=5,JDMLME=6,
     +          JDMLKT=7,JDMLFR=8,LDMLTA=8)
