*CD dneujj
      INTEGER JDNENA,JDNEE0,JDNETH,JDNEPH,JDNER1,JDNER2,JDNEPC,JDNEDE,
     +          LDNEUA
      PARAMETER(JDNENA=1,JDNEE0=2,JDNETH=3,JDNEPH=4,JDNER1=5,JDNER2=6,
     +          JDNEPC=7,JDNEDE=8,LDNEUA=8)
