*CD dsicjj
      INTEGER JDSIIS,JDSIEC,JDSICR,JDSICP,JDSIZC,JDSIXI,JDSIYI,JDSINP,
     +          JDSIND,LDSICA
      PARAMETER(JDSIIS=1,JDSIEC=2,JDSICR=3,JDSICP=4,JDSIZC=5,JDSIXI=6,
     +          JDSIYI=7,JDSINP=8,JDSIND=9,LDSICA=9)
