*CD dtmcjj
      INTEGER JDTMPX,JDTMPY,JDTMPZ,JDTMMA,JDTMPA,JDTMOV,JDTMEV,JDTMHC,
     +          LDTMCA
      PARAMETER(JDTMPX=1,JDTMPY=2,JDTMPZ=3,JDTMMA=4,JDTMPA=5,JDTMOV=6,
     +          JDTMEV=7,JDTMHC=8,LDTMCA=8)
