*CD dtrajj
      INTEGER JDTRCH,JDTRP0,JDTRTH,JDTRPH,JDTRD0,JDTRZ0,JDTRER,JDTRTF,
     +          JDTRHO,JDTRHM,JDTRVB,JDTRQF,JDTREA,JDTRVI,LDTRAA
      PARAMETER(JDTRCH=1,JDTRP0=2,JDTRTH=3,JDTRPH=4,JDTRD0=5,JDTRZ0=6,
     +          JDTRER=7,JDTRTF=12,JDTRHO=13,JDTRHM=14,JDTRVB=15,
     +          JDTRQF=16,JDTREA=17,JDTRVI=27,LDTRAA=27)
