*CD ealijj
      INTEGER JEALID,JEALAM,JEALTD,JEALMP,JEALPL,JEALSE,JEALCL,JEALRW,
     +          JEALLP,LEALIA
      PARAMETER(JEALID=1,JEALAM=2,JEALTD=18,JEALMP=34,JEALPL=46,
     +          JEALSE=54,JEALCL=58,JEALRW=66,JEALLP=82,LEALIA=113)
