*CD ecgnjj
      INTEGER JECGID,JECGLS,JECGLP,JECGSC,JECGSY,JECGMD,JECGPL,JECGST,
     +          JECGCL,JECGRG,JECGSS,JECGRW,JECGXW,JECGEC,JECGXG,JECGNP,
     +          JECGPR,JECGBL,JECGBO,JECGEI,JECGEW,JECGEL,JECGGP,JECGWS,
     +          JECGAP,JECGAL,JECGDM,JECGTI,JECGC1,JECGC2,JECGM1,JECGM2,
     +          JECGR1,JECGR2,LECGNA
      PARAMETER(JECGID=1,JECGLS=2,JECGLP=3,JECGSC=4,JECGSY=5,JECGMD=6,
     +          JECGPL=7,JECGST=8,JECGCL=9,JECGRG=10,JECGSS=11,
     +          JECGRW=12,JECGXW=13,JECGEC=14,JECGXG=15,JECGNP=16,
     +          JECGPR=17,JECGBL=18,JECGBO=19,JECGEI=20,JECGEW=21,
     +          JECGEL=22,JECGGP=23,JECGWS=24,JECGAP=25,JECGAL=26,
     +          JECGDM=27,JECGTI=43,JECGC1=44,JECGC2=45,JECGM1=46,
     +          JECGM2=47,JECGR1=48,JECGR2=49,LECGNA=49)
