*CD ecnsjj
      INTEGER JECNID,JECNVR,JECNEH,JECNEL,JECNCT,JECNSS,JECNSM,JECNPM,
     +          JECNEP,JECNER,JECNEI,JECNPR,JECNEM,JECNEB,JECNME,JECNR1,
     +          JECNR2,JECNR3,JECNRG,JECNCF,LECNSA
      PARAMETER(JECNID=1,JECNVR=2,JECNEH=4,JECNEL=5,JECNCT=6,JECNSS=7,
     +          JECNSM=8,JECNPM=9,JECNEP=10,JECNER=13,JECNEI=16,
     +          JECNPR=17,JECNEM=18,JECNEB=19,JECNME=21,JECNR1=22,
     +          JECNR2=23,JECNR3=24,JECNRG=25,JECNCF=26,LECNSA=26)
