*CD ecobjj
      INTEGER JECOEN,JECOEG,JECORC,JECOIT,JECOCV,JECONH,JECONT,JECOPF,
     +          JECOEB,JECOEH,JECOET,LECOBA
      PARAMETER(JECOEN=1,JECOEG=4,JECORC=5,JECOIT=6,JECOCV=8,JECONH=11,
     +          JECONT=12,JECOPF=13,JECOEB=14,JECOEH=15,JECOET=16,
     +          LECOBA=16)
