*CD edstjj
      INTEGER JEDSTJ,JEDSFI,JEDSDK,JEDSME,JEDSSC,JEDSIO,JEDSDI,JEDSER,
     +          JEDSED,JEDSES,LEDSTA
      PARAMETER(JEDSTJ=1,JEDSFI=2,JEDSDK=3,JEDSME=4,JEDSSC=5,JEDSIO=6,
     +          JEDSDI=7,JEDSER=8,JEDSED=9,JEDSES=10,LEDSTA=10)
