*CD egazjj
      INTEGER JEGATM,JEGATX,JEGAC1,JEGAC2,JEGAC3,JEGAC4,JEGAC5,JEGAC6,
     +          LEGAZA
      PARAMETER(JEGATM=1,JEGATX=2,JEGAC1=3,JEGAC2=4,JEGAC3=5,JEGAC4=6,
     +          JEGAC5=7,JEGAC6=8,LEGAZA=8)
