*CD ehypjj
      INTEGER JEHYTY,JEHYEN,JEHYRA,JEHYTH,JEHYPH,JEHYEC,JEHYEH,JEHYEP,
     +          LEHYPA
      PARAMETER(JEHYTY=1,JEHYEN=2,JEHYRA=3,JEHYTH=4,JEHYPH=5,JEHYEC=6,
     +          JEHYEH=7,JEHYEP=8,LEHYPA=8)
