*CD eibrjj
      INTEGER JEIBEN,JEIBTE,JEIBPH,JEIBPX,JEIBPY,JEIBPZ,JEIBEI,JEIBPE,
     +          LEIBRA
      PARAMETER(JEIBEN=1,JEIBTE=2,JEIBPH=3,JEIBPX=4,JEIBPY=5,JEIBPZ=6,
     +          JEIBEI=7,JEIBPE=8,LEIBRA=8)
