*CD ematjj
      INTEGER JEMAID,JEMAMI,JEMAMN,JEMAAW,JEMAAN,JEMADE,JEMARL,JEMAAL,
     +          LEMATA
      PARAMETER(JEMAID=1,JEMAMI=2,JEMAMN=3,JEMAAW=7,JEMAAN=8,JEMADE=9,
     +          JEMARL=10,JEMAAL=11,LEMATA=11)
