*CD emirjj
      INTEGER JEMIID,JEMIVR,JEMINM,JEMITP,JEMITE,JEMITF,JEMIAP,JEMIAE,
     +          JEMIAF,JEMITN,JEMIEP,LEMIRA
      PARAMETER(JEMIID=1,JEMIVR=2,JEMINM=4,JEMITP=6,JEMITE=9,JEMITF=12,
     +          JEMIAP=13,JEMIAE=16,JEMIAF=19,JEMITN=20,JEMIEP=21,
     +          LEMIRA=21)
