*CD eparjj
      INTEGER JEPATY,JEPATH,JEPAPH,JEPADT,JEPADP,JEPAIT,JEPAEN,JEPAEH,
     +          JEPAEP,LEPARA
      PARAMETER(JEPATY=1,JEPATH=2,JEPAPH=3,JEPADT=4,JEPADP=5,JEPAIT=6,
     +          JEPAEN=8,JEPAEH=9,JEPAEP=10,LEPARA=10)
