*CD escojj
      INTEGER JESCID,JESCNM,JESCLI,JESCMD,JESCCF,JESCRF,JESCRL,JESCEC,
     +          JESCEQ,JESCET,JESCFR,JESCLS,JESCS1,JESCS2,LESCOA
      PARAMETER(JESCID=1,JESCNM=2,JESCLI=6,JESCMD=10,JESCCF=18,
     +          JESCRF=19,JESCRL=20,JESCEC=21,JESCEQ=22,JESCET=23,
     +          JESCFR=24,JESCLS=25,JESCS1=26,JESCS2=27,LESCOA=27)
