*CD estojj
      INTEGER JESTXI,JESTXO,JESTIX,JESTOX,JESTSX,JESTYI,JESTYO,JESTIY,
     +          JESTOY,JESTSY,JESTZI,JESTZO,JESTIZ,JESTOZ,JESTSZ,JESTSN,
     +          JESTMN,JESTOF,LESTOA
      PARAMETER(JESTXI=1,JESTXO=5,JESTIX=9,JESTOX=10,JESTSX=11,
     +          JESTYI=12,JESTYO=16,JESTIY=20,JESTOY=21,JESTSY=22,
     +          JESTZI=23,JESTZO=27,JESTIZ=31,JESTOZ=32,JESTSZ=33,
     +          JESTSN=34,JESTMN=35,JESTOF=36,LESTOA=36)
