*CD etyvjj
      INTEGER JETYID,JETYFC,JETYCR,JETYNG,JETYFT,JETYFR,JETYFF,JETYLT,
     +          JETYLR,JETYLF,LETYVA
      PARAMETER(JETYID=1,JETYFC=2,JETYCR=3,JETYNG=4,JETYFT=5,JETYFR=6,
     +          JETYFF=7,JETYLT=8,JETYLR=9,JETYLF=10,LETYVA=10)
