*CD fkaljj
      INTEGER JFKABR,JFKABL,JFKAVL,JFKAIR,JFKAIL,JFKAIG,JFKAIT,JFKATL,
     +          JFKATG,JFKAZI,JFKAZO,JFKAII,JFKAIO,JFKAOI,JFKAOO,JFKASI,
     +          JFKASO,LFKALA
      PARAMETER(JFKABR=1,JFKABL=3,JFKAVL=5,JFKAIR=7,JFKAIL=8,JFKAIG=9,
     +          JFKAIT=10,JFKATL=11,JFKATG=12,JFKAZI=13,JFKAZO=15,
     +          JFKAII=17,JFKAIO=19,JFKAOI=21,JFKAOO=23,JFKASI=25,
     +          JFKASO=27,LFKALA=28)
