*CD fkinjj
      INTEGER JFKIPX,JFKIPY,JFKIPZ,JFKIMA,JFKIPA,JFKIOV,JFKIEV,JFKIHC,
     +          LFKINA
      PARAMETER(JFKIPX=1,JFKIPY=2,JFKIPZ=3,JFKIMA=4,JFKIPA=5,JFKIOV=6,
     +          JFKIEV=7,JFKIHC=8,LFKINA=8)
