*CD fscojj
      INTEGER JFSCEN,JFSCIH,JFSCE1,JFSCE2,JFSCE3,JFSCH1,JFSCH2,JFSCTH,
     +          JFSCPH,JFSCIP,LFSCOA
      PARAMETER(JFSCEN=1,JFSCIH=2,JFSCE1=3,JFSCE2=4,JFSCE3=5,JFSCH1=6,
     +          JFSCH2=7,JFSCTH=8,JFSCPH=9,JFSCIP=10,LFSCOA=10)
