*CD fstrjj
      INTEGER JFSTPX,JFSTPY,JFSTPZ,JFSTIQ,JFSTIH,JFSTCH,JFSTNH,JFSTD0,
     +          JFSTPH,JFSTZ0,JFSTAV,JFSTS2,JFSTNW,JFSTM2,JFSTNM,JFSTNC,
     +          JFSTMC,JFSTIC,LFSTRA
      PARAMETER(JFSTPX=1,JFSTPY=2,JFSTPZ=3,JFSTIQ=4,JFSTIH=5,JFSTCH=6,
     +          JFSTNH=7,JFSTD0=8,JFSTPH=9,JFSTZ0=10,JFSTAV=11,
     +          JFSTS2=12,JFSTNW=13,JFSTM2=14,JFSTNM=15,JFSTNC=16,
     +          JFSTMC=17,JFSTIC=18,LFSTRA=18)
