*CD fverjj
      INTEGER JFVEVX,JFVEVY,JFVEVZ,JFVETO,JFVEIP,JFVEIS,JFVENS,JFVEVN,
     +          JFVEVM,LFVERA
      PARAMETER(JFVEVX=1,JFVEVY=2,JFVEVZ=3,JFVETO=4,JFVEIP=5,JFVEIS=6,
     +          JFVENS=7,JFVEVN=8,JFVEVM=9,LFVERA=9)
