*CD hbarjj
      INTEGER JHBAID,JHBAVR,JHBASN,JHBANS,JHBARP,JHBARR,JHBANF,JHBANB,
     +          JHBANL,LHBARA
      PARAMETER(JHBAID=1,JHBAVR=2,JHBASN=4,JHBANS=5,JHBARP=6,JHBARR=9,
     +          JHBANF=12,JHBANB=13,JHBANL=14,LHBARA=14)
