*CD hcaljj
      INTEGER JHCAID,JHCAVR,JHCACN,JHCANS,JHCANT,JHCANP,JHCANR,JHCAIT,
     +          JHCAIH,JHCAGA,JHCATF,JHCATL,LHCALA
      PARAMETER(JHCAID=1,JHCAVR=2,JHCACN=4,JHCANS=5,JHCANT=6,JHCANP=7,
     +          JHCANR=8,JHCAIT=9,JHCAIH=10,JHCAGA=11,JHCATF=12,
     +          JHCATL=13,LHCALA=13)
