*CD hcosjj
      INTEGER JHCOTA,JHCOTS,JHCOOL,JHCOMT,JHCOEA,JHCOEF,JHCOEB,JHCOCF,
     +          JHCOIF,JHCOMA,LHCOSA
      PARAMETER(JHCOTA=1,JHCOTS=2,JHCOOL=3,JHCOMT=4,JHCOEA=5,JHCOEF=6,
     +          JHCOEB=7,JHCOCF=8,JHCOIF=9,JHCOMA=10,LHCOSA=10)
