*CD hcsejj
      INTEGER JHCSTN,JHCSLN,JHCSMN,JHCSPN,JHCSTA,JHCSTX,JHCSTY,JHCSPW,
     +          JHCSXA,JHCSYA,JHCSZA,JHCSTR,JHCSHT,JHCSFT,JHCSFS,LHCSEA
      PARAMETER(JHCSTN=1,JHCSLN=2,JHCSMN=3,JHCSPN=4,JHCSTA=5,JHCSTX=6,
     +          JHCSTY=7,JHCSPW=8,JHCSXA=9,JHCSYA=10,JHCSZA=11,
     +          JHCSTR=12,JHCSHT=13,JHCSFT=14,JHCSFS=15,LHCSEA=15)
