*CD hemtjj
      INTEGER JHEMID,JHEMVR,JHEMMT,JHEMXM,JHEMYM,JHEMNI,JHEMNO,JHEMHS,
     +          LHEMTA
      PARAMETER(JHEMID=1,JHEMVR=2,JHEMMT=4,JHEMXM=5,JHEMYM=13,JHEMNI=21,
     +          JHEMNO=22,JHEMHS=23,LHEMTA=23)
