*CD hendjj
      INTEGER JHENID,JHENVR,JHENSN,JHENNS,JHENRP,JHENRR,JHENSG,JHENNF,
     +          JHENNB,JHENNW,JHENNL,LHENDA
      PARAMETER(JHENID=1,JHENVR=2,JHENSN=4,JHENNS=5,JHENRP=6,JHENRR=9,
     +          JHENSG=12,JHENNF=13,JHENNB=14,JHENNW=15,JHENNL=16,
     +          LHENDA=17)
