*CD hetcjj
      INTEGER JHETID,JHETVR,JHETNT,JHETEW,JHETDW,JHETTG,JHETE2,JHETIZ,
     +          JHETLT,JHETLI,JHETLO,JHETAI,JHETAO,LHETCA
      PARAMETER(JHETID=1,JHETVR=2,JHETNT=4,JHETEW=5,JHETDW=6,JHETTG=7,
     +          JHETE2=8,JHETIZ=9,JHETLT=10,JHETLI=14,JHETLO=54,
     +          JHETAI=134,JHETAO=144,LHETCA=163)
