*CD hgeajj
      INTEGER JHGEBM,JHGEPM,JHGEDM,JHGECH,JHGECN,JHGECM,JHGECG,JHGECE,
     +          LHGEAA
      PARAMETER(JHGEBM=1,JHGEPM=2,JHGEDM=3,JHGECH=4,JHGECN=5,JHGECM=6,
     +          JHGECG=7,JHGECE=8,LHGEAA=8)
