*CD hpcojj
      INTEGER JHPCDI,JHPCDE,JHPCC1,JHPCC2,JHPCND,JHPCIP,JHPCFP,JHPCLP,
     +          JHPCMD,JHPCPD,JHPCCX,JHPCCY,JHPCBF,JHPCHT,JHPCHP,LHPCOA
      PARAMETER(JHPCDI=1,JHPCDE=2,JHPCC1=3,JHPCC2=4,JHPCND=5,JHPCIP=6,
     +          JHPCFP=7,JHPCLP=8,JHPCMD=9,JHPCPD=10,JHPCCX=11,
     +          JHPCCY=12,JHPCBF=13,JHPCHT=14,JHPCHP=15,LHPCOA=15)
