*CD hsbajj
      INTEGER JHSBID,JHSBVR,JHSBEN,JHSBSN,JHSBMT,JHSBXS,JHSBRS,JHSBPM,
     +          JHSBHB,LHSBAA
      PARAMETER(JHSBID=1,JHSBVR=2,JHSBEN=4,JHSBSN=5,JHSBMT=6,JHSBXS=7,
     +          JHSBRS=10,JHSBPM=13,JHSBHB=14,LHSBAA=14)
