*CD hsecjj
      INTEGER JHSEID,JHSEVR,JHSEFN,JHSESN,JHSESL,JHSEMT,JHSEXS,JHSERS,
     +          JHSEPM,JHSEHE,LHSECA
      PARAMETER(JHSEID=1,JHSEVR=2,JHSEFN=4,JHSESN=5,JHSESL=6,JHSEMT=7,
     +          JHSEXS=8,JHSERS=11,JHSEPM=14,JHSEHE=15,LHSECA=15)
