*CD hstojj
      INTEGER JHSTXI,JHSTXO,JHSTIX,JHSTOX,JHSTSX,JHSTYI,JHSTYO,JHSTIY,
     +          JHSTOY,JHSTSY,JHSTZI,JHSTZO,JHSTIZ,JHSTOZ,JHSTSZ,JHSTSN,
     +          JHSTMN,JHSTOF,LHSTOA
      PARAMETER(JHSTXI=1,JHSTXO=5,JHSTIX=9,JHSTOX=10,JHSTSX=11,
     +          JHSTYI=12,JHSTYO=16,JHSTIY=20,JHSTOY=21,JHSTSY=22,
     +          JHSTZI=23,JHSTZO=27,JHSTIZ=31,JHSTOZ=32,JHSTSZ=33,
     +          JHSTSN=34,JHSTMN=35,JHSTOF=36,LHSTOA=36)
