*CD htidjj
      INTEGER JHTIIB,JHTIIE,JHTICI,JHTICO,JHTIPC,JHTIPE,JHTIPR,JHTIPB,
     +          JHTIPL,JHTIPO,LHTIDA
      PARAMETER(JHTIIB=1,JHTIIE=2,JHTICI=4,JHTICO=5,JHTIPC=6,JHTIPE=7,
     +          JHTIPR=9,JHTIPB=10,JHTIPL=11,JHTIPO=12,LHTIDA=12)
