*CD htuejj
      INTEGER JHTUMN,JHTUN4,JHTUN3,JHTUN2,JHTUMS,JHTUN8,JHTULN,JHTUN0,
     +          JHTUNF,LHTUEA
      PARAMETER(JHTUMN=1,JHTUN4=3,JHTUN3=4,JHTUN2=5,JHTUMS=6,JHTUN8=8,
     +          JHTULN=9,JHTUN0=10,JHTUNF=11,LHTUEA=11)
