*CD icutjj
      INTEGER JICUID,JICUVR,JICURM,JICUSR,JICUSZ,JICUML,JICUJD,JICUJC,
     +          JICUUZ,JICUCL,JICUCP,JICUCA,JICUMA,JICUDM,JICUCM,JICUC1,
     +          JICUC4,LICUTA
      PARAMETER(JICUID=1,JICUVR=2,JICURM=4,JICUSR=7,JICUSZ=10,JICUML=12,
     +          JICUJD=14,JICUJC=16,JICUUZ=18,JICUCL=20,JICUCP=22,
     +          JICUCA=23,JICUMA=24,JICUDM=25,JICUCM=26,JICUC1=27,
     +          JICUC4=28,LICUTA=28)
