*CD ieddjj
      INTEGER JIEDID,JIEDVR,JIEDLN,JIEDNB,JIEDBW,JIEDBL,JIEDBH,JIEDDD,
     +          LIEDDA
      PARAMETER(JIEDID=1,JIEDVR=2,JIEDLN=4,JIEDNB=5,JIEDBW=6,JIEDBL=7,
     +          JIEDBH=8,JIEDDD=9,LIEDDA=58)
