*CD ihitjj
      INTEGER JIHITN,JIHILN,JIHIWN,JIHIDD,JIHIDA,JIHIZH,JIHITH,JIHITF,
     +          LIHITA
      PARAMETER(JIHITN=1,JIHILN=2,JIHIWN=3,JIHIDD=4,JIHIDA=5,JIHIZH=6,
     +          JIHITH=7,JIHITF=8,LIHITA=8)
