*CD ihocjj
      INTEGER JIHOID,JIHOAM,JIHOAT,JIHOAW,JIHOAO,JIHOAD,JIHOZM,JIHOZZ,
     +          JIHOZW,JIHOZT,JIHOZB,JIHORD,JIHORN,JIHORE,JIHORR,JIHORV,
     +          JIHOPD,JIHOPN,JIHOPM,JIHOPR,JIHOZN,JIHOZD,JIHOZR,JIHORP,
     +          JIHORY,JIHORS,JIHOHT,LIHOCA
      PARAMETER(JIHOID=1,JIHOAM=2,JIHOAT=3,JIHOAW=4,JIHOAO=5,JIHOAD=6,
     +          JIHOZM=7,JIHOZZ=8,JIHOZW=9,JIHOZT=10,JIHOZB=11,
     +          JIHORD=12,JIHORN=13,JIHORE=14,JIHORR=15,JIHORV=16,
     +          JIHOPD=17,JIHOPN=18,JIHOPM=19,JIHOPR=20,JIHOZN=22,
     +          JIHOZD=23,JIHOZR=24,JIHORP=27,JIHORY=28,JIHORS=29,
     +          JIHOHT=32,LIHOCA=35)
