*CD ilyrjj
      INTEGER JILYID,JILYVR,JILYLN,JILYNW,JILYRW,JILYPO,JILYCH,JILYIP,
     +          LILYRA
      PARAMETER(JILYID=1,JILYVR=2,JILYLN=4,JILYNW=5,JILYRW=6,JILYPO=7,
     +          JILYCH=8,JILYIP=9,LILYRA=9)
