*CD impajj
      INTEGER JIMPND,JIMPIX,JIMPIY,JIMPIZ,JIMPUD,JIMPVD,JIMPWD,JIMPEN,
     +          LIMPAA
      PARAMETER(JIMPND=1,JIMPIX=2,JIMPIY=3,JIMPIZ=4,JIMPUD=5,JIMPVD=6,
     +          JIMPWD=7,JIMPEN=8,LIMPAA=8)
