*CD iqxtjj
      INTEGER JIQXFL,JIQXWN,JIQXCO,JIQXPW,JIQXWX,JIQXHX,JIQXDC,JIQXDT,
     +          JIQXDD,JIQXER,JIQXRD,JIQXRF,JIQXRZ,JIQXEZ,LIQXTA
      PARAMETER(JIQXFL=1,JIQXWN=2,JIQXCO=3,JIQXPW=4,JIQXWX=5,JIQXHX=8,
     +          JIQXDC=11,JIQXDT=12,JIQXDD=13,JIQXER=14,JIQXRD=15,
     +          JIQXRF=16,JIQXRZ=17,JIQXEZ=18,LIQXTA=18)
