*CD irfejj
      INTEGER JIRFID,JIRFVR,JIRFBW,JIRFZB,JIRFDV,JIRFMC,JIRFCL,JIRFCH,
     +          JIRFIT,LIRFEA
      PARAMETER(JIRFID=1,JIRFVR=2,JIRFBW=4,JIRFZB=5,JIRFDV=6,JIRFMC=7,
     +          JIRFCL=15,JIRFCH=23,JIRFIT=31,LIRFEA=31)
