*CD itftjj
      INTEGER JITFIR,JITFTL,JITFP0,JITFD0,JITFZ0,JITFSA,JITFCM,JITFCD,
     +          JITFND,JITFFT,LITFTA
      PARAMETER(JITFIR=1,JITFTL=2,JITFP0=3,JITFD0=4,JITFZ0=5,JITFSA=6,
     +          JITFCM=7,JITFCD=28,JITFND=29,JITFFT=30,LITFTA=30)
