*CD ithtjj
      INTEGER JITHTN,JITHLN,JITHWN,JITHPI,JITHZI,JITHPR,JITHZR,JITHPD,
     +          JITHTF,LITHTA
      PARAMETER(JITHTN=1,JITHLN=2,JITHWN=3,JITHPI=4,JITHZI=5,JITHPR=6,
     +          JITHZR=7,JITHPD=8,JITHTF=9,LITHTA=9)
