*CD itmejj
      INTEGER JITMTN,JITMMA,JITMFD,JITMMS,JITMDE,JITMEP,JITMST,JITMVO,
     +          JITMGP,JITMFL,LITMEA
      PARAMETER(JITMTN=1,JITMMA=5,JITMFD=9,JITMMS=10,JITMDE=11,
     +          JITMEP=12,JITMST=13,JITMVO=14,JITMGP=15,JITMFL=16,
     +          LITMEA=16)
