*CD ixcrjj
      INTEGER JIXCIH,JIXCOH,JIXCMH,JIXCTT,JIXCBB,JIXCTC,JIXCHC,JIXCPI,
     +          JIXCHT,JIXCBV,JIXCFM,LIXCRA
      PARAMETER(JIXCIH=1,JIXCOH=2,JIXCMH=3,JIXCTT=4,JIXCBB=5,JIXCTC=6,
     +          JIXCHC=7,JIXCPI=8,JIXCHT=9,JIXCBV=17,JIXCFM=25,
     +          LIXCRA=25)
