*CD izfejj
      INTEGER JIZFID,JIZFVR,JIZFBW,JIZFZB,JIZFEX,JIZFS1,JIZFS2,JIZFS3,
     +          JIZFOO,JIZFCL,JIZFCH,JIZFIT,LIZFEA
      PARAMETER(JIZFID=1,JIZFVR=2,JIZFBW=4,JIZFZB=5,JIZFEX=6,JIZFS1=7,
     +          JIZFS2=8,JIZFS3=9,JIZFOO=10,JIZFCL=11,JIZFCH=19,
     +          JIZFIT=27,LIZFEA=27)
