*CD izscjj
      INTEGER JIZSID,JIZSVR,JIZSLC,JIZSOF,JIZSEX,JIZSDL,JIZSCL,JIZSCH,
     +          JIZSSG,JIZSPL,JIZSZP,JIZSTS,JIZSTW,JIZSIT,LIZSCA
      PARAMETER(JIZSID=1,JIZSVR=2,JIZSLC=4,JIZSOF=5,JIZSEX=6,JIZSDL=7,
     +          JIZSCL=8,JIZSCH=9,JIZSSG=10,JIZSPL=11,JIZSZP=12,
     +          JIZSTS=13,JIZSTW=14,JIZSIT=15,LIZSCA=15)
