*CD jconjj
      INTEGER JJCODX,JJCODY,JJCODZ,JJCOGT,JJCODB,JJCOEZ,JJCOCF,JJCOTP,
     +          JJCONR,JJCOSN,LJCONA
      PARAMETER(JJCODX=1,JJCODY=2,JJCODZ=3,JJCOGT=4,JJCODB=5,JJCOEZ=8,
     +          JJCOCF=10,JJCOTP=11,JJCONR=12,JJCOSN=13,LJCONA=48)
