*CD jpasjj
      INTEGER JJPAZO,JJPANU,JJPANC,JJPADT,JJPAVT,JJPAVO,JJPAVN,JJPATC,
     +          JJPAET,JJPADA,JJPATI,JJPANM,JJPAHP,JJPAHC,LJPASA
      PARAMETER(JJPAZO=1,JJPANU=2,JJPANC=3,JJPADT=4,JJPAVT=7,JJPAVO=8,
     +          JJPAVN=9,JJPATC=11,JJPAET=12,JJPADA=13,JJPATI=14,
     +          JJPANM=15,JJPAHP=16,JJPAHC=17,LJPASA=17)
