*CD jtrejj
      INTEGER JJTRWT,JJTRPT,JJTRMD,JJTRTW,JJTRTP,JJTRDF,JJTRHR,JJTRRR,
     +          JJTRBH,JJTRTT,JJTRDP,JJTRBC,JJTRFA,JJTRFB,JJTRFC,LJTREA
      PARAMETER(JJTRWT=1,JJTRPT=2,JJTRMD=3,JJTRTW=4,JJTRTP=5,JJTRDF=6,
     +          JJTRHR=7,JJTRRR=8,JJTRBH=9,JJTRTT=10,JJTRDP=11,
     +          JJTRBC=12,JJTRFA=13,JJTRFB=14,JJTRFC=15,LJTREA=15)
