*CD ksecjj
      INTEGER JKSEGI,JKSEGV,JKSEGN,JKSEAN,JKSEGX,JKSEGE,JKSEAX,JKSEAE,
     +          LKSECA
      PARAMETER(JKSEGI=1,JKSEGV=2,JKSEGN=3,JKSEAN=4,JKSEGX=5,JKSEGE=6,
     +          JKSEAX=7,JKSEAE=8,LKSECA=8)
