*CD lalijj
      INTEGER JLALID,JLALVR,JLALDX,JLALDR,JLALDM,JLALDT,JLALDP,JLALLS,
     +          LLALIA
      PARAMETER(JLALID=1,JLALVR=2,JLALDX=4,JLALDR=7,JLALDM=10,JLALDT=13,
     +          JLALDP=14,JLALLS=15,LLALIA=15)
