*CD lbakjj
      INTEGER JLBAHI,JLBACP,JLBALO,JLBASA,JLBATR,JLBAF1,JLBAF2,JLBANS,
     +          JLBAF3,JLBAF4,JLBABH,JLBANP,JLBABA,JLBASE,LLBAKA
      PARAMETER(JLBAHI=1,JLBACP=3,JLBALO=5,JLBASA=7,JLBATR=9,JLBAF1=11,
     +          JLBAF2=13,JLBANS=15,JLBAF3=17,JLBAF4=19,JLBABH=21,
     +          JLBANP=23,JLBABA=25,JLBASE=26,LLBAKA=26)
