*CD lbcs
      INTEGER LMHLEN, LMHCOL, LMHROW
      PARAMETER (LMHLEN=2, LMHCOL=1, LMHROW=2)
C
      PARAMETER (LBCS=600000,NAMAX=1100)
      COMMON /BCS/   IW(LBCS)
      INTEGER IW
      REAL RW(1000)
      EQUIVALENCE (RW(1),IW(1))
C
