*CD lceljj
      INTEGER JLCEID,JLCEVR,JLCEAM,JLCETH,JLCESN,JLCETN,JLCEWN,JLCECN,
     +          JLCEGV,JLCETR,LLCELA
      PARAMETER(JLCEID=1,JLCEVR=2,JLCEAM=4,JLCETH=5,JLCESN=8,JLCETN=11,
     +          JLCEWN=14,JLCECN=17,JLCEGV=18,JLCETR=19,LLCELA=19)
