*CD ldrejj
      INTEGER JLDRID,JLDRVR,JLDRDT,JLDRD2,JLDRDS,JLDRXL,JLDRXH,JLDRYS,
     +          JLDRY0,JLDRDY,JLDRY5,JLDRDW,LLDREA
      PARAMETER(JLDRID=1,JLDRVR=2,JLDRDT=4,JLDRD2=5,JLDRDS=6,JLDRXL=7,
     +          JLDRXH=11,JLDRYS=15,JLDRY0=19,JLDRDY=20,JLDRY5=21,
     +          JLDRDW=22,LLDREA=22)
