*CD lfiljj
      INTEGER JLFILF,JLFIFR,JLFILR,JLFINV,JLFILE,JLFIBX,JLFIBY,JLFIBZ,
     +          JLFIEX,JLFIEY,JLFIEZ,JLFIOF,LLFILA
      PARAMETER(JLFILF=1,JLFIFR=2,JLFILR=3,JLFINV=4,JLFILE=5,JLFIBX=6,
     +          JLFIBY=7,JLFIBZ=8,JLFIEX=9,JLFIEY=10,JLFIEZ=11,
     +          JLFIOF=12,LLFILA=12)
