*CD lidtjj
      INTEGER JLIDIF,JLIDEC,JLIDTC,JLIDPC,JLIDE4,JLIDE1,JLIDE2,JLIDR1,
     +          JLIDR2,JLIDXX,JLIDYY,JLIDXY,JLIDDA,JLIDNT,JLIDLO,JLIDLS,
     +          JLIDST,LLIDTA
      PARAMETER(JLIDIF=1,JLIDEC=2,JLIDTC=3,JLIDPC=4,JLIDE4=5,JLIDE1=6,
     +          JLIDE2=7,JLIDR1=8,JLIDR2=9,JLIDXX=10,JLIDYY=11,
     +          JLIDXY=12,JLIDDA=13,JLIDNT=17,JLIDLO=18,JLIDLS=19,
     +          JLIDST=20,LLIDTA=20)
