*CD lmtyjj
      INTEGER JLMTID,JLMTVR,JLMTMT,JLMTNS,JLMTNL,JLMTNP,JLMTNW,JLMTN2,
     +          JLMTNR,JLMTNT,JLMTFL,JLMTFR,JLMTBL,JLMTBR,JLMTST,JLMTRA,
     +          JLMTDT,JLMTCC,JLMTBA,JLMTBS,JLMTRD,JLMTXD,JLMTYD,LLMTYA
      PARAMETER(JLMTID=1,JLMTVR=2,JLMTMT=4,JLMTNS=5,JLMTNL=6,JLMTNP=9,
     +          JLMTNW=10,JLMTN2=11,JLMTNR=12,JLMTNT=13,JLMTFL=14,
     +          JLMTFR=15,JLMTBL=16,JLMTBR=17,JLMTST=18,JLMTRA=21,
     +          JLMTDT=24,JLMTCC=25,JLMTBA=26,JLMTBS=27,JLMTRD=28,
     +          JLMTXD=29,JLMTYD=30,LLMTYA=30)
