*CD lobjjj
      INTEGER JLOBCH,JLOBEC,JLOBTC,JLOBPC,JLOBKD,JLOBKT,JLOBR1,JLOBR2,
     +          JLOBR3,JLOBR4,JLOBLI,LLOBJA
      PARAMETER(JLOBCH=1,JLOBEC=2,JLOBTC=3,JLOBPC=4,JLOBKD=5,JLOBKT=6,
     +          JLOBR1=7,JLOBR2=8,JLOBR3=9,JLOBR4=10,JLOBLI=11,
     +          LLOBJA=11)
