*CD lonljj
      INTEGER JLONGB,JLONTR,JLONLO,JLONHI,JLONVH,JLONLL,JLONHL,JLONRA,
     +          LLONLA
      PARAMETER(JLONGB=1,JLONTR=2,JLONLO=3,JLONHI=4,JLONVH=5,JLONLL=6,
     +          JLONHL=7,JLONRA=8,LLONLA=8)
