*CD lpftjj
      INTEGER JLPFIX,JLPFDP,JLPFRT,JLPFVN,JLPFPT,JLPFPS,JLPFQT,JLPFQS,
     +          JLPFCT,JLPFCV,JLPFBH,JLPFEA,JLPFLT,JLPFCL,JLPFVT,JLPFVA,
     +          JLPFIT,JLPFIC,JLPFTP,JLPFXP,JLPFTM,JLPFXM,JLPFSM,JLPFSS,
     +          LLPFTA
      PARAMETER(JLPFIX=1,JLPFDP=2,JLPFRT=3,JLPFVN=4,JLPFPT=5,JLPFPS=6,
     +          JLPFQT=7,JLPFQS=8,JLPFCT=19,JLPFCV=20,JLPFBH=36,
     +          JLPFEA=40,JLPFLT=44,JLPFCL=45,JLPFVT=67,JLPFVA=68,
     +          JLPFIT=76,JLPFIC=77,JLPFTP=78,JLPFXP=79,JLPFTM=117,
     +          JLPFXM=118,JLPFSM=156,JLPFSS=160,LLPFTA=175)
