*CD lplsjj
      INTEGER JLPLIX,JLPLDP,JLPLRT,JLPLVN,JLPLRM,JLPLMQ,JLPLA2,JLPLA3,
     +          JLPLQP,JLPLQM,JLPLLA,JLPLLB,JLPLLC,JLPLLD,JLPLLE,JLPLLF,
     +          JLPLLG,JLPLLH,JLPLLI,JLPLLJ,JLPLGM,JLPLB2,JLPLBI,JLPLPW,
     +          JLPLPG,JLPLWA,JLPLWB,JLPLWC,JLPLWD,JLPLWE,JLPLWF,JLPLWG,
     +          JLPLWH,JLPLBS,JLPLBA,JLPLBU,JLPLZA,JLPLZB,JLPLZC,JLPLZD,
     +          JLPLZE,JLPLZF,JLPLZG,JLPLZH,JLPLTX,JLPLTY,JLPLSF,JLPLSG,
     +          JLPLSH,JLPLSI,LLPLSA
      PARAMETER(JLPLIX=1,JLPLDP=2,JLPLRT=3,JLPLVN=4,JLPLRM=5,JLPLMQ=6,
     +          JLPLA2=8,JLPLA3=10,JLPLQP=12,JLPLQM=13,JLPLLA=14,
     +          JLPLLB=18,JLPLLC=22,JLPLLD=26,JLPLLE=30,JLPLLF=34,
     +          JLPLLG=38,JLPLLH=42,JLPLLI=46,JLPLLJ=50,JLPLGM=54,
     +          JLPLB2=55,JLPLBI=57,JLPLPW=59,JLPLPG=60,JLPLWA=61,
     +          JLPLWB=62,JLPLWC=63,JLPLWD=64,JLPLWE=65,JLPLWF=66,
     +          JLPLWG=67,JLPLWH=68,JLPLBS=69,JLPLBA=70,JLPLBU=78,
     +          JLPLZA=86,JLPLZB=88,JLPLZC=90,JLPLZD=92,JLPLZE=94,
     +          JLPLZF=96,JLPLZG=98,JLPLZH=100,JLPLTX=102,JLPLTY=103,
     +          JLPLSF=104,JLPLSG=105,JLPLSH=106,JLPLSI=107,LLPLSA=107)
