*CD lpltjj
      INTEGER JLPLIX,JLPLDP,JLPLRT,JLPLVN,JLPLQT,JLPLBQ,JLPLDQ,JLPLA1,
     +          JLPLQP,JLPLQM,JLPLLA,JLPLGT,JLPLMS,JLPLMI,JLPLPW,JLPLBS,
     +          JLPLBU,JLPLZL,JLPLDD,JLPLT1,JLPLSS,LLPLTA
      PARAMETER(JLPLIX=1,JLPLDP=2,JLPLRT=3,JLPLVN=4,JLPLQT=5,JLPLBQ=6,
     +          JLPLDQ=7,JLPLA1=8,JLPLQP=16,JLPLQM=17,JLPLLA=18,
     +          JLPLGT=86,JLPLMS=87,JLPLMI=89,JLPLPW=91,JLPLBS=101,
     +          JLPLBU=119,JLPLZL=127,JLPLDD=143,JLPLT1=144,JLPLSS=152,
     +          LLPLTA=167)
