*CD lpztjj
      INTEGER JLPZIX,JLPZDP,JLPZRT,JLPZVN,JLPZFL,JLPZRN,JLPZPN,JLPZBV,
     +          JLPZNP,JLPZNM,JLPZHT,JLPZHL,JLPZFT,JLPZEF,JLPZNT,JLPZMR,
     +          JLPZMT,JLPZMP,JLPZUM,JLPZET,JLPZEH,JLPZIT,JLPZIP,JLPZTT,
     +          JLPZTP,JLPZPT,JLPZPP,JLPZLU,JLPZCT,JLPZCL,JLPZST,JLPZSS,
     +          LLPZTA
      PARAMETER(JLPZIX=1,JLPZDP=2,JLPZRT=3,JLPZVN=4,JLPZFL=5,JLPZRN=6,
     +          JLPZPN=7,JLPZBV=8,JLPZNP=9,JLPZNM=10,JLPZHT=11,
     +          JLPZHL=12,JLPZFT=13,JLPZEF=14,JLPZNT=15,JLPZMR=16,
     +          JLPZMT=17,JLPZMP=18,JLPZUM=52,JLPZET=68,JLPZEH=69,
     +          JLPZIT=101,JLPZIP=102,JLPZTT=118,JLPZTP=119,JLPZPT=135,
     +          JLPZPP=136,JLPZLU=152,JLPZCT=168,JLPZCL=169,JLPZST=189,
     +          JLPZSS=193,LLPZTA=208)
