*CD lscojj
      INTEGER JLSCID,JLSCVR,JLSCCN,JLSCNS,JLSCRP,JLSCRR,JLSCSG,JLSCLC,
     +          LLSCOA
      PARAMETER(JLSCID=1,JLSCVR=2,JLSCCN=4,JLSCNS=5,JLSCRP=6,JLSCRR=9,
     +          JLSCSG=12,JLSCLC=13,LLSCOA=13)
