*CD lsinjj
      INTEGER JLSIK1,JLSIK2,JLSIKH,JLSIKL,JLSITH,JLSIPH,JLSIEN,JLSIIF,
     +          JLSIIT,LLSINA
      PARAMETER(JLSIK1=1,JLSIK2=2,JLSIKH=3,JLSIKL=4,JLSITH=5,JLSIPH=6,
     +          JLSIEN=7,JLSIIF=8,JLSIIT=9,LLSINA=9)
