*CD lslojj
      INTEGER JLSLID,JLSLVR,JLSLSN,JLSLXS,JLSLRS,JLSLXM,JLSLTM,JLSLPM,
     +          JLSLLM,JLSLLS,LLSLOA
      PARAMETER(JLSLID=1,JLSLVR=2,JLSLSN=4,JLSLXS=5,JLSLRS=8,JLSLXM=11,
     +          JLSLTM=14,JLSLPM=15,JLSLLM=16,JLSLLS=17,LLSLOA=17)
