*CD lsntjj
      INTEGER JLSNID,JLSNVR,JLSNAL,JLSNRL,JLSNFL,JLSNTH,JLSNMM,JLSNMA,
     +          JLSNSA,JLSNNS,JLSNNP,LLSNTA
      PARAMETER(JLSNID=1,JLSNVR=2,JLSNAL=4,JLSNRL=5,JLSNFL=6,JLSNTH=7,
     +          JLSNMM=8,JLSNMA=9,JLSNSA=13,JLSNNS=14,JLSNNP=15,
     +          LLSNTA=15)
