*CD lumijj
      INTEGER JLUMHI,JLUMLO,JLUMCP,JLUMSA,JLUMTR,JLUMF1,JLUMF2,JLUMNS,
     +          JLUMF3,JLUMF4,JLUMBH,JLUMNP,JLUMB1,JLUMB2,JLUMLL,JLUMVH,
     +          JLUMNV,JLUMLU,JLUMSE,JLUMSY,LLUMIA
      PARAMETER(JLUMHI=1,JLUMLO=2,JLUMCP=3,JLUMSA=4,JLUMTR=5,JLUMF1=6,
     +          JLUMF2=7,JLUMNS=8,JLUMF3=9,JLUMF4=10,JLUMBH=11,
     +          JLUMNP=12,JLUMB1=13,JLUMB2=14,JLUMLL=15,JLUMVH=16,
     +          JLUMNV=17,JLUMLU=18,JLUMSE=19,JLUMSY=20,LLUMIA=20)
