*CD lupajj
      INTEGER JLUPGB,JLUPHV,JLUPT1,JLUPL2,JLUPTE,JLUPLO,JLUPAM,JLUPMD,
     +          JLUPEF,JLUPEC,JLUPEW,JLUPXC,JLUPYC,JLUPTC,JLUPPC,JLUPAX,
     +          JLUPAY,JLUPXX,JLUPYY,JLUPXY,JLUPXA,JLUPYA,JLUPXD,JLUPYD,
     +          JLUPAD,JLUPIT,JLUPCT,JLUPTT,JLUPPT,JLUPXT,JLUPYT,JLUPE1,
     +          JLUPE2,JLUPXL,JLUPYL,JLUPAI,JLUPES,JLUPXS,JLUPYS,JLUPAS,
     +          LLUPAA
      PARAMETER(JLUPGB=1,JLUPHV=2,JLUPT1=3,JLUPL2=4,JLUPTE=5,JLUPLO=6,
     +          JLUPAM=7,JLUPMD=8,JLUPEF=9,JLUPEC=10,JLUPEW=12,
     +          JLUPXC=14,JLUPYC=16,JLUPTC=18,JLUPPC=20,JLUPAX=22,
     +          JLUPAY=24,JLUPXX=26,JLUPYY=28,JLUPXY=30,JLUPXA=32,
     +          JLUPYA=34,JLUPXD=36,JLUPYD=38,JLUPAD=40,JLUPIT=42,
     +          JLUPCT=44,JLUPTT=46,JLUPPT=48,JLUPXT=50,JLUPYT=52,
     +          JLUPE1=54,JLUPE2=56,JLUPXL=58,JLUPYL=60,JLUPAI=62,
     +          JLUPES=64,JLUPXS=66,JLUPYS=68,JLUPAS=70,LLUPAA=71)
