*CD lwrgjj
      INTEGER JLWRID,JLWRVR,JLWRLW,JLWRTW,JLWRD2,JLWRXL,JLWRYL,JLWRYH,
     +          JLWRLM,LLWRGA
      PARAMETER(JLWRID=1,JLWRVR=2,JLWRLW=4,JLWRTW=5,JLWRD2=6,JLWRXL=7,
     +          JLWRYL=8,JLWRYH=9,JLWRLM=10,LLWRGA=10)
