*CD lxbmjj
      INTEGER JLXBCE,JLXBLE,JLXBQE,JLXBCP,JLXBLP,JLXBQP,JLXBHE,JLXBHP,
     +          JLXBVE,JLXBVP,LLXBMA
      PARAMETER(JLXBCE=1,JLXBLE=2,JLXBQE=3,JLXBCP=4,JLXBLP=5,JLXBQP=6,
     +          JLXBHE=7,JLXBHP=9,JLXBVE=11,JLXBVP=13,LLXBMA=14)
