*CD lxgbjj
      INTEGER JLXGMO,JLXGMN,JLXGFI,JLXGNT,JLXGNW,JLXGWS,JLXGEN,JLXGBN,
     +          JLXGRF,JLXGEH,JLXGEF,JLXGLU,JLXGLE,JLXGSP,JLXGVE,JLXGLF,
     +          JLXGLR,JLXGMD,JLXGMM,LLXGBA
      PARAMETER(JLXGMO=1,JLXGMN=6,JLXGFI=7,JLXGNT=8,JLXGNW=9,JLXGWS=10,
     +          JLXGEN=11,JLXGBN=12,JLXGRF=13,JLXGEH=14,JLXGEF=15,
     +          JLXGLU=16,JLXGLE=17,JLXGSP=18,JLXGVE=19,JLXGLF=20,
     +          JLXGLR=22,JLXGMD=24,JLXGMM=26,LLXGBA=125)
