*CD lxipjj
      INTEGER JLXISI,JLXIBU,JLXIGF,JLXIST,JLXIXP,JLXISP,JLXIYP,JLXISS,
     +          JLXIXE,JLXISE,JLXIYE,JLXISL,LLXIPA
      PARAMETER(JLXISI=1,JLXIBU=2,JLXIGF=3,JLXIST=4,JLXIXP=5,JLXISP=6,
     +          JLXIYP=7,JLXISS=8,JLXIXE=9,JLXISE=10,JLXIYE=11,
     +          JLXISL=12,LLXIPA=12)
