*CD lxkgjj
      INTEGER JLXKIT,JLXKTL,JLXKTR,JLXKSP,JLXKSR,JLXKSE,JLXKSC,JLXKLL,
     +          JLXKLR,JLXKBL,JLXKBR,JLXKB1,JLXKB2,JLXKB3,JLXKRU,JLXKRD,
     +          JLXKRI,JLXKRO,JLXKRA,JLXKRM,LLXKGA
      PARAMETER(JLXKIT=1,JLXKTL=2,JLXKTR=3,JLXKSP=4,JLXKSR=5,JLXKSE=6,
     +          JLXKSC=7,JLXKLL=8,JLXKLR=9,JLXKBL=10,JLXKBR=11,
     +          JLXKB1=12,JLXKB2=13,JLXKB3=14,JLXKRU=15,JLXKRD=16,
     +          JLXKRI=17,JLXKRO=18,JLXKRA=19,JLXKRM=20,LLXKGA=20)
