*CD lxrfjj
      INTEGER JLXRNA,JLXRHE,JLXRHA,JLXRCB,JLXRVL,JLXRDL,JLXRPS,JLXRKF,
     +          JLXRKR,JLXRRF,JLXRDS,JLXRCF,JLXRCR,LLXRFA
      PARAMETER(JLXRNA=1,JLXRHE=6,JLXRHA=9,JLXRCB=12,JLXRVL=15,
     +          JLXRDL=18,JLXRPS=21,JLXRKF=22,JLXRKR=24,JLXRRF=25,
     +          JLXRDS=26,JLXRCF=27,JLXRCR=28,LLXRFA=28)
