*CD lxunjj
      INTEGER JLXUTR,JLXUWA,JLXUCE,JLXULE,JLXUQE,JLXUCP,JLXULP,JLXUQP,
     +          LLXUNA
      PARAMETER(JLXUTR=1,JLXUWA=2,JLXUCE=3,JLXULE=4,JLXUQE=5,JLXUCP=6,
     +          JLXULP=7,JLXUQP=8,LLXUNA=8)
