*CD lyftjj
      INTEGER JLYFIX,JLYFDP,JLYFRT,JLYFVN,JLYFPT,JLYFPS,JLYFQT,JLYFQS,
     +          JLYFCT,JLYFCV,JLYFBT,JLYFBH,JLYFEA,JLYFLT,JLYFCL,JLYFVT,
     +          JLYFVA,JLYFIT,JLYFIC,JLYFTP,JLYFXP,JLYFTM,JLYFXM,JLYFSM,
     +          JLYFSS,LLYFTA
      PARAMETER(JLYFIX=1,JLYFDP=2,JLYFRT=3,JLYFVN=4,JLYFPT=5,JLYFPS=6,
     +          JLYFQT=7,JLYFQS=8,JLYFCT=19,JLYFCV=20,JLYFBT=36,
     +          JLYFBH=37,JLYFEA=41,JLYFLT=45,JLYFCL=46,JLYFVT=76,
     +          JLYFVA=77,JLYFIT=85,JLYFIC=86,JLYFTP=87,JLYFXP=88,
     +          JLYFTM=126,JLYFXM=127,JLYFSM=165,JLYFSS=169,LLYFTA=184)
