*CD lyztjj
      INTEGER JLYZIX,JLYZDP,JLYZRT,JLYZVN,JLYZFL,JLYZRN,JLYZMT,JLYZMO,
     +          JLYZPN,JLYZBV,JLYZNP,JLYZHT,JLYZHL,JLYZFT,JLYZEF,JLYZNT,
     +          JLYZMR,JLYZFI,JLYZMM,JLYZMP,JLYZET,JLYZEH,JLYZIT,JLYZIP,
     +          JLYZTT,JLYZTP,JLYZPT,JLYZPP,JLYZLU,JLYZCT,JLYZCL,JLYZST,
     +          JLYZSS,LLYZTA
      PARAMETER(JLYZIX=1,JLYZDP=2,JLYZRT=3,JLYZVN=4,JLYZFL=5,JLYZRN=6,
     +          JLYZMT=7,JLYZMO=8,JLYZPN=9,JLYZBV=10,JLYZNP=11,
     +          JLYZHT=12,JLYZHL=13,JLYZFT=14,JLYZEF=15,JLYZNT=16,
     +          JLYZMR=17,JLYZFI=18,JLYZMM=19,JLYZMP=20,JLYZET=54,
     +          JLYZEH=55,JLYZIT=87,JLYZIP=88,JLYZTT=104,JLYZTP=105,
     +          JLYZPT=121,JLYZPP=122,JLYZLU=138,JLYZCT=154,JLYZCL=155,
     +          JLYZST=167,JLYZSS=171,LLYZTA=186)
