*CD lzatjj
      INTEGER JLZADP,JLZAHP,JLZART,JLZAVN,JLZAIT,JLZAIL,JLZAVD,JLZAVS,
     +          JLZATP,JLZALL,JLZASM,JLZASS,JLZABC,JLZALC,JLZAKO,JLZAKT,
     +          JLZAKW,JLZAKM,JLZAUN,JLZAUT,JLZAUB,JLZAIS,JLZAIR,JLZAPS,
     +          JLZAPD,JLZATS,JLZASR,LLZATA
      PARAMETER(JLZADP=1,JLZAHP=2,JLZART=3,JLZAVN=4,JLZAIT=5,JLZAIL=8,
     +          JLZAVD=16,JLZAVS=21,JLZATP=37,JLZALL=47,JLZASM=57,
     +          JLZASS=67,JLZABC=77,JLZALC=83,JLZAKO=89,JLZAKT=91,
     +          JLZAKW=92,JLZAKM=94,JLZAUN=95,JLZAUT=100,JLZAUB=101,
     +          JLZAIS=105,JLZAIR=106,JLZAPS=108,JLZAPD=116,JLZATS=120,
     +          JLZASR=122,LLZATA=141)
