*CD lzftjj
      INTEGER JLZFDP,JLZFHP,JLZFRT,JLZFVN,JLZFPT,JLZFPS,JLZFQT,JLZFQS,
     +          JLZFCT,JLZFCV,JLZFZT,JLZFZL,JLZFBT,JLZFBH,JLZFSL,JLZFBK,
     +          JLZFLT,JLZFCL,JLZFVT,JLZFVA,JLZFIT,JLZFIC,JLZFTP,JLZFXP,
     +          JLZFTM,JLZFXM,JLZFSM,JLZFSS,LLZFTA
      PARAMETER(JLZFDP=1,JLZFHP=2,JLZFRT=3,JLZFVN=4,JLZFPT=5,JLZFPS=6,
     +          JLZFQT=7,JLZFQS=8,JLZFCT=19,JLZFCV=20,JLZFZT=34,
     +          JLZFZL=35,JLZFBT=41,JLZFBH=42,JLZFSL=52,JLZFBK=62,
     +          JLZFLT=66,JLZFCL=67,JLZFVT=97,JLZFVA=98,JLZFIT=106,
     +          JLZFIC=107,JLZFTP=108,JLZFXP=109,JLZFTM=147,JLZFXM=148,
     +          JLZFSM=186,JLZFSS=190,LLZFTA=205)
