*CD mbtgjj
      INTEGER JMBTID,JMBTVR,JMBTNA,JMBTZB,JMBTRB,JMBTY1,JMBTY2,JMBTNX,
     +          JMBTZT,JMBTRT,JMBTW1,LMBTGA
      PARAMETER(JMBTID=1,JMBTVR=2,JMBTNA=4,JMBTZB=5,JMBTRB=6,JMBTY1=7,
     +          JMBTY2=8,JMBTNX=9,JMBTZT=10,JMBTRT=11,JMBTW1=12,
     +          LMBTGA=12)
