*CD mcutjj
      INTEGER JMCUPM,JMCUPH,JMCUAL,JMCUAA,JMCURW,JMCUTE,JMCUNE,JMCUNL,
     +          JMCUNM,JMCUWC,LMCUTA
      PARAMETER(JMCUPM=1,JMCUPH=2,JMCUAL=3,JMCUAA=5,JMCURW=6,JMCUTE=7,
     +          JMCUNE=8,JMCUNL=9,JMCUNM=10,JMCUWC=11,LMCUTA=11)
