*CD ndgcjj
      INTEGER JNDGDA,JNDGDX,JNDGDZ,JNDGXM,JNDGCX,JNDGCY,JNDGCZ,JNDGPX,
     +          JNDGPY,JNDGPZ,LNDGCA
      PARAMETER(JNDGDA=1,JNDGDX=2,JNDGDZ=3,JNDGXM=4,JNDGCX=5,JNDGCY=6,
     +          JNDGCZ=7,JNDGPX=8,JNDGPY=9,JNDGPZ=10,LNDGCA=10)
