*CD ndhejj
      INTEGER JNDHKR,JNDHKE,JNDHTR,JNDHTP,JNDHPF,JNDHSC,JNDHSE,JNDHDS,
     +          JNDHP2,JNDHVX,JNDHVY,JNDHVZ,JNDHS1,JNDHS2,JNDHT1,JNDHT2,
     +          JNDHM1,JNDHM2,LNDHEA
      PARAMETER(JNDHKR=1,JNDHKE=2,JNDHTR=3,JNDHTP=4,JNDHPF=5,JNDHSC=6,
     +          JNDHSE=7,JNDHDS=8,JNDHP2=9,JNDHVX=10,JNDHVY=11,
     +          JNDHVZ=12,JNDHS1=13,JNDHS2=14,JNDHT1=15,JNDHT2=16,
     +          JNDHM1=17,JNDHM2=18,LNDHEA=18)
