*CD ndv0jj
      INTEGER JNDVHY,JNDVVX,JNDVVY,JNDVVZ,JNDVVM,JNDVTH,JNDVPH,JNDVPP,
     +          JNDVC2,JNDVDL,JNDVTT,LNDV0A
      PARAMETER(JNDVHY=1,JNDVVX=2,JNDVVY=3,JNDVVZ=4,JNDVVM=5,JNDVTH=6,
     +          JNDVPH=7,JNDVPP=8,JNDVC2=9,JNDVDL=10,JNDVTT=11,
     +          LNDV0A=11)
