*CD nrftjj
      INTEGER JNRFPN,JNRFTL,JNRFP0,JNRFD0,JNRFZ0,JNRFRP,JNRFEM,JNRFNL,
     +          LNRFTA
      PARAMETER(JNRFPN=1,JNRFTL=2,JNRFP0=3,JNRFD0=4,JNRFZ0=5,JNRFRP=6,
     +          JNRFEM=7,JNRFNL=22,LNRFTA=30)
