*CD nyv0jj
      INTEGER JNYVHY,JNYVVX,JNYVVY,JNYVVZ,JNYVVM,JNYVTH,JNYVPH,JNYVPP,
     +          JNYVC2,JNYVDL,JNYVTT,LNYV0A
      PARAMETER(JNYVHY=1,JNYVVX=2,JNYVVY=3,JNYVVZ=4,JNYVVM=5,JNYVTH=6,
     +          JNYVPH=7,JNYVPP=8,JNYVC2=9,JNYVDL=10,JNYVTT=11,
     +          LNYV0A=11)
