*CD oalejj
      INTEGER JOALID,JOALNA,JOALNC,JOALEB,JOALTS,JOALSD,JOALFB,JOALAL,
     +          LOALEA
      PARAMETER(JOALID=1,JOALNA=2,JOALNC=6,JOALEB=7,JOALTS=8,JOALSD=9,
     +          JOALFB=10,JOALAL=11,LOALEA=11)
