*CD ocomjj
      INTEGER JOCOID,JOCONA,JOCONS,JOCOFS,JOCOEB,JOCOTS,JOCORO,JOCOSD,
     +          JOCOFB,JOCOCM,JOCOMC,JOCOOA,LOCOMA
      PARAMETER(JOCOID=1,JOCONA=2,JOCONS=6,JOCOFS=7,JOCOEB=8,JOCOTS=9,
     +          JOCORO=10,JOCOSD=11,JOCOFB=12,JOCOCM=13,JOCOMC=17,
     +          JOCOOA=18,LOCOMA=18)
