*CD oscojj
      INTEGER JOSCID,JOSCNA,JOSCNS,JOSCFS,JOSCEB,JOSCTS,JOSCRO,JOSCSD,
     +          JOSCFB,JOSCOC,JOSCSC,JOSCCS,LOSCOA
      PARAMETER(JOSCID=1,JOSCNA=2,JOSCNS=6,JOSCFS=7,JOSCEB=8,JOSCTS=9,
     +          JOSCRO=10,JOSCSD=11,JOSCFB=12,JOSCOC=13,JOSCSC=14,
     +          JOSCCS=18,LOSCOA=18)
