*CD oslojj
      INTEGER JOSLID,JOSLNA,JOSLPR,JOSLNE,JOSLRO,JOSLSD,JOSLFB,JOSLOS,
     +          JOSLSL,JOSLLS,LOSLOA
      PARAMETER(JOSLID=1,JOSLNA=2,JOSLPR=6,JOSLNE=7,JOSLRO=8,JOSLSD=9,
     +          JOSLFB=10,JOSLOS=11,JOSLSL=12,JOSLLS=16,LOSLOA=16)
