*CD pcaljj
      INTEGER JPCANC,JPCANH,JPCAEC,JPCAS1,JPCAS2,JPCAS3,JPCAS5,JPCAKD,
     +          JPCAFW,LPCALA
      PARAMETER(JPCANC=1,JPCANH=2,JPCAEC=3,JPCAS1=4,JPCAS2=5,JPCAS3=6,
     +          JPCAS5=7,JPCAKD=8,JPCAFW=9,LPCALA=12)
