*CD pfrfjj
      INTEGER JPFRIR,JPFRTL,JPFRP0,JPFRD0,JPFRZ0,JPFRAL,JPFREO,JPFREM,
     +          JPFRC2,JPFRNO,LPFRFA
      PARAMETER(JPFRIR=1,JPFRTL=2,JPFRP0=3,JPFRD0=4,JPFRZ0=5,JPFRAL=6,
     +          JPFREO=7,JPFREM=13,JPFRC2=28,JPFRNO=29,LPFRFA=29)
