*CD pgidjj
      INTEGER JPGIIF,JPGIDE,JPGICM,JPGIM1,JPGIM2,JPGIM3,JPGICE,JPGITH,
     +          JPGIPH,JPGIPE,LPGIDA
      PARAMETER(JPGIIF=1,JPGIDE=2,JPGICM=3,JPGIM1=4,JPGIM2=5,JPGIM3=6,
     +          JPGICE=7,JPGITH=8,JPGIPH=9,JPGIPE=10,LPGIDA=10)
