*CD phmajj
      INTEGER JPHMMH,JPHMIG,JPHMED,JPHMCS,JPHMND,JPHMIE,JPHMIT,JPHMIF,
     +          JPHMTN,LPHMAA
      PARAMETER(JPHMMH=1,JPHMIG=2,JPHMED=3,JPHMCS=4,JPHMND=5,JPHMIE=6,
     +          JPHMIT=7,JPHMIF=8,JPHMTN=9,LPHMAA=9)
