*CD plidjj
      INTEGER JPLIIF,JPLIEC,JPLITC,JPLIPC,JPLIE4,JPLIE1,JPLIE2,JPLIR1,
     +          JPLIR2,JPLIXX,JPLIYY,JPLIXY,JPLIDA,JPLINT,JPLIPE,JPLIPL,
     +          JPLIST,LPLIDA
      PARAMETER(JPLIIF=1,JPLIEC=2,JPLITC=3,JPLIPC=4,JPLIE4=5,JPLIE1=6,
     +          JPLIE2=7,JPLIR1=8,JPLIR2=9,JPLIXX=10,JPLIYY=11,
     +          JPLIXY=12,JPLIDA=13,JPLINT=17,JPLIPE=18,JPLIPL=19,
     +          JPLIST=20,LPLIDA=20)
