*CD pmg1jj
      INTEGER JPMGID,JPMGVR,JPMGNA,JPMGRI,JPMGRO,JPMGZN,JPMGZX,JPMGPN,
     +          JPMGPX,JPMGNM,LPMG1A
      PARAMETER(JPMGID=1,JPMGVR=2,JPMGNA=4,JPMGRI=8,JPMGRO=9,JPMGZN=10,
     +          JPMGZX=11,JPMGPN=12,JPMGPX=13,JPMGNM=14,LPMG1A=14)
