*CD pmskjj
      INTEGER JPMSKT,JPMSEM,JPMSF1,JPMSF3,JPMST1,JPMSP1,JPMST3,JPMSP3,
     +          JPMSTH,JPMSPH,JPMSPF,LPMSKA
      PARAMETER(JPMSKT=1,JPMSEM=2,JPMSF1=3,JPMSF3=4,JPMST1=5,JPMSP1=6,
     +          JPMST3=7,JPMSP3=8,JPMSTH=9,JPMSPH=10,JPMSPF=11,
     +          LPMSKA=11)
