*CD ppobjj
      INTEGER JPPODI,JPPODE,JPPOC1,JPPOC2,JPPOIP,JPPOFP,JPPOLP,JPPOMD,
     +          JPPOPD,LPPOBA
      PARAMETER(JPPODI=1,JPPODE=2,JPPOC1=3,JPPOC2=4,JPPOIP=5,JPPOFP=6,
     +          JPPOLP=7,JPPOMD=8,JPPOPD=9,LPPOBA=9)
