*CD ptmejj
      INTEGER JPTMTN,JPTMMA,JPTMFD,JPTMMS,JPTMDE,JPTMEP,JPTMST,JPTMVO,
     +          JPTMGP,JPTMFL,LPTMEA
      PARAMETER(JPTMTN=1,JPTMMA=5,JPTMFD=9,JPTMMS=10,JPTMDE=11,
     +          JPTMEP=12,JPTMST=13,JPTMVO=14,JPTMGP=15,JPTMFL=16,
     +          LPTMEA=16)
