*CD ptunjj
      INTEGER JPTUID,JPTUVR,JPTURS,JPTUPS,JPTUZS,JPTUSR,JPTUSZ,JPTUPB,
     +          JPTUZB,JPTUTM,JPTUTL,JPTUAD,JPTURP,LPTUNA
      PARAMETER(JPTUID=1,JPTUVR=2,JPTURS=4,JPTUPS=5,JPTUZS=6,JPTUSR=7,
     +          JPTUSZ=8,JPTUPB=9,JPTUZB=10,JPTUTM=11,JPTUTL=12,
     +          JPTUAD=13,JPTURP=14,LPTUNA=14)
