*CD pyv0jj
      INTEGER JPYVK1,JPYVK2,JPYVVX,JPYVVY,JPYVVZ,JPYVVE,JPYVVC,JPYVPX,
     +          JPYVPY,JPYVPZ,JPYVPE,JPYVPC,JPYVX1,JPYVX2,JPYVXE,JPYVXC,
     +          JPYVC2,LPYV0A
      PARAMETER(JPYVK1=1,JPYVK2=2,JPYVVX=3,JPYVVY=4,JPYVVZ=5,JPYVVE=6,
     +          JPYVVC=9,JPYVPX=12,JPYVPY=13,JPYVPZ=14,JPYVPE=15,
     +          JPYVPC=18,JPYVX1=21,JPYVX2=22,JPYVXE=23,JPYVXC=25,
     +          JPYVC2=26,LPYV0A=26)
