*CD qug1jj
      INTEGER JQUGID,JQUGVR,JQUGNA,JQUGRI,JQUGRO,JQUGZN,JQUGX0,JQUGY0,
     +          JQUGNM,LQUG1A
      PARAMETER(JQUGID=1,JQUGVR=2,JQUGNA=4,JQUGRI=8,JQUGRO=9,JQUGZN=10,
     +          JQUGX0=11,JQUGY0=12,JQUGNM=13,LQUG1A=13)
