*CD ralejj
      INTEGER JRALRN,JRALLR,JRALRS,JRALRT,JRALTT,JRALTM,JRALEP,JRALMP,
     +          JRALMC,JRALMA,JRALMB,JRALNA,JRALNB,JRALQA,JRALQB,JRALDU,
     +          JRALCO,JRALVD,JRALIT,JRALTP,JRALEC,JRALHC,JRALMU,JRALSA,
     +          JRALLC,JRALBC,LRALEA
      PARAMETER(JRALRN=1,JRALLR=2,JRALRS=3,JRALRT=4,JRALTT=6,JRALTM=8,
     +          JRALEP=9,JRALMP=13,JRALMC=14,JRALMA=15,JRALMB=16,
     +          JRALNA=17,JRALNB=18,JRALQA=19,JRALQB=20,JRALDU=21,
     +          JRALCO=22,JRALVD=24,JRALIT=26,JRALTP=27,JRALEC=29,
     +          JRALHC=32,JRALMU=35,JRALSA=41,JRALLC=43,JRALBC=45,
     +          LRALEA=46)
