*CD rfunjj
      INTEGER JRFUTR,JRFUWA,JRFUQE,JRFUPE,JRFUQP,JRFUPP,JRFUPZ,JRFUDE,
     +          JRFUZV,LRFUNA
      PARAMETER(JRFUTR=1,JRFUWA=2,JRFUQE=3,JRFUPE=4,JRFUQP=5,JRFUPP=6,
     +          JRFUPZ=7,JRFUDE=11,JRFUZV=15,LRFUNA=18)
