*CD rhohjj
      INTEGER JRHOPN,JRHOPD,JRHOPH,JRHOPV,JRHOAV,JRHODV,JRHODD,JRHONI,
     +          JRHONO,LRHOHA
      PARAMETER(JRHOPN=1,JRHOPD=3,JRHOPH=4,JRHOPV=5,JRHOAV=6,JRHODV=7,
     +          JRHODD=8,JRHONI=9,JRHONO=10,LRHOHA=10)
