*CD rksejj
      INTEGER JRKSVS,JRKSRN,JRKSYG,JRKSND,JRKSLE,JRKSR1,JRKSR2,JRKSKV,
     +          JRKSJV,JRKSGV,JRKSMV,JRKSDV,JRKSNE,JRKSLT,JRKSKX,JRKSKE,
     +          JRKSPX,JRKSPE,JRKSKW,LRKSEA
      PARAMETER(JRKSVS=1,JRKSRN=4,JRKSYG=5,JRKSND=6,JRKSLE=7,JRKSR1=8,
     +          JRKSR2=9,JRKSKV=10,JRKSJV=11,JRKSGV=12,JRKSMV=13,
     +          JRKSDV=14,JRKSNE=15,JRKSLT=16,JRKSKX=17,JRKSKE=18,
     +          JRKSPX=19,JRKSPE=20,JRKSKW=21,LRKSEA=35)
