*CD rtlojj
      INTEGER JRTLPA,JRTLET,JRTLTN,JRTLTM,JRTLT1,JRTLT2,JRTLT3,JRTLR1,
     +          JRTLR2,JRTLEL,JRTLCT,JRTLCH,LRTLOA
      PARAMETER(JRTLPA=1,JRTLET=2,JRTLTN=3,JRTLTM=4,JRTLT1=5,JRTLT2=6,
     +          JRTLT3=7,JRTLR1=8,JRTLR2=9,JRTLEL=10,JRTLCT=11,
     +          JRTLCH=12,LRTLOA=12)
