*CD rxyzjj
      INTEGER JRXYRN,JRXYNV,JRXYFL,JRXYBX,JRXYBY,JRXYBZ,JRXYEX,JRXYEY,
     +          JRXYEZ,JRXYLU,JRXYOF,LRXYZA
      PARAMETER(JRXYRN=1,JRXYNV=2,JRXYFL=3,JRXYBX=4,JRXYBY=5,JRXYBZ=6,
     +          JRXYEX=7,JRXYEY=8,JRXYEZ=9,JRXYLU=10,JRXYOF=11,
     +          LRXYZA=11)
