*CD sbhajj
      INTEGER JSBHME,JSBHES,JSBHET,JSBHDN,JSBHDX,JSBHTI,JSBHTO,JSBHLI,
     +          JSBHLO,JSBHVN,JSBHVX,JSBHHN,JSBHHX,JSBHAC,JSBHCS,JSBHXV,
     +          JSBHXH,JSBHER,JSBHST,JSBHGE,JSBHEG,LSBHAA
      PARAMETER(JSBHME=1,JSBHES=2,JSBHET=3,JSBHDN=4,JSBHDX=5,JSBHTI=6,
     +          JSBHTO=7,JSBHLI=8,JSBHLO=9,JSBHVN=10,JSBHVX=11,
     +          JSBHHN=12,JSBHHX=13,JSBHAC=14,JSBHCS=15,JSBHXV=16,
     +          JSBHXH=17,JSBHER=18,JSBHST=19,JSBHGE=20,JSBHEG=21,
     +          LSBHAA=21)
