*CD sclbjj
      INTEGER JSCLID,JSCLVR,JSCLNW,JSCLCB,JSCLTO,JSCLNP,JSCLTB,JSCLTD,
     +          JSCLTS,JSCLCR,JSCLCH,LSCLBA
      PARAMETER(JSCLID=1,JSCLVR=2,JSCLNW=4,JSCLCB=5,JSCLTO=77,JSCLNP=78,
     +          JSCLTB=79,JSCLTD=80,JSCLTS=81,JSCLCR=181,JSCLCH=187,
     +          LSCLBA=187)
