*CD sclsjj
      INTEGER JSCLEC,JSCLRC,JSCLZC,JSCLPC,JSCLTC,JSCLWP,JSCLWR,JSCLER,
     +          JSCLCR,JSCLCP,JSCLCT,JSCLR3,JSCLE1,JSCLE2,JSCLE3,JSCLOV,
     +          JSCLSP,LSCLSA
      PARAMETER(JSCLEC=1,JSCLRC=2,JSCLZC=3,JSCLPC=4,JSCLTC=5,JSCLWP=6,
     +          JSCLWR=7,JSCLER=8,JSCLCR=9,JSCLCP=10,JSCLCT=11,
     +          JSCLR3=12,JSCLE1=15,JSCLE2=20,JSCLE3=25,JSCLOV=30,
     +          JSCLSP=31,LSCLSA=31)
