*CD sftrjj
      INTEGER JSFTNF,JSFTC2,JSFTQF,JSFTTH,JSFTPH,JSFTX0,JSFTY0,JSFTCM,
     +          JSFTLI,LSFTRA
      PARAMETER(JSFTNF=1,JSFTC2=2,JSFTQF=3,JSFTTH=4,JSFTPH=5,JSFTX0=6,
     +          JSFTY0=7,JSFTCM=8,JSFTLI=18,LSFTRA=18)
