*CD sigojj
      INTEGER JSIGNM,JSIGNR,JSIGNP,JSIGNZ,JSIGRN,JSIGRX,JSIGPS,JSIGZ0,
     +          JSIGZW,JSIGZ1,JSIGZ2,JSIGZF,JSIGZB,JSIGOV,JSIGRF,JSIGRL,
     +          LSIGOA
      PARAMETER(JSIGNM=1,JSIGNR=2,JSIGNP=3,JSIGNZ=4,JSIGRN=5,JSIGRX=6,
     +          JSIGPS=7,JSIGZ0=10,JSIGZW=11,JSIGZ1=12,JSIGZ2=13,
     +          JSIGZF=14,JSIGZB=15,JSIGOV=16,JSIGRF=17,JSIGRL=18,
     +          LSIGOA=18)
