*CD silhjj
      INTEGER JSILGB,JSILHV,JSILT1,JSILT2,JSILTE,JSILLO,JSILS2,JSILDW,
     +          JSILSC,JSILAM,JSILWI,LSILHA
      PARAMETER(JSILGB=1,JSILHV=2,JSILT1=3,JSILT2=4,JSILTE=5,JSILLO=6,
     +          JSILS2=7,JSILDW=8,JSILSC=11,JSILAM=14,JSILWI=15,
     +          LSILHA=15)
