*CD silujj
      INTEGER JSILIS,JSILEC,JSILER,JSILEF,JSILRC,JSILCR,JSILPC,JSILCP,
     +          JSILTC,JSILCT,JSILZC,JSILDR,JSILDP,JSILRI,JSILPI,JSILXI,
     +          JSILYI,JSILXF,JSILYF,JSILNP,JSILND,JSILEP,JSILES,JSILRS,
     +          JSILPS,JSILZS,JSILNS,LSILUA
      PARAMETER(JSILIS=1,JSILEC=2,JSILER=3,JSILEF=4,JSILRC=16,JSILCR=17,
     +          JSILPC=18,JSILCP=19,JSILTC=20,JSILCT=21,JSILZC=22,
     +          JSILDR=23,JSILDP=24,JSILRI=25,JSILPI=26,JSILXI=27,
     +          JSILYI=28,JSILXF=29,JSILYF=30,JSILNP=31,JSILND=32,
     +          JSILEP=33,JSILES=78,JSILRS=79,JSILPS=80,JSILZS=81,
     +          JSILNS=82,LSILUA=82)
