*CD skanjj
      INTEGER JSKASI,JSKANP,JSKAC2,JSKAAX,JSKAAY,JSKAXX,JSKAXY,JSKAYY,
     +          LSKANA
      PARAMETER(JSKASI=1,JSKANP=2,JSKAC2=3,JSKAAX=4,JSKAAY=5,JSKAXX=6,
     +          JSKAXY=7,JSKAYY=8,LSKANA=8)
