*CD slumjj
      INTEGER JSLUSI,JSLUSU,JSLUDP,JSLUTI,JSLUTO,JSLULI,JSLULO,JSLUVR,
     +          JSLUHR,JSLULU,JSLULV,JSLULH,JSLUSE,JSLUSY,LSLUMA
      PARAMETER(JSLUSI=1,JSLUSU=2,JSLUDP=3,JSLUTI=4,JSLUTO=5,JSLULI=6,
     +          JSLULO=7,JSLUVR=8,JSLUHR=9,JSLULU=10,JSLULV=11,
     +          JSLULH=12,JSLUSE=13,JSLUSY=14,LSLUMA=14)
