*CD srktjj
      INTEGER JSRKID,JSRKVR,JSRKTL,JSRKTU,JSRKRU,JSRKSI,JSRKDT,JSRKDS,
     +          JSRKDG,JSRKNP,JSRKCH,JSRKCT,JSRKCP,JSRKZW,JSRKST,JSRKMP,
     +          JSRKMD,LSRKTA
      PARAMETER(JSRKID=1,JSRKVR=2,JSRKTL=4,JSRKTU=5,JSRKRU=6,JSRKSI=7,
     +          JSRKDT=8,JSRKDS=9,JSRKDG=10,JSRKNP=11,JSRKCH=12,
     +          JSRKCT=13,JSRKCP=14,JSRKZW=15,JSRKST=16,JSRKMP=17,
     +          JSRKMD=18,LSRKTA=18)
