*CD stmejj
      INTEGER JSTMTN,JSTMMA,JSTMFD,JSTMMS,JSTMDE,JSTMEP,JSTMST,JSTMVO,
     +          JSTMGP,JSTMFL,LSTMEA
      PARAMETER(JSTMTN=1,JSTMMA=5,JSTMFD=9,JSTMMS=10,JSTMDE=11,
     +          JSTMEP=12,JSTMST=13,JSTMVO=14,JSTMGP=15,JSTMFL=16,
     +          LSTMEA=16)
