*CD strkjj
      INTEGER JSTRNP,JSTRC2,JSTRTH,JSTRPH,JSTRTT,JSTRTP,JSTRPP,JSTRQF,
     +          JSTRLI,LSTRKA
      PARAMETER(JSTRNP=1,JSTRC2=2,JSTRTH=3,JSTRPH=4,JSTRTT=5,JSTRTP=6,
     +          JSTRPP=7,JSTRQF=8,JSTRLI=9,LSTRKA=9)
