*CD tanfjj
      INTEGER JTANFM,JTANFS,JTANTM,JTANTN,JTANTO,JTANRE,JTANTI,JTANTF,
     +          JTANTW,JTANCT,LTANFA
      PARAMETER(JTANFM=1,JTANFS=2,JTANTM=3,JTANTN=4,JTANTO=5,JTANRE=6,
     +          JTANTI=7,JTANTF=8,JTANTW=9,JTANCT=10,LTANFA=10)
