*CD tarcjj
      INTEGER JTARIR,JTARTL,JTARP0,JTARD0,JTARZ0,JTARC1,JTARC2,JTARER,
     +          JTARPI,JTAROF,JTARNC,JTARAN,JTARTN,LTARCA
      PARAMETER(JTARIR=1,JTARTL=2,JTARP0=3,JTARD0=4,JTARZ0=5,JTARC1=6,
     +          JTARC2=7,JTARER=8,JTARPI=13,JTAROF=14,JTARNC=15,
     +          JTARAN=16,JTARTN=17,LTARCA=17)
