*CD tccnjj
      INTEGER JTCCID,JTCCVR,JTCCZT,JTCCZ0,JTCCD0,JTCCRM,JTCCDW,JTCCDZ,
     +          JTCCWS,JTCCZS,JTCCMG,JTCCZN,JTCCPN,JTCCCU,JTCCDT,JTCCMA,
     +          JTCCSW,JTCCSF,JTCCSZ,JTCCCC,JTCCCL,JTCCCJ,JTCCCS,LTCCNA
      PARAMETER(JTCCID=1,JTCCVR=2,JTCCZT=4,JTCCZ0=5,JTCCD0=6,JTCCRM=7,
     +          JTCCDW=8,JTCCDZ=9,JTCCWS=10,JTCCZS=11,JTCCMG=12,
     +          JTCCZN=13,JTCCPN=14,JTCCCU=15,JTCCDT=16,JTCCMA=17,
     +          JTCCSW=18,JTCCSF=19,JTCCSZ=20,JTCCCC=21,JTCCCL=22,
     +          JTCCCJ=23,JTCCCS=24,LTCCNA=24)
