*CD tcgdjj
      INTEGER JTCGID,JTCGVR,JTCGCN,JTCGNS,JTCGNC,JTCGNE,JTCGAS,JTCGRS,
     +          JTCGPH,JTCGPS,JTCGPW,JTCGGW,JTCGEW,JTCGES,JTCGBD,JTCGTS,
     +          JTCGTH,JTCGWP,JTCGWD,JTCGTO,JTCGTT,JTCGWT,JTCGWE,JTCGWW,
     +          JTCGWK,JTCGFT,LTCGDA
      PARAMETER(JTCGID=1,JTCGVR=2,JTCGCN=4,JTCGNS=5,JTCGNC=6,JTCGNE=7,
     +          JTCGAS=8,JTCGRS=9,JTCGPH=10,JTCGPS=11,JTCGPW=12,
     +          JTCGGW=13,JTCGEW=14,JTCGES=15,JTCGBD=16,JTCGTS=17,
     +          JTCGTH=18,JTCGWP=19,JTCGWD=20,JTCGTO=21,JTCGTT=24,
     +          JTCGWT=27,JTCGWE=28,JTCGWW=29,JTCGWK=30,JTCGFT=33,
     +          LTCGDA=33)
