*CD tchajj
      INTEGER JTCHIR,JTCHTL,JTCHP0,JTCHD0,JTCHZ0,JTCHLC,JTCHC1,JTCHC2,
     +          JTCHER,JTCHPI,JTCHOF,JTCHNC,LTCHAA
      PARAMETER(JTCHIR=1,JTCHTL=2,JTCHP0=3,JTCHD0=4,JTCHZ0=5,JTCHLC=6,
     +          JTCHC1=7,JTCHC2=8,JTCHER=9,JTCHPI=24,JTCHOF=25,
     +          JTCHNC=26,LTCHAA=26)
