*CD tclbjj
      INTEGER JTCLCD,JTCLCT,JTCLNT,JTCLPD,JTCLPT,JTCLWT,JTCLPL,JTCLWL,
     +          LTCLBA
      PARAMETER(JTCLCD=1,JTCLCT=2,JTCLNT=3,JTCLPD=4,JTCLPT=5,JTCLWT=6,
     +          JTCLPL=7,JTCLWL=8,LTCLBA=8)
