*CD tdvvjj
      INTEGER JTDVID,JTDVVR,JTDVVX,JTDVVY,JTDVVZ,JTDVEX,JTDVEY,JTDVEZ,
     +          JTDVJV,JTDVCH,JTDVNF,JTDVPR,JTDVTP,LTDVVA
      PARAMETER(JTDVID=1,JTDVVR=2,JTDVVX=4,JTDVVY=5,JTDVVZ=6,JTDVEX=7,
     +          JTDVEY=8,JTDVEZ=9,JTDVJV=10,JTDVCH=11,JTDVNF=12,
     +          JTDVPR=13,JTDVTP=14,LTDVVA=14)
