*CD tdxcjj
      INTEGER JTDXFW,JTDXCT,JTDXTC,JTDXFP,JTDXMI,JTDXMX,JTDXGT,JTDXLI,
     +          JTDXUI,JTDXD0,JTDXZ0,JTDXWT,LTDXCA
      PARAMETER(JTDXFW=1,JTDXCT=2,JTDXTC=3,JTDXFP=4,JTDXMI=5,JTDXMX=6,
     +          JTDXGT=7,JTDXLI=8,JTDXUI=9,JTDXD0=10,JTDXZ0=11,
     +          JTDXWT=12,LTDXCA=12)
