*CD tgftjj
      INTEGER JTGFIR,JTGFTL,JTGFP0,JTGFD0,JTGFZ0,JTGFEM,JTGFCD,JTGFDF,
     +          JTGFTC,LTGFTA
      PARAMETER(JTGFIR=1,JTGFTL=2,JTGFP0=3,JTGFD0=4,JTGFZ0=5,JTGFEM=6,
     +          JTGFCD=21,JTGFDF=22,JTGFTC=23,LTGFTA=23)
