*CD tinfjj
      INTEGER JTINEC,JTINEL,JTINRB,JTINWB,JTINSA,JTINPW,JTINRT,JTINRM,
     +          JTINNM,JTINFM,JTINOL,LTINFA
      PARAMETER(JTINEC=1,JTINEL=2,JTINRB=3,JTINWB=4,JTINSA=5,JTINPW=6,
     +          JTINRT=7,JTINRM=8,JTINNM=9,JTINFM=10,JTINOL=11,
     +          LTINFA=11)
