*CD tlasjj
      INTEGER JTLALR,JTLAET,JTLALV,JTLALE,JTLALC,JTLANV,JTLANE,JTLANC,
     +          JTLAEF,JTLACF,LTLASA
      PARAMETER(JTLALR=1,JTLAET=2,JTLALV=3,JTLALE=4,JTLALC=5,JTLANV=6,
     +          JTLANE=7,JTLANC=8,JTLAEF=9,JTLACF=10,LTLASA=10)
