*CD tlcpjj
      INTEGER JTLCID,JTLCVR,JTLCA1,JTLCA2,JTLCA3,JTLCB1,JTLCB2,JTLCB3,
     +          LTLCPA
      PARAMETER(JTLCID=1,JTLCVR=2,JTLCA1=4,JTLCA2=5,JTLCA3=6,JTLCB1=7,
     +          JTLCB2=8,JTLCB3=9,LTLCPA=9)
