*CD tmtyjj
      INTEGER JTMTID,JTMTVR,JTMTMO,JTMTPP,JTMTRF,JTMTNP,JTMTPR,JTMTRT,
     +          JTMTNT,JTMTTR,JTMTAT,JTMTTC,JTMTPW,JTMTNW,JTMTEF,JTMTEL,
     +          JTMTWF,LTMTYA
      PARAMETER(JTMTID=1,JTMTVR=2,JTMTMO=4,JTMTPP=5,JTMTRF=6,JTMTNP=7,
     +          JTMTPR=8,JTMTRT=20,JTMTNT=21,JTMTTR=22,JTMTAT=33,
     +          JTMTTC=34,JTMTPW=38,JTMTNW=39,JTMTEF=40,JTMTEL=41,
     +          JTMTWF=42,LTMTYA=45)
