*CD tncojj
      INTEGER JTNCID,JTNCVR,JTNCSN,JTNCNS,JTNCRP,JTNCAZ,JTNCAX,JTNCAY,
     +          JTNCSG,JTNCTC,LTNCOA
      PARAMETER(JTNCID=1,JTNCVR=2,JTNCSN=4,JTNCNS=5,JTNCRP=6,JTNCAZ=9,
     +          JTNCAX=10,JTNCAY=11,JTNCSG=12,JTNCTC=13,LTNCOA=13)
