*CD tnlojj
      INTEGER JTNLID,JTNLVR,JTNLSN,JTNLSB,JTNLSS,JTNLDS,JTNLAS,JTNLRS,
     +          JTNLDZ,JTNLRZ,JTNLAZ,JTNLTM,JTNLTN,LTNLOA
      PARAMETER(JTNLID=1,JTNLVR=2,JTNLSN=4,JTNLSB=5,JTNLSS=6,JTNLDS=7,
     +          JTNLAS=8,JTNLRS=9,JTNLDZ=10,JTNLRZ=11,JTNLAZ=12,
     +          JTNLTM=13,JTNLTN=14,LTNLOA=14)
