*CD tpcojj
      INTEGER JTPCIN,JTPCRV,JTPCPH,JTPCZV,JTPCSR,JTPCSZ,JTPCOF,JTPCTN,
     +          JTPCCN,JTPCIT,JTPCRR,JTPCRZ,LTPCOA
      PARAMETER(JTPCIN=1,JTPCRV=2,JTPCPH=3,JTPCZV=4,JTPCSR=5,JTPCSZ=6,
     +          JTPCOF=7,JTPCTN=8,JTPCCN=9,JTPCIT=10,JTPCRR=11,
     +          JTPCRZ=12,LTPCOA=12)
