*CD tptejj
      INTEGER JTPTKT,JTPTXA,JTPTYA,JTPTZA,JTPTDX,JTPTDY,JTPTDZ,JTPTPV,
     +          JTPTLN,JTPTTF,JTPTPM,JTPTCH,LTPTEA
      PARAMETER(JTPTKT=1,JTPTXA=2,JTPTYA=3,JTPTZA=4,JTPTDX=5,JTPTDY=6,
     +          JTPTDZ=7,JTPTPV=8,JTPTLN=9,JTPTTF=10,JTPTPM=11,
     +          JTPTCH=12,LTPTEA=12)
