*CD tscljj
      INTEGER JTSCNS,JTSCPO,JTSCFP,JTSCNC,JTSCCO,JTSCTC,JTSCAW,JTSCQU,
     +          JTSCSP,JTSCSB,JTSCCR,JTSCCL,LTSCLA
      PARAMETER(JTSCNS=1,JTSCPO=2,JTSCFP=3,JTSCNC=4,JTSCCO=5,JTSCTC=6,
     +          JTSCAW=7,JTSCQU=8,JTSCSP=9,JTSCSB=10,JTSCCR=11,
     +          JTSCCL=12,LTSCLA=12)
