*CD tscojj
      INTEGER JTSCID,JTSCVR,JTSCSN,JTSCNS,JTSCRP,JTSCAZ,JTSCAX,JTSCAY,
     +          JTSCSG,JTSCTC,LTSCOA
      PARAMETER(JTSCID=1,JTSCVR=2,JTSCSN=4,JTSCNS=5,JTSCRP=6,JTSCAZ=9,
     +          JTSCAX=10,JTSCAY=11,JTSCSG=12,JTSCTC=13,LTSCOA=13)
