*CD tslojj
      INTEGER JTSLID,JTSLVR,JTSLSN,JTSLSB,JTSLSS,JTSLDS,JTSLAS,JTSLRS,
     +          JTSLTM,JTSLTS,LTSLOA
      PARAMETER(JTSLID=1,JTSLVR=2,JTSLSN=4,JTSLSB=5,JTSLSS=6,JTSLDS=7,
     +          JTSLAS=8,JTSLRS=9,JTSLTM=10,JTSLTS=11,LTSLOA=11)
