*CD tsorjj
      INTEGER JTSOFI,JTSOBF,JTSOSW,JTSOWG,JTSOLE,JTSOCC,JTSOPW,JTSOCH,
     +          JTSOCL,JTSORR,JTSOS1,JTSOS2,JTSOD1,JTSOD2,JTSODE,JTSODL,
     +          JTSOAP,JTSOAT,JTSOGP,JTSOGT,LTSORA
      PARAMETER(JTSOFI=1,JTSOBF=2,JTSOSW=3,JTSOWG=4,JTSOLE=5,JTSOCC=6,
     +          JTSOPW=7,JTSOCH=8,JTSOCL=9,JTSORR=10,JTSOS1=11,
     +          JTSOS2=12,JTSOD1=13,JTSOD2=14,JTSODE=15,JTSODL=16,
     +          JTSOAP=17,JTSOAT=18,JTSOGP=19,JTSOGT=20,LTSORA=20)
