*CD tspujj
      INTEGER JTSPTC,JTSPPC,JTSPPT,JTSPIT,JTSPT1,JTSPT2,JTSPQF,JTSPPN,
     +          JTSPSC,LTSPUA
      PARAMETER(JTSPTC=1,JTSPPC=2,JTSPPT=3,JTSPIT=4,JTSPT1=5,JTSPT2=6,
     +          JTSPQF=7,JTSPPN=8,JTSPSC=9,LTSPUA=9)
