*CD tswpjj
      INTEGER JTSWML,JTSWMX,JTSWPS,JTSWPO,JTSWPD,JTSWTH,JTSWMA,JTSWMS,
     +          JTSWCN,JTSWR1,JTSWR2,JTSWR3,JTSWR4,JTSWR5,JTSWR6,JTSWR7,
     +          LTSWPA
      PARAMETER(JTSWML=1,JTSWMX=2,JTSWPS=3,JTSWPO=4,JTSWPD=5,JTSWTH=6,
     +          JTSWMA=7,JTSWMS=8,JTSWCN=9,JTSWR1=10,JTSWR2=11,
     +          JTSWR3=12,JTSWR4=13,JTSWR5=14,JTSWR6=15,JTSWR7=16,
     +          LTSWPA=16)
