*CD ttrcjj
      INTEGER JTTRID,JTTRVR,JTTRNT,JTTRNG,JTTRNM,JTTRDP,JTTRDZ,JTTRRR,
     +          JTTRRZ,JTTRCC,JTTRSU,JTTRST,JTTRSI,JTTRLM,JTTRMK,JTTRD2,
     +          JTTRPM,LTTRCA
      PARAMETER(JTTRID=1,JTTRVR=2,JTTRNT=4,JTTRNG=5,JTTRNM=6,JTTRDP=7,
     +          JTTRDZ=8,JTTRRR=9,JTTRRZ=10,JTTRCC=11,JTTRSU=12,
     +          JTTRST=13,JTTRSI=14,JTTRLM=15,JTTRMK=16,JTTRD2=17,
     +          JTTRPM=18,LTTRCA=18)
