*CD twcojj
      INTEGER JTWCFL,JTWCSG,JTWCUF,JTWCZF,JTWCE0,JTWCE1,JTWCC0,JTWCC1,
     +          JTWCC2,JTWCC3,LTWCOA
      PARAMETER(JTWCFL=1,JTWCSG=2,JTWCUF=3,JTWCZF=4,JTWCE0=5,JTWCE1=6,
     +          JTWCC0=7,JTWCC1=8,JTWCC2=9,JTWCC3=10,LTWCOA=10)
