*CD twnfjj
      INTEGER JTWNFM,JTWNFS,JTWNTM,JTWNTN,JTWNTO,JTWNRE,JTWNTI,JTWNTF,
     +          JTWNTW,JTWNCT,LTWNFA
      PARAMETER(JTWNFM=1,JTWNFS=2,JTWNTM=3,JTWNTN=4,JTWNTO=5,JTWNRE=6,
     +          JTWNTI=7,JTWNTF=8,JTWNTW=9,JTWNCT=10,LTWNFA=10)
