*CD twrcjj
      INTEGER JTWRID,JTWRVR,JTWRMV,JTWRTP,JTWRMS,JTWRRM,JTWRAL,JTWRSD,
     +          JTWRSZ,LTWRCA
      PARAMETER(JTWRID=1,JTWRVR=2,JTWRMV=4,JTWRTP=5,JTWRMS=6,JTWRRM=7,
     +          JTWRAL=8,JTWRSD=9,JTWRSZ=10,LTWRCA=10)
