*CD twtcjj
      INTEGER JTWTID,JTWTVR,JTWTFC,JTWTMT,JTWTCM,JTWTZW,JTWTSP,JTWTMS,
     +          JTWTMD,JTWTMK,JTWTRM,JTWTZS,LTWTCA
      PARAMETER(JTWTID=1,JTWTVR=2,JTWTFC=4,JTWTMT=5,JTWTCM=6,JTWTZW=7,
     +          JTWTSP=8,JTWTMS=9,JTWTMD=10,JTWTMK=11,JTWTRM=12,
     +          JTWTZS=13,LTWTCA=13)
