*CD vcabjj
      INTEGER JVCAAL,JVCAAF,JVCAAW,JVCAAV,JVCATL,JVCATF,JVCATW,JVCATV,
     +          LVCABA
      PARAMETER(JVCAAL=1,JVCAAF=2,JVCAAW=3,JVCAAV=4,JVCATL=5,JVCATF=6,
     +          JVCATW=7,JVCATV=8,LVCABA=8)
