*CD vcsgjj
      INTEGER JVCSRP,JVCSMP,JVCSRF,JVCSSG,JVCSFF,JVCSSA,JVCSMF,JVCSCM,
     +          LVCSGA
      PARAMETER(JVCSRP=1,JVCSMP=2,JVCSRF=5,JVCSSG=6,JVCSFF=7,JVCSSA=8,
     +          JVCSMF=11,JVCSCM=14,LVCSGA=14)
