*CD vdeljj
      INTEGER JVDEST,JVDEEC,JVDENL,JVDENC,JVDENE,JVDEPN,JVDEIC,JVDEPC,
     +          JVDEEG,LVDELA
      PARAMETER(JVDEST=1,JVDEEC=3,JVDENL=5,JVDENC=6,JVDENE=7,JVDEPN=8,
     +          JVDEIC=9,JVDEPC=10,JVDEEG=11,LVDELA=11)
