*CD vdepjj
      INTEGER JVDEEM,JVDEHM,JVDEET,JVDEHT,JVDEHE,JVDEHH,JVDEAV,JVDEDV,
     +          JVDEST,JVDEEC,JVDENL,JVDENC,JVDESN,JVDENE,JVDEPN,JVDEIC,
     +          JVDEMF,JVDEEG,LVDEPA
      PARAMETER(JVDEEM=1,JVDEHM=2,JVDEET=3,JVDEHT=4,JVDEHE=5,JVDEHH=6,
     +          JVDEAV=7,JVDEDV=8,JVDEST=9,JVDEEC=11,JVDENL=13,
     +          JVDENC=14,JVDESN=16,JVDENE=18,JVDEPN=20,JVDEIC=22,
     +          JVDEMF=24,JVDEEG=25,LVDEPA=25)
