*CD vdhtjj
      INTEGER JVDHTN,JVDHLN,JVDHPN,JVDHXE,JVDHYE,JVDHZE,JVDHXL,JVDHYL,
     +          JVDHZL,JVDHER,LVDHTA
      PARAMETER(JVDHTN=1,JVDHLN=2,JVDHPN=3,JVDHXE=4,JVDHYE=5,JVDHZE=6,
     +          JVDHXL=7,JVDHYL=8,JVDHZL=9,JVDHER=10,LVDHTA=10)
