*CD vdlhjj
      INTEGER JVDLXI,JVDLXO,JVDLMO,JVDLWA,JVDLCO,JVDLER,JVDLTR,JVDLHT,
     +          LVDLHA
      PARAMETER(JVDLXI=1,JVDLXO=4,JVDLMO=7,JVDLWA=8,JVDLCO=9,JVDLER=10,
     +          JVDLTR=11,JVDLHT=12,LVDLHA=12)
