*CD vdmejj
      INTEGER JVDMAL,JVDMTI,JVDMTR,JVDMER,JVDMCB,JVDMCA,JVDMCR,JVDMCT,
     +          JVDMSA,JVDMGA,JVDMSP,JVDMNS,LVDMEA
      PARAMETER(JVDMAL=1,JVDMTI=3,JVDMTR=5,JVDMER=6,JVDMCB=8,JVDMCA=9,
     +          JVDMCR=10,JVDMCT=11,JVDMSA=12,JVDMGA=13,JVDMSP=14,
     +          JVDMNS=15,LVDMEA=15)
