*CD vdmsjj
      INTEGER JVDMWI,JVDMFL,JVDMRA,JVDMUC,JVDMWC,JVDMPV,JVDMPU,JVDMPW,
     +          JVDMCU,JVDMSG,LVDMSA
      PARAMETER(JVDMWI=1,JVDMFL=2,JVDMRA=3,JVDMUC=4,JVDMWC=5,JVDMPV=6,
     +          JVDMPU=7,JVDMPW=8,JVDMCU=9,JVDMSG=10,LVDMSA=10)
