*CD vdspjj
      INTEGER JVDSBA,JVDSVN,JVDSDN,JVDSDV,JVDSOF,JVDSML,JVDSMS,JVDSMT,
     +          JVDSCH,JVDSCB,JVDSCT,LVDSPA
      PARAMETER(JVDSBA=1,JVDSVN=2,JVDSDN=3,JVDSDV=4,JVDSOF=5,JVDSML=6,
     +          JVDSMS=14,JVDSMT=22,JVDSCH=30,JVDSCB=31,JVDSCT=32,
     +          LVDSPA=32)
