*CD vdssjj
      INTEGER JVDSTN,JVDSLN,JVDSPN,JVDSXE,JVDSYE,JVDSZE,JVDSXL,JVDSYL,
     +          JVDSZL,JVDSER,JVDSRN,JVDSES,LVDSSA
      PARAMETER(JVDSTN=1,JVDSLN=2,JVDSPN=3,JVDSXE=4,JVDSYE=5,JVDSZE=6,
     +          JVDSXL=7,JVDSYL=8,JVDSZL=9,JVDSER=10,JVDSRN=11,
     +          JVDSES=12,LVDSSA=12)
