*CD vdxyjj
      INTEGER JVDXXC,JVDXYC,JVDXUC,JVDXSX,JVDXSY,JVDXSU,JVDXPH,JVDXQF,
     +          JVDXNA,JVDXIP,JVDXIW,JVDXIH,LVDXYA
      PARAMETER(JVDXXC=1,JVDXYC=2,JVDXUC=3,JVDXSX=4,JVDXSY=5,JVDXSU=6,
     +          JVDXPH=7,JVDXQF=8,JVDXNA=9,JVDXIP=10,JVDXIW=11,
     +          JVDXIH=12,LVDXYA=12)
