*CD vglbjj
      INTEGER JVGLNS,JVGLME,JVGLPN,JVGLPT,JVGLP2,JVGLNP,JVGLOP,JVGLMK,
     +          JVGLBS,JVGLMF,JVGLUI,JVGLFC,JVGLPK,JVGLPS,LVGLBA
      PARAMETER(JVGLNS=1,JVGLME=2,JVGLPN=3,JVGLPT=4,JVGLP2=5,JVGLNP=6,
     +          JVGLOP=7,JVGLMK=8,JVGLBS=9,JVGLMF=10,JVGLUI=11,
     +          JVGLFC=12,JVGLPK=13,JVGLPS=14,LVGLBA=14)
