*CD vhybjj
      INTEGER JVHYLO,JVHYLT,JVHYLH,JVHYLF,JVHYLI,JVHYCE,JVHYCW,JVHYCL,
     +          JVHYCT,JVHYSP,LVHYBA
      PARAMETER(JVHYLO=1,JVHYLT=2,JVHYLH=3,JVHYLF=4,JVHYLI=5,JVHYCE=6,
     +          JVHYCW=7,JVHYCL=8,JVHYCT=9,JVHYSP=10,LVHYBA=11)
