*CD vrcnjj
      INTEGER JVRCMX,JVRCMF,JVRCMH,JVRCMN,JVRCPU,JVRCCM,JVRCMU,JVRCMS,
     +          JVRCFS,JVRCHC,JVRCLC,JVRCMZ,JVRCMP,LVRCNA
      PARAMETER(JVRCMX=1,JVRCMF=2,JVRCMH=3,JVRCMN=4,JVRCPU=5,JVRCCM=6,
     +          JVRCMU=7,JVRCMS=8,JVRCFS=9,JVRCHC=10,JVRCLC=11,
     +          JVRCMZ=12,JVRCMP=13,LVRCNA=13)
