*CD vrdojj
      INTEGER JVRDRZ,JVRDRP,JVRDFZ,JVRDFP,JVRDOZ,JVRDOP,JVRDSZ,JVRDDZ,
     +          JVRDDP,JVRDEZ,JVRDEP,JVRDWB,LVRDOA
      PARAMETER(JVRDRZ=1,JVRDRP=2,JVRDFZ=3,JVRDFP=4,JVRDOZ=5,JVRDOP=6,
     +          JVRDSZ=7,JVRDDZ=8,JVRDDP=9,JVRDEZ=10,JVRDEP=11,
     +          JVRDWB=12,LVRDOA=12)
