*CD vrldjj
      INTEGER JVRLBR,JVRLBL,JVRLIR,JVRLIL,JVRLIG,JVRLIT,JVRLTL,JVRLTG,
     +          JVRLZI,JVRLZO,JVRLII,JVRLIO,JVRLOI,JVRLOO,JVRLSI,JVRLSO,
     +          LVRLDA
      PARAMETER(JVRLBR=1,JVRLBL=2,JVRLIR=3,JVRLIL=4,JVRLIG=5,JVRLIT=6,
     +          JVRLTL=7,JVRLTG=8,JVRLZI=9,JVRLZO=10,JVRLII=11,
     +          JVRLIO=12,JVRLOI=13,JVRLOO=14,JVRLSI=15,JVRLSO=16,
     +          LVRLDA=16)
