*CD vtcejj
      INTEGER JVTCEL,JVTCES,JVTCIU,JVTCOU,JVTCLW,JVTCOW,JVTCUN,JVTCWN,
     +          JVTCMS,JVTCAC,JVTCDF,JVTCNP,JVTCRH,LVTCEA
      PARAMETER(JVTCEL=1,JVTCES=2,JVTCIU=3,JVTCOU=4,JVTCLW=5,JVTCOW=6,
     +          JVTCUN=7,JVTCWN=8,JVTCMS=9,JVTCAC=10,JVTCDF=11,
     +          JVTCNP=12,JVTCRH=13,LVTCEA=13)
