*CD vtmajj
      INTEGER JVTMNL,JVTMNU,JVTMNW,JVTMC2,JVTMIT,JVTMFR,JVTMUW,JVTMWW,
     +          JVTMIU,JVTMIW,JVTMWI,JVTMR0,JVTMPH,JVTMZ0,JVTMUC,JVTMWC,
     +          JVTMSU,JVTMSW,JVTMCO,LVTMAA
      PARAMETER(JVTMNL=1,JVTMNU=2,JVTMNW=3,JVTMC2=4,JVTMIT=5,JVTMFR=6,
     +          JVTMUW=7,JVTMWW=11,JVTMIU=15,JVTMIW=19,JVTMWI=23,
     +          JVTMR0=27,JVTMPH=31,JVTMZ0=35,JVTMUC=39,JVTMWC=43,
     +          JVTMSU=47,JVTMSW=51,JVTMCO=55,LVTMAA=58)
