*CD vtmejj
      INTEGER JVTMTN,JVTMMA,JVTMFD,JVTMMS,JVTMDE,JVTMEP,JVTMST,JVTMVO,
     +          JVTMGP,JVTMFL,LVTMEA
      PARAMETER(JVTMTN=1,JVTMMA=5,JVTMFD=9,JVTMMS=10,JVTMDE=11,
     +          JVTMEP=12,JVTMST=13,JVTMVO=14,JVTMGP=15,JVTMFL=16,
     +          LVTMEA=16)
