*CD vtrajj
      INTEGER JVTRRA,JVTRRB,JVTRRC,JVTRNC,JVTRNS,JVTRNW,JVTREC,JVTRAN,
     +          LVTRAA
      PARAMETER(JVTRRA=1,JVTRRB=2,JVTRRC=3,JVTRNC=4,JVTRNS=5,JVTRNW=6,
     +          JVTREC=7,JVTRAN=8,LVTRAA=8)
