*CD vtrpjj
      INTEGER JVTRMC,JVTRML,JVTRFN,JVTRSC,JVTRCC,JVTRCI,JVTRMP,JVTRBE,
     +          JVTRUS,JVTRWS,JVTRUP,JVTRWP,LVTRPA
      PARAMETER(JVTRMC=1,JVTRML=2,JVTRFN=3,JVTRSC=4,JVTRCC=5,JVTRCI=6,
     +          JVTRMP=7,JVTRBE=8,JVTRUS=9,JVTRWS=10,JVTRUP=11,
     +          JVTRWP=12,LVTRPA=12)
