*CD vwgejj
      INTEGER JVWGSA,JVWGSB,JVWGNZ,JVWGNP,JVWGPZ,JVWGPP,JVWGLZ,JVWGLP,
     +          JVWGAZ,JVWGAP,JVWGBZ,JVWGBP,JVWGWT,LVWGEA
      PARAMETER(JVWGSA=1,JVWGSB=2,JVWGNZ=3,JVWGNP=4,JVWGPZ=5,JVWGPP=6,
     +          JVWGLZ=7,JVWGLP=8,JVWGAZ=9,JVWGAP=10,JVWGBZ=11,
     +          JVWGBP=12,JVWGWT=13,LVWGEA=13)
