*CD vwgmjj
      INTEGER JVWGNS,JVWGDI,JVWGRS,JVWGRP,JVWGSL,JVWGTK,JVWGAV,JVWGDV,
     +          LVWGMA
      PARAMETER(JVWGNS=1,JVWGDI=3,JVWGRS=5,JVWGRP=7,JVWGSL=9,JVWGTK=11,
     +          JVWGAV=12,JVWGDV=13,LVWGMA=13)
