*CD xcntjj
      INTEGER JXCNBP,JXCNBB,JXCNGB,JXCNL1,JXCNL2,JXCNBL,JXCNTV,JXCNGA,
     +          JXCNEB,JXCNNL,JXCNGL,JXCNNB,JXCNLY,JXCNBU,JXCNPV,JXCNRE,
     +          LXCNTA
      PARAMETER(JXCNBP=1,JXCNBB=2,JXCNGB=3,JXCNL1=4,JXCNL2=5,JXCNBL=6,
     +          JXCNTV=7,JXCNGA=8,JXCNEB=9,JXCNNL=10,JXCNGL=11,
     +          JXCNNB=12,JXCNLY=13,JXCNBU=14,JXCNPV=15,JXCNRE=16,
     +          LXCNTA=20)
