*CD xsgejj
      INTEGER JXSGGS,JXSGTR,JXSGTO,JXSGNE,JXSGEB,JXSG1A,JXSG1S,JXSGCN,
     +          JXSGER,JXSGRV,LXSGEA
      PARAMETER(JXSGGS=1,JXSGTR=2,JXSGTO=3,JXSGNE=4,JXSGEB=5,JXSG1A=6,
     +          JXSG1S=7,JXSGCN=8,JXSGER=9,JXSGRV=10,LXSGEA=15)
