*CD xtbnjj
      INTEGER JXTBID,JXTBVR,JXTBTN,JXTBTB,JXTBBM,JXTBBN,JXTBAD,JXTBL1,
     +          JXTBL2,LXTBNA
      PARAMETER(JXTBID=1,JXTBVR=2,JXTBTN=4,JXTBTB=5,JXTBBM=6,JXTBBN=8,
     +          JXTBAD=18,JXTBL1=23,JXTBL2=24,LXTBNA=24)
