*CD xtebjj
      INTEGER JXTET1,JXTET2,JXTEL2,JXTEHT,JXTEHW,JXTELW,JXTEEW,JXTELT,
     +          JXTETE,JXTEIT,JXTETP,LXTEBA
      PARAMETER(JXTET1=1,JXTET2=2,JXTEL2=3,JXTEHT=4,JXTEHW=16,JXTELW=28,
     +          JXTEEW=40,JXTELT=52,JXTETE=56,JXTEIT=58,JXTETP=62,
     +          LXTEBA=65)
