*CD ycftjj
      INTEGER JYCFIR,JYCFTL,JYCFP0,JYCFD0,JYCFZ0,JYCFEM,JYCFC2,JYCFDF,
     +          JYCFCH,JYCFND,JYCFPT,JYCFNM,JYCFPM,JYCFPV,JYCFPC,LYCFTA
      PARAMETER(JYCFIR=1,JYCFTL=2,JYCFP0=3,JYCFD0=4,JYCFZ0=5,JYCFEM=6,
     +          JYCFC2=21,JYCFDF=22,JYCFCH=23,JYCFND=24,JYCFPT=25,
     +          JYCFNM=26,JYCFPM=27,JYCFPV=28,JYCFPC=29,LYCFTA=29)
