*CD ykcijj
      INTEGER JYKCFI,JYKCFO,JYKCFZ,JYKCMX,JYKCMZ,JYKCNB,JYKCCC,JYKCTC,
     +          JYKCVC,JYKCVD,JYKCV2,LYKCIA
      PARAMETER(JYKCFI=1,JYKCFO=2,JYKCFZ=3,JYKCMX=4,JYKCMZ=5,JYKCNB=6,
     +          JYKCCC=7,JYKCTC=8,JYKCVC=9,JYKCVD=10,JYKCV2=11,
     +          LYKCIA=11)
