*CD ynftjj
      INTEGER JYNFMO,JYNFTL,JYNFP0,JYNFD0,JYNFZ0,JYNFEM,JYNFC2,JYNFDF,
     +          JYNFCH,JYNFND,JYNFPT,JYNFNM,JYNFPM,JYNFPV,JYNFPC,LYNFTA
      PARAMETER(JYNFMO=1,JYNFTL=2,JYNFP0=3,JYNFD0=4,JYNFZ0=5,JYNFEM=6,
     +          JYNFC2=21,JYNFDF=22,JYNFCH=23,JYNFND=24,JYNFPT=25,
     +          JYNFNM=26,JYNFPM=27,JYNFPV=28,JYNFPC=29,LYNFTA=29)
