*CD ynmajj
      INTEGER JYNMMT,JYNMPA,JYNMMA,JYNMEM,JYNMVD,JYNMVS,JYNMIC,JYNMNA,
     +          JYNMPR,LYNMAA
      PARAMETER(JYNMMT=1,JYNMPA=2,JYNMMA=3,JYNMEM=4,JYNMVD=5,JYNMVS=6,
     +          JYNMIC=7,JYNMNA=8,JYNMPR=9,LYNMAA=10)
