*CD ysctjj
      INTEGER JYSCPV,JYSCSM,JYSCC2,JYSCRL,JYSCRH,JYSCDR,JYSCCF,JYSCRM,
     +          JYSCS1,JYSCS2,LYSCTA
      PARAMETER(JYSCPV=1,JYSCSM=2,JYSCC2=3,JYSCRL=4,JYSCRH=5,JYSCDR=6,
     +          JYSCCF=7,JYSCRM=8,JYSCS1=9,JYSCS2=10,LYSCTA=10)
