*CD ysmojj
      INTEGER JYSMTN,JYSMSC,JYSMPI,JYSMPO,JYSMPS,JYSMPC,JYSMIO,JYSMXP,
     +          JYSMYP,JYSMZP,LYSMOA
      PARAMETER(JYSMTN=1,JYSMSC=2,JYSMPI=3,JYSMPO=4,JYSMPS=5,JYSMPC=6,
     +          JYSMIO=7,JYSMXP=8,JYSMYP=9,JYSMZP=10,LYSMOA=10)
