*CD ysvtjj
      INTEGER JYSVTN,JYSVSC,JYSVPI,JYSVPO,JYSVPS,JYSVPC,JYSVIO,JYSVXP,
     +          JYSVYP,JYSVZP,LYSVTA
      PARAMETER(JYSVTN=1,JYSVSC=2,JYSVPI=3,JYSVPO=4,JYSVPS=5,JYSVPC=6,
     +          JYSVIO=7,JYSVXP=8,JYSVYP=9,JYSVZP=10,LYSVTA=10)
