*CD ysvxjj
      INTEGER JYSVVX,JYSVVY,JYSVVZ,JYSVVM,JYSVC2,JYSVDF,JYSVOF,JYSVTM,
     +          JYSVCM,JYSV0M,JYSVPX,JYSVPY,JYSVPZ,JYSVPM,JYSVQU,LYSVXA
      PARAMETER(JYSVVX=1,JYSVVY=2,JYSVVZ=3,JYSVVM=4,JYSVC2=10,JYSVDF=11,
     +          JYSVOF=12,JYSVTM=13,JYSVCM=16,JYSV0M=17,JYSVPX=18,
     +          JYSVPY=19,JYSVPZ=20,JYSVPM=21,JYSVQU=27,LYSVXA=27)
