*CD ytcpjj
      INTEGER JYTCVC,JYTCPC,JYTCRD,JYTCMM,JYTCZD,JYTCNA,JYTCLI,JYTCHI,
     +          LYTCPA
      PARAMETER(JYTCVC=1,JYTCPC=2,JYTCRD=3,JYTCMM=4,JYTCZD=5,JYTCNA=6,
     +          JYTCLI=7,JYTCHI=8,LYTCPA=8)
