*CD ytrljj
      INTEGER JYTRIR,JYTRTL,JYTRP0,JYTRD0,JYTRZ0,JYTREM,JYTRVN,JYTRTN,
     +          LYTRLA
      PARAMETER(JYTRIR=1,JYTRTL=2,JYTRP0=3,JYTRD0=4,JYTRZ0=5,JYTREM=6,
     +          JYTRVN=12,JYTRTN=13,LYTRLA=13)
