*CD ytvpjj
      INTEGER JYTVVC,JYTVPC,JYTVDC,JYTVMD,JYTVZD,JYTVNA,JYTVPI,JYTVPR,
     +          JYTVPJ,LYTVPA
      PARAMETER(JYTVVC=1,JYTVPC=2,JYTVDC=3,JYTVMD=4,JYTVZD=5,JYTVNA=6,
     +          JYTVPI=7,JYTVPR=8,JYTVPJ=9,LYTVPA=9)
