*CD yvncjj
      INTEGER JYVNO1,JYVNO2,JYVNCT,JYVNPS,JYVNRV,JYVNZV,JYVNDI,JYVNC2,
     +          JYVNCS,JYVNCO,JYVNPM,JYVNNT,JYVNNC,JYVNMD,JYVNDZ,JYVNZZ,
     +          LYVNCA
      PARAMETER(JYVNO1=1,JYVNO2=2,JYVNCT=3,JYVNPS=4,JYVNRV=5,JYVNZV=6,
     +          JYVNDI=7,JYVNC2=8,JYVNCS=9,JYVNCO=10,JYVNPM=11,
     +          JYVNNT=12,JYVNNC=13,JYVNMD=14,JYVNDZ=15,JYVNZZ=16,
     +          LYVNCA=16)
