*CD yvxljj
      INTEGER JYVXVT,JYVXXP,JYVXYP,JYVXZP,JYVXEM,JYVXCH,JYVXDF,JYVXOF,
     +          JYVXNT,LYVXLA
      PARAMETER(JYVXVT=1,JYVXXP=2,JYVXYP=3,JYVXZP=4,JYVXEM=5,JYVXCH=11,
     +          JYVXDF=12,JYVXOF=13,JYVXNT=14,LYVXLA=14)
