C     ------CSYSBOS
C     COMMENT FOR COMMON/SYSBOS/
C
C     COMMON/SYSBOS/
C
C     NSYST        NUMBER OF SYSTEM WORDS IN EACH ARRAY
C     NAMES        MAX. NUMBER OF NAMES
C     NPRIM        PRIME NUMBER FOR HASH SEARCH
C     IDNAM        INDEX OF WORK BANK WITH NAMES
C     IDPTR        INDEX OF WORK BANK WITH POINTERS
C     IDFMT        INDEX OF WORK BANK WITH FORMAT INDICES
C     NDUMM        -
C     NRESR        NUMBER OF RESERVED WORDS (WBANK)
C     NLPLM        NUMBER OF BANKS FOR GIVEN NAME WITHOUT LINK BANK
C     NARR         NUMBER OF INITIALIZED ARRAYS
C     IARR(10)     ARRAY ADRESSES
C     IEFMT        ERROR FLAG FOR FORMATS
C     TLEFT        TIME LEFT AT START OF BOS
C     LEPIO        INIT FLAG FOR EPIO PACKAGE
C     NAMI         NAME INDEX
C     INDI         LAST INDEX
C     INDJ         INDEX ORIGIN OF INDI
C     INTA(200)    INTERMEDIATE ARRAY
C     ------
