#if defined(DESYIBM)
*     USES ASSEMBLER FUNCTION
      CALL DELAY(NHSEC)
#else
#if defined(ALEPH_DEC) &&  ! defined(UNIX)
*     PAUSE TASK FOR A FIXED PERIOD
*     ITIME IA NR OF UNITS WHERE A UNIT IS 10 MSEC
      IMPLICIT INTEGER*4 (A-Z)
      INTEGER IDELT(2)
      INTEGER MSEC
      DATA MSEC/10/
      IDELT(1)=SYS$SCHDWK(,,IDELT,)
      IDELT(2)=SYS$HIBER(1)
#else
*     WAIT FOR SOME TIME BEFORE RETURN
*     THIS VERSION JUST READS SOME RECORDS
*
#include "dacom.h"
      INTEGER IRECU(8)
*     NEXT STATEMENT TO SUPPRESS POSSIBLE COMPILER DIAGNOSTIC
      IRECU(1)=NHSEC
      READ (UNIT=LUNDA,REC=3) IRECU
      READ (UNIT=LUNDA,REC=1) IRECU
      READ (UNIT=LUNDA,REC=2) IRECU
#endif
#endif
