#if defined(FUTURE)
C     ------INDEX
C     STATEMENTS INSERTED IN SUBPROGRAM
C     RETURNS INDI = INDEX OF BANK WITH NAME-INDEX NAMI AND NUMBER NR
C                    OR ZERO
C             INDJ = PREVIOUS INDEX (JW(INDJ-1) CONTAINS INDI)
C
*     USING IN ADDITION LAST INDEX INDJ
*      INCREASE JW(INM) AND JW(IGP) BY NAMES - CHANGE WORD AT DELETE
      INDI=JW(NAMI+NAMES)
      NLPL=0
      IF(INDI.NE.0) THEN
         IF(JW(INDI).NE.0) THEN
            IF(JW(JW(INDI-1)-2).LE.NR) GOTO 2
         END IF
      END IF
      INDI=NAMI+1
    2 INDJ=INDI
      INDI=JW(INDJ-1)
      IF(INDI.NE.0) THEN
         NLPL=NLPL+1
         IF(JW(INDI-2).LT.NR) GOTO 2
         IF(JW(INDI-2).GT.NR) INDI=0
      END IF
C     ------
#else
C     ------INDEX
C     STATEMENTS INSERTED IN SUBPROGRAM
C     RETURNS INDI = INDEX OF BANK WITH NAME-INDEX NAMI AND NUMBER NR
C                    OR ZERO
C             INDJ = PREVIOUS INDEX (JW(INDJ-1) CONTAINS INDI)
C
      INDI=NAMI+1
      NLPL=0
    2 INDJ=INDI
      INDI=JW(INDJ-1)
      IF(INDI.NE.0) THEN
         NLPL=NLPL+1
         IF(JW(INDI-2).LT.NR) GOTO 2
         IF(JW(INDI-2).GT.NR) INDI=0
      END IF
C     ------
#endif
