#if defined(IBM) || defined(GOULD)
C     ------NAMCHA
C     STATEMENTS INSERTED INTO SUBPROGRAM
C     RETURNS NAMA = INTEGER FROM CHARACTER*4 NAME
C
C     ... (NAME IS INTEGER HERE)
      NAMA=NAME
C     ------
#else
#if defined(ALEPH_DEC) || defined(ALEPH_LINUX)
C     ------NAMCHA
C     STATEMENTS INSERTED INTO SUBPROGRAM
C     RETURNS NAMA = INTEGER FROM CHARACTER*4 NAME
C
      CHARACTER*4 NAME
C     ...
      CALL UCTOH(NAME,NAMA,4,4)
C     ------
#else
#if defined(CRAY)
C     ------NAMCHA
C     STATEMENTS INSERTED INTO SUBPROGRAM
C     RETURNS NAMA = INTEGER FROM CHARACTER*4 NAME
C
      CHARACTER*4 NAME
C     ...
      NAMA=OR(SHIFTL(ICHAR(NAME(1:1)),24),
     +     OR(SHIFTL(ICHAR(NAME(2:2)),16),
     +     OR(SHIFTL(ICHAR(NAME(3:3)), 8),ICHAR(NAME(4:4)))))
C     ------
#else
C     ------NAMCHA
C     STATEMENTS INSERTED INTO SUBPROGRAM
C     RETURNS NAMA = INTEGER FROM CHARACTER*4 NAME
C
      CHARACTER*4 NAME
C     ...
      NAMA=IOR(ISHFT(ICHAR(NAME(1:1)),24),
     +     IOR(ISHFT(ICHAR(NAME(2:2)),16),
     +     IOR(ISHFT(ICHAR(NAME(3:3)), 8),ICHAR(NAME(4:4)))))
C     ------
#endif
#endif
#endif
