      SUBROUTINE ASIGEA
C ----------------------------------------------------------------------
C. - F.Ranjard - 850306
C! interface GALEPH_GEANT3
C. - Fill GEANT3 common blocks
C. - called by    ASIRUN                               from this .HLB
C. - calls        GINIT , GZINIT                       from GEANT3.PAM
C.                GDINIT                               from GEANG3.PAM
C.                ASGPAR                               from this .HLB
C ----------------------------------------------------------------------
      COMMON/GCTRAK/GVECT(7),GETOT,GEKIN,GVOUT(7),NGMEC,LGMEC(30)
     &,NGAMEC(30),NGSTEP,MGXNST,GDESTP,GDESTL,GSAFET,GSLENG,GSTEP,GSNEXT
     &,GSFIEL,GTOFG,GEKRAT,GUPWGH,IGNEXT,IGNWVO,IGSTOP,IGAUTO,IGEKBI
     &,IGLOSL,IGMULL,IGNGOT,NGLDOW,NGLVIN,NGLVSA,IGSTRY
C
      PARAMETER (KGWBK=69000,KGWRK=5200)
      COMMON /GCBANK/   NGZEBR,GVERSN,GZVERS,IGXSTO,IGXDIV,IGXCON,
     &                  GFENDQ(16),LGMAIN,LGR1,GWS(KGWBK)
      DIMENSION IGB(1),GB(1),LGB(8000),IGWS(1)
      EQUIVALENCE (GB(1),IGB(1),LGB(9)),(LGB(1),LGMAIN),(IGWS(1),GWS(1))
C
      COMMON/GCLINK/JGDIGI,JGDRAW,JGHEAD,JGHITS,JGKINE,JGMATE,JGPART
     +        ,JGROTM,JGRUN,JGSET,JGSTAK,JGGSTA,JGTMED,JGTRAC,JGVERT
     +        ,JGVOLU,JGXYZ,JGPAR,JGPAR2,JGSKLT
C
      COMMON /GCCUTS/   GCUTGA,GCUTEL,GCUTNE,GCUTHA,GCUTMU
     &                , GBCUTE,GBCUTM,GDCUTE,GDCUTM,GPPCUT
     &                , GTOFMX,GCUTS(5)
C
      COMMON/GCFLAG/IGDEBU,IGDEMI,IGDEMA,IGTEST ,IGDRUN ,IGDEVT
     +             ,IGEORU,IGEOTR,IGEVEN
     +             ,IGSWIT(10),IGFINI(20),NGEVEN,NGRND(2)
C
      COMMON/GCPHYS/ IGPAIR,GSPAIR,GSLPAI,GZINPA,GSTPPA
     &              ,IGCOMP,GSCOMP,GSLCOM,GZINCO,GSTPCO
     &              ,IGPHOT,GSPHOT,GSLPHO,GZINPH,GSTPPH
     &              ,IGPFIS,GSPFIS,GSLPFI,GZINPF,GSTPPF
     &              ,IGDRAY,GSDRAY,GSLDRA,GZINDR,GSTPDR
     &              ,IGANNI,GSANNI,GSLANN,GZINAN,GSTPAN
     &              ,IGBREM,GSBREM,GSLBRE,GZINBR,GSTPBR
     &              ,IGHADR,GSHADR,GSLHAD,GZINHA,GSTPHA
     &              ,IGMUNU,GSMUNU,GSLMUN,GZINMU,GSTPMU
     &              ,IGDCAY,GSDCAY,GSLIFE,GSUMLI,GDPHY1
     &              ,IGLOSS,GSLOSS,GSOLOS,GSTLOS,GDPHY2
     &              ,IGMULS,GSMULS,GSOMUL,GSTMUL,GDPHY3
     &              ,IGRAYL,GSRAYL,GSLRAY,GZINRA,GSTPRA
C
      COMMON/ALFGEO/ALRMAX,ALZMAX,ALFIEL,ALECMS
C
      PARAMETER (LFIL=6)
      COMMON /IOCOM/   LGETIO,LSAVIO,LGRAIO,LRDBIO,LINPIO,LOUTIO
      DIMENSION LUNIIO(LFIL)
      EQUIVALENCE (LUNIIO(1),LGETIO)
      COMMON /IOKAR/   TFILIO(LFIL),TFORIO(LFIL)
      CHARACTER TFILIO*60, TFORIO*4
C
      PARAMETER (LOFFMC = 1000)
      PARAMETER (LHIS=20, LPRI=20, LTIM=6, LPRO=6, LRND=3)
      PARAMETER (LBIN=20, LST1=LBIN+3, LST2=3)
      PARAMETER (LSET=15, LTCUT=5, LKINP=20)
      PARAMETER (LDET=9,  LGEO=LDET+4, LBGE=LGEO+5)
      PARAMETER (LCVD=10, LCIT=10, LCTP=10, LCEC=15, LCHC=10, LCMU=10)
      PARAMETER (LCLC=10, LCSA=10, LCSI=10)
      COMMON /JOBCOM/   JDATJO,JTIMJO,VERSJO
     &                 ,NEVTJO,NRNDJO(LRND),FDEBJO,FDISJO
     &                 ,FBEGJO(LDET),TIMEJO(LTIM),NSTAJO(LST1,LST2)
     &                 ,IDB1JO,IDB2JO,IDB3JO,IDS1JO,IDS2JO
     &                 ,MBINJO(LST2),MHISJO,FHISJO(LHIS)
     &                 ,IRNDJO(LRND,LPRO)
     &                 ,IPRIJO(LPRI),MSETJO,IRUNJO,IEXPJO,AVERJO
     3                 ,MPROJO,IPROJO(LPRO),MGETJO,MSAVJO,TIMLJO,IDATJO
     5                 ,TCUTJO(LTCUT),IBREJO,NKINJO,BKINJO(LKINP),IPACJO
     6                 ,IDETJO(LDET),IGEOJO(LGEO),LVELJO(LGEO)
     7                 ,ICVDJO(LCVD),ICITJO(LCIT),ICTPJO(LCTP)
     8                 ,ICECJO(LCEC),ICHCJO(LCHC),ICLCJO(LCLC)
     9                 ,ICSAJO(LCSA),ICMUJO(LCMU),ICSIJO(LCSI)
     &                 ,FGALJO,FPARJO,FXXXJO,FWRDJO,FXTKJO,FXSHJO,CUTFJO
     &                 ,IDAFJO,IDCHJO,TVERJO
      LOGICAL FDEBJO,FDISJO,FHISJO,FBEGJO,FGALJO,FPARJO,FXXXJO,FWRDJO
     &       ,FXTKJO,FXSHJO
      COMMON /JOBKAR/   TITLJO,TSETJO(LSET),TPROJO(LPRO)
     1                 ,TKINJO,TGEOJO(LBGE),TRUNJO
      CHARACTER TRUNJO*60
      CHARACTER*4 TKINJO,TPROJO,TSETJO,TITLJO*40
      CHARACTER*2 TGEOJO
C
      PARAMETER (LERR=20)
      COMMON /JOBERR/   ITELJO,KERRJO,NERRJO(LERR)
      COMMON /JOBCAR/   TACTJO
      CHARACTER*6 TACTJO
C
      INTEGER LMHLEN, LMHCOL, LMHROW
      PARAMETER (LMHLEN=2, LMHCOL=1, LMHROW=2)
C
      COMMON /BCS/   IW(1000)
      INTEGER IW
      REAL RW(1000)
      EQUIVALENCE (RW(1),IW(1))
C
C ----------------------------------------------------------------------
C
C - Fill GEANT3 common blocks with data read in ASREDC
C
      IGPAIR = 1
      IGCOMP = 1
      IGPHOT = 1
      IGBREM = 1
      IGHADR = 1
      IGANNI = 1
      IGDRAY = 1
      IGLOSS = 1
      IGDCAY = 1
      IGMULS = 1
      IGMUNU = 0
      IGPFIS = 0
      IGRAYL = 0
C - set AUTO flag for GEANT version above 3.140
      IF (GVERSN .GE. 3.14) THEN
         IGAUTO = 0
         IF (IW(NAMIND('AUTO')).GT.0) IGAUTO = 1
         WRITE (LOUTIO,*) ' ****ASIGEA*** IGAUTO = ', IGAUTO
C - set CUTHAD = cut on charged hadrons to 6 MeV when running with
C   GEANT 315 and no TCUT card
         IF (IW(NAMIND('TCUT')).EQ.0) TCUTJO(3) = 0.006
      ENDIF
      NGEVEN = 100000
      IGDRUN = IRUNJO
C
      IF(TCUTJO(1).GT.0.) GCUTGA=TCUTJO(1)
      IF(TCUTJO(2).GT.0.) GCUTEL=TCUTJO(2)
      IF(TCUTJO(3).GT.0.) GCUTHA=TCUTJO(3)
      IF(TCUTJO(4).GT.0.) GCUTNE=TCUTJO(4)
      IF(TCUTJO(5).GT.0.) GCUTMU=TCUTJO(5)
C
C - Initialize ZEBRA structure
C
      CALL GZINIT
C
C - Fill 'PTYP' GEANT banks
C
      CALL ASGPAR
C
      RETURN
       END
