      SUBROUTINE ITROTI
C.
C...ITROTI  1.10  870922  14:47                     R.Beuselinck
C.
C!  Initialise ITC alignment constants.
C.
C-----------------------------------------------------------------------
      SAVE
      COMMON/ITROTC/EULRIT(3),DXYZIT(3),ROTITC(3,3),ITSHFT,WSAGIT
      REAL EULRIT,DXYZIT,ROTITC,WSAGIT
      LOGICAL ITSHFT
C
      INTEGER LMHLEN, LMHCOL, LMHROW
      PARAMETER (LMHLEN=2, LMHCOL=1, LMHROW=2)
C
      COMMON /BCS/   IW(1000)
      INTEGER IW
      REAL RW(1000)
      EQUIVALENCE (RW(1),IW(1))
C
      PARAMETER(JIALID=1,JIALVR=2,JIALDX=4,JIALDR=7,JIALIS=10,LIALIA=10)
      PARAMETER(JIDRID=1,JIDRVR=2,JIDRTO=4,JIDRCO=5,LIDRPA=9)
      PARAMETER(JIGEID=1,JIGEVR=2,JIGENA=4,JIGERI=8,JIGERO=9,JIGEZN=10,
     +          JIGEZX=11,JIGEIP=12,LIGEOA=12)
      PARAMETER(JILYID=1,JILYVR=2,JILYLN=4,JILYNW=5,JILYRW=6,JILYPO=7,
     +          JILYCH=8,JILYIP=9,LILYRA=9)
      PARAMETER(JIPMID=1,JIPMVR=2,JIPMHN=4,JIPMIS=5,LIPMOA=5)
      PARAMETER(JIRFID=1,JIRFVR=2,JIRFBW=4,JIRFZB=5,JIRFDV=6,JIRFMC=7,
     +          JIRFCL=15,JIRFCH=23,JIRFIT=31,LIRFEA=31)
      PARAMETER(JIRRID=1,JIRRVR=2,JIRRMX=4,JIRRMN=5,JIRRCP=6,JIRRCN=11,
     +          LIRRFA=15)
      PARAMETER(JISCID=1,JISCVR=2,JISCSN=4,JISCIT=5,LISCOA=5)
      PARAMETER(JISLID=1,JISLVR=2,JISLXS=4,JISLRS=7,JISLIS=10,LISLOA=10)
      PARAMETER(JISUID=1,JISUVR=2,JISUIP=4,LISURA=4)
      PARAMETER(JITCID=1,JITCVR=2,JITCCN=4,JITCNL=5,JITCWL=6,JITCWS=7,
     +          LITCCA=7)
      PARAMETER(JITKID=1,JITKVR=2,JITKSR=4,JITKSZ=5,JITKRS=6,JITKRL=7,
     +          JITKIT=8,LITKPA=8)
      PARAMETER(JIZNLO=1,JIZNS1=9,JIZNS2=10,JIZNS3=11,LIZNLA=11)
      PARAMETER(JIZFID=1,JIZFVR=2,JIZFBW=4,JIZFZB=5,JIZFEX=6,JIZFS1=7,
     +          JIZFS2=8,JIZFS3=9,JIZFOO=10,JIZFCL=11,JIZFCH=19,
     +          JIZFIT=27,LIZFEA=27)
      PARAMETER(JIZRID=1,JIZRVR=2,JIZRLN=4,JIZRCO=5,JIZRTR=7,LIZRSA=7)
C
      EXTERNAL NAMIND
C
C--  Fill the alignment data.
C--
      IND = IW(NAMIND('IALI')) + LMHLEN
      DO 20 I=1,3
        DXYZIT(I) = RW(IND+JIALDX+I-1)
        EULRIT(I) = RW(IND+JIALDR+I-1)
        ITSHFT = ITSHFT.OR.(DXYZIT(I).NE.0.).OR.(EULRIT(I).NE.0.)
   20 CONTINUE
C
      C1 = COS(EULRIT(1))
      C2 = COS(EULRIT(2))
      C3 = COS(EULRIT(3))
      S1 = SIN(EULRIT(1))
      S2 = SIN(EULRIT(2))
      S3 = SIN(EULRIT(3))
C
      ROTITC(1,1) =  C3*C2*C1 - S3*S1
      ROTITC(2,1) =  C3*C2*S1 + S3*C1
      ROTITC(3,1) = -C3*S2
      ROTITC(1,2) = -S3*C2*C1 - C3*S1
      ROTITC(2,2) = -S3*C2*S1 + C3*C1
      ROTITC(3,2) =  S3*S2
      ROTITC(1,3) =  S2*C1
      ROTITC(2,3) =  S2*S1
      ROTITC(3,3) =  C2
      END
