      SUBROUTINE SABOOK
C-----------------------------------------------------------------------
C!    Histogram booking for the SATR
      SAVE
      PARAMETER (LFIL=6)
      COMMON /IOCOM/   LGETIO,LSAVIO,LGRAIO,LRDBIO,LINPIO,LOUTIO
      DIMENSION LUNIIO(LFIL)
      EQUIVALENCE (LUNIIO(1),LGETIO)
      COMMON /IOKAR/   TFILIO(LFIL),TFORIO(LFIL)
      CHARACTER TFILIO*60, TFORIO*4
C
      PARAMETER (LOFFMC = 1000)
      PARAMETER (LHIS=20, LPRI=20, LTIM=6, LPRO=6, LRND=3)
      PARAMETER (LBIN=20, LST1=LBIN+3, LST2=3)
      PARAMETER (LSET=15, LTCUT=5, LKINP=20)
      PARAMETER (LDET=9,  LGEO=LDET+4, LBGE=LGEO+5)
      PARAMETER (LCVD=10, LCIT=10, LCTP=10, LCEC=15, LCHC=10, LCMU=10)
      PARAMETER (LCLC=10, LCSA=10, LCSI=10)
      COMMON /JOBCOM/   JDATJO,JTIMJO,VERSJO
     &                 ,NEVTJO,NRNDJO(LRND),FDEBJO,FDISJO
     &                 ,FBEGJO(LDET),TIMEJO(LTIM),NSTAJO(LST1,LST2)
     &                 ,IDB1JO,IDB2JO,IDB3JO,IDS1JO,IDS2JO
     &                 ,MBINJO(LST2),MHISJO,FHISJO(LHIS)
     &                 ,IRNDJO(LRND,LPRO)
     &                 ,IPRIJO(LPRI),MSETJO,IRUNJO,IEXPJO,AVERJO
     3                 ,MPROJO,IPROJO(LPRO),MGETJO,MSAVJO,TIMLJO,IDATJO
     5                 ,TCUTJO(LTCUT),IBREJO,NKINJO,BKINJO(LKINP),IPACJO
     6                 ,IDETJO(LDET),IGEOJO(LGEO),LVELJO(LGEO)
     7                 ,ICVDJO(LCVD),ICITJO(LCIT),ICTPJO(LCTP)
     8                 ,ICECJO(LCEC),ICHCJO(LCHC),ICLCJO(LCLC)
     9                 ,ICSAJO(LCSA),ICMUJO(LCMU),ICSIJO(LCSI)
     &                 ,FGALJO,FPARJO,FXXXJO,FWRDJO,FXTKJO,FXSHJO,CUTFJO
     &                 ,IDAFJO,IDCHJO,TVERJO
      LOGICAL FDEBJO,FDISJO,FHISJO,FBEGJO,FGALJO,FPARJO,FXXXJO,FWRDJO
     &       ,FXTKJO,FXSHJO
      COMMON /JOBKAR/   TITLJO,TSETJO(LSET),TPROJO(LPRO)
     1                 ,TKINJO,TGEOJO(LBGE),TRUNJO
      CHARACTER TRUNJO*60
      CHARACTER*4 TKINJO,TPROJO,TSETJO,TITLJO*40
      CHARACTER*2 TGEOJO
C
      PARAMETER (LERR=20)
      COMMON /JOBERR/   ITELJO,KERRJO,NERRJO(LERR)
      COMMON /JOBCAR/   TACTJO
      CHARACTER*6 TACTJO
C
      COMMON/SATRCO/NSECSA,NCRASA,NCARSA,NTDCSA,NSIDSA,NLAYSA,NBRASA,
     .      RMINSA,RMAXSA,BRTHSA,ZLUMSA,DEADSA,DGASSA,COSTSA,
     .      NHITSA,NLOSSA,NWIRSA,XHITSA,XLOSSA,XWIRSA,XEVTSA,
     .      NHLASA(9),NHLDSA(9),PHIBSA(9)
C
      CHARACTER CNUM*2
      DATA ID/600/
      EBEAM=0.5*(BKINJO(5)+BKINJO(6))
      WRITE(LOUTIO,'(''0 SABOOK CALLED, SATR HIST. BOOK. STEP EBEAM='',
     .   F12.4)') EBEAM
      CALL HBOOK1(ID+1,'SATR CHARGED MULTIPLICITY',20,0.,20.,0)
      CALL HBOOK1(ID+2,'SATR NEUTRAL  MULTIPLICITY',20,0.,20.,0)
      CALL HBOOK1(ID+3,'SATR SEC. CHARGED MULT. ACCEPTED',20,0.,20.,0)
      CALL HBOOK1(ID+4,'SATR NEUTRAL MULTIPLICITY ACCEPTED',20,0.,20.,0)
      CALL HBOOK1(ID+5,'SATR PRIMARY ENER. DISTR',100,EBEAM-10.,EBEAM,0)
      CALL HBOOK1(ID+6,'SATR CHARGED SECONDARY ENERGY DISTR.',
     1            100,0.,0.2*EBEAM,0)
      CALL HBOOK1(ID+7,'SATR CHARGED SECONDARY ENERGY DISTR. ACCEPTED',
     1            100,0.,0.2*EBEAM,0)
      CALL HBOOK1(ID+8,'SATR NEUTRAL SECONDARY ENERGY DISTR.',
     1            100,0.,0.2*EBEAM,0)
      CALL HBOOK1(ID+9,'SATR NEUTRAL SECONDARY ENERGY DISTR. ACCEPTED',
     1            100,0.,0.2*EBEAM,0)
      CTHMAX=COS(BKINJO(7))
      CALL HBOOK1(ID+10,'SATR ORIGINAL COST DISTR.',10,.996,.999,0)
      CALL HBOOK1(ID+16,'SATR NUM. CHAR SEC IN COST',10,.996,.999,0)
      CALL HBOOK2(ID+11,'SATR DIST SEC-MAIN VS ENERGY AT LUMI ENTRANCE',
     1            40,0.,20.,25,0.,.5*EBEAM,0)
      CALL HBPRO(ID+11,0)
      CALL HBOOK2(ID+12,
     1 'SATR DIST SEC-MAIN IN THETA VS ENERGY AT LUMI ENTRANCE',
     1            40,0.,8.,25,0.,.5*EBEAM,0)
      CALL HBPRO(ID+12,0)
      CALL HBOOK1(ID+13,'SATR THETA SEEN-ORIGINAL',100,-.001,.001,0)
      CALL HBOOK2(ID+14,'SATR DIST NEUT SEC-MAIN VS ENER AT LUMI ENTR.',
     1            40,0.,20.,25,0.,.5*EBEAM,0)
      CALL HBPRO(ID+14,0)
      CALL HBOOK2(ID+15,
     1 'SATR DIST NEUT SEC-MAIN IN THETA VS ENERGY AT LUMI ENTRANCE$',
     1            40,0.,8.,25,0.,.5*EBEAM,0)
      CALL HBPRO(ID+15,0)
      CALL HBOOK1(ID+26,'SATR HITS  PER EVENT',100,0.,100.,0)
      CALL HBOOK1(ID+27,'SATR WIRES PER EVENT', 50,0.,50.,0)
      CALL HBOOK1(ID+28,'SATR LOST HITS/EVENT', 50,0.,50.,0)
      CALL HBOOK1(ID+29,'SATR ORED WIRES/EVENT',20,0.,20.,0)
      DO 10 ILAY=1,9
        WRITE(CNUM,'(I2)') ILAY
        CALL HBOOK1(ID+30+ILAY,'SATR HITS PER LAYER  '//CNUM,
     .       50,0.,50.,0)
        CALL HBOOK1(ID+40+ILAY,'SATR WIRES PER LAYER '//CNUM,
     .       25,0.,25.,0)
   10 CONTINUE
      END
